### ISSUE TITLE
Add "backport-all" label to backport to all currently supported release lines

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#1048]
## Summary

It'd be nice to have a label which will open backports to every supported release line rather than having to add all the labels. This decreases the likelyhood a release line is missed

cc @crodriguezvega 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
I think I will close the issue, since we are rarely back porting a PR to all release branches nowadays...
