### ISSUE TITLE
Remove localhost client 

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#1089]
## Summary

The localhost client is currently non-functional. We should either fix it or remove it so there is no confusion. I propose we remove it. The existing code is minimal and I think it'd be easy enough to reimplement it from scratch if we so desire. There was an existing proposed [ADR](https://github.com/cosmos/ibc-go/pull/75) on how to fix the implementation, but it's still very unclear when a use case for the localhost will arise (thus far no one has asked for it to be functional)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Can we use this as a learning exercise? Is there anything valuable about IBC and/or light clients that could be learnt from fixing/re-implementing this?
