### ISSUE TITLE
Don't use arbitrary error message as the acknowledgement

### ISSUE THREAD

**Issue by yihuang** [cosmos/ibc-go#1103]
## Summary

currently, the transfer app uses whatever error message is returned as acknowledgment ([code](https://github.com/cosmos/ibc-go/blob/main/modules/apps/transfer/ibc_module.go#L185)), which makes the error message a part of consensus state, so the error message change will be a consensus breaking change, which may not align with people's intuition, making it easier to bring in consensus breaking changes in minor upgrades.

## Proposal

Use static errors, suggested by @leejw51crypto

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by damiannolan** [comment]
Hi @yihuang, thanks for opening this issue. The code which you link is calling `types.NewErrorAcknowledgement(err)` from the transfer `types` pkg. See [here](https://github.com/cosmos/ibc-go/blob/d40f1da72649ad720c7926069cd0b0454997a19d/modules/apps/transfer/types/ack.go#L19). 

This function extracts the abci error code and then includes a static ack error string (string constant). 

```
// NewErrorAcknowledgement returns a deterministic error string which may be used in
// the packet acknowledgement.
func NewErrorAcknowledgement(err error) channeltypes.Acknowledgement {
	// the ABCI code is included in the abcitypes.ResponseDeliverTx hash
	// constructed in Tendermint and is therefore deterministic
	_, code, _ := sdkerrors.ABCIInfo(err, false) // discard non-determinstic codespace and log values

	errorString := fmt.Sprintf("ABCI code: %d: %s", code, ackErrorString)

	return channeltypes.NewErrorAcknowledgement(errorString)
}
```

I believe this is the desired behaviour which you propose. Please review this and feel free to close the issue or raise any other questions. Many thanks!

**Comment by yihuang** [comment]
I see, I checked that in v2 and v3, it's indeed as you described, the issue I described is only in v1. I'll close this.
