### ISSUE TITLE
ICA Migration docs

### ISSUE THREAD

**Issue by faddat** [cosmos/ibc-go#1147]
## Summary

ibc-go has the authoritative documentation on chain upgrades.  I refer many new users and devs to this repository.

Since I am currently upgrading Juno (SDK 45) to support ica, I am making some improvements to the migration docs based on my mistakes.

## Problem Definition

We need this feature so that it is very easy to add ica support, hopefully 100% copy and paste for common transactions in the cosmos sdk.

## Proposal

https://github.com/cosmos/ibc-go/pull/1146
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closing this since #1146 was also closed.
