### ISSUE TITLE
Provide an experimental Gaia branch for ICS29 Fee Middleware

### ISSUE THREAD

**Issue by soareschen** [cosmos/ibc-go#1162]
## Summary

The changes in #276 requires non-trivial changes to be made in Gaia. It would be great if an experimental branch of Gaia can be provided that uses the ibc-go version provided in #1981.

Having a Gaia fork with fee enabled would allow us to develop the fee feature in Hermes without having to wait for an official Gaia release. (https://github.com/informalsystems/ibc-rs/issues/1967) We would also able to provide early feedback in case we find any issue with the current design.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
Is it not possible to use the [`simapp`](https://github.com/cosmos/ibc-go/tree/main/testing/simapp) within ibc-go?

**Comment by crodriguezvega** [comment]
I think @seantking and @damiannolan have set up something similar as the [interchain-accounts-demo repo](https://github.com/cosmos/interchain-accounts-demo) when they did the QA for alpha a few weeks, but it's not available in any repo yet.

**Comment by damiannolan** [comment]
We tested e2e using [`simapp`](https://github.com/cosmos/ibc-go/tree/main/testing/simapp), modifying the ica demo scripts to bootstrap two chains.

**Comment by fedekunze** [comment]
@soareschen Happy to add this functionality to the Evmos testnet to try it with Gaia. We are running on the latest version and we have already implemented 2 middlewares

**Comment by fig666** [comment]
🤔

**Comment by soareschen** [comment]
> Is it not possible to use the [`simapp`](https://github.com/cosmos/ibc-go/tree/main/testing/simapp) within ibc-go?

Thanks for the suggestion! I just tried running the ibc-rs integration tests with `simapp` in https://github.com/informalsystems/ibc-rs/pull/1996 and it does seem to work!

In that case this issue can be closed, and we'll try and develop ICS29 support with the `simapp`. Will report if we encounter any issue with that.
