### ISSUE TITLE
Require document for application module `transfer`

### ISSUE THREAD

**Issue by kth-tw** [cosmos/ibc-go#1167]
## Summary

Require document for application module `transfer` module.

## Problem Definition

There are two application module in [modules/apps](https://github.com/cosmos/ibc-go/tree/main/modules/apps), but only one in [docs/apps](https://github.com/cosmos/ibc-go/tree/main/docs/apps).

## Proposal

Maybe copy file from [here](https://github.com/cosmos/ibc-go/tree/main/modules/apps/transfer/spec) to document folder. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
@kth-tw thanks for opening this issue, but we already had an issue to do this work: [#652](https://github.com/cosmos/ibc-go/issues/652). We are now planning work for Q2 2022 and this might very well be in our scope.
