### ISSUE TITLE
Missing IBC transfer spec in docs

### ISSUE THREAD

**Issue by fedekunze** [cosmos/ibc-go#1174]
## Summary of Bug

Currently, only the Interchain accounts spec is included in the documentation

## Version

`main`

## Steps to Reproduce

See [docs](https://ibc.cosmos.network/main/)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
@fedekunze Thanks for pointing this out, but we already have #652 to bring the docs from the [spec folder of the transfer app](https://github.com/cosmos/ibc-go/tree/main/modules/apps/transfer/spec) to `docs/app_modules/transfer`. We will most likely work on this in Q2.
