### ISSUE TITLE
Finish `verifyMisbehaviour` chainID revision tests

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#1184]
## Summary

There are a few tests from #1166 which are commented out. They should be completed once a `Endpoint{}.UpgradeChain()` function is added.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by seantking** [comment]
`verifyHeader` needs the respective tests also. The remaining test cases needed to be ported over are still being tested as part of the `CheckHeaderAndUpdateState` function.

**Comment by colin-axner** [comment]
closed by #1302
