### ISSUE TITLE
Update godoc for `VerifyClientMessage` in 07-tendermint

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#1185]
## Summary

godoc introduced by #1119 can be improved upon. It should emphasis the validation done by `verifyHeader` and `verifyMisbehaviour` in a useful manner without going into too much detail but without being too vague

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closed by #1281
