### ISSUE TITLE
Add `VerifyClientMessage` to ClientState interface

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#1191]
## Summary

Add `VerifyClientMessage` to ClientState interface. The API should be aligned between solo machine and tendermint. Optionally, in 02-client add a call to this function before `CheckHeaderAndUpdateState` (or can be left until completing #668)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closed by #1196
