### ISSUE TITLE
Add `UpdateState` to ClientState interface

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#1194]
## Summary

Should be done after #1193 and #1190 . Add `UpdateState` to the ClientState interface. If #1193 added the call to `UpdateStateOnMisbehaviour` before `CheckHeaderAndUpdateState` then the same change can be made

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by damiannolan** [comment]
I think we previously discussed removing the return values. However, returned `ClientState` is used for [event emission](https://github.com/cosmos/ibc-go/blob/02-client-refactor/modules/core/02-client/keeper/client.go#L123), similarly for [misbehaviour event emission](https://github.com/cosmos/ibc-go/blob/02-client-refactor/modules/core/02-client/keeper/client.go#L140).

**Comment by colin-axner** [comment]
Hmm. Not returning the `ClientState` makes the API clean and it is a bit more clear to developers they need to set the ClientState. Returning the ClientState does allow for one less store query/less gas used, but it does open the possibility to a developer returning a different client state than that set in state (although hopefully not problematic if the returned client state is used for events only)

**Comment by seantking** [comment]
> Hmm. Not returning the `ClientState` makes the API clean and it is a bit more clear to developers they need to set the ClientState. Returning the ClientState does allow for one less store query/less gas used, but it does open the possibility to a developer returning a different client state than that set in state (although hopefully not problematic if the returned client state is used for events only)

This is a good point. I'm actually more fond of APIs that return the updated values but as you point out this may not actually be the case.

I'm fine with leaving it out and doing an additional query to the store.
