### ISSUE TITLE
Prune a consensus state on duplicate client updates

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#1207]
## Summary

Currently after performing many changes to the 02-client-refactor branch, a duplicate update will not perform the normal pruning of the oldest consensus state (if expired). I propose we restructure the code such that pruning happens first. [See code](https://github.com/cosmos/ibc-go/blob/02-client-refactor/modules/light-clients/07-tendermint/types/update.go#L248-#L253)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Would the work be moving [this line](https://github.com/cosmos/ibc-go/blob/main/modules/light-clients/07-tendermint/update.go#L143) before [this line](https://github.com/cosmos/ibc-go/blob/main/modules/light-clients/07-tendermint/update.go#L138) + adapting/adding any necessary tests?
