### ISSUE TITLE
Add end to end solo machine tests

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#121]
## Summary

an end to end solo machine test would have caught #119. It would be great if we could utilize v2 of the testing package to quickly write integration tests

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
@colin-axner Can this issue be considered done with the tests added as part of the 02-client refactor?

**Comment by colin-axner** [comment]
Yup!
