### ISSUE TITLE
change migration link on release tab.

### ISSUE THREAD

**Issue by fly33499** [cosmos/ibc-go#1273]
Hi. I've found wrong link address on the release tab (3.0)

When I click "The migration from ibc-go v2 to v3.", wrong address error is shown.

Please fix it ^^ and thank you for great product.

[Before]
https://github.com/cosmos/ibc-go/blob/main/docs/migrations/v1-to-v3.md

[To-Be]
https://github.com/cosmos/ibc-go/blob/main/docs/migrations/v2-to-v3.md

**Comment by crodriguezvega** [comment]
That's a good catch. Thanks, @fly33499!

I just fixed it.
