### ISSUE TITLE
Return error if fee module is locked before distributing fees on acknowledgement and timeout

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#1320]
Return an error in case the fee modules is locked and don’t delete fees in escrow in [`DistributePacketFeesOnAcknowledgement`](https://github.com/cosmos/ibc-go/blob/main/modules/apps/29-fee/keeper/escrow.go#L48) and [`DistributePacketFeesOnTimeout`](https://github.com/cosmos/ibc-go/blob/main/modules/apps/29-fee/keeper/escrow.go#L105).

**Comment by colin-axner** [comment]
Move `DeletePacketFees` call into the Distribution functions. The `packetID` will need to be added as an argument to the distribution function
