### ISSUE TITLE
Update Client Recovery Proposal Documentation

### ISSUE THREAD

**Issue by AdityaSripal** [cosmos/ibc-go#1337]
The update client recovery proposal is allowed to change the chain-id to account for changing chain-ids during a chain halt.

This is allowed since it is gated by governance.

However, the documentation still refers to the original restrictions in which the chain-id must be the exact same value.

https://ibc.cosmos.network/main/ibc/proposals.html#steps

The documentation should be updated to the latest logic

**Comment by crodriguezvega** [comment]
Closing as the docs already list chain ID as one of the chain parameters that are allowed to change during a client recovery.
