### ISSUE TITLE
Update or remove OLD_README.md

### ISSUE THREAD

**Issue by AdityaSripal** [cosmos/ibc-go#134]
- [ ] Spec doc: https://github.com/cosmos/ibc-go/blob/main/docs/spec.md

It's worth double checking rest of links and adding them here as TODOs

**Comment by colin-axner** [comment]
OLD_README.md in `docs/` has many broken links. It should be updated and used for some purpose or removed entirely

**Comment by albertchon** [comment]
The code comments also have many broken links. One can easily just search `github.com/cosmos/ics` and see a lot of the outdated links

**Comment by crodriguezvega** [comment]
Closed by #2898.
