### ISSUE TITLE
Publish the proto module on BSR

### ISSUE THREAD

**Issue by mzabaluev** [cosmos/ibc-go#1345]
## Summary

Publish the ibc proto module on Buf Schema Registry.

## Problem Definition

Application developers wishing to use [buf](https://buf.build/) to manage the protobuf definitions and their dependencies would benefit from the IBC protobuf files being published on BSR as a module. Case in point: https://github.com/informalsystems/ibc-rs/pull/2199.
As the repository has already been equipped with buf manifests allowing code to be built from the ibc-go repository as an input, it would seem like a logical progression to fully convert the proto files to a module.

## Proposal

Replace `third_party/proto` files with dependencies managed via the `buf.yaml` file. To generate Go code, define `buf.gen.yaml` and specify proper use of protoc plugins rather than the current transitional solution invoking `buf protoc`.
Once the adaptation is done and passes the required lints, push the module to BSR as `https://buf.build/cosmos/ibc`.

This may need some work on behalf of tendermint, as those proto files are not currently in BSR either, and we don't want to diamond them via cosmos-sdk and ibc-go.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
I believe this is the same proposal as #808? 

In favor of adding our proto files to the buf schema registry :+1:

**Comment by damiannolan** [comment]
closed by https://github.com/cosmos/ibc-go/pull/2705
