### ISSUE TITLE
why could a client have multiple connections? 

### ISSUE THREAD

**Issue by kimroniny** [cosmos/ibc-go#1346]
"A client can be associated with any number of connections to multiple chains". It is from [cosmos docs ](https://docs.cosmos.network/master/ibc/overview.html#clients)

if a client could have multiple connections which connect to multiple different chains, then the client needs to set multiple chains's consensus states.

**However**, the client doesn't set consensus states of multiple chains. It sets the consensus state of only one chain.

So, how could a client connect to multiple chains with multiple connections?

Maybe I am misunderstanding, but pls tell me the reason thank u

**Comment by crodriguezvega** [comment]
I agree that statement might not be completely accurate...

Every chain needs to run a different light client for the counterparty chains that is communicating with. So indeed, a single light client cannot connect to multiple chains simultaneously.

If you have more questions, please ask better instead in the [Cosmos Network Discord](https://discord.gg/cosmosnetwork)!

**Comment by kimroniny** [comment]
> I agree that statement might not be completely accurate...
> 
> Every chain needs to run a different light client for the counterparty chains that is communicating with. So indeed, a single light client cannot connect to multiple chains simultaneously.
> 
> If you have more questions, please ask better instead in the [Cosmos Network Discord](https://discord.gg/cosmosnetwork)!

thanks master, I get the answer clearly. Recently, my lab is doing some researches on IBC but we don't understand why a client could have multiple connections because the programming code show us that it couldn't. According to your answer, I know that maybe it is just an accurate statement on official website so I suggest maybe you can update that doc.

**Comment by crodriguezvega** [comment]
Those docs in the cosmos SDK website are out of date (in fact, they should be removed). ibc-go has now its own documentation website and you can check [there](https://ibc.cosmos.network/main/ibc/overview.html#clients) that the description is correct.

Please get in touch if we can help/support somehow during your research of IBC!

**Comment by kimroniny** [comment]
> Those docs in the cosmos SDK website are out of date (in fact, they should be removed). ibc-go has now its own documentation website and you can check [there](https://ibc.cosmos.network/main/ibc/overview.html#clients) that the description is correct.
> 
> Please get in touch if we can help/support somehow during your research of IBC!

Of course! Thank u for your help/support!
