### ISSUE TITLE
The old version "Found an issue" button cannot jump to Github

### ISSUE THREAD

**Issue by xxxxxchan** [cosmos/ibc-go#1354]
## Summary of Bug

When I am reading the past version of the document, I click the "found an issue" button in the lower right corner, it will jump to the wrong Github page, it is recommended to update the link so that more people can contribute to the document

![image](https://user-images.githubusercontent.com/82381764/168415074-98d36569-968c-4ec7-bf9d-06d59b655f49.png)

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Well spotted! Thanks for opening an issue for it, @xxxxxchan!
