### ISSUE TITLE
Blocked list instead of allowed list for ICA host message types?

### ISSUE THREAD

**Issue by seantking** [cosmos/ibc-go#1400]
## Summary

It appears to be a [UX pain point](https://github.com/cosmos/gaia/issues/1498) that developers integrating the interchain account host module are required to create an allow list of all messages types that accounts on the host chain can execute. 

The primary reason for this approach was to force teams using the host module to consider the implications of an ICA executing a particular message and ensure that only required messages are allowed. 

Should we consider switching from an allow list to a blocked list? This would mean all messages are enabled by default. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by nooomski** [comment]
I'm in favor of this idea. Any messages that can be executed via ICA can also be executed via a regular account, so I don't consider this feature to add any additional risks to a chain, and would be in favor of a blocked list.

cc @mmulji-ic @yaruwangway

**Comment by crodriguezvega** [comment]
After user feedback it has been decided to keep the whitelist, but implement the possibility to allow all messages. So closing this issue now in favor of #1479.
