### ISSUE TITLE
Proof verification fails for client state

### ISSUE THREAD

**Issue by sahith-narahari** [cosmos/ibc-go#142]
## Summary of Bug
I created two chains and setup clients. The issue I'm facing is when I try to create a proof that client of A exists on B, it fails with the error ```  chained membership proof failed to verify membership of value: 0A2B2F6962632E6C69676874636C69656E74732E74656E6465726D696E742E76312E436C69656E74537461746512790A0A74657374636861696E311204080110031A040880EA4922040880DF6E2A02080A32003A02101642190A090801180120012A0100120C0A02000110211804200C300142190A090801180120012A0100120C0A02000110201801200130014A07757067726164654A1075706772616465644942435374617465 in subroot 99896CA53B888E8E15B0460182BB7B045F39A3623DA58A5AADCA31DE2BF06CB0 at index 0. Please ensure the path and value are both correct.: invalid proof```

I'm using a ported version of ibc testing package to simulate this in a test. The proof is being generated using the following method https://github.com/tendermint/cns/blob/f797a3ba980c27c0e43a13ad54c65a6988c04a62/x/ibc/testing/chain.go#L226.
I want to extend this to multiple chains for CNS, but couldn't resolve the issue of proof verification. Should this proof be enough or should I create the proof differently.
## Steps to Reproduce
- Here's the test case where the verification fails https://github.com/tendermint/cns/blob/dbf4173f335f5de88afdb1d2c12c9c031f5885b8/x/cns/keeper/verify_test.go#L13

cc\ @AdityaSripal @gamarin2
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
I think you need to update the client before attempting to process the proof. Can you do that and see if it fixes the error?

I discussed updating clients after processing messages such as handshakes with @AdityaSripal and we opted against it for the new testing package, but I think it'd be better to add it back even if it causes twice as many updates (ie update before/after the message). Thoughts @AdityaSripal ?

**Comment by sahith-narahari** [comment]
I tried updating the clients in a different setup, still faced the same issue.

After discussing with @AdityaSripal , we decided it's better to port the setup to use the testing V2 package. I'll post an update once I port the tests, and check if the issue still persists

**Comment by colin-axner** [comment]
Closing this issue since there hasn't been a followup
