### ISSUE TITLE
portkeepers should be able to handle adding their routes to ibcrouter

### ISSUE THREAD

**Issue by charleenfei** [cosmos/ibc-go#1449]
## Summary of Bug

ideally the app dev doesnt need to call ibcRouter.AddRoute(xyz) or instantiate the NewRouter (ibcRouter type) for each module.

just adding this here for visibility/to simplify app wiring, @AdityaSripal you may already have a solution in mind

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by charleenfei** [comment]
just discussed with @AdityaSripal , we should add a batch of work to the channel upgradeability sprint to revisit the ibc router as a whole, especially in light of the new smart contract ibc use cases

**Comment by colin-axner** [comment]
closing for lack of concrete issue/proposal outline
