### ISSUE TITLE
Abuse of Contributor Covenant

### ISSUE THREAD

**Issue by faddat** [cosmos/ibc-go#1453]
## Summary of Bug

1) The contributor covenant is open to abuse due to its sprawling language. 
2) An interchain foundation lead member, Billy Rennekamp, suggested in a private discord server that my behavior on twitter during the cosmos hub proposal 69 debate represented a violation of codes of conduct due to "the volume of tweets".
3) The contributor covenant in this repository makes me feel unsafe because Billy Rennekamp could very well be one of the parties at the end of the e-mail address listed in the contributor covenant in this repository.

## Version

all.  this is a social problem. 

## Steps to Reproduce

1) become a cosmos hub validator
2) disagree vigorously with Billy Rennekamp's position on a hotly debated issue, and present evidence contrary to his claims
3) wait

## Solutions

* use Jacob's tiny CoC or another scope-restricted CoC that protects freedom of expression outside of the workplace
* devise a new CoC
* (minimally) allow contributors to feel safe from political repirsal by ensuring that Billy Rennekamp is entirely out of the loop on CoC enforcement matters, by specifying directly individuals or an individual to enforce the existing CoC in this repository.

## Proof

Sadly, if I didn't support these claims, they might not be heard.

https://github.com/notional-labs/notional/blob/master/incidents/Letter%20to%20the%20cosmos%20ecosystem%20concerning%20the%20care%20and%20maintenance%20of%20the%20cosmos%20hub.pdf

This is an unfortunate matter, but, facts are facts.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Hi @faddat. I am sorry to hear there was some friction between you and Billy. I hope you two can take a step back and reconcile... Thanks for opening this issue, but to be honest I am a bit hesitant to make any changes to the CoC, specially if they are as drastic as the ones you propose in your PR. :)
