### ISSUE TITLE
Replace Proposals with Msgs with Approved signers

### ISSUE THREAD

**Issue by AdityaSripal** [cosmos/ibc-go#1478]
Now with the changes to governance and groups module in SDK v0.46, I think we can switch the governance proposals in IBC into regular msgs.

The messages will only succeed if they are signed by an approved list of senders that can be a parameter of IBC.

This allows us to support the current default behaviour by having the governance module account be one of the approved signers.

But we can also allow governance to delegate this responsibility to trusted groups and add the group account address to the approved sender list.

I believe this would be the preferred approach with SDK v0.46, correct me if im wrong @marbar3778 

cc: @ValarDragon since I believe you were the one to bring up the inconvenience of governance-gated IBC recovery solutions

**Comment by ValarDragon** [comment]
This would be awesome!

**Comment by colin-axner** [comment]
same issue as #1282. Do you have a preference to keep this open instead?

**Comment by AdityaSripal** [comment]
I think yours is more structured. Im ok with just copying any relevant rationale into your issue and closing this one thanks!

**Comment by colin-axner** [comment]
cool I added some of the addition rationale for allowing of delegation to trusted groups
