### ISSUE TITLE
UX: Provide endpoint to get full denom of account balance

### ISSUE THREAD

**Issue by AdityaSripal** [cosmos/ibc-go#1480]
Currently getting the account balance of an address will return the hashed IBC denoms. This hashed denom must then be converted to a full trace in a second query.

We could provide a convenience function to both query account balance and retrieve full IBC traces for IBC denoms in one query.

**Comment by crodriguezvega** [comment]
So is the idea that should add a a new CLI/gRPC that returns the same result as `q bank balances` but incorporates an extra field with the IBC trace in case the balance of the account includes IBC tokens?

**Comment by ValarDragon** [comment]
I feel like this is generally not the right direction.

I think IBC should commit to doing a migration to get much more human readable denoms by default, and only hash in the situation where its too long. (Say total denom > 256 chars)

I then think we change the bank layer, to have a "trusted denom display" registry, where it can maintain a map from "input name" to on-chain denom, that we get all coins parsing to use, and a map from "on-chain denom" to "preferred display denom". Then we make bank queries / all user output use that.

**Comment by crodriguezvega** [comment]
Closing this issue for now. After discussion with the SDK team, we will try to implement a solution on the SDK (see [#14181](https://github.com/cosmos/cosmos-sdk/issues/14181)).
