### ISSUE TITLE
`Height` semantics inconsistent with ICS 7

### ISSUE THREAD

**Issue by plafer** [cosmos/ibc-go#1576]
[ICS-7 `Height` definition](https://github.com/cosmos/ibc/blob/master/spec/client/ics-007-tendermint-client/README.md#height) doesn't treat `0` as a special case; in fact, it mentions "resetting the height to 0". However, ibc-go treats `0` as a special case throughout the codebase: it is rejected in, say, [`ClientState` height validation](https://github.com/cosmos/ibc-go/blob/20ffa6f1aca8adddccdcd714488eead2256a420d/modules/light-clients/07-tendermint/types/client_state.go#L133).

This causes problems for other implementations (notably in Rust): we can either copy ibc-go's semantics, or follow the standard and be incompatible with ibc-go.

It is unclear to me whether the standard or the implementation should change, so I'm posting this here to start.

**Comment by crodriguezvega** [comment]
If I am not mistaken 0 is an invalid block height in Tendermint:
- See [here](https://docs.tendermint.com/master/spec/core/state.html): _The initial height will be 1 in the typical case, 0 is an invalid value_),
- and [here](https://docs.tendermint.com/master/spec/core/data_structures.html#header): _Must be > 0, >= initialHeight, and == previous Height+1_

So could it be that the implementation in ibc-go is correct, but the spec is not? @AdityaSripal @colin-axner

**Comment by AdityaSripal** [comment]
Yes, Tendermint block heights initialize to 1. So 0 should not be accepted.

We should change the spec to address this. Thanks @plafer !

**Comment by hu55a1n1** [comment]
On a similar note, I think it would be helpful to clarify if a packet `TimeoutHeight` with a non-zero `RevisionNumber` but zero `RevisionHeight` is valid or not because such a timeout might not make sense for a Tendermint chain.

**Comment by crodriguezvega** [comment]
Ok, then I think we can close this issue and one should be open in the cosmos/ibc repo to address this in the spec, correct? Can you please do that, @plafer?

**Comment by plafer** [comment]
I amended [this issue](https://github.com/cosmos/ibc/issues/777) to fix the inconsistency on the standard side. 

However, to @hu55a1n1's point, `Packet.TimeoutHeight` is now inconsistent with the standard, as `Height {revision_number: 0, revision_height: 0}` is used to encode "zero height", where the correct `0` value should be `Height {revision_number: 0, revision_height: 1}`. We had to create a [different `Height` type](https://github.com/informalsystems/ibc-rs/blob/385c3ab5940968772f8c3598ae4e70d57027f8e1/modules/src/core/ics04_channel/timeout.rs#L22) in Rust to encode these special semantics.

Would you prefer a different issue be opened for this?

**Comment by AdityaSripal** [comment]
I don't understand why that would be necessary.

Here when we refer to `zero height` on the timeout this is equivalent to: no timeout height is defined. So it makes sense to me that it stays {0, 0}

**Comment by plafer** [comment]
ICS-4 currently uses `timeoutHeight == 0` to mean "no timeout". For example, this check in `timeoutPacket()`:

```js
abortTransactionUnless(
      (packet.timeoutHeight > 0 && proofHeight >= packet.timeoutHeight) ||
      (packet.timeoutTimestamp > 0 && connection.getTimestampAtHeight(proofHeight) > packet.timeoutTimestamp))
```
According to this, and since we also agree that `{0, 1}` is the minimum Tendermint height (denoted as `0` in ICS-2), then `{0, 1}` should be used to indicate "no timeout". Otherwise, if `{0, 0}` is used to encode "no timeout", then the check `packet.timeoutHeight > 0` is meaningless since `{0, 0}` is not a valid value for a height (and thus cannot be compared to other heights).

However, I agree with you that `{0, 0}` is better, as it encodes something closer to `null` than `{0, 1}` does, and the standard should be changed (specifically with respect to `packet.timeoutHeight > 0` checks). In fact I already opened [an issue](https://github.com/cosmos/ibc/issues/776) that attempts to capture this.

If we agree that the standard should change instead of ibc-go's implementation, then we can close this issue and fix the inconsistency on the standard's side.

**Comment by colin-axner** [comment]
I'm closing this issue for now. I think we should change the standards. The original design around Height semantics was implemented first in ibc-go and then documented in the spec. It should have been the other way around, but for historical reasons it happened so. 

I think we should fix the spec first. Then if it is agreed that ibc-go should change it's code, there should be a followup change on the spec repo indicating this
