### ISSUE TITLE
Add upgrade states to `04-channel` `State` enum proto

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#1604]
## Summary

The channel [`State`](https://github.com/cosmos/ibc-go/blob/main/proto/ibc/core/channel/v1/channel.proto#L53) enum should be extended to include the new upgrade state values.

Add the following values to the channel `State` enum protobuf definition:

- `STATE_UPGRADE_INIT`
- `STATE_UPGRADE_TRY`

The chain that is proposing the upgrade should set the channel state from `OPEN` to `UPGRADE_INIT`.
The counterparty chain that accepts the upgrade should set the channel state from `OPEN` to `UPGRADE_TRY`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
closed by #1789
