### ISSUE TITLE
Add upgrade handshake rpcs to `04-channel` protobuf `Msg` service

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#1617]
## Summary

The following channel upgrade handshake rpcs should be added to the `04-channel` protobuf `Msg` service:

```proto
rpc ChannelUpgradeInit(MsgChannelUpgradeInit) returns (MsgChannelUpgradeInitResponse);

rpc ChannelUpgradeTry(MsgChannelUpgradeTry) returns (MsgChannelUpgradeTryResponse);

rpc ChannelUpgradeAck(MsgChannelUpgradeAck) returns (MsgChannelUpgradeAckResponse);

rpc ChannelUpgradeConfirm(MsgChannelUpgradeConfirm) returns (MsgChannelUpgradeConfirmResponse);
```

- [x] https://github.com/cosmos/ibc-go/issues/1622
- [x] https://github.com/cosmos/ibc-go/issues/1618
- [x] https://github.com/cosmos/ibc-go/issues/1619
- [x] https://github.com/cosmos/ibc-go/issues/1620
- [x] https://github.com/cosmos/ibc-go/issues/1621

ref: [ICS004 - Channel Upgrades - Upgrade Handshake](https://github.com/cosmos/ibc/blob/master/spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md#Upgrade-Handshake)
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by DimitrisJim** [comment]
I believe this should also be closed now. Re-open if am mistaken.
