### ISSUE TITLE
Implement `sdk.Msg` interface for channel upgrade handshake messages

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#1622]
## Summary

Implement the `sdk.Msg` interface for the `04-channel` upgrade handshake messages.
Add the `sdk.Msg` methods to the `04-channel` [msgs.go](https://github.com/cosmos/ibc-go/blob/main/modules/core/04-channel/types/msgs.go) file.

- [x] `MsgChannelUpgradeInit` (@charleenfei)
  - `ValidateBasic`
  - `GetSigners`
- [x] `MsgChannelUpgradeTry` (@charleenfei)
  - `ValidateBasic`
  - `GetSigners`
- [x] `MsgChannelUpgradeAck` (@charleenfei)
  - `ValidateBasic`
  - `GetSigners`
- [x] `MsgChannelUpgradeConfirm`  (@chatton)
  - `ValidateBasic`
  - `GetSigners`
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by damiannolan** [comment]
Preferably split the work into 4 PRs, one per message type

**Comment by chatton** [comment]
I will pick up `MsgChannelUpgradeConfirm`
