### ISSUE TITLE
Create ibc-go documentation website

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#168]
## Summary

I added the basic necessities to build locally the ibc-go website in #146. It could use some prettyness work but the main missing component is the logo in the corner

Now we just need to deploy it and ideally integrate its deployment into our github actions. I'm not sure how to handle this part

@okwme do you know who could help deploying this? I was thinking of using the ibc.cosmos.network domain

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by okwme** [comment]
pinging @marbar3778 and @lovincyrus to confirm. I believe it can be deployed with netlify if it needs a build script (and routing) or github pages if it's just markdown files. Either way we can set up CNAMEs to use a subdomain. I like `ibc.cosmos.network` but there's also the option of using the `ibcprotocol.org` website like `docs.ibcprocol.org`.

**Comment by colin-axner** [comment]
I think we can close this! http://ibc.cosmos.network/main/ibc/overview.html
