### ISSUE TITLE
Remove `GetVersions` from Connection interface

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#1689]
## Summary

Remove [GetVersions](https://github.com/cosmos/ibc-go/blob/c449d858e73e3e9de8ded269ebb11d62a8b96d54/modules/core/exported/connection.go#L8) from the connection interface. 

## Problem Definition

This function is unused as an interface. The only calls to this function use the [concrete connection type](https://github.com/cosmos/ibc-go/blob/c449d858e73e3e9de8ded269ebb11d62a8b96d54/modules/core/04-channel/keeper/handshake.go#L36). The connection interface only exists to avoid import cycles (we only use one concrete connection type). 

## Proposal

Remove `GetVersions` from the connection interface. Leave the function within the ConnectionEnd implementation. Please include a changelog entry. This change doesn't need to be backported

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by Daniyal98** [comment]
Hello, I would like to start working on this one if it is still open

**Comment by crodriguezvega** [comment]
> Hello, I would like to start working on this one if it is still open

Yes, it's still available! Thanks very much for offering to pick it up. I will assign it to you now!

**Comment by Daniyal98** [comment]
Thank you! I would start working on it now.
