### ISSUE TITLE
Include Module name in channel callback errors

### ISSUE THREAD

**Issue by AdityaSripal** [cosmos/ibc-go#1728]
Better error messages indicating which module failed for OnChanOpenInit etc.

Taken from #40

**Comment by crodriguezvega** [comment]
- Change the [error returned after `OnChanOpenInit` callback ](https://github.com/cosmos/ibc-go/blob/main/modules/core/keeper/msg_server.go#L192) to:

```go
sdkerrors.Wrapf(err, "channel open init callback failed for module: %s", module)
```

- Change the [error returned after `OnChanOpenTry` callback ](https://github.com/cosmos/ibc-go/blob/main/modules/core/keeper/msg_server.go#L233) to:

```go
sdkerrors.Wrapf(err, "channel open try callback failed for module: %s", module)
```

- Change the [error returned after `OnChanOpenAck` callback ](https://github.com/cosmos/ibc-go/blob/main/modules/core/keeper/msg_server.go#L271) to:

```go
sdkerrors.Wrapf(err, "channel open ack callback failed for module: %s", module)
```

- Change the [error returned after `OnChanOpenConfirm` callback ](https://github.com/cosmos/ibc-go/blob/main/modules/core/keeper/msg_server.go#L305) to:

```go
sdkerrors.Wrapf(err, "channel open confirm callback failed for module: %s", module)
```

- Change the [error returned after `OnChanCloseInit` callback ](https://github.com/cosmos/ibc-go/blob/main/modules/core/keeper/msg_server.go#L330) to:

```go
sdkerrors.Wrapf(err, "channel close init callback failed for module: %s", module)
```

- Change the [error returned after `OnChanCloseConfirm` callback ](https://github.com/cosmos/ibc-go/blob/main/modules/core/keeper/msg_server.go#L358) to:

```go
sdkerrors.Wrapf(err, "channel close confirm callback failed for module: %s", module)
```

**Comment by alizahidraja** [comment]
👋
