### ISSUE TITLE
allow governance (client UpgradeProposals) to change all parameters on an IBC client

### ISSUE THREAD

**Issue by charleenfei** [cosmos/ibc-go#1758]
[As described in this comment](https://github.com/cosmos/ibc-go/pull/1713#pullrequestreview-1046458011), we should allow governance to update all IBC client parameters.

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closed in favour of #1171
