### ISSUE TITLE
Confusion regarding next sequence recv

### ISSUE THREAD

**Issue by adizere** [cosmos/ibc-go#1783]
## Summary

A relayer operator reported this confusion:

> what is the expected behaviour of the /ibc/core/channel/v1/channels/{channel_id}/ports/{port_id}/next_sequence endpoint? it seems to always return “next_sequence_receive”: “1" (https://rest-cosmoshub.ecostake.com/ibc/core/channel/v1/channels/channel-141/ports/transfer/next_sequence)

The answer, thanks for @crodriguezvega, was:

> I see that this endpoint [retrieves the next sequence recv](https://github.com/cosmos/ibc-go/blob/48a6ae512b4ea42c29fdf6c6f5363f50645591a2/modules/core/04-channel/keeper/grpc_query.go#L482) and I think that value [is set on ](https://github.com/cosmos/ibc-go/blob/48a6ae512b4ea42c29fdf6c6f5363f50645591a2/modules/core/04-channel/keeper/packet.go#L281)RecvPacket[ only for ordered channels](https://github.com/cosmos/ibc-go/blob/48a6ae512b4ea42c29fdf6c6f5363f50645591a2/modules/core/04-channel/keeper/packet.go#L281). So I guess it returns 1 because the transfer channel is unordered and the next sequence recv has never been incremented after being initialized to 1 either in ChanOpenInit ([here](https://github.com/cosmos/ibc-go/blob/7370a8b438b5a7d9e3982673bcfbfc550145b1f2/modules/core/04-channel/keeper/handshake.go#L83)) or ChanOpenTry ([here](https://github.com/cosmos/ibc-go/blob/7370a8b438b5a7d9e3982673bcfbfc550145b1f2/modules/core/04-channel/keeper/handshake.go#L192)).

## Expected Behaviour

No confusion regarding this undocumented feature.

Possible suggestion for a fix:

> Just an idea: could it be set to `null` for unordered channels to avoid the confusion?

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
Thanks for opening the issue @adizere! I agree with the suggested fix of using null as a return on unordered channels

**Comment by crodriguezvega** [comment]
Then the solution for now is to modify [`NextSequenceReceive`](https://github.com/cosmos/ibc-go/blob/main/modules/core/04-channel/keeper/grpc_query.go#L472) by adding some code to retrieve the channel:

```
channel, found := q.GetChannel(ctx, req.PortId, req.ChannelId)
if !found {
	return nil, status.Error(
		codes.NotFound,
		sdkerrors.Wrapf(types.ErrChannelNotFound, "port-id: %s, channel-id %s", req.PortId, req.ChannelId).Error(),
	)
}
```

and then we declare and initialize to 0 the `sequence` and if the channel is `UNORDERED` then we do the same thing that we're already doing to retrieve the sequence:

```
var sequence uint64 = 0 // return 0 for ordered channels
if channel.Ordering == types.UNORDERED {
	sequence, found = q.GetNextSequenceRecv(ctx, req.PortId, req.ChannelId)
	if !found {
		return nil, status.Error(
			codes.NotFound,
			sdkerrors.Wrapf(types.ErrSequenceReceiveNotFound, "port-id: %s, channel-id %s", req.PortId, req.ChannelId).Error(),
		)
	}
}
```
