### ISSUE TITLE
add a version tracker issue for ibc-go v5 (and subsequent version releases)

### ISSUE THREAD

**Issue by charleenfei** [cosmos/ibc-go#1799]
currently there is some deal of community confusion as to the [latest status of the ibc-go v5 release](https://github.com/cosmos/ibc-go/pull/1653) that corresponds to the 0.46 sdk release

as per an idea from @colin-axner, we should have a version tracker issue as soon as we know what the next version release will be that discusses all the steps to be taken before a final release is cut, this way there is more clarity and transparency on the timeline.

the issue should also contain a high level TLDR at the topic covering the main features of the release, for easy consumption.

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closed by #1800

**Comment by charleenfei** [comment]
Should we also open one now for ibc-go V6 since that process has also started?

**Comment by crodriguezvega** [comment]
> Should we also open one now for ibc-go V6 since that process has also started?

Will do soon as well. Although we cannot pin more than three issues at the same time... :(

**Comment by colin-axner** [comment]
Guess we need to close v4 tracking issue ;)
