### ISSUE TITLE
light client guide: concepts/vocabulary

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#1850]
## Summary

Add documentation for the concepts and vocabulary for creating a light client. Should explain all the defined [interfaces](https://github.com/cosmos/ibc-go/blob/02-client-refactor/modules/core/exported/client.go). Explanation of each of the functions within the interface will occur in followup documentation

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
The link in the description was pointing at a feature branch. I believe [this](https://github.com/cosmos/ibc-go/blob/main/modules/core/exported/client.go) is where we should look for the interfaces now.

**Comment by damiannolan** [comment]
I can take a stab at getting started on this. This should be included in "Overview" (page 1), right? And lay out some of the basics with descriptions of what each interface is used for.
