### ISSUE TITLE
light client guide: existence/non-existence proofs

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#1853]
## Summary

Explain how existence and non-existence proofs are used within core IBC and how they might be implemented

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
@AdityaSripal can you comment if there is anything specific that should be included in this documentation?

**Comment by AdityaSripal** [comment]
We should include how to "mock" non-existence proofs if the counterparty does not have ability to prove absence.

> Since the verification method is designed to give complete control to client implementations, clients can support chains that do not provide absence proofs by verifying the existence of a non-empty sentinel ABSENCE value. Thus in these special cases, the proof provided will be an ICS-23 Existence proof, and the client will verify that the ABSENCE value is stored under the given path for the given height.
