### ISSUE TITLE
light client guide: upgrades

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#1855]
## Summary

Explain how to implement `VerifyUpgradeAndUpdateState`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by damiannolan** [comment]
ref: https://ibc.cosmos.network/main/ibc/upgrades/developer-guide.html
