### ISSUE TITLE
Remove localhost handler code

### ISSUE THREAD

**Issue by AdityaSripal** [cosmos/ibc-go#187]
It's currently not possible to initialize and create a localhost client, however we still have special exception code that is hanging around in the client handlers that doesn't do anything but make the code ugly.

We should just remove them as a future localhost client implementation will certainly endeavor to avoid having them in the first place.

The client tests still set localhost client and tests handler code even though the implementation would never use it.

**Comment by AdityaSripal** [comment]
cc: @colin-axner for ack

**Comment by colin-axner** [comment]
ACK, but I don't see a need to have it in 1.0.0 since this is a pure aesthetics issue. Would prefer we just fix localhost post 1.0.0

Happy to review a pr though

**Comment by colin-axner** [comment]
closed by #1187
