### ISSUE TITLE
make goimports doesn't work

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#1879]
## Summary

When goimports fails on CI and I run `make goimports` locally, if there's an issue I receive the output:
```
/usr/local/bin/docker run  -v /home/bartleby/work/go/src/github.com/cosmos/ibc-go:/ibc-go --rm  -w "/ibc-go" cytopia/goimports -w -local 'github.com/cosmos/ibc-go' "" &> /dev/null || echo "No changed go files to format"
No changed go files to format
```
but if I fix the issue I receive
```
/usr/local/bin/docker run  -v /home/bartleby/work/go/src/github.com/cosmos/ibc-go:/ibc-go --rm  -w "/ibc-go" cytopia/goimports -w -local 'github.com/cosmos/ibc-go' "testing/chain.go" &> /dev/null || echo "No changed go files to format"
```

Running the command causes no changes in diffs. Should it? 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closing this issue since we got rid of `goimports` in https://github.com/cosmos/ibc-go/pull/2549.
