### ISSUE TITLE
Use commitmenttypes.MerklePath in VerifyMembership/VerifyNonMembership arguments

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#1884]
## Summary

In `VerifyMembership` and `VerifyNonMembership` we should use the merkle path interface instead of bytes to reduce unnecessary marshal/unmarshling. Use casting, open issue for removing path interface

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by damiannolan** [comment]
I think we are using `[]byte` as this would result in an import cycle, right? 

We register `exported` interfaces in [`23-commitment/types/codec.go`](https://github.com/cosmos/ibc-go/blob/main/modules/core/23-commitment/types/codec.go) against the concrete types, so using `MerklePath` would result in an import cycle.
