### ISSUE TITLE
Add tests cases for disabled IBC transfers

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#1913]
## Summary

Add test cases for `apps/transfer` which fail when the chain has sends/receives disabled

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by stackman27** [comment]
@colin-axner @crodriguezvega can i get little more context on this issue. I think i can take this on

**Comment by bznein** [comment]
I'd like to take this issue if possibile :)

**Comment by crodriguezvega** [comment]
Hey @bznein. Thank you, that would be fantastic. I will assign it to you now. :) Feel free to ask questions if you need to.
