### ISSUE TITLE
MsgTransferResponse should include the packet sequence

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#1969]
## Summary

`MsgTransferResponse` should include the sequence of the packet the transfer is sent in. The value derived in `SendTransfer` within `relay.go` should be returned in the message response. The SendTransfer API will need to be modified. 

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
This has addition has been requested from [external feedback](https://github.com/cosmos/ibc-go/pull/1703#discussion_r950915915)

**Comment by crodriguezvega** [comment]
- Add sequence number to [`MsgTransferResponse` in `proto/ibc/applications/transfer/v1/tx.proto`](https://github.com/cosmos/ibc-go/blob/main/proto/ibc/applications/transfer/v1/tx.proto#L44):

```proto
// MsgTransferResponse defines the Msg/Transfer response type.
message MsgTransferResponse {
  // sequence number of the packet the transfer is sent it
  uint64 sequence = 1;
}
```

- Change signature of [`SendTransfer` function in `modules/apps/transfer/keeper/relay.go`](https://github.com/cosmos/ibc-go/blob/main/modules/apps/transfer/keeper/relay.go#L53) to :

```go
func (k Keeper) SendTransfer(
	ctx sdk.Context,
	sourcePort,
	sourceChannel string,
	token sdk.Coin,
	sender sdk.AccAddress,
	receiver string,
	timeoutHeight clienttypes.Height,
	timeoutTimestamp uint64,
) (error, uint64) 
```

- Return 0 in the second return argument for all the error situations inside the `SendTransfer` function; return the [`sequence` found](https://github.com/cosmos/ibc-go/blob/main/modules/apps/transfer/keeper/relay.go#L80) in the [last return statement of the function](https://github.com/cosmos/ibc-go/blob/main/modules/apps/transfer/keeper/relay.go#L186).

- Retrieve the `sequence` on [the place where `SendTransfer` is called in `modules/apps/transfer/keeper/msg_server.go`](https://github.com/cosmos/ibc-go/blob/main/modules/apps/transfer/keeper/msg_server.go#L22-L26) and include it in the `MsgTransferResponse`:

```go
err, sequence := k.SendTransfer(
  ctx, msg.SourcePort, msg.SourceChannel, msg.Token, sender, msg.Receiver, msg.TimeoutHeight, msg.TimeoutTimestamp,)
if err != nil {
  return nil, err
}

...

return &types.MsgTransferResponse{sequence}, nil
```

**Comment by crodriguezvega** [comment]
Assigned to @agouin.
