### ISSUE TITLE
Make IBCtesting GetStakingKeeper be based on an interface

### ISSUE THREAD

**Issue by ValarDragon** [cosmos/ibc-go#1971]
## Summary

The IBCtesting `GetStakingKeeper` required interface method (https://github.com/cosmos/ibc-go/blob/main/testing/app.go#L39) should not depend on the literal staking keeper in the hub.

This should instead have an interface dependency, to account for apps doing weirder things with their staking modules. E.g. Osmosis superfluid staking, we really need to look at what IBC depends on, to determine what we should be returning.

Also would recommend renaming to `GetIBCTestingStakingKeeper` as part of this.

## Problem Definition

The current design inhibits modularity of ibctesting, for a small reason.

## Proposal

Define an interface for what keeper methods IBC depends on from the staking keeper, and then define an interface accordingly. Use that interface in the required ibctesting app interface.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
@ValarDragon if the API is changed to:
```go
GetStakingKeeper() ibctestingtypes.StakingKeeper
```

do you still want this change:
> Also would recommend renaming to GetIBCTestingStakingKeeper as part of this.
