### ISSUE TITLE
Move verifyMisbehaviour to misbehaviour_handle.go for 06-solomachine

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2004]
## Summary

[`verifyMisbehaviour`](https://github.com/cosmos/ibc-go/blob/main/modules/light-clients/06-solomachine/update.go#L86) should be placed in `misbehaviour_handle.go`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by Daniyal98** [comment]
Hello, I am looking to contribute on this issue.
