### ISSUE TITLE
Move non-verification misbehaviour checks to CheckForMisbehaviour

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2007]
## Summary

In 07-tendermint, we are checking whether something is misbehaviour in `VerifyClientMessage`, we should instead be doing this in `CheckForMisbehaviour`. Move this batch of [code](https://github.com/cosmos/ibc-go/blob/main/modules/light-clients/07-tendermint/misbehaviour_handle.go#L26-#L46) to `CheckForMisbehaviour

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by Daniyal98** [comment]
Hello, I would like to start working on this issue. Thank you!

**Comment by charleenfei** [comment]
@Daniyal98 are you still working on this?

**Comment by Daniyal98** [comment]
@charleenfei It wasn't assigned to me so I didn't start working on it

**Comment by charleenfei** [comment]
sorry about that! i am assigning you now :)

**Comment by colin-axner** [comment]
Apologies for the delayed reply @Daniyal98. Will you be able to work on this issue now, or is it not the right time to pickup the issue? This issue is apart of our next iteration (Nov 28 - Dec 11) and we would like to complete it soon

**Comment by Daniyal98** [comment]
@colin-axner yeah sure. I will try my best :)

**Comment by Daniyal98** [comment]
@colin-axner the statement of this issue seems a bit misleading. The part that you mentioned is already in CheckForMisbehaviour. Am I missing something?

**Comment by colin-axner** [comment]
Hi @Daniyal98 apologies again for the late reply! When I made the issue, I linked to main, but the code got moved around. The part of the code that should be moved is [here](https://github.com/cosmos/ibc-go/blob/7d60efa07b7d564e5d4f531a0398d3f670fc973f/modules/light-clients/07-tendermint/misbehaviour_handle.go#L71-#L93), it should be moved into the switch statement case `Misbehaviour` in `CheckForMisbehaviour`

The idea is that when we check for misbehaviour, we have three cases to check for:
- if it is a header, check if we already had a valid update for this height (and that the update isn't a duplicate)
- if it is misbehaviour, check for time misbehaviour (produced two headers which disobey BFT time restrictions
- if it is misbheaviour, check for fork misbehaviour (two headers at the same height)

Since `CheckForMisbehaviour` should check all three cases, moving the code will complete this logical layout with `verifyMisbehaviour` only verifying that the two headers provided were produced by the validator set

**Comment by crodriguezvega** [comment]
@Daniyal98 will you have time to work on this one relatively soon? No worries if you can't, but please let us know, so that we can take it otherwise. Thanks!

**Comment by Daniyal98** [comment]
Yes sure. I'll start working on it right away.
@crodriguezvega

**Comment by crodriguezvega** [comment]
> Yes sure. I'll start working on it right away.
> @crodriguezvega

Much appreciated, @Daniyal98!
