### ISSUE TITLE
Update e2e test harness to allow for n chains 

### ISSUE THREAD

**Issue by seantking** [cosmos/ibc-go#2012]
## Summary

Currently, the helper fns in our TestSuite allows for only [two chains](https://github.com/cosmos/ibc-go/blob/main/e2e/testsuite/testsuite.go#L95) to be run as part of the network. 

[Some tests](https://github.com/cosmos/ibc-go/issues/1968) will require 3+ chains with channels created between them. 

- [ ] Update the helper fns to allow for a user-defined amount of chains to be spun up as part of the test network. 
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
Worth nothing that we also want to be able to run tests with a single chain, so we should make sure to account for n >= 1

**Comment by chatton** [comment]
this is now supported :partying_face:
