### ISSUE TITLE
change type of `scopedKeeper` in all `Keeper`s to interface

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#2020]
The `scopedKeeper` in all `Keeper`s in ibc-go has at the moment a concrete type (i.e. `capabilitykeeper.ScopedKeeper`), but there is no good reason why we should not use an interface instead. Other keepers in the `Keeper` types are already using interfaces.

### Proposal

1. Add `ScopedKeeper` interface.

For 05-port create an `expected_keepers.go` file in package `types` and add the following interface:
 
```go
type ScopedKeeper interface {
  NewCapability(ctx sdk.Context, name string) (*capabilitytypes.Capability, error)
  GetCapability(ctx sdk.Context, name string) (*capabilitytypes.Capability, bool)
  AuthenticateCapability(ctx sdk.Context, cap *capabilitytypes.Capability, name string) bool
  LookupModules(ctx sdk.Context, name string) ([]string, *capabilitytypes.Capability, error)
}
```

For `04-channel` add the following interface to [`expected_keepers.go`](https://github.com/cosmos/ibc-go/blob/v4.0.0/modules/core/04-channel/types/expected_keepers.go):

```go
type ScopedKeeper interface {
  NewCapability(ctx sdk.Context, name string) (*capabilitytypes.Capability, error)
  AuthenticateCapability(ctx sdk.Context, cap *capabilitytypes.Capability, name string) bool
  LookupModules(ctx sdk.Context, name string) ([]string, *capabilitytypes.Capability, error)
}
```

For `transfer` add the following interface to [`expected_keepers.go`](https://github.com/cosmos/ibc-go/blob/v4.0.0/modules/apps/transfer/types/expected_keepers.go):

```go
type ScopedKeeper interface {
  GetCapability(ctx sdk.Context, name string) (*capabilitytypes.Capability, bool)
  AuthenticateCapability(ctx sdk.Context, cap *capabilitytypes.Capability, name string) bool
  LookupModules(ctx sdk.Context, name string) ([]string, *capabilitytypes.Capability, error)
}
```

For `27-interchain-accounts` add the following interface to [`expected_keepers.go`](https://github.com/cosmos/ibc-go/blob/v4.0.0/modules/apps/27-interchain-accounts/types/expected_keepers.go):

```go
type ScopedKeeper interface {
  GetCapability(ctx sdk.Context, name string) (*capabilitytypes.Capability, bool)
  AuthenticateCapability(ctx sdk.Context, cap *capabilitytypes.Capability, name string) bool
  LookupModules(ctx sdk.Context, name string) ([]string, *capabilitytypes.Capability, error)
}
```

where `capabilitytypes` is alias for `github.com/cosmos/cosmos-sdk/x/capability/types`.

2. Change the type for the `scopedKeeper` field in the `Keeper` type of:
- [05-port](https://github.com/cosmos/ibc-go/blob/v4.0.0/modules/core/05-port/keeper/keeper.go#L19) - [PR](https://github.com/cosmos/ibc-go/pull/2025)
- [04-channel](https://github.com/cosmos/ibc-go/blob/v4.0.0/modules/core/04-channel/keeper/keeper.go#L35) - [PR](https://github.com/cosmos/ibc-go/pull/2024)
- [transfer](https://github.com/cosmos/ibc-go/blob/v4.0.0/modules/apps/transfer/keeper/keeper.go#L28) - [PR](https://github.com/cosmos/ibc-go/pull/2034)
- [27-interchain-accounts controller](https://github.com/cosmos/ibc-go/blob/v4.0.0/modules/apps/27-interchain-accounts/controller/keeper/keeper.go#L31) and [27-interchain-accounts host](https://github.com/cosmos/ibc-go/blob/v4.0.0/modules/apps/27-interchain-accounts/host/keeper/keeper.go#L31) - [PR](https://github.com/cosmos/ibc-go/pull/2035/files)

to the corresponding interface type created on step 1.

### Notes

- Consider opening different PRs for the changes affecting each part of the codebase.
- This is an API breaking change.

**Comment by Anmol1696** [comment]
Would like to take this up?

**Comment by crodriguezvega** [comment]
> Would like to take this up?

That would be great! Thanks! I will assign the issue to you now. Don't hesitate to reach out if there's something we can help you with.

**Comment by Anmol1696** [comment]
Wanted to ask, how is this API breaking change? Since the scopedKeeper is just an unexported struct field.

**Comment by Anmol1696** [comment]
Created the first PR for 04-channel, let me know if there is anything missing here, will be creating following PRs.
The only thing i am still not sure off is the changes needed for the core keeper.

**Comment by crodriguezvega** [comment]
> Wanted to ask, how is this API breaking change? Since the scopedKeeper is just an unexported struct field.

Thanks for asking! We are changing the type of the field, so the `NewKepper` function accepts now as well a different type for this field, and since this function is part of our external API, then we consider it a breaking change. Basically what @colin-axner  also says [here](https://github.com/cosmos/ibc-go/pull/2024#pullrequestreview-1075802093). I hope this answers your question!

**Comment by Anmol1696** [comment]
Yup it does, thanks. Will complete all the other remaining PRs.

**Comment by Anmol1696** [comment]
After all the PRs, I feel the only place left where we do not use a keeper interface is [core/keeper](https://github.com/cosmos/ibc-go/blob/main/modules/core/keeper/keeper.go#L42).

Do you guys think it makes sense to have a `ScopedKeeper` interface? Would a bit tricky since we would have to create interface with union of methods in `core/types` perhaps or use the interface from one of the modules which has the most methods, like the way this NewKeeper uses `clienttypes.StakingKeeper` interface.

**Comment by colin-axner** [comment]
You can add the interface to the [exported directory](https://github.com/cosmos/ibc-go/tree/main/modules/core/exported). Maybe add a `expected_keepers.go` file?

**Comment by crodriguezvega** [comment]
@Anmol1696 would you like to try @colin-axner's proposal to see if that would work?

**Comment by damiannolan** [comment]
> You can add the interface to the [exported directory](https://github.com/cosmos/ibc-go/tree/main/modules/core/exported). Maybe add a `expected_keepers.go` file?

Would this interface fit in `channel.go`? 🤔

**Comment by colin-axner** [comment]
The purpose of the exported directory is to expose interfaces which will be imported outside of a single package which allows us to work around import cycles created by the dependency of `core/types` on its subdirectory types. It allows us to import shared interfaces. Putting the interface in the 04-channel types directory is probably more intuitive. 05-port already imports channeltypes anyways (which is the other submodule using this keeper)

**Comment by Anmol1696** [comment]
So the expection here is we move all the `ScopedKeeper interface` to exported package and use that instead of defining the similar interface everywhere (04-channel, 05-port, transfer, 27-interchain)?

**Comment by Anmol1696** [comment]
I can restrcuture the interfaces if you think so, just want to understand that is what is needed here.

**Comment by colin-axner** [comment]
I don't have a strong preference. I'd be fine leaving the scoped keeper as a concrete type in the ibc keeper, there isn't a good reason for it to be swapped for a different capability implementation. If we wanted to make it an interface, I think all scoped keepers relying on an interface within exported probably makes the most sense

**Comment by damiannolan** [comment]
Personally I feel like this would have been fine left as the concrete type from `x/capability`. Like you said I don't see any reason why someone would use a modified capability implementation. But given that the current state is a `ScopedKeeper` interface in each module I would at least like to see it move out to exported so that it is common.

**Comment by Anmol1696** [comment]
The only reason to make this into an interface in the first place was to add composibility for each of the package. Moving it to exported to me makes it a weird dependency loop. Either i am not understanding the name of the package `exported`, to me it is still weird internal packages use exported interfaces.

But since both @damiannolan and @colin-axner both want the interface to be moved to exported package, i will create the PR for the same then.

**Comment by Anmol1696** [comment]
For the PR I moved the scoped interface to core/exported package, and that is used everywhere now. 
I am not 100% sure on the dependency loop it creates from `app` to `core` though. 

Let me know if it makes sense, or we want to keep the `app` ScopedInterface seperate.

PS. I also updated the changelog, but all points point to the same PR. Let me know if that is ok.

**Comment by colin-axner** [comment]
I am not sure I follow your concerns. `exported` perhaps isn't the best naming, but the purpose of the `exported` package is to gather all the shared interfaces into one package. The `exported` package should not import any of ibc-go (thus creating import cycles). Does that ease your concerns?

**Comment by Anmol1696** [comment]
Makes sense @colin-axner thanks. Yes, not a concern, just the name `exported` confused me.
