### ISSUE TITLE
/ibc/apps/transfer/v1/denom_hashes/{trace} is not a supported query endpoint

### ISSUE THREAD

**Issue by charleenfei** [cosmos/ibc-go#2031]
## Summary of Bug

we've got the endpoint in the query proto but it actually doesnt have a handler, we should remove it or support it

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Maybe I'm missing something, but isn't it implemented in [this handler](https://github.com/cosmos/ibc-go/blob/main/modules/apps/transfer/keeper/grpc_query.go#L86)?

**Comment by charleenfei** [comment]
oh yea, it should be. but apparently it's not working? let me actually close this issue and get a bug report from the person who reported.
