### ISSUE TITLE
Add the ability to inject message routers that support ADR 031

### ISSUE THREAD

**Issue by Taztingo** [cosmos/ibc-go#2044]
## Summary

The ibc-go submodule keepers do not allow custom message routing, and we are forced to use baseapp.MsgServiceRouter. It would be very helpful to allow injection of custom routers that support ADR 031 request type routing.

## Problem Definition

This is an issue for projects that need use their own router. **ICA is unusable to them, and is currently blocking them**

## Proposal

Allow users to inject routers that support ADR 031 into icacontroller.keeper and icahost.keeper. A great example of this is how wasmd added the MessageRouter interface. https://github.com/CosmWasm/wasmd/pull/717

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
Ah yes! Nice suggestion, sorry we didn't implement this from the start!
