### ISSUE TITLE
Add ics27 e2e test with governance

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2063]
## Summary

Add an e2e test with ics27 using governance as the authorization method. Low priority

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
It looks like this is not actually possible using the new governance module. See [this slack thread](https://interchainfoundation.slack.com/archives/C026XUXCE7K/p1662566685645849). And [the gov module docs](https://github.com/cosmos/gaia/blob/glnro/gov-docs/docs/modules/gov.md)

**Comment by chatton** [comment]
It looks like [this issue](https://github.com/cosmos/cosmos-sdk/issues/13389) is preventing the full flow to work as events are not being emitted correctly once the governance proposal passes. thank you @damiannolan for all the help investigating this issue ❤️

**Comment by okwme** [comment]
Fix is included in https://github.com/cosmos/cosmos-sdk/releases/tag/v0.46.4
