### ISSUE TITLE
Add Params gRPC to transfer 

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2066]
## Summary

Add a `Params` gRPC for the ics20 module. Following #2010 we will need to self manage our own params. Thus it makes sense to expose a Params gRPC as soon as possible for backwards compatibility purposes

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
We should backport to any versions for which we will still be supporting when the x/params module is deprecated

**Comment by crodriguezvega** [comment]
If I'm not mistaken, this is actually already implemented:

- [rpc service definition](https://github.com/cosmos/ibc-go/blob/main/proto/ibc/applications/transfer/v1/query.proto#L24-L27) in `proto/ibc/applications/transfer/v1/query.proto`.
- [implementation of gRPC endpoint](https://github.com/cosmos/ibc-go/blob/main/modules/apps/transfer/keeper/grpc_query.go#L75-L83) in `modules/apps/transfer/keeper/grpc_query.go` with corresponding [tests](https://github.com/cosmos/ibc-go/blob/main/modules/apps/transfer/client/cli/query.go#L85-L112).
- [CLI query](https://github.com/cosmos/ibc-go/blob/main/modules/apps/transfer/client/cli/query.go#L85-L112) in `modules/apps/transfer/client/cli/query.go`.

**Comment by colin-axner** [comment]
Yup! Looks like it to me
