### ISSUE TITLE
e2e tests aren't checking transaction execution code to determine successful result

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2070]
## Summary

While working on governance proposal submission tests I realized it was possible to have a failed transaction which returned no error. So:
```go
txResp, err := s.BroadcastMessages(msg) // message fails
s.Require().NoError(err) // this check pass
s.Require().AssertValidTxResponse(txResp) // fails on empty events
```

The message is broadcasted but errors in the state machine so the transaction code != 0. Our code isn't really explicitly checking this. 

## Proposal

Change `AssertValidTxResponse` to `AssertSuccessfulTx` (or `AssertTxSuccess`). Add a line to the function
```go
s.Require().Equal(0, txResp.Code)
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Proposed change has been [implemented](https://github.com/cosmos/ibc-go/blob/main/e2e/testsuite/tx.go#L109) in https://github.com/cosmos/ibc-go/pull/3475.
