### ISSUE TITLE
Remove simd gen accounts command in favor of SDK command

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2072]
## Summary

We should import the SDK genesis accounts command instead of replicating our [own](https://github.com/cosmos/ibc-go/blob/main/testing/simapp/simd/cmd/root.go#L165)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by hieuvubk** [comment]
Is this issue still available @colin-axner ? I would like to work with it

**Comment by crodriguezvega** [comment]
> Is this issue still available @colin-axner ? I would like to work with it

Yes, thank you, @hieuvubk!
