### ISSUE TITLE
e2e IBC client upgrade

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2074]
## Summary

Add an e2e test for upgrading an ibc client. In theory it should be [possible](https://github.com/strangelove-ventures/ibctest/pull/197). Might be useful to split this issue up into smaller bite sized sections (add just submission of the upgrade proposal, add execution of the upgrade, add relaying of the MsgUpgradeClient, etc)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
Here's how the test can work:
- create two chains, a channel between them, send a packet
- create a [ibc software uprgade proposal](https://github.com/cosmos/ibc-go/blob/main/modules/core/02-client/types/proposal.go#L75)
- perform the upgrade using a handler which changes a chain specific field like the [unbonding period](https://github.com/cosmos/gaia/pull/500/files#diff-0f1d2976054440336a576d47a44a37b80cdf6701dd9113012bce0e3c425819b7R264)
- restart the chains
- ensure the clients cannot be updated normally
- use the relayers to perform the client upgrade
- ensure clients can be updated normally/process packets

**Comment by chatton** [comment]
After doing some investigation into this, I've run into a few issues.

- The [relayer](https://github.com/strangelove-ventures/interchaintest/blob/main/ibc/relayer.go#L25) interface does not yet expose an `UpgradeClient` function.
-  The golang relayer will create a new client when there is a mismatch [here](https://github.com/cosmos/relayer/blob/a75b26f0239031f6c139bd6dba920c8442083463/relayer/provider/matcher.go#L18) and so it is difficult to re-use the existing client in the test to verify it does not work.

I'm not sure if it is possible to actually write this test without being able to
- directly specify an existing client ID to attempt to re-use in a test.

**Comment by crodriguezvega** [comment]
I will close this issue in favour of https://github.com/cosmos/ibc-go/issues/4619, but I will link it there not to lose the comments here.
