### ISSUE TITLE
expose connection version as a grpc query

### ISSUE THREAD

**Issue by charleenfei** [cosmos/ibc-go#211]
## Summary

Currently, the connection version is negotiated during the connection handshake. It would be great to expose a query which returns this value, in order to support use cases like versioning between ibc + general fees mechanism and ibc without.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
The connection version is stored in the connection structure. Is there a reason the connection grpc cannot be used?

**Comment by colin-axner** [comment]
Closing since the version can be obtained from the connection end
