### ISSUE TITLE
Make the number of validators and full nodes configurable in E2E tests

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#2111]
## Summary

The current numbers are specified directly [here](https://github.com/cosmos/ibc-go/blob/0fa2978b0edad338f995790b5ab3a517ff302351/e2e/testsuite/testsuite.go#L333)

We should allow the number of validators and full nodes to be configurable on a per test basis. This could be done with more env vars or some sort of other configuration method.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by damiannolan** [comment]
can this be closed?

**Comment by chatton** [comment]
I think so yes 👍
