### ISSUE TITLE
Add gRPC for ics27 controller params

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2115]
## Summary

Same issue as #2066 but for ics27 controller params

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
I think this is [already implemented](https://github.com/cosmos/ibc-go/blob/main/modules/apps/27-interchain-accounts/controller/keeper/grpc_query.go#L38-L46).

**Comment by colin-axner** [comment]
Yup!
