### ISSUE TITLE
Add param change e2e test for ics27 controller params

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2116]
## Summary

Add an e2e test for modifying ics27 controller params. Should ensure the controller is enabled and accounts can be registered/used and then the controller should be disabled and accounts cannot be registered/used

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Use gov v1 message when #3590 is merged.
