### ISSUE TITLE
Add gRPC for ics27 host

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2117]
## Summary

Same issue as https://github.com/cosmos/ibc-go/issues/2066 but for ics27 host params

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
I think this is [already implemented](https://github.com/cosmos/ibc-go/blob/main/modules/apps/27-interchain-accounts/host/keeper/grpc_query.go#L13-L21).

**Comment by colin-axner** [comment]
Ay looks like it, nice catch
