### ISSUE TITLE
Add gRPC for 02-client params

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2119]
## Summary

Same as #2066 but for 02-client params

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
I think this is [already implemented](https://github.com/cosmos/ibc-go/blob/main/modules/core/02-client/keeper/grpc_query.go#L255-L263).

**Comment by colin-axner** [comment]
Yup, but I think we could rename to params to be consistent
