### ISSUE TITLE
Allow for silencing of logs on e2e

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2129]
## Summary

It'd be nice if we could silence the node logs on e2e tests. When writing the test, I often just look for the s.Require() output and ignore all the logs

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
To clarify are you suggesting we silence logs  when running locally, but not on GH workflow runs.  Or a mechanism to reduce verbosity in both places?

**Comment by colin-axner** [comment]
I'd like at least the ability to silence logs locally

**Comment by expertdicer** [comment]
Is this still needed? TYSM

**Comment by colin-axner** [comment]
I'm going to close the issue, I've become acclimatized to the logs. It helps you know the test is running. The main pain point would be the extra logs dumped after the failure, but I believe the issue for that is in interchain test

Thanks for asking @expertdicer
