### ISSUE TITLE
Empty ICA state causes a panic on ExportGenesis

### ISSUE THREAD

**Issue by technicallyty** [cosmos/ibc-go#2151]
## Summary of Bug

If no initial state is given to the module, calling ExportGenesis on the module, or the app in general, will cause a panic, due to [this line](https://github.com/cosmos/ibc-go/blob/main/modules/apps/27-interchain-accounts/host/keeper/params.go#L13), which gets the params from the paramKeeper subspace. `subspace.Get` causes a panic if the parameter does not yet exist.

## Expected Behaviour

ExportGenesis should not panic if the module has no state. It might be more preferable to use `GetIfExists` when getting the parameters for exporting state to prevent such errors.

## Version

[v5](https://github.com/cosmos/ibc-go/releases/tag/v5.0.0-rc1)

## Steps to Reproduce

- add ICA to new chain
- do not import any state or set any params
- export genesis on the chain
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
Hi @technicallyty, thanks for opening the issue. Based on your [comment](https://github.com/regen-network/regen-ledger/pull/1441/files#r959053366) this looks like a duplicate issue of #1352. Is that correct?

I believe it is expected that a panic will occur if an SDK module does not have its state initialized

**Comment by colin-axner** [comment]
We will implement sims for >= v5 and then second concern will be addressed when we migrate our params to be self managed #2010 

I believe the SDK traditionally panic'd on [unset params](https://github.com/cosmos/cosmos-sdk/blob/252c6736161e51342bb7dd6af984082a2b064742/x/bank/keeper/send.go#L63) (this is from v0.46.1) and that this behaviour changed when it migrated to self managed params. I agree this behaviour is incorrect as one should not cause ExportGenesis to panic. It seems like a very unlikely edge case as the app.go would have to be misconfigured (not calling app.mm.InitGenesis) so I don't see reason to prioritize this change
