### ISSUE TITLE
Emit events from keeper rather than msg_server for client/connection

### ISSUE THREAD

**Issue by seantking** [cosmos/ibc-go#221]
## Summary of Bug
Same issue as https://github.com/cosmos/ibc-go/issues/219 but for the client/connection handlers. 

We can remove these and emit the events in the keeper + msg_server directly. 

## Version

v1.00 beta

## Steps to Reproduce

When calling the keeper functions directly, we do not emit any events. This is a problem when you need the relayer to listen for events and want to call the IBC keeper functions from other modules.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
@seantking, if I am not mistaken this issue is out of date now, right? I will close for now. If am wrong, please reopen it.
