### ISSUE TITLE
SendTransfer should return the sequence of the packet back in return arg

### ISSUE THREAD

**Issue by charleenfei** [cosmos/ibc-go#2264]
## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
@charleenfei, I believe this would be a duplicate of [#1969](https://github.com/cosmos/ibc-go/issues/1969)?

**Comment by charleenfei** [comment]
ah yes that looks right! We need to pick up this issue 🙈 I'll close this one then
