### ISSUE TITLE
modules/apps/27-interchain-accounts/types: simply use a string concatenation instead of fmt.Sprint(PortPrefix, owner) to build PortID in NewControllerPortID

### ISSUE THREAD

**Issue by odeke-em** [cosmos/ibc-go#2265]
## Summary of Bug
This is more of a nit but one of caution to avoid complex code yet the result is to be a simple string concatenation per https://github.com/cosmos/ibc-go/blob/8045fcccbd30d28e50146a75e50773d8aafe84ab/modules/apps/27-interchain-accounts/types/port.go#L16

which really is a string concatenation but somehow fmt.Sprint was used. That code can quickly become invalid if someone mistakenly used fmt.Sprintf with this simple demo at https://go.dev/play/p/HQw2_PJIQ1M or inlined below

```go
package main

import (
	"fmt"
)

const PortPrefix = "icacontroller-"

func main() {
	p1 := fmt.Sprint(PortPrefix, "owner")
	println("Current", p1)

	p2 := fmt.Sprintf(PortPrefix, "owner")
	println("Caution", p2)

	p3 := PortPrefix + "owner"
	println("Simpler", p3)
}
```

which prints out
```shell
Current icacontroller-owner
Caution icacontroller-%!(EXTRA string=owner)
Simpler icacontroller-owner
```

## Version
a4be5614fb2fc92cfb430c82f18e7a9f67383c6e

____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
I guess the alternative would be to use `+`, right? I don't have a strong preference for either, but I guess that if somebody made the mistake of using `fmt.Sprintf` that should have been easily caught in a unit test.
