### ISSUE TITLE
modules/apps/27-interchain-accounts/controller/types: (Params).Validate suspiciously performs no checks yet unnecessary conversions from bool to interface then checks if value is a bool and not if it is enabled

### ISSUE THREAD

**Issue by odeke-em** [cosmos/ibc-go#2266]
## Summary of Bug

This code in here https://github.com/cosmos/ibc-go/blob/8045fcccbd30d28e50146a75e50773d8aafe84ab/modules/apps/27-interchain-accounts/controller/types/params.go#L34-L41

claims its purpose is to
```go
// Validate validates all controller submodule parameters
```

but if we examine its internals, firstly p.ControllerEnabled is a bool, but when it gets passed into validateEnabled, it gets turned into an interface{} value https://github.com/cosmos/ibc-go/blob/8045fcccbd30d28e50146a75e50773d8aafe84ab/modules/apps/27-interchain-accounts/controller/types/params.go#L50 and alas all that code does is type assert that the value is of type bool (hint: it was a bool) and that's all that that function does https://github.com/cosmos/ibc-go/blob/8045fcccbd30d28e50146a75e50773d8aafe84ab/modules/apps/27-interchain-accounts/controller/types/params.go#L50-L57 so essentially that code does nothing.

## Suggestion
Shouldn't we be returning an error if !p.ControllerEnabled?

## Version
a4be5614fb2fc92cfb430c82f18e7a9f67383c6e

____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Thanks very much, @odeke-em, for these issues that you have opened!

Regarding this one in particular, I was digging a bit and it seems like we do a similar thing for other params: see for [ics20 transfer](https://github.com/cosmos/ibc-go/blob/8045fcccbd30d28e50146a75e50773d8aafe84ab/modules/apps/transfer/types/params.go#L41-L48) and [ics27 ICA host](https://github.com/cosmos/ibc-go/blob/8045fcccbd30d28e50146a75e50773d8aafe84ab/modules/apps/27-interchain-accounts/host/types/params.go#L41-L51). And I was checking the SDK as well a bit and similar thing seems to be done for [x/staking](https://github.com/cosmos/cosmos-sdk/blob/main/x/staking/types/params.go#L89-L111).

So if I understand it correctly it seems like this validation makes sure that the parameters are of the correct type and are in an allowed range, so to reply to your questions "Shouldn't we be returning an error if !p.ControllerEnabled?" I think we should not.

Why the parameters are converted to an `interface` and then casted to the expected type that's something I don't know... Maybe @colin-axner knows the reason for that.

**Comment by odeke-em** [comment]
Thank you @crodriguezvega for the reply! The current form of that code basically does nothing so if all that code were scraped and nil were returned it would be the equivalent. We should perhaps figure out what to validate in there.
