### ISSUE TITLE
modules/core/keeper: NewKeeper blank value detection assumes interface values are all non-pointer receivers and will fail to detect blank pointer receivers

### ISSUE THREAD

**Issue by odeke-em** [cosmos/ibc-go#2268]
## Summary of Bug
The code inside https://github.com/cosmos/ibc-go/blob/a4be5614fb2fc92cfb430c82f18e7a9f67383c6e/modules/core/keeper/keeper.go#L52-L60 checks if values are Zero values using reflect.ValueOf. That'll work in cases where value receivers are passed in. However, for a general purpose package that receives either pointer or value receivers, this forces odd behavior in which only value receivers can be checked. For example if we examine https://go.dev/play/p/zfFZRDjqz-X or inlined below
```go

package main

import (
	"io"
	"reflect"
)

type dt struct {
	i int
	s string
}

func (dt) Write(b []byte) (int, error) { return len(b), nil }

func main() {
	println(reflect.ValueOf(dt{}).IsZero())
	println(reflect.ValueOf(&dt{}).IsZero())
	println(reflect.ValueOf((io.Writer)(dt{})).IsZero())
	println(reflect.ValueOf((io.Writer)(&dt{})).IsZero())
}
```

Which prints out

```shell
true
false
true
false
```

But really if zero value checking were implemented correctly by dereferencing pointers, every line should print true.

## Expected Behaviour
Catching blank pointer values

Just an FYI for my colleagues @elias-orijtech @kirbyquerby @willpoint

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Maybe I am missing something, but the `stakingKeeper` and `upgradeKeeper` parameters need to be passed by value ([as the signature of NewKeeper indicates](https://github.com/cosmos/ibc-go/blob/a4be5614fb2fc92cfb430c82f18e7a9f67383c6e/modules/core/keeper/keeper.go#L39-L43)), so if in the upstream caller function they were pointers, they would need to be dereferenced before being passed to `NewKeeper`, right?

**Comment by odeke-em** [comment]
@crodriguezvega it expects values that conform to an interface. Anything that conforms to that interface can be passed in and they could either be pointers or non-pointers.

**Comment by crodriguezvega** [comment]
> @crodriguezvega it expects values that conform to an interface. Anything that conforms to that interface can be passed in and they could either be pointers or non-pointers.

Ah, yes, I see now. Thanks!

**Comment by alizahidraja** [comment]
Hey! I have added a switch case to cater to this issue, let me know if that works
