### ISSUE TITLE
modules/core/02-client/types: IsClientIDFormat regex permits invalid client types due to misinterpretation of regex syntax for character sets and also doesn't respect the specification which requires entirely ASCII

### ISSUE THREAD

**Issue by odeke-em** [cosmos/ibc-go#2269]
## Summary of Bug
The definition of an identifier is specified loosely at https://github.com/cosmos/ibc/tree/main/spec/core/ics-024-host-requirements#paths-identifiers-separators and it should
* contain entirely ASCII
* not have the path separator "/" in it
<img width="1275" alt="Screen Shot 2022-09-10 at 5 22 50 PM" src="https://user-images.githubusercontent.com/4898263/189506233-a6f62a62-da77-4438-aa3a-d9752feaf9b3.png">

If we look at this validation regex https://github.com/cosmos/ibc-go/blob/37aa2ebec4f63a178659db2de2761f3cbafb583c/modules/core/02-client/types/keys.go#L35-L37 and read the comment above, it says it would like to ensure that client IDs are in the format `{client-type}-{N}` but if we look closely we can see a few things, the regex rule is `^.*[^\n-]-[0-9]{1,20}`
What that means:
* It can be preceded with anything but before we hit the hyphen "-" for the value of N, we can't have a newline "\n" nor hyphen "-"
* we can have non-ASCII in there

Unfortunately that means that now client-type can be "\t\t\t\t\t\t\t\t" (repeated as many times) then say "a" plus hyphen "-" then a number and the following values will erroneously be accepted:
* "\t\t\ta-100"
* "-----a-100"
* "                  a-100"
* "🚨😎-100"
and plenty more invalid patterns left to the imagination

## Remedy
If we were to correctly write that regex, we can simply eliminate and reduce it to `^\w+([\w-]+\w)?-[0-9]{1,20}$` to make it conform to specification

## Expected Behaviour

Rejection of the above listed patterns and non-ASCII values

## Version
a4be5614fb2fc92cfb430c82f18e7a9f67383c6e

____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Great catch, thanks!
