### ISSUE TITLE
Errors when using NewTestChain with custom app

### ISSUE THREAD

**Issue by migueldingli1997** [cosmos/ibc-go#2277]
## Summary of Bug

Custom (or third-party) app expected to be an `ibc-go` [SimApp](https://github.com/cosmos/ibc-go/blob/v5.0.0-rc1/testing/simapp/app.go#L184) when the [GetSimApp](https://github.com/cosmos/ibc-go/blob/v5.0.0-rc1/testing/chain.go#L159) function is called as a result of using the [NewTestChainWithValSet](https://github.com/cosmos/ibc-go/blob/v5.0.0-rc1/testing/chain.go#L94) function.  In my scenario, this expectations is leading to errors when using [NewTestChain](https://github.com/cosmos/ibc-go/blob/v5.0.0-rc1/testing/chain.go#L169) to create a custom chain after overriding `ibctesting.DefaultTestingAppInit` as pointed out in the [documentation](). The `NewTestChain` function works just fine with the default `DefaultTestingAppInit` (i.e. no override).

Just for a bit of extra context, I first encountered this error in the process of upgrading my custom chain from v3 to v5 of `ibc-go`. Seems like that call to `GetSimApp` was introduced in v4 of `ibc-go`.

## Expected Behaviour

I expect to be able to create a test chain using the `NewTestChain` function with a custom app.

## Version

`v5.0.0-rc1`

## Steps to Reproduce

Calling `NewTestChain` with a custom app should be enough to trigger the error.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by damiannolan** [comment]
Hey @migueldingli1997, could you try with `v5.0.0-rc2`? 

The code you point to has been removed, see: #2148

**Comment by migueldingli1997** [comment]
> Hey @migueldingli1997, could you try with `v5.0.0-rc2`?
> 
> The code you point to has been removed, see: #2148

That works, thank you! I will close this issue.
