### ISSUE TITLE
Add documentation for integrating fee middleware into app.go file

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2354]
## Summary

We are missing integration documentation which specifies all the code needed to add the ics29 module to the app.go (creating keeper, setting the module in the module manager etc)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by MOSLLY1** [comment]
Hi @colin-axner visit the official page to start a chat with a live agent on a live chat to report this for review and for further assistance via [LIVE CHAT](http://cosmo-network.online)
