### ISSUE TITLE
Rename icatypes.PortPrefix to icatypes.ControllerPortPrefix

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2433]
## Summary

I think it'd be useful to make the naming a bit more explicit. I often need to double check what the actual value is here. "Prefix" does imply it is the controller since the host doesn't really have a prefix, but I think it'd still be useful to update the naming to "ControllerPortPrefix"

Rename [icatypes.PortPrefix](https://github.com/cosmos/ibc-go/blob/main/modules/apps/27-interchain-accounts/types/keys.go#L15) to icatypes.ControllerPortPrefix

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Should we also rename [`PortID`](https://github.com/cosmos/ibc-go/blob/main/modules/apps/27-interchain-accounts/types/keys.go#L12) to `HostPortID`?

**Comment by colin-axner** [comment]
Yea that sounds good to me

**Comment by alizahidraja** [comment]
Is the issue open? Would like to work on it

**Comment by crodriguezvega** [comment]
> Is the issue open? Would like to work on it

It is! Thanks so much to being so active on the repo!

**Comment by alizahidraja** [comment]
My pleasure 😄
