### ISSUE TITLE
Remove all "TypeMsg.." constants

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2434]
## Summary

Throughout the codebase we have "TypeMsg..." constants such as:
- TypeMsgTransfer
- TypeMsgCreateClient
- etc

These should be removed

## Problem Definition

These constants are a relic of previous SDK functionality which used a string returned from a "Type()" function to route messages internally. The SDK now uses gRPC and thus the proto url to route messages. These constants should be unused and have no intended meaning at the moment

## Proposal

Remove all "TypeMsg..." constants. If they are being used somewhere, replace with appropriate usage

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
In the implementation of the `Type()` functions (like [here for transfer](https://github.com/cosmos/ibc-go/blob/main/modules/apps/transfer/types/msgs.go#L44), should we then just return the string directly (i.e. `"transfer"`)?

I also noticed that not all our messages implement this function: is it always needed? When is it required to be implemented?

**Comment by alizahidraja** [comment]
Lmk if I can work on this 👋

**Comment by crodriguezvega** [comment]
Yes, thank you, @alizahidraja!
