### ISSUE TITLE
e2e: Add upgrade test for v6 -> v7

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2438]
## Summary

requires: #2437 

Add an upgrade test to test upgrading from a v6 chain to v7 chain (or ideally upgrading from any pre v7 version)

ref #1908 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closed in favor of #2813
