### ISSUE TITLE
Change simd base image to reduce image size

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#2442]
## Summary of Bug

Currently we are using `ubuntu:20.04` as the base image for simd/icad. We could switch to an alpine based image to reduce image size and result in a minor speed improvement in e2e. (more so for forks as we only build the image once when running e2e )

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by DimitrisJim** [comment]
side comment: we build simd for fork pr's using `ubuntu-latest`, we might want to keep them in-sync unless we switch `e2e-fork.yml` to re-use the workflow `e2e.yaml` uses.
