### ISSUE TITLE
How ibc-go generate the existence proof of a packet?

### ISSUE THREAD

**Issue by ImJeremyHe** [cosmos/ibc-go#2449]
## Summary of Bug
I have investigated for a while that how an existence proof is generated in `ibc-go`.
But I found that it is always `nil` in the response.
https://github.com/cosmos/ibc-go/blob/ceddad57c9cae83ee8770cfdbbc2249ab749a14f/modules/core/04-channel/keeper/grpc_query.go#L223
I'm not sure whether this is the relevant code I am looking for.

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Hi @ImJeremyHe. The reason why the proof is `nil` in that response (and in the response of other gRPC queries of ibc-go) is the lack of support at SDK/Tendermint level for gRPC calls to return proofs for the query. There is [this issue](https://github.com/cosmos/cosmos-sdk/issues/7036) open in the SDK repo to add support for it. 

The way to get the proof would be to make an ABCI query using either [Tendermint's RPC endpoint](https://docs.tendermint.com/v0.34/rpc/#/ABCI/abci_query) or the [SDK's gRPC endpoint](https://github.com/cosmos/cosmos-sdk/pull/11642) that has been added recently (and released in v0.46).

I hope this helps!

**Comment by ImJeremyHe** [comment]
@crodriguezvega Thank you for your reply! Do you know where I can read the exact implementation of getting proof? There are so many relevant repo and I have no clue.

**Comment by crodriguezvega** [comment]
@ImJeremyHe Sorry for the late reply, but I didn't have the knowledge to be able to answer your question, until @AdityaSripal actually explained this week how it works.

When a relayer makes an ABCI query on Tendermint't RPC endpoint, Tendermint routes via ABCI [the query to the SDK](https://github.com/cosmos/cosmos-sdk/blob/main/baseapp/abci.go#L439). 

The steps to follow where a proof for data stored in IAVL is obtained are these: [1](https://github.com/cosmos/cosmos-sdk/blob/main/baseapp/abci.go#L474), [2](https://github.com/cosmos/cosmos-sdk/blob/main/baseapp/abci.go#L825), [3](https://github.com/cosmos/cosmos-sdk/blob/main/baseapp/abci.go#L842), [4](https://github.com/cosmos/cosmos-sdk/blob/main/store/rootmulti/store.go#L632), [5](https://github.com/cosmos/cosmos-sdk/blob/main/store/rootmulti/store.go#L651), [6](https://github.com/cosmos/cosmos-sdk/blob/main/store/iavl/store.go#L315), [7](https://github.com/cosmos/cosmos-sdk/blob/main/store/iavl/store.go#L360), [8](https://github.com/cosmos/cosmos-sdk/blob/main/store/iavl/store.go#L393) and finally inside this function the IAVL tree`GetMembershipProof` or `GetNonMembershipProof` functions are used to retrieved a proof depending on whether a existence or non-existence proof is needed.

I hope this helps!
