### ISSUE TITLE
Add incoming minor releases to compatibility tests

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2484]
## Summary

We have compatibility e2e tests that can be triggered via an action. I believe we need to add the release branches for v2.5, v3.4, v4.2, v5.1 to run the tests for these minor releases. I think they may need json files with the matrix as well, see https://github.com/cosmos/ibc-go/tree/main/.github/compatibility-test-matrices

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
We need to add json files as well as adding an entry [here](https://github.com/cosmos/ibc-go/blob/9fdcf2cfe7fa9905a02261c49134eeb9e5c2d8ef/.github/workflows/e2e-compatibility.yaml#L9-L11)

**Comment by crodriguezvega** [comment]
I believe this can be closed as done by #2640.
