### ISSUE TITLE
Unused variables in channel keeper 

### ISSUE THREAD

**Issue by alizahidraja** [cosmos/ibc-go#2486]
## Summary of Bug

This is a small issue, a bunch of unused variables in the following places.

[clientIDA](https://github.com/cosmos/ibc-go/blob/main/modules/core/04-channel/keeper/packet_test.go#L26)
[clientIDB](https://github.com/cosmos/ibc-go/blob/main/modules/core/04-channel/keeper/packet_test.go#L27) 
[portID](https://github.com/cosmos/ibc-go/blob/main/modules/core/04-channel/keeper/packet_test.go#L30)
[channelIDA](https://github.com/cosmos/ibc-go/blob/main/modules/core/04-channel/keeper/packet_test.go#L31)
[channelIDB](https://github.com/cosmos/ibc-go/blob/main/modules/core/04-channel/keeper/packet_test.go#L32)

 [err](https://github.com/cosmos/ibc-go/blob/main/modules/core/04-channel/keeper/handshake_test.go#L641)

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Thanks for pointing this out, @alizahidraja! Would you be interested in opening a PR to clean these up?

**Comment by alizahidraja** [comment]
No prob!

@Daniyal98 would be interested to work on it

**Comment by Daniyal98** [comment]
Thank you @alizahidraja. I would like to start working on it if this issue is still open.

**Comment by crodriguezvega** [comment]
> Thank you @alizahidraja. I would like to start working on it if this issue is still open.

It is, @Daniyal98. Thanks for picking it up!
