### ISSUE TITLE
ICS26 Spec inconsistencies and improvements

### ISSUE THREAD

**Issue by ebuchman** [cosmos/ibc-go#25]
Surfaced from Informal Systems IBC Audit

## Summary of Bug

ICS26 is effectively implemented in the `x/ibc/core/keeper/`. This could be clarified.

Code vs Spec:
- [ ] Spec always [calls module handler ("callback")](https://github.com/cosmos/ics/tree/4a85fc9/spec/ics-026-routing-module#channel-lifecycle-management) before calling IBC handler. Code alternates
  - eg. [ChanOpenInit](https://github.com/cosmos/cosmos-sdk/blob/88e03e4/x/ibc/core/keeper/msg_server.go#L266)/Try call the IBC handler first, module handler (callback) second, while OpenAck/Confirm do the reverse
  - eg. handlePacketRecv and handlePacketAck spec calls app handler first, code calls IBC handler first
  - does it matter what order these are called in ? Should we be consistent?
- [ ] [handlePacketRecv](https://github.com/cosmos/ics/tree/4a85fc9/spec/ics-026-routing-module#packet-relay) in spec doesnt write the ack; in [code](https://github.com/cosmos/cosmos-sdk/blob/88e03e4/x/ibc/core/keeper/msg_server.go#L453) it does

Few notes around return values and events. Could potentially be cleaned up clarified a bit:
- [ ] All returned results are empty - any data is sent through events.
- [ ] Inconsistency in where events are emitted. For client and connection handlers, events are emitted in the [ICS26](https://github.com/cosmos/cosmos-sdk/blob/88e03e4/x/ibc/core/keeper/msg_server.go#L239) code. For channels, events are emitted in [ICS04](https://github.com/cosmos/cosmos-sdk/blob/88e03e4f4056e8614847fd6adf17ce9252b6a89b/x/ibc/core/04-channel/handler.go#L21) code. 
- [ ] ICS04 handshake handlers [return sdk.Result containing events](https://github.com/cosmos/cosmos-sdk/blob/88e03e4f4056e8614847fd6adf17ce9252b6a89b/x/ibc/core/04-channel/handler.go#L36), but they're [ignored](https://github.com/cosmos/cosmos-sdk/blob/88e03e4/x/ibc/core/keeper/msg_server.go#L266)
- [ ] App module packet callbacks return sdk.Result containing events, but they're ignored (onReceive/Timeout/AcknowledgePacket)

Other code notes:
- [ ] packet-based [telemetry code](https://github.com/cosmos/cosmos-sdk/blob/88e03e4/x/ibc/core/keeper/msg_server.go#L459) in RecvPacket/Timeout/TimeoutOnClose can be deduplicated

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by crodriguezvega** [comment]
> - [ ] Spec always [calls module handler ("callback")](https://github.com/cosmos/ics/tree/4a85fc9/spec/ics-026-routing-module#channel-lifecycle-management) before calling IBC handler. Code alternates
>  - eg. [ChanOpenInit](https://github.com/cosmos/cosmos-sdk/blob/88e03e4/x/ibc/core/keeper/msg_server.go#L266)/Try call the IBC handler first, module handler (callback) second, while OpenAck/Confirm do the reverse
>  - eg. handlePacketRecv and handlePacketAck spec calls app handler first, code calls IBC handler first
>  - does it matter what order these are called in ? Should we be consistent?

I opened [an issue in the spec repo](https://github.com/cosmos/ibc/issues/851) asking if the spec should be updated to match the implementation.

> - [ ] [handlePacketRecv](https://github.com/cosmos/ics/tree/4a85fc9/spec/ics-026-routing-module#packet-relay) in spec doesnt write the ack; in [code](https://github.com/cosmos/cosmos-sdk/blob/88e03e4/x/ibc/core/keeper/msg_server.go#L453) it does


> - [ ] All returned results are empty - any data is sent through events.


> - [ ] Inconsistency in where events are emitted. For client and connection handlers, events are emitted in the [ICS26](https://github.com/cosmos/cosmos-sdk/blob/88e03e4/x/ibc/core/keeper/msg_server.go#L239) code. For channels, events are emitted in [ICS04](https://github.com/cosmos/cosmos-sdk/blob/88e03e4f4056e8614847fd6adf17ce9252b6a89b/x/ibc/core/04-channel/handler.go#L21) code.
> - [ ] ICS04 handshake handlers [return sdk.Result containing events](https://github.com/cosmos/cosmos-sdk/blob/88e03e4f4056e8614847fd6adf17ce9252b6a89b/x/ibc/core/04-channel/handler.go#L36), but they're [ignored](https://github.com/cosmos/cosmos-sdk/blob/88e03e4/x/ibc/core/keeper/msg_server.go#L266)
> - [ ] App module packet callbacks return sdk.Result containing events, but they're ignored (onReceive/Timeout/AcknowledgePacket)
