### ISSUE TITLE
Add assertions on escrow balance and error codes in transfer relay_test.go for send packet

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2514]
## Summary

see [comment](https://github.com/cosmos/ibc-go/pull/2446/files#r984321648). We should add assertions to `TestSendTransfer` in `modules/apps/transfer/keeper/relay_test.go`, which asserts that the tokens sent were deducted from the sender account balance and added to the escrow account. If an error is expected, if possible, we should assert the expected error code. If the error code comes from outside of ibc-go, I think it makes sense to simply assert that an error was returned (so as not to be dependent on outside error codes which might change)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
@colin-axner Isn't this the same as [this](https://github.com/cosmos/ibc-go/issues/2483)?

**Comment by colin-axner** [comment]
yes it is!
