### ISSUE TITLE
`ConnOpenInit()` should hardcode counterparty `connectionId` to `""`

### ISSUE THREAD

**Issue by plafer** [cosmos/ibc-go#2538]
## Summary of Bug
The spec [mandates](https://github.com/cosmos/ibc/blob/main/spec/core/ics-003-connection-semantics/README.md#opening-handshake) the counterparty `connectionId` to be set to `""` in `ConnOpenInit`. [ibc-go currently](https://github.com/cosmos/ibc-go/blob/c8e2ebcf2eaa6b487ca52499063c7c3db4253398/modules/core/03-connection/keeper/handshake.go#L41) needlessly relies on the relayer to set the value properly.

Analogous to https://github.com/cosmos/ibc-rs/issues/174.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Thanks for catching this, @plafer!

Way to fix it:

```diff
+ counterparty.ConnectionId = ""
  connection := types.NewConnectionEnd(types.INIT, clientID, counterparty, types.ExportedVersionsToProto(versions), delayPeriod)
  k.SetConnection(ctx, connectionID, connection)
```

**Comment by damiannolan** [comment]
The relayer should be able to leave the field empty and protobuf encoding will default to the field's zero value.

It's mandated in [`MsgConnectionOpenInit.ValidateBasic()`](https://github.com/cosmos/ibc-go/blob/main/modules/core/03-connection/types/msgs.go#L49) that it's unset, i.e. empty string.

**Comment by crodriguezvega** [comment]
Ah, cool. Thanks, @damiannolan, for pointing this out. Then we can close the issue.
