### ISSUE TITLE
Create a `CancelUpgradeProposal` type and Handler

### ISSUE THREAD

**Issue by AdityaSripal** [cosmos/ibc-go#255]
Currently there is a way to schedule upgrade in IBC, but no way to cancel.

We need to implement this to reach feature parity with regular upgrades.

cc: @colin-axner

**Comment by colin-axner** [comment]
IBC upgrades can be cancelled with a regular cancel upgrade proposal. What is the benefit of re-implementing it for IBC?

**Comment by AdityaSripal** [comment]
Oh perfect. then closing
