### ISSUE TITLE
Getting invalid route trying to create LinkRequest on Axelar with ICA

### ISSUE THREAD

**Issue by schnetzlerjoe** [cosmos/ibc-go#2554]
## Summary of Bug

I am submitting a TX via Interchain Accounts on Axelar, a MsgLinkRequest and I am receiving an "invalid route" response. I can see it is coming from here [line](https://github.com/cosmos/ibc-go/blob/90b051ec3c2e7d3576f9f2c99c470761735092f8/modules/apps/27-interchain-accounts/host/keeper/relay.go#L117) but I am not sure why. Maybe a better error message in future versions as well?

## Expected Behaviour

I expect it to work like any other ICA message, to run the LinkRequest message for me on the remote chain (Axelar).

## Version

IBC Go V3

## Steps to Reproduce

You can follow this repo here https://github.com/pitalco/axelar-transfer 
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Thanks, @schnetzlerjoe. I see that we discard the error returned by `Handler`, so I guess we could not discard it, and in case an error happens then we can wrap it and provide some extra information.

However, I also see that `Handler` is simply doing a [`map` lookup](https://github.com/cosmos/cosmos-sdk/blob/main/baseapp/msg_service_router.go#L36), so I guess the only possible error is that the message you're trying to execute is not present in the [`routes` map](https://github.com/cosmos/cosmos-sdk/blob/main/baseapp/msg_service_router.go#L19) and therefore it cannot find a `MsgServiceHandler` for it... Would it be possible for you to double check that the message is properly registered?



If we make this change in a branch, would it be possible for you to build the `axelard` binary with it and test in the repository that you link? I guess it will be easier to debug the issue if we know what

**Comment by colin-axner** [comment]
Does the counterparty chain register the message you are trying to send?

**Comment by schnetzlerjoe** [comment]
> Thanks, @schnetzlerjoe. I see that we discard the error returned by `Handler`, so I guess we could not discard it, and in case an error happens then we can wrap it and provide some extra information.
> 
> However, I also see that `Handler` is simply doing a [`map` lookup](https://github.com/cosmos/cosmos-sdk/blob/main/baseapp/msg_service_router.go#L36), so I guess the only possible error is that the message you're trying to execute is not present in the [`routes` map](https://github.com/cosmos/cosmos-sdk/blob/main/baseapp/msg_service_router.go#L19) and therefore it cannot find a `MsgServiceHandler` for it... Would it be possible for you to double check that the message is properly registered?

Yeah. Here https://github.com/pitalco/axelar-core/blob/384fdd16b90d92e5e74a998298696b173134de6b/x/axelarnet/types/tx.pb.go#L724 . I will say they do have a wrapped string ChainName and in the protoc generated ts files it just uses a string. You think that could be it. Its not registering it as the correct msg type?

**Comment by damiannolan** [comment]
It doesn't look like the `MsgServer` is being bound in the axelarnet [`RegisterServices`](https://github.com/pitalco/axelar-core/blob/384fdd16b90d92e5e74a998298696b173134de6b/x/axelarnet/module.go#L169).

For example, see [`x/bank`](https://github.com/cosmos/cosmos-sdk/blob/main/x/bank/module.go#L113)

**Comment by schnetzlerjoe** [comment]
> It doesn't look like the `MsgServer` is being bound in the axelarnet [`RegisterServices`](https://github.com/pitalco/axelar-core/blob/384fdd16b90d92e5e74a998298696b173134de6b/x/axelarnet/module.go#L169).
> 
> For example, see [`x/bank`](https://github.com/cosmos/cosmos-sdk/blob/main/x/bank/module.go#L113)

I thought that to but even when adding `RegisterMsgServiceServer` which is Axelars `RegisterMsgServiceServer` still receives the same `invalid route` error

**Comment by damiannolan** [comment]
It may be worth putting a debugger on the code and seeing if there's anything at all registered in the [`MsgServiceRouter`](https://github.com/cosmos/cosmos-sdk/blob/main/baseapp/msg_service_router.go#L16-L20).

Perhaps the axelar code base is deviating from the standard sdk message routing approach.

**Comment by colin-axner** [comment]
I think we might need a little more information to debug. 

Can you confirm the tx flow? Is the interchain account hosted on axelar or another chain? `MsgLinkRequest` is a msg on axelar? You are initiating an interchain transaction from axelar or the other chain? You expect the message to be executed on axelar or the other chain?

Thanks!

**Comment by schnetzlerjoe** [comment]
> I think we might need a little more information to debug. 
> 
> Can you confirm the tx flow? Is the interchain account hosted on axelar or another chain? `MsgLinkRequest` is a msg on axelar? You are initiating an interchain transaction from axelar or the other chain? You expect the message to be executed on axelar or the other chain?
> 
> Thanks!

`MsgLinkRequest` within Axelarnet creates a deposit address on Axelar and listens to the address to then send around. `MsgLinkRequest` in EVM does the same but on an EVM chain.

Both are messages that are on Axelar so it's a message that ICA should run. Just like any other standard SDK message, custom or basic SDK. And to be clear, I am running dev EVM chains locally but thats beyond this. If the ICA message would run and I wasn't running those chains the message should still run and then it would fail on the Relayer side.

Hope that helps!

**Comment by schnetzlerjoe** [comment]
Closing this. Incase any one needs this in the future, you need to add the msg service register for ALL modules. Then Axelar will start working for ICA.
