### ISSUE TITLE
Upgraded to IBC-Go V4 and all of sudden getting decoding bech32 failed

### ISSUE THREAD

**Issue by schnetzlerjoe** [cosmos/ibc-go#2559]
We upgraded to Ibc-Go v4 from v3 and now are receiving the `decoding bech32 failed` below. It is coming from [here](https://github.com/cosmos/ibc-go/blob/197555e7b879032cdbda32d1dba60b6164f9a0f6/modules/core/04-channel/types/msgs.go#L48).

It seems to be coming from [here](https://github.com/cosmos/ibc-go/blob/98f6e574695c5ba419516c6e99050412a5c61ea7/modules/apps/27-interchain-accounts/controller/keeper/account.go#L63) even further down the line 

```bash
Error: rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: string could not be parsed as address: decoding bech32 failed: invalid separator index -1: invalid address [cosmos/ibc-go/v4@v4.0.1/modules/core/04-channel/types/msgs.go:48] With gas wanted: '0' and gas used: '142155' : unknown request
```

## Version

IBC-Go V4
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Hi @schnetzlerjoe. So the doing the same attempt to register an interchain account worked with v3 but then failed with v4, right? Is the signer of the message to register an interchain account a regular user account? Or is it a smart contract?

**Comment by schnetzlerjoe** [comment]
> Hi @schnetzlerjoe. So doing the same attempt to register an interchain account worked with v3 but then failed with v4, right? Is the signer of the message to register an interchain account a regular user account? Or is it a smart contract?

It is a smart contract aka module account that is signing the msg which contains a register interchain account call. It seems like the signer is being set as `interchainaccount` by the ICA 27 module though

**Comment by schnetzlerjoe** [comment]
> > Hi @schnetzlerjoe. So doing the same attempt to register an interchain account worked with v3 but then failed with v4, right? Is the signer of the message to register an interchain account a regular user account? Or is it a smart contract?
> 
> It is a smart contract aka module account that is creating the call to the function which contains a register interchain account call. It seems like the signer is being set as `interchainaccount` via icatypes.modulename by the ICS 27 module though 

See https://github.com/cosmos/ibc-go/blob/98f6e574695c5ba419516c6e99050412a5c61ea7/modules/apps/27-interchain-accounts/controller/keeper/account.go#L63

**Comment by boosik** [comment]
We also have same issue, and we modified using the address of module account, not module name to signer in forked ibc-go.

**Comment by schnetzlerjoe** [comment]
> We also have same issue, and we modified using the address of module account, not module name to signer in forked ibc-go.

Yeah we did same!

**Comment by puneet2019** [comment]
@schnetzlerjoe @boosik 
https://github.com/cosmos/cosmos-sdk/tree/reflection-45
this branch was created for cosmos-sdk to solve for the issue. 
the issue is coming after upgrading cosmos-sdk to v0.45.9.

**Comment by ivivanov** [comment]
Replacing 45.9 of the SDK with the patch in this branch https://github.com/cosmos/cosmos-sdk/tree/reflection-45
solves `decoding bech32 failed` issue for me. Maybe PR should be opened?
