### ISSUE TITLE
EOL: Remove v5.x legacy e2e tests and workflows

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#2593]
## Summary

This issue exists to track legacy code which can be removed when `ibc-go/v5` reaches end-of-life.

- [x] Remove `intertx` interchain accounts e2e tests
- [x] Remove `icad` github workflows and references to `intertx` e2e tests

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by damiannolan** [comment]
Tests may want to be kept around until legacy APIs are removed from later releases. E.g. `ibc-go/v6` still supports the auth module/middleware approach.

**Comment by crodriguezvega** [comment]
This has already been done. 🥳
