### ISSUE TITLE
Migrate to cosmos/gogoproto

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2650]
## Summary

Migrate from `gogo/protobuf` to `cosmos/gogoproto`, [ref issue](https://github.com/cosmos/cosmos-sdk/issues/10925) and [ref pr](https://github.com/cosmos/cosmos-sdk/pull/13070)

## Problem Definition

We are still using the go mod replace directive to [unmaintained code](https://github.com/regen-network/protobuf/)

## Proposal

Switch from the regen fork to the cosmos fork. I'm unsure how involved this work will be outside of updating imports

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
I think Simon is actually working on this as part of the upgrade to SDK 0.47. I will check with him.

**Comment by colin-axner** [comment]
Lets bring it out as a separate pr, it doesn't need to wait for v0.47 correct?

**Comment by julienrbrt** [comment]
> Lets bring it out as a separate pr, it doesn't need to wait for v0.47 correct?

Unfortunately, it does. IBC depends on SDK 0.46, which still uses `gogo/protobuf`, so the `proto.Message` must be using `gogo/protobuf`.
