### ISSUE TITLE
Use smaller number of validators when running tests locally

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#2667]
## Summary

Currently, we have [hard coded values](https://github.com/cosmos/ibc-go/blob/8991eaa08d0f582234b3500e67253e2bbc686e3c/e2e/testsuite/testsuite.go#L421) for validators to run in our tests.

These numbers are good for CI, but when iterating on tests locally can be pain unless manually changed to a lower number. We can lower these to `1, 0` for example when not running in CI.

in github actions, a `CI=true` environment variable is set, we could leverage this existing value to conditionally set these values.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by DimitrisJim** [comment]
> I think this should be closed as I saw that someone already do this

Nice find! This was indeed addressed in aabb07a12457b35b9b28493311a9278639dd529b of https://github.com/cosmos/ibc-go/pull/3079
