### ISSUE TITLE
update buf usage for sdk 0.47

### ISSUE THREAD

**Issue by tac0turtle** [cosmos/ibc-go#2671]
## Summary of Bug

please update your bus usage to follow sdk conventions. The version used in ibc is very old.

**Comment by tac0turtle** [comment]
proto docs were deprecated as well. should migrate to but system so other teams can import your proto definitions without needing to copy paste the files

**Comment by damiannolan** [comment]
Thanks for opening this, I strongly agree. Will try to get this prioritised

**Comment by damiannolan** [comment]
See https://github.com/cosmos/ibc-go/pull/2705 for details on updating buf for sdk 0.47
