### ISSUE TITLE
Add e2e test for ICS27 channel reopening

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#2675]
## Summary

Add an e2e test for ICS27 channel reopening. This can be done using the new controller `MsgServer` API.
The e2e test should follow the flow defined below:

1. Register an interchain account from chainA (controller) to chainB (host)
2. Broadcast a new `MsgSendTx` with a short-lived timeout
3. Wait a number of blocks or potentially sleep for a short period to allow the timeout to pass
4. Start the relayer and allow it to timeout the packet and in turn close the ICA channel
5. Attempt to reopen the channel. This should be possible routing a new `MsgRegisterInterchainAccount` or `MsgChannelOpenInit` to the controller chain
7. Broadcast a new `MsgSendTx` which executes successfully

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
@charleenfei thanks for picking this up! 

Some [work](https://github.com/cosmos/ibc-go/blob/carlos/add-ica-reopen-channel-test/e2e/tests/interchain_accounts/base_test.go#L241) has been done for this on [this branch](https://github.com/cosmos/ibc-go/tree/carlos/add-ica-reopen-channel-test) that might be possible to be reused. But unfortunately it is not working: for some reason it seems like the channel [does not get closed](https://github.com/cosmos/ibc-go/blob/carlos/add-ica-reopen-channel-test/e2e/tests/interchain_accounts/base_test.go#L341). Here's a sample [run](https://github.com/cosmos/ibc-go/actions/runs/3173989741/jobs/5170232917) using the v0.1.5 tag of icad. Maybe it's better to just use simd with v6.0.0 instead from now on.

**Comment by colin-axner** [comment]
Looks like it should be [`channels[1]`](https://github.com/cosmos/ibc-go/blob/carlos/add-ica-reopen-channel-test/e2e/tests/interchain_accounts/base_test.go#L341), not [`channels[0]`](https://github.com/cosmos/ibc-go/blob/carlos/add-ica-reopen-channel-test/e2e/tests/interchain_accounts/base_test.go#L246)

**Comment by crodriguezvega** [comment]
> Looks like it should be [`channels[1]`](https://github.com/cosmos/ibc-go/blob/carlos/add-ica-reopen-channel-test/e2e/tests/interchain_accounts/base_test.go#L341), not [`channels[0]`](https://github.com/cosmos/ibc-go/blob/carlos/add-ica-reopen-channel-test/e2e/tests/interchain_accounts/base_test.go#L246)

hmmm, in the test run that I will in my comment above it's possible to see in the logs the information for `channels[0]`:

```
{State:STATE_OPEN Ordering:ORDER_ORDERED Counterparty:{PortID:icahost ChannelID:channel-1} ConnectionHops:[connection-0] Version:{"version":"ics27-1","controller_connection_id":"connection-0","host_connection_id":"connection-0","address":"cosmos152tahxw0mfvq7rd2gqahpzz2pjs562rs89jdefpnehaes0a238jq55d9aj","encoding":"proto3","tx_type":"sdk_multi_msg"} PortID:icacontroller-cosmos1k88wju6m4j6hycum00h5untgkxnzndcrccuvjh ChannelID:channel-1}
```

So `channels[0]` should be the ordered channel created for the interchain account...
