### ISSUE TITLE
Add portID into MsgRegisterInterchainAccountResponse

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2724]
## Summary

Add generated portID into [`MsgRegisterInterchainAccountResponse`](https://github.com/cosmos/ibc-go/blob/82397d68ff9e11059e4baebb57fa14a73cedd5ed/proto/ibc/applications/interchain_accounts/controller/v1/tx.proto#L29). Not necessary, but improves dev-UX to prevent devs from needing to call another function to generate the portID

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by GNaD13** [comment]
Hi sir @colin-axner @crodriguezvega, can I take this issue?

**Comment by crodriguezvega** [comment]
> Hi sir @colin-axner @crodriguezvega, can I take this issue?

Yes, @GNaD13, this issue is still available; I will assign it to you now. Thanks a lot for working on it!
