### ISSUE TITLE
Add debug logging for failed acknowledgement errors

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2725]
## Summary

In the same spirit as #2713, we should add debug level logging for the error message which is discarded when generated a failed acknowledgement. This should occur for:
- 20-transfer
- 27-interchain-accounts (host)
- 29-fee

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by GNaD13** [comment]
Hi @colin-axner, can I take this issue?

**Comment by crodriguezvega** [comment]
@GNaD13 Yes, you can take this issue. Thanks!

Please have a look at [the PR](https://github.com/cosmos/ibc-go/pull/2976) that closed the issue #2713 mentioned above for reference.
