### ISSUE TITLE
Cleanup 03-connection msg validate basic test

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2747]
## Summary

[`TestNewMsgConnectionOpenConfirm`](https://github.com/cosmos/ibc-go/blob/main/modules/core/03-connection/types/msgs_test.go#L211) is not very ergonomic. It should be restructured to combine the msgs into the test cases:

```go
testCases := []struct {
		name    string
		msg     *types.MsgConnectionOpenTry
		expPass bool
}{
```

exactly the same as the other test cases in the same file. 

1. put the test case name first
2. move testMsgs into the test case struct
3. set expPass bool last

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
> Can you pls review my changes? Thank you

Sorry for the late reply, but yes, definitely! Thanks for opening quickly a PR!
