### ISSUE TITLE
Remove e2e tests for all branches but main

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#2811]
## Summary

E2E tests only run on the main branch. Based on when some release branches were cut, they contain some of the e2e test suites. These are safe to remove on all but `main`. Note: we must keep the docker build tasks. As the images for the release branches are built on the release branches, not from main.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
While fixing the conflicts for the back ports of #2868 I deleted the e2e folder in `release/v5.2.x`. That was the only remaining e2e folder in the currently active release branches.
