### ISSUE TITLE
ibc-go feature: Beefy light client

### ISSUE THREAD

**Issue by livelybug** [cosmos/ibc-go#2818]
## Summary

Beefy light client on ibc-go needed for Substrate <> Cosmos cross-chain transaction(ICS20).

## Problem Definition

The [substrate-ibc](https://github.com/octopus-network/substrate-ibc) project to enable Substrate <> Cosmos cross-chain transaction(ICS20) is in progress.

On the Substrate side, we use [substrate-ibc pallet](https://github.com/octopus-network/substrate-ibc) integrated with [ibc-rs](https://github.com/octopus-network/ibc-rs), where the Tendermint light client resides in and verifies the messages from the Cosmos side.

The Substrate uses [GRANDPA](https://github.com/paritytech/finality-grandpa#finality-grandpa) for block finalization and adopts [Beefy as a secondary protocol alone with GRANDPA for efficient bridging](https://github.com/paritytech/grandpa-bridge-gadget#beefy). On the Cosmos side, a corresponding light client is needed to verify messages from Substrate finalized by GRANDPA & Beefy. No such light client has been released for now, and the substrate-ibc project is blocked. Composable Finance team is developing a [beefy light client on ibc-go](https://github.com/ComposableFi/ibc-go/blob/e871fd96b657c1364c7d70294d30ba1c18c14f54/modules/light-clients/11-beefy/README.md) (@seunlanlege), which is in progress and can't be used for integrated testing. 
[The testing issue](https://github.com/ComposableFi/ibc-go/issues/34) is submitted to CF team.

## Proposal

We would like to develop a light client on [ibc-go](https://github.com/cosmos/ibc-go) with [updated ICS10 spec](https://github.com/cosmos/ibc/pull/883) and the code of CF's light client as references. Noted that CF team is developing a [Beefy light client by Rust](https://github.com/ComposableFi/centauri/tree/83cdbd978ab31dd5df1b7c2eff119dc43ef62148/light-clients/ics11-beefy), which may benefit the chains embedded with Cosmwasm. Cosmos chains without Cosmwasm still need Beefy light client in Golang to enable IBC connection with Substrate chains.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Hi @livelybug, thanks for opening the issue.

If I remember correctly the Composable Finance team hit some roadblocks on their implementation of a beefy light client for ibc-go and decided to implement it in Rust instead. Do you have a plan of how you will solve those issues that Composable Finance faced on the implementation of the Go light client? And have coordinated with Composable Finance to maybe continue the work from where they left off?

**Comment by blasrodri** [comment]
One of the issues/blockers we had was: https://github.com/ChainSafe/gossamer/issues/2329

**Comment by boern** [comment]
@blasrodri Thank you for your feedback, we are communicating with @qdm12 about this issue and trying to resolve it, other than that, are there any other issues during the development of the beefy light client?

**Comment by crodriguezvega** [comment]
@livelybug I will close this issue for now, since there's no concrete action for us to take at the moment. If you develop a  beefy light client in Go it will be not mandatory for it to be in ibc-go in order for chains to use it. From ibc-go v7.0.0 onwards light clients will need to [implement the `AppModuleBasic` interface](https://ibc.cosmos.network/main/ibc/light-clients/setup.html), so they can be regular SDK modules living in their own repositories. See [this PR for an example with 07-tendermint](https://github.com/cosmos/ibc-go/pull/2825).

Good luck with this endeavor!
