### ISSUE TITLE
Investigate non-determinstic failures in e2e

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2827]
## Summary

Occasionally the e2e's will fail [unexpectedly](https://github.com/cosmos/ibc-go/actions/runs/3530533337/jobs/5922676431). The behaviour appears to be non-determinstic and only occur around 5% of the time. It is unpredictable which test will fail. As we increase our reliance on the e2e's, we should also ensure we understand why this instances are failing and fix the issue if possible. [Here](https://github.com/cosmos/ibc-go/actions/runs/3530940914/jobs/5923576191) is another example of a different test failing which typically succeeds

If we make our e2e's [importable via a workflow](https://github.com/cosmos/ibc-go/issues/2501), it would be less than ideal if our tests randomly failed

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
I think the first link was an issue with the specific test [which  has been resolved](https://github.com/cosmos/ibc-go/pull/2858), however the second link is the real problem. The periodic network failures during set up. These are relatively consistent.

**Comment by colin-axner** [comment]
Looking at this [failure](https://github.com/cosmos/ibc-go/actions/runs/4383152405/jobs/7673162930) with tm logs on debug as well as this [failure](https://github.com/cosmos/ibc-go/actions/runs/4378231603/jobs/7663140896), I noticed something really intersting. 

The failing node contains 38 or 39 instances of:
```
Inbound Peer rejected                        module=p2p err="auth failure: secret conn failed: proto: illegal wireType 7" numPeers=4
```

All other nodes have instances of:
```
D[2023-03-10|09:42:20.344] served RPC HTTP response                     module=rpc-server method=POST url=/ status=200 duration=0 remoteAddr=172.18.0.1:34828
```
while the failing node does not. 


It appears to me that the HTTP request to query the node status is somehow ending up on the p2p port, which tendermint then attempts to perform the secret handshake used for encrypted communication. Obviously the response expected back is an HTTP response and not a encoded public key, thus causing a failure. What I'm really not certain of is how this network routing failure is occurring? Is interchain test returning the p2p port on accident? Is docker to blame? Why do we see this issue so randomly? The depth of this sudoku puzzle continues...

**Comment by colin-axner** [comment]
Opened an issue on [cometbft](https://github.com/cometbft/cometbft/issues/516)

**Comment by colin-axner** [comment]
Closing because I believe we have surfaced all the root issues for the non-determinism :)
