### ISSUE TITLE
Support running compatibility tests for ICAD

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#2837]
## Summary 

Add support for running compatibility tests with icad (can be done in the demo repo)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
this functionality was added to the interchain-accounts-demo repo in [this pr](https://github.com/cosmos/interchain-accounts-demo/pull/160).

**Comment by chatton** [comment]
thanks for the help @crodriguezvega 🥇

**Comment by crodriguezvega** [comment]
> thanks for the help @crodriguezvega 🥇

My pleasure! 🤛
