### ISSUE TITLE
Add solomachine clientID constant to testing package

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2843]
## Summary

Add a default clientID used for association of solo machine clients created on a tendermint chain:
```diff
diff --git a/testing/values.go b/testing/values.go
index 460e27a23..44af56e8f 100644
--- a/testing/values.go
+++ b/testing/values.go
@@ -18,9 +18,10 @@ import (
 )
 
 const (
-       FirstClientID     = "07-tendermint-0"
-       FirstChannelID    = "channel-0"
-       FirstConnectionID = "connection-0"
+       FirstClientID       = "07-tendermint-0"
+       FirstChannelID      = "channel-0"
+       FirstConnectionID   = "connection-0"
+       SolomachineClientID = "06-solomachine-0"
 
        // Default params constants used to create a TM client
        TrustingPeriod     time.Duration = time.Hour * 24 * 7 * 2


```

Replace all usage of the "06-solomachine-0" string. See [comment](https://github.com/cosmos/ibc-go/pull/2800#discussion_r1034673455)

It could make sense to use the name `DefaultSolomachineClientID` over `SolomachineClientID`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by PanGan21** [comment]
Hi! Is anyone currently working on this issue? I would like to give it a try :)

**Comment by crodriguezvega** [comment]
> Hi! Is anyone currently working on this issue? I would like to give it a try :)

No, nobody is working on this issue yet, so thanks very much of volunteering! I will assign it to you now.

**Comment by PanGan21** [comment]
Which could be a good place to export such a variable in your opinion? Since it is used only from test files is the `testing/solomachine.go` a good option?
