### ISSUE TITLE
Use `LogDeferred` to handle errors when closing iteration

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2846]
## Summary

Currently we ignore any errors returned by `iterator.Close()`, once we update to SDK v0.47, we should utilize the newly added https://github.com/cosmos/cosmos-sdk/issues/11785 `LogDeferred` function. I think it is fine to do all the `LogDeferred` additions in a single pr as the changes should be straight forward. 

This change might require a version > v0.47 (I haven't checked what release the function will be in)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Looks like this will be released in v0.47 (see [changelog of v0.47-alpha2](https://github.com/cosmos/cosmos-sdk/blob/v0.47.0-alpha2/CHANGELOG.md#improvements-1)). For reference, this is [the PR](https://github.com/cosmos/cosmos-sdk/pull/13619) that implemented the `LogDeferred` function in SDK.
