### ISSUE TITLE
Emit events indicating total fees paid upon a packet relay in ics29

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2847]
## Summary

Using the event system, an external user should be able to determine the amount of fees paid via ics29. Add an event upon distribution of fees. 

## Problem Definition

We currently only emit total fees escrowed (which doesn't indicate total fees paid)

## Proposal

Add a function `EmitDistributeFeeEvent` to [events.go](https://github.com/cosmos/ibc-go/blob/main/modules/apps/29-fee/keeper/events.go)

Within [`distributeFeeOnAcknowledgement`](https://github.com/cosmos/ibc-go/blob/main/modules/apps/29-fee/keeper/escrow.go#L86) keep track of the total fees not refunded. Pass the total amount into `EmitDistributeFeeEvent`

Within [`distributeFeeOnTimeoutEvent`](https://github.com/cosmos/ibc-go/blob/main/modules/apps/29-fee/keeper/escrow.go#L138), call `EmitDistributeFeeEvent` using the [`timeoutFee`](https://github.com/cosmos/ibc-go/blob/main/modules/apps/29-fee/keeper/escrow.go#L146)
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
It's probably desirable to know which address is receiving the fee. Instead of batching up the total fees distributed, each time a non refund fee is distributed, emit a distribution event which includes the total amount and the address being distributed to

**Comment by crodriguezvega** [comment]
Background information shared by @adizere to inform priority:

```
it would be good if this can be done (not released, only drafted in a PR so we can use it in simd) as soon as possible -- if possible December or January, it would be amazing!
for context, we're doing a demo for relayer operators demonstrating the usefulness of fees, and this feature seems necessary we're still experimenting with things so we might have additional feedback by the way
```

**Comment by crodriguezvega** [comment]
> It's probably desirable to know which address is receiving the fee. Instead of batching up the total fees distributed, each time a non refund fee is distributed, emit a distribution event which includes the total amount and the address being distributed to

Given this comment by @colin-axner I think the easiest will be to call `EmitDistributeFeeEvent` inside [`distributeFee`](https://github.com/cosmos/ibc-go/blob/866bb9afddb77d6461f52af62e566a95cab804ff/modules/apps/29-fee/keeper/escrow.go#L152) in the case when the call to `k.bankKeeper.SendCoinsFromModuleToAccount` does not return an error.
