### ISSUE TITLE
Flakey Test: TestMsgSubmitTx_SuccessfulTransfer_AfterReopeningICA

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#2850]
## Summary

I've noticed the [TestMsgSubmitTx_SuccessfulTransfer_AfterReopeningICA](https://github.com/cosmos/ibc-go/actions/runs/3582474704/jobs/6026798971#logs) test failing for reasons other than docker setup failure.

```
=== RUN   TestInterchainAccountsTestSuite/TestMsgSubmitTx_SuccessfulTransfer_AfterReopeningICA/verify_tokens_not_transferred
=== RUN   TestInterchainAccountsTestSuite/TestMsgSubmitTx_SuccessfulTransfer_AfterReopeningICA/register_interchain_account#01
=== RUN   TestInterchainAccountsTestSuite/TestMsgSubmitTx_SuccessfulTransfer_AfterReopeningICA/verify_new_channel_is_now_open_and_interchain_account_has_been_reregistered_with_the_same_portID
=== RUN   TestInterchainAccountsTestSuite/TestMsgSubmitTx_SuccessfulTransfer_AfterReopeningICA/broadcast_MsgSendTx
=== RUN   TestInterchainAccountsTestSuite/TestMsgSubmitTx_SuccessfulTransfer_AfterReopeningICA/verify_tokens_transferred
=== CONT  TestInterchainAccountsTestSuite/TestMsgSubmitTx_SuccessfulTransfer_AfterReopeningICA
    base_test.go:416: 
        	Error Trace:	/home/runner/work/ibc-go/ibc-go/e2e/tests/interchain_accounts/base_test.go:416
        	Error:      	Not equal: 
        	            	expected: 100010000
        	            	actual  : 100000000
        	Test:       	TestInterchainAccountsTestSuite/TestMsgSubmitTx_SuccessfulTransfer_AfterReopeningICA
```

The test usually passes after a re-run but we should look into this to prevent the flakiness.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
Hmm, my gut says the relayer isn't relaying fast enough. 

The first time we send a tx, we start the relayer https://github.com/cosmos/ibc-go/blob/main/e2e/tests/interchain_accounts/base_test.go#L340 which blocks on finishing all relays

but the second go around we assume it'll be relayed before we verify the tokens are transferred https://github.com/cosmos/ibc-go/blob/main/e2e/tests/interchain_accounts/base_test.go#L410

I'd guess this is causing the flakeyness in our other tests as well
