### ISSUE TITLE
Investigate using generics to provide flexible store iteration

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2853]
## Summary

We should support iteration over our stores without requiring additional logic to be added to our keepers. For example, in order to iterate over only a specific client type, I needed to use a function signature which took in a store key. 

## Problem Definition

In order to iterate over a sub section of our stores which we do not provide functionality for, a store key needs to be provided. Our low level key/value parsing is exposed. 

## Proposal

Add an iteration function
```go
func (k Keeper) Iterate(ctx sdk.Context, prefix []byte, filterFn func(key []byte, value []byte) T, bool) []T 
```

This function should take in the context (to create the store), a prefix (a starting point for the iteration), and a filter function which takes in a generic key and a generic value. The filter function should be able to parse the key and value and return a generic type containing the desired information. It should also have a boolean returned indicating when to stop iteration. 

example usage from v7 automatic migration:
```go
clientIDs := clientKeeper.Iterate(ctx, clientType, func(key []byte, _ []byte) ClientState, bool {
		if !strings.Contains(string(key), host.KeyClientState) {
			// skip non client state keys
			return nil, false
		}

		clientID := host.MustParseClientStatePath(path)

		// optimization: exit after a single tendermint client iteration
		if strings.Contains(clientID, exported.Tendermint) {
			return clientID, true
		}
		
		return clientID, false
	}
     })
```

Thanks @chatton for the idea :)

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
I briefly looked into this with @colin-axner, the following generic code works to perform the iteration

```golang
func Iterate[T any](ctx sdk.Context, storeKey storetypes.StoreKey, prefix []byte, filterFn func(key []byte, val []byte) ([]T, bool)) []T {
	store := ctx.KVStore(storeKey)
	iterator := sdk.KVStorePrefixIterator(store, prefix)
	defer iterator.Close()

	var results []T

	for ; iterator.Valid(); iterator.Next() {
		res, shouldBreak := filterFn(iterator.Key(), iterator.Value())
		if shouldBreak {
			return append(results, res...)
		}
		results = append(results, res...)
	}

	return results
}

```


With an example usage of 

```golang
func (k Keeper) GetAllClientConnectionPaths(ctx sdk.Context) []types.ConnectionPaths {
	return keeper.Iterate(ctx, k.storeKey, host.KeyClientStorePrefix, func(key []byte, val []byte) ([]types.ConnectionPaths, bool) {
		var result []types.ConnectionPaths
		path := string(key)
		if !strings.Contains(path, host.KeyClientState) {
			// skip non client state keys
			return result, false
		}

		clientID := host.MustParseClientStatePath(path)
		paths, found := k.GetClientConnectionPaths(ctx, clientID)
		if !found {
			// continue when connection handshake is not initialized
			return result, false
		}

		connPaths := types.NewConnectionPaths(clientID, paths)
		return append(result, connPaths), false
	})
}
```


After some discussion we decided that the generic version doesn't add much in terms of readability, and it will actually be easier to just create distinct iteration functions for each key/value in the store that we need to be able to iterate over.

**Comment by crodriguezvega** [comment]
Thanks @colin-axner and @chatton for exploring this design!
