### ISSUE TITLE
Make port keeper's IsBound a public function

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#288]
## Summary

Port Keeper has a function [`isBound`](https://github.com/cosmos/ibc-go/blob/0afa15af41997cfb4c5dd5f98de8043961e26195/modules/core/05-port/keeper/keeper.go#L33) which checks if the provided portID is already binded to a module. 

## Problem Definition

ICA needs to check if a portID is already bound, otherwise the port keeper will panic. I realized the current implementation incorrectly checks if the port is bound and does result in a panic. This only occurs if another module claimed a portID within the namespace ICA is working in

The problem was ICA was checking against its [scoped keeper](https://github.com/cosmos/ibc-go/blob/b870be4cd8406b8b327d58424d591484ee75fab9/modules/apps/27-interchain-accounts/keeper/keeper.go#L100), replicating the code in 05-port. But 05-port checks against the IBC scoped keeper. So any port bound that ICA did not claim would cause a panic. 

## Proposal

The `isBound` function should be public OR return errors in 05-port instead of panicking #41 

cc @AdityaSripal 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by seantking** [comment]
I can pick this up. Should we just make `IsBound` public?

**Comment by colin-axner** [comment]
> I can pick this up. Should we just make `IsBound` public?

I'm in favor of it being public and eventually 05-port returning errors instead of panics, but the public change seems like a good short term fix

**Comment by seantking** [comment]
Nice. I'll make a PR, thanks. :+1:
