### ISSUE TITLE
Replacing the concrete keeper structs with interfaces in IBC keeper

### ISSUE THREAD

**Issue by SebastianElvis** [cosmos/ibc-go#2880]
## Summary

This issue proposes to replace the concrete keeper structs with interfaces in the IBC keeper, in order to allow IBC-enabled applications to add extra functionalities atop these keepers.

## Problem Definition

The IBC keeper struct has fields of [concrete types of other keepers](https://github.com/cosmos/ibc-go/blob/main/modules/core/keeper/keeper.go#L31-L34), thus does not allow to drop in any other structs that implement the same set of functions.

This rules out the possibility for IBC-enabled applications to add extra functionalities atop these keepers (without forking IBC-Go). For example, possible extensions of these keepers include
- adding hooks to these keepers, so that other modules can learn internal states of IBC
- defining and emitting new events upon certain state changes in the IBC module
- implementing new queries and messages for these internal keepers

In addition, the implementation also differs from the practice in Cosmos SDK, where each module contains a set of "expected keeper" interfaces, and the module keeper implements these expected keeper interfaces (e.g., [in staking keeper](https://github.com/cosmos/cosmos-sdk/blob/main/x/staking/types/expected_keepers.go)).

## Proposal

This issue proposes to replace the concrete keeper structs with interfaces in the IBC keeper. Specifically, one possible and arguably least intrusive approach is as follows
- for each of the {client, connection, channel, port} keepers, add a file `exported/exported.go`. The file provides an interface that includes all public functions of the concrete keeper implementation.
- replace the concrete keeper structs with these interfaces [in the IBC keeper definition](https://github.com/cosmos/ibc-go/blob/main/modules/core/keeper/keeper.go#L31-L34).

This shall not break any existing functionality or unit tests, and is a practice as done in Cosmos SDK (e.g., [staking keeper's exported interface](https://github.com/cosmos/cosmos-sdk/blob/main/x/staking/exported/exported.go)).

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
Hi! Thanks for opening an issue! It was well written and easy to follow. Apologies for the time delay in following up.

I like the proposal and the solution is very minimal and unobtrusive. The only concerns that arise for me is when users use this interface incorrectly, such as by providing client, connection, or channel keepers that change internal IBC functionality improperly. There's always an argument for trusting user development, but as safety and security is a high priority for me, I'd like to just take an extra second to think if there's a way we could address desired use cases without introducing the ability for accidental vulnerabilities

What is your use case precisely? From my perspective, the use cases that require this change are ones that work with low level core IBC concepts. IBC applications should make use of middleware, as it is a well defined design pattern, and easier for us to support (think security updates, upgrades, etc)

Is there documentation on how to use this design pattern as solely an extension? I would not really want to endorse people building custom connection keepers, but rather extending connection keepers, ie ensuring that the logic we write is always executed

**Comment by SebastianElvis** [comment]
Thanks for following up!

> What is your use case precisely? From my perspective, the use cases that require this change are ones that work with low level core IBC concepts. IBC applications should make use of middleware, as it is a well defined design pattern, and easier for us to support (think security updates, upgrades, etc)

There are two major use cases. Both of them are enabled by exposing hooks triggered upon a header with a valid quorum, and have the same goal: improving a Cosmos zone's economic security (more specifically, resilience to safety attacks).

### 1. Checkpointing Cosmos zones to Bitcoin

We ([Babylon](https://babylonchain.io/)) have built a Cosmos zone, [Babylon](https://github.com/babylonchain/babylon), that checkpoints itself to Bitcoin via a designated protocol, and checkpoints other Cosmos zones to itself via *IBC's light client protocol*. The Babylon protocol raises the economic security to Bitcoin level. That is, to revert a block in a Babylon-integrated Cosmos zone, one needs to be able to revert a block on BTC. The formal security analysis is shown in [this paper](https://eprint.iacr.org/2022/932.pdf).

In the implementation level, we have developed a fork of IBC-Go in which the [02-client keeper](https://github.com/babylonchain/ibc-go/blob/babylon-v5.0.0/modules/core/02-client/keeper/extended_keeper.go) further exposes a [hook](https://github.com/babylonchain/ibc-go/blob/babylon-v5.0.0/modules/core/02-client/keeper/extended_keeper_hooks.go#L10) `AfterHeaderWithValidCommit`. The `AfterHeaderWithValidCommit` hooks is triggered upon a header with a valid quorum certificate. Babylon's [ZoneConcierge](https://github.com/babylonchain/babylon/blob/dev/x/zoneconcierge/keeper/hooks.go#L26-L78) module then leverages this hook to checkpoint headers of other Cosmos zones.

You can find more details in our [codebase](https://github.com/babylonchain/babylon) and [documentation](https://docs.babylonchain.io/).

### 2. Interchain timestamping for mesh security

The Cosmos community has developed the concept of [mesh security](https://informal.systems/2022/11/04/replicated-vs-mesh-security), where Cosmos zones get economic security from each other. You may know an existing proposal for achieving mesh security is [cross-staking](https://informal.systems/2022/11/04/replicated-vs-mesh-security), where stakes of a zone can be replicated to other zones.

We have another proposal [interchain timestamping](https://babylonchain.io/blogs/f/interchain-timestamping-for-mesh-security) for achieving mesh security. The proposal is simple and can be made compatible with existing IBC stack. The key idea is that one zone checkpoints to another consecutively (e.g., A -> B -> C -> D -> E), such that he economic security of A is raised from `MarketCap(A)` to `MarketCap(A+B+C+D+E)`. We have a preliminary analysis [here](https://babylonchain.io/blogs/f/interchain-timestamping-for-mesh-security), and a formal research paper describing this idea will come soon.

The interchain timestamping protocol can be implemented by using the IBC protocol directly. We have observed that the IBC's light client protocol, apart from being a subprotocol of sending IBC packets, is itself effectively a timestamping protocol: zone A maintains zone B's header chain that is consistent and live with the full ledger of Zone B. In the implementation level, the only thing needed for implementing the interchain timestamping protocol is to expose APIs for querying/notifying headers with a valid quorum certificate, e.g., like we do in `AfterHeaderWithValidCommit`.

To conclude, all of our use cases are based on a single observation: IBC's light client is effectively a timestamping protocol and is not just useful for verifying IBC packets. We thus are seeking methods for reading IBC light clients from the application level.

> Is there documentation on how to use this design pattern as solely an extension? I would not really want to endorse people building custom connection keepers, but rather extending connection keepers, ie ensuring that the logic we write is always executed

We totally agree that the feature has to be used in a minimal and non-intrusive way. What we do in [Babylon's IBC-Go fork](https://github.com/babylonchain/ibc-go) is to

- [replace the `ClientKeeper` in IBC keeper with an interface
](https://github.com/babylonchain/ibc-go/blob/babylon-v5.0.0/modules/core/keeper/keeper.go#L32)
- develop an extended `ClientKeeper` that [inherits](https://github.com/babylonchain/ibc-go/blob/babylon-v5.0.0/modules/core/02-client/keeper/extended_keeper.go#L26) all functionalities from the original `ClientKeeper`, implements [some additional logic](https://github.com/babylonchain/ibc-go/blob/babylon-v5.0.0/modules/core/02-client/keeper/extended_keeper.go#L60-L113) for verifying incoming headers, and exposes the `AfterHeaderWithValidCommit` hook.
- replace the original `ClientKeeper` with the extended one [in Babylon](https://github.com/babylonchain/babylon/blob/dev/app/app.go#L446-L452).

As you can see, [our modification](https://github.com/babylonchain/IBC-Go/compare/v5.0.0...babylon-v5.0.0) only includes 500 LoCs.

I hope the above information gives you enough context for our motivation. Please let me know if you have further questions.

**Comment by SebastianElvis** [comment]
Thanks for your support on this idea! I will add the corresponding documentations in https://github.com/cosmos/ibc-go/pull/2967

> As a side note, I looked at the linked diffs, I believe with v7, you can reduce down your custom logic in the extended UpdateClient, since the light client interface functions have been split up, you can validate a header/check for misbehaviour without the client updating its own internal state. That is, [these lines are stateless](https://github.com/cosmos/ibc-go/blob/main/modules/core/02-client/keeper/client.go?rgh-link-date=2023-02-22T15%3A09%3A32Z#L60-#L64)

Yep you are right. Looks like v7 wraps separates verifications of the quorum certificate and the misbehaviours in `VerifyClientMessage` and `CheckForMisbehaviour`, respectively. Actually we had a [PR](https://github.com/babylonchain/ibc-go/pull/5/files) to this end, and are currently waiting for the first release of v7 (there is only rc0 at the moment).

**Comment by crodriguezvega** [comment]
Closing the issue for now, since Babylon team will make use of SDK post handlers instead.
