### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Nakamura0315** [cosmos/ibc-go#2888]
I impleement the IBC on my chain now.

But it shows error like below.

Building proto...
cannot build app:

        lstat /home/shota/go/pkg/mod/github.com/cosmos/ibc-go/v6@v6.0.0-rc1/v5/modules/core: no such file or directory
Waiting for a fix before retrying...

How can I solve this issue?

**Comment by crodriguezvega** [comment]
Hi @Nakamura0315, did you do `go get github.com/cosmos/ibc-go/v6@v6.0.0-rc1`?

**Comment by crodriguezvega** [comment]
So if I understand correctly you are bootstrapping your chain with ignite, correct? I guess in that case the problem is that ignite is not using the latest ibc-go v6.0.0-rc1 tag, but probably some release of ibc-go v5?

**Comment by Nakamura0315** [comment]
This is source code. https://github.com/Nakamura0315/auction

There are ibc-go v6.0.0-rc1, v5 and v1.5 in the go.mod file.
I think that there is issue here, but not sure.

**Comment by crodriguezvega** [comment]
Yeah, I think that's a problem... If you really want to use v6.0.0-rc1 I think I would remove v1.5 and v5 from the go.mod file and then do `go mod tidy` and maybe as well `go mod vendor`. Hopefully that will clean up the go.mod and go.sum. But then you might need to do some updates in your chain for the API breaking changes of v6. Check out the migration docs [here](https://github.com/cosmos/ibc-go/blob/main/docs/migrations/v5-to-v6.md).

**Comment by damiannolan** [comment]
Hi @Nakamura0315, import paths in your go sources should be updated to use ibc-go/v6. For example, [here[(https://github.com/Nakamura0315/auction/blob/main/x/auction/keeper/keeper.go#L14) is an import which would force the go toolchain to import 1.x. I would ensure all import paths are up to date to use v6 import path of ibc-go, then running `go mod tidy` as @crodriguezvega suggests should clean up your dependency graph.

**Comment by Nakamura0315** [comment]
Thanks!
I fixed the issue with v5.
