### ISSUE TITLE
migrate error packages

### ISSUE THREAD

**Issue by tac0turtle** [cosmos/ibc-go#2896]
## Summary

Cosmos SDK has spun out the errors package into its own go.mod in light of the recent conversation on reducing dependency on the sdk, ibc-go should be migrated to cosmossdk.io/errors to take advantage of this. 

We did not move the default error types over cause the idea is that users/app devs will create their own with their custom codespace. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by damiannolan** [comment]
> We did not move the default error types over cause the idea is that users/app devs will create their own with their custom codespace.

Should ibc-go not be using the default types from the sdk root codespace then, such as `ErrInvalidCoins`, `ErrInvalidAddress` etc?
