### ISSUE TITLE
20-transfer: store trace information in metadata instead of storing it separately

### ISSUE THREAD

**Issue by cwgoes** [cosmos/ibc-go#29]
Also, take the trace as user input and calculate the hash instead of looking up (so we shouldn't need to look it up from metadata).

**Comment by colin-axner** [comment]
This would require users to pass in the full denom and trace history. Given that this is a performance improvement that hasn't been requested which requires UX to lessen, I will close the issue. A new issue can be opened if the 1 disc read becomes a serious concern (in addition to the extra storage), but I imagine not
