### ISSUE TITLE
clientIDs currently increment based on overall number of clients per chain, rather than per clienttype

### ISSUE THREAD

**Issue by charleenfei** [cosmos/ibc-go#2907]
## Summary of Bug

for example, if two tendermint clients are created with IDs 07-tendermint-0 and 07-tendermint-1 respectively, a new solomachine client will be created with ID 06-solomachine-2

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
This is intentional. We currently don't have any protections against two clients having the same client type. We would need to add client type registration to increment the identifier based on the client type

**Comment by charleenfei** [comment]
got it, thanks! will close this issue then :)
