### ISSUE TITLE
Tag v5.2.0

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#2921]
- Bumps SDK to ~~v0.46.6~~ v0.46.7 (see comments below).
- Retract previous versions in v5.

**Comment by julienrbrt** [comment]
We are going to retract again all previous version of v0.46 with 0.46.7 (https://github.com/cosmos/cosmos-sdk/pull/14103).
You may want to wait then.

**Comment by crodriguezvega** [comment]
> We are going to retract again all previous version of v0.46 with 0.46.7 ([cosmos/cosmos-sdk#14103](https://github.com/cosmos/cosmos-sdk/pull/14103)).
> You may want to wait then.

Thanks for the heads up, @julienrbrt!

**Comment by crodriguezvega** [comment]
[Compatibility test run](https://github.com/cosmos/ibc-go/actions/runs/3732222448) pre-release.

**Comment by crodriguezvega** [comment]
Closed by [v5.2.0](https://github.com/cosmos/ibc-go/releases/tag/v5.2.0).
