### ISSUE TITLE
docs: IBC docs out of date

### ISSUE THREAD

**Issue by okwme** [cosmos/ibc-go#293]
## Summary of Bug

Reposting an issue from @albertchon from the Cosmos SK repository: https://github.com/cosmos/cosmos-sdk/issues/9764

> It would be great if the IBC docs could be kept up to date since custom IBC integrations are still quite new for projects
> 
> Here are some issues I found
> - [ ] Packet Flow Handling [diagram](https://github.com/cosmos/cosmos-sdk/blob/master/docs/ibc/custom.md#packet-flow-handling)
> - [x] Evidence router example code not needed/out of date [here](https://github.com/cosmos/cosmos-sdk/blob/master/docs/ibc/integration.md#register-routers)
> 
> ## Existing issues 
> - [x] https://github.com/cosmos/cosmos-sdk/issues/9587
> - [x] https://github.com/cosmos/cosmos-sdk/issues/8973
> - [x] https://github.com/cosmos/cosmos-sdk/pull/9763

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
Evidence router issue has been taken care of in this repo. Implementation of #168 would be a big help so we could manage docs in one place

**Comment by colin-axner** [comment]
Looks like this will be closed by #415!
