### ISSUE TITLE
Address relayer fee proto file suggestions

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#294]
## Summary

Resolve outstanding [comments](https://github.com/cosmos/ibc-go/pull/272#issuecomment-886597690)

- [ ] [using query params for query height/relayer](https://github.com/cosmos/ibc-go/pull/272#discussion_r676486321)
- [ ] [using incentivized packet fee](https://github.com/cosmos/ibc-go/pull/272#discussion_r676495836)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by AdityaSripal** [comment]
Agreed with both of your suggestions 👍
