### ISSUE TITLE
Return result and acknowledgement from RelayPacket

### ISSUE THREAD

**Issue by migueldingli1997** [cosmos/ibc-go#2956]
## Summary

Return result and acknowledgement from [RelayPacket](https://github.com/cosmos/ibc-go/blob/c86d27fc280cfb342a9e4689b381e5823441b694/testing/path.go#L38-L92) function for possibility of applying checks or further operations based on these values.

## Problem Definition

I have found the RelayPacket function to be very useful for tests where the packet is parsed from events and then relayed. An example from this repository that served as inspiration is the following: https://github.com/cosmos/ibc-go/blob/c86d27fc280cfb342a9e4689b381e5823441b694/modules/apps/transfer/keeper/relay_test.go#L223-L230

As my code has gotten more complex I have found myself wanting to relay packets that were committed on the counterparty chain as a result of a packet relayed on the original chain. For example, an interchain accounts transaction with a `MsgTransfer` will create a packet on the counterparty chain during the ICA host's `OnRecvPacket`.

The way I see it, the easiest way to then relay this second packet would be to get a hold of the `OnRecvPacket`'s events and look for the packet there. However the `RelayPacket` function currently discards the result containing the events.

So what I'm hoping for here is:
- RelayPacket starts returning the result (and might as well return the acknowledgement as well).
- Find an easy way to do this without requiring changes to RelayPacket. Perhaps the events can be obtained in another way?

## Proposal

From:
```go
func (path *Path) RelayPacket(packet channeltypes.Packet) error
```

To:
```go
func (path *Path) RelayPacket(packet channeltypes.Packet) (res *sdk.Result, ack []byte, err error)
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Hi @migueldingli1997. Sorry for the late reply...

We have discussed this issue and we have a proposal: we would like to keep `RelayPacket` as is, but instead add a new function (tentatively called `RelayPacketWithResults`), with the same functionality as `RelayPacket, but that will return what you need (i.e `(res *sdk.Result, ack []byte, err error)`). That way the existing `RelayPacket` functions doesn't need to change and usages of it can remain the same.

How does this sound? Would it work for you?

**Comment by migueldingli1997** [comment]
That would work @crodriguezvega :)
