### ISSUE TITLE
Persist channel state before calling OnChanOpenAck

### ISSUE THREAD

**Issue by alpe** [cosmos/ibc-go#2962]
## Summary
We have this code smell in [x/wasm/ibc.go](https://github.com/CosmWasm/wasmd/blob/main/x/wasm/ibc.go#L162) for backwards compatibility . Can you set the [channel state](https://github.com/cosmos/ibc-go/pull/647/files#diff-54b5be375a2333c56f2ae1b5b4dc13ac9c734561e30286505f39837ee75762c7R25) before `OnChanOpenAck` is called (as it was in the past) ? It probably does not make a big difference for you but we need the channel active for the contract. The ack callback may trigger the first IBC package to be sent.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Thanks for opening this issue, @alpe! If I understand it correctly, your request is to move [this line](https://github.com/cosmos/ibc-go/blob/main/modules/core/keeper/msg_server.go#L276) before [this one](https://github.com/cosmos/ibc-go/blob/main/modules/core/keeper/msg_server.go#L271), right?

How much are you blocked on this? Would you require this change for the upgrade of wasmd to SDK 0.47?

**Comment by alpe** [comment]
> , your request is to move [this line](https://github.com/cosmos/ibc-go/blob/main/modules/core/keeper/msg_server.go#L276) before [this one](https://github.com/cosmos/ibc-go/blob/main/modules/core/keeper/msg_server.go#L271), right?

Correct 👍 
> How much are you blocked on this?

We are not blocked by this as we persist the channel state ourself. But that is a hack that I would like to see removed in our code as soon as possible. 

> Would you require this change for the upgrade of wasmd to SDK 0.47?

This is unrelated to the SDK upgrade. A backport to [v4.2](https://github.com/CosmWasm/wasmd/blob/main/go.mod#L11) would be great to so that we can apply this early

**Comment by crodriguezvega** [comment]
All right. Thanks for the clarifications!

**Comment by damiannolan** [comment]
afaik we made these changes just for consistency when adding the application version negotiation return values for `OnChanOpenInit` and `OnChanOpenTry`. 
I think it should be fine to change the `ChanOpenAck` to write the channel before the app cbs are invoked, but we should probably do the same for `ChanOpenConfirm` also. cc @AdityaSripal

**Comment by AdityaSripal** [comment]
> afaik we made these changes just for consistency when adding the application version negotiation return values for OnChanOpenInit and OnChanOpenTry.
I think it should be fine to change ChanOpenAck to write the channel before the app cbs are invoked, but we should probably do the same for ChanOpenConfirm also. cc @AdityaSripal

Yes that is correct
