### ISSUE TITLE
authz/ics20: unit tests for `ValidateBasic` method of `TransferAuthorization`

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#2963]
Unit tests for the following scenarios:

- Validation should fail if for any allocation in `TransferAuthorization` when:
  - `spend_limit` is `nil`.
  - Any of the coins in `spend_limit` is not valid.
  - Either the source port or source channel is not a valid identifier.
  - There are more than one allocations AND the same source port and source channel combination is present in more than one allocation.
  - The `allow_list` for an allocation contains duplicate addresses.
  
- Validation should succeed when:
  - There are one or more allocations AND `spend_limit` is not nil and all coins are valid AND source port and source channel are valid identifiers AND source port/source channel combination is not duplicated AND `allow_list` is either empty or does not contain duplicate addresses.

Open PRs against the [feature branch](https://github.com/cosmos/ibc-go/tree/feat/authz-ics20).

**Comment by damiannolan** [comment]
closed by #2992
