### ISSUE TITLE
authz/ics20: add e2e tests

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#2964]
- One happy path where the granter can grant privileges to the grantee and the grantee succeeds on transferring tokens to the recipient.
- One unhappy path where the grantee does not have privileges and the attempt to transfer tokens fails.

Open PRs against the [feature branch](https://github.com/cosmos/ibc-go/tree/feat/authz-ics20).

**Comment by chatton** [comment]
One thing to keep in mind is that we run all our E2E tests against main, so the E2E test itself can be on main, but the images used need to be built from the feature branch. 

However if we need to use ibc-go types from the feature branch, then opening a PR against the feature branch might be the best option.
