### ISSUE TITLE
CodeQL analysis workflow timing out 

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#2970]
## Summary

Looks like the codeql workflow is running for hours until it eventually fails.
We should see if we can address this 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
I think that after merging the [PR with the SDK v0.47 upgrade](https://github.com/cosmos/ibc-go/pull/2672) this is working now, but I will keep an eye on it for a few days before closing.

**Comment by crodriguezvega** [comment]
This seems to be working fine now. Closing...
