### ISSUE TITLE
clean up `{accept,implement}_interface`

### ISSUE THREAD

**Issue by pyramation** [cosmos/ibc-go#2977]
we need to keep in sync with using full-scoped interface names in protos (already merged in cosmos-sdk)

- [reference PR](https://github.com/cosmos/cosmos-sdk/pull/14476)
- [issue describing problem](https://github.com/cosmos/cosmos-sdk/issues/14353)
- [new updated docs with required changes](https://github.com/cosmos/cosmos-sdk/blob/a0da913e86e43fd8cb1eafb49f5473e976d0b514/UPGRADING.md#acceptsimplements_interface-proto-annotations)

**Comment by pyramation** [comment]
cc @amaurym

**Comment by damiannolan** [comment]
Hey, thanks for opening the issue. So, as I understand it, any protobuf defintions which make use of `cosmos_proto.implements_interface` should use the full typeURL excluding the preceding `/` which we [normally see used in the sdk](https://github.com/cosmos/cosmos-sdk/blob/main/types/tx_msg.go#L84)?

I think this is already covered for proposals [here](https://github.com/cosmos/ibc-go/blob/c86d27fc280cfb342a9e4689b381e5823441b694/proto/ibc/core/client/v1/client.proto#L46) and [here](https://github.com/cosmos/ibc-go/blob/c86d27fc280cfb342a9e4689b381e5823441b694/proto/ibc/core/client/v1/client.proto#L46).

`InterchainAccount` uses this annoation [here](https://github.com/cosmos/ibc-go/blob/c86d27fc280cfb342a9e4689b381e5823441b694/proto/ibc/applications/interchain_accounts/v1/account.proto#L15) but it references a local/relative interface. Should this be updated to a fully qualified typeURL?

Aside from that the only other outstanding one I can think of is the feature branch work for ics20 authz. The `TransferAuthorization` should be updated to include the full typeURL [here](https://github.com/cosmos/ibc-go/blob/feat/authz-ics20/proto/ibc/applications/transfer/v2/authz.proto#L26).

**Comment by pyramation** [comment]
The issue was that,  while originally the spec allowed for local/relative/full-path references, they weren't correct in that many folks just put arbitrary names as shown [here](https://github.com/cosmos/cosmos-sdk/issues/14353). The best solution for now that was discussed with the SDK team was to simply remove local/relative paths and only use fully-scoped to remove any ambiguity.

> Hey, thanks for opening the issue. So, as I understand it, any protobuf defintions which make use of `cosmos_proto.implements_interface` should use the full typeURL excluding the preceding `/` which we [normally see used in the sdk](https://github.com/cosmos/cosmos-sdk/blob/main/types/tx_msg.go#L84)?

yes :) 

> `InterchainAccount` uses this annoation [here](https://github.com/cosmos/ibc-go/blob/c86d27fc280cfb342a9e4689b381e5823441b694/proto/ibc/applications/interchain_accounts/v1/account.proto#L15) but it references a local/relative interface. Should this be updated to a fully qualified typeURL?
> 
> Aside from that the only other outstanding one I can think of is the feature branch work for ics20 authz. The `TransferAuthorization` should be updated to include the full typeURL [here](https://github.com/cosmos/ibc-go/blob/feat/authz-ics20/proto/ibc/applications/transfer/v2/authz.proto#L26).

yea so anything not fully qualified needs to be, otherwise it won't conform to the new standard.

**Comment by pyramation** [comment]
also related https://github.com/CosmWasm/wasmd/issues/1155
