### ISSUE TITLE
cli: ICA transaction commands not registered

### ISSUE THREAD

**Issue by MalteHerrmann** [cosmos/ibc-go#2987]
## Summary of Bug

According to the [IBC documentation](https://ibc.cosmos.network/main/apps/interchain-accounts/client.html#transactions) it should e.g. be possible to generate packet data using an ICA host transaction.

```
simd tx interchain-accounts host generate-packet-data '[{
  "@type":"/cosmos.bank.v1beta1.MsgSend",
  "from_address":"cosmos15ccshhmp0gsx29qpqq6g4zmltnnvgmyu9ueuadh9y2nc5zj0szls5gtddz",
  "to_address":"cosmos10h9stc5v6ntgeygf5xf945njqq5h32r53uquvw",
  "amount": [
    {
      "denom": "stake",
      "amount": "1000"
    }
  ]
}]' --memo memo
```

When building a chain that has any of the ICA host or controller submodules enabled, these transaction commands do not show up in the CLI. I've tested this with Evmos, Gaia, Osmosis and Stride and none of them have the ICA TX commands.

```
 $ simd tx interchain-accounts
Error: unknown command "interchain-accounts" for "tx"
```

The query commands show up fine (e.g. `simd q ica params`).

## Expected Behaviour

The commands for the enabled submodules should be listed as they are for the queries.

## Steps to Reproduce

Example: Build Gaia

```
git clone https://github.com/cosmos/gaia
cd gaia
make build
./build/gaiad tx ica
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by damiannolan** [comment]
The cmd `$BINARY tx interchain-accounts host generate-packet-data` was added in ibc-go/v6. 
I don't believe `gaiad` is using ibc-go/v6 yet.

**Comment by MalteHerrmann** [comment]
Ohhh I didn't realize this was only on `v6`... sorry!
