### ISSUE TITLE
Add documentation on best practise for using the ICS20 memo field

### ISSUE THREAD

**Issue by womensrights** [cosmos/ibc-go#3008]
## Summary
The memo field was added to ICS20 at the end of last year but there is not currently any documentation on its expected use in the ibc-go documentation.

## Problem Definition
There is a concern that the having an unspecified memo field could lead to incompatible use of the field for similar applications and general incompatibilities across different use cases.

## Proposal
Add some documentation to specify the string formatting for different use cases. There are already some example use cases to consider for best practises and guidance:
- Using the memo field to [initiate a cosmwasm contract call](https://github.com/osmosis-labs/osmosis/tree/main/x/ibc-hooks#ics20-packet-structure)
- Using the memo field to [pass the ibc callback to a cosmwasm contract](https://github.com/osmosis-labs/osmosis/tree/main/x/ibc-hooks#callback-information-in-memo)
- Using the memo field for packet routing with [middleware](https://github.com/strangelove-ventures/packet-forward-middleware/commit/a2395f086700a05610c85aa0fef5387631f7862c)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by womensrights** [comment]
Here is also another example for [1 click liquid staking on Stride](https://github.com/Stride-Labs/stride/blob/e44b97fe11c498bb292be6716e527f0e7b7a09cb/x/app-router/module_ibc.go#L162)

**Comment by crodriguezvega** [comment]
@womensrights can this issue be closed now that [memo field usage is documented in chain registry](https://github.com/cosmos/chain-registry/tree/master/_memo_keys)?

**Comment by DimitrisJim** [comment]
does it make sense to at least link to it in the docs? I personally wouldn't know to look in that repo.

**Comment by womensrights** [comment]
I would agree with Jim that it shouldn't be closed and there should be a link to the registry and a suggestion to use a json format for an executable memo in the docs
