### ISSUE TITLE
Add e2e tests for `09-localhost`

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#3033]
## Summary

E2E tests should be added for the `09-localhost` client.

- [x] E2E test using `transfer` module on sentinel localhost connection.
- [x] E2E test using `27-interchain-accounts` module on sentinel localhost connection.
- [x] E2E upgrade test for running chain upgrade migration handler to enable localhost client

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
Is this issue completed?

**Comment by damiannolan** [comment]
Need to add a basic upgrade test that runs automatic migrations. 

We can't actually reuse "normal upgrade" in simapp in its current state. For example, if we upgrade from v7.0.0 -> v7.1.0, then "normal upgrade" is already a registered upgrade handler and on x/upgrade begin block we fail [here](https://github.com/cosmos/cosmos-sdk/blob/v0.47.0-rc2/x/upgrade/abci.go#L90-L94). We basically need to register the default upgrade handler against a new name in the v7.1.0 binary.

**Comment by colin-axner** [comment]
That makes sense. Essentially each upgrade/bin needs a unique name?

**Comment by damiannolan** [comment]
Yeah, we can reuse [`CreateDefaultUpgradeHandler`](https://github.com/cosmos/ibc-go/blob/main/testing/simapp/upgrades/upgrades.go#L16) but we need a unique name for each version increment.
