### ISSUE TITLE
ICS4: Prevent multiple TRY messages to succeed for single INIT message

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#3037]
Following a similar logic as the one implemented in the [PR](https://github.com/cosmos/ibc-go/pull/1723) fixing a similar issue at the 03-connection layer, we should prevent that multiple `MsgChannelOpenTry` messages with the same counterparty are accepted and that they generate multiple channel ends.

**Comment by colin-axner** [comment]
Given direction of ibc eureka/v2, I don't think we will be making adjustments to handshake logic unless strictly necessary, I'm going to close this issue 👍
