### ISSUE TITLE
unable to compile proto files

### ISSUE THREAD

**Issue by aleem1314** [cosmos/ibc-go#3047]
## Summary of Bug

The `make proto-gen` command fails with an error

```
Generating Protobuf files
Generating gogo proto code
cp: can't stat 'github.com/cosmos/ibc-go/v*/modules/*': No such file or directory
make: *** [Makefile:317: proto-gen] Error 1
```

## Version

`main`

## Steps to Reproduce

Run `make proto-gen` command on `main` branch.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Hmm, this seems to be working for me... Could this be some permissions issue with the docker client?
