### ISSUE TITLE
Create pre-commit hook to run all the linters

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#3048]
## Summary

There are several different linters and we have make targets to run formatters. We should add a pre-commit hook which runs all the linters.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by expertdicer** [comment]
To my knowledge, there are 2 ways of doing this :

1. Create a ``.pre-commit-config.yaml``, which involves installing ``pre-commit`` package.
2. Create a bash file in .git/hooks folder, but this one can not be push on remote repo, therefore require a manual move command. 

I don't know which way is better ?

**Comment by chatton** [comment]
it might be nice to use the `.pre-commit-config.yaml`, but I'm currently using a pre-commit hook locally that looks like

```sh
#!/bin/sh

echo "running pre-commit hook"
make lint-fix-changed
make docs-lint-changed

go_files="$(git diff --name-only | grep \.go$)"
for f in $go_files; do
  git add $f
done

md_files="$(git diff --name-only | grep \.md$)"
for f in $md_files; do
  git add $f
done
```

A pre-commit hook in the repo with a command to symlink them might also do the trick. Symlink allows for updates to the pre-commit in the repo to be reflected upon changes without manually moving it. But it has the same drawback of requiring that additional step.

**Comment by expertdicer** [comment]
I guess I will create a ``.pre-commit-config.yaml`` ? Or you prefer a hook locally like yours ?

**Comment by chatton** [comment]
I think a simple solution right now could be to create a pre-commit hook in the repo, and add a Makefile target that will do a symlink, this way we can update the pre-commit hook over time. What do you think?

**Comment by expertdicer** [comment]
Yes. I think that would be the optimal solution.
