### ISSUE TITLE
Add 09-localhost client creation to `InitGenesis`

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#3058]
## Summary

Create the `09-localhost` loopback client in the 02-client submodule `InitGenesis` function.
Initially we can create the `09-localhost` client by default, and revisit if this should be controlled via a boolean flag.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
closed by #3092
