### ISSUE TITLE
20-transfer miscellaneous clean-up

### ISSUE THREAD

**Issue by cwgoes** [cosmos/ibc-go#31]
- [ ] Clarify comment about preventing transfers in transfer.proto (no cross-chain per-denom enable/disable)
- [ ] Use SHA256 instead of imported tmhash
- [ ] Add comment explaining why base denom is not validated (coming from another chain)
- [ ] Rename `validatePrefixedDenom` 
- [ ] Replace "ibc" with constant
- [ ] Remove hardcoded numbers (e.g. [4:] should be length of a constant) in DenomTraceFromHash and elsewhere
- [ ] Add comment why the acknowledgement is 1
- [ ] Abstract out denomination calculation functions
- [ ] Add comment about zero-coins
- [ ] Move events around (after state changes, not in-between)
- [ ] Comment to clarify security model around denomination space namespacing in RecvPacket
- [ ] Improve naming of trace functions generally
- [ ] Note that ordered channels are considered dangerous

**Comment by colin-axner** [comment]
closing as stale
