### ISSUE TITLE
Add basic validation of client upgrade proposal contents

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#3106]
## Summary

We should consider adding an additional validation step of at minimum (chainID suffix, height revision number) before proceeding with client upgrade proposals. 

For example, if a client upgrade proposal is submitted which modifies the chainID from `testchain-1` to `testchain-2`, then it is required for the `UpgradedClientState` provided in the proposal contents to ensure the client state `LatestHeight.RevisionNumber` follows suit and increments from revision 1 to 2. 

The issue arises when a misconfigured upgrade proposal is accepted and a relayer attempts to upgrade the client on the counterparty chain. This results in an error being returned from [`VerifyUpgradeAndUpdateState`](https://github.com/cosmos/ibc-go/blob/main/modules/light-clients/07-tendermint/upgrade.go#L106-L108) when attempting to call [`Validate`](https://github.com/cosmos/ibc-go/blob/main/modules/light-clients/07-tendermint/client_state.go#L138-L142) on the new client state. 

Adding an additional basic validation step to the proposal handler will allow this to be caught much earlier in the client upgrade process.

ref: https://github.com/informalsystems/hermes/issues/3057

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by adizere** [comment]
Thank you Damian! This hygienic improvement would likely make diagnosing the problem on the relayer side easier also.

**Comment by phamminh0811** [comment]
hi @adizere , can I handle this issue?

**Comment by crodriguezvega** [comment]
@phamminh0811 We have decided to close this issue in favour of #1310. However, we can't be work on #1310 yet, since it needs #1282 first.
