### ISSUE TITLE
why ICA only support the ordered channels?

### ISSUE THREAD

**Issue by lyh169** [cosmos/ibc-go#3124]
Why the ICA only support ordered channels, but not supprot unordered channels?( because  the timeout packets, the ordered channels should be closed, this maybe a bad experience). I want know the reason of this design. Can some one help me ?  thanks. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
Hi, it's a [desired property](https://github.com/cosmos/ibc/tree/main/spec/app/ics-027-interchain-accounts#desired-properties) that transactions for an interchain account are ordered. From the spec:
> The ordering of transactions sent to an interchain account on a host chain must be maintained. Transactions must be executed by an interchain account in the order in which they are sent by the controller chain.

Without this property, I don't believe it would be possible to safely send multiple transactions as transactions may be dependent upon a certain order that may not be guaranteed. Closing this issue as it isn't ibc-go specific
