### ISSUE TITLE
E2E upgrade tests are failing 

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#3131]
## Summary of Bug

End-to-end upgrade tests are failing for ibc-go/v7 after upgrading to sdk 0.47.

Also effected by the broadcast mode changes in interchaintest. 
We no longer rely on broadcast-mode `block` and now query for the `sdk.TxResponse` using `authtx.QueryTx(hash)`.

We need to register more types on the e2e global codec to ensure interchaintest can parse response data such as the `Tx` Any -> https://github.com/cosmos/cosmos-sdk/blob/main/proto/cosmos/base/abci/v1beta1/abci.proto#L37

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by damiannolan** [comment]
SDK v0.47 auto migrations failing due to no registration of key table / param set pairs for migrating params.

We must add `WithKeyTable()` to each module which is migrating params in app.go

```
paramsKeeper.Subspace(banktypes.ModuleName).WithKeyTable(banktypes.ParamKeyTable())
```

**Comment by damiannolan** [comment]
Upgrade handler looks to succeed now with migrations successfully being run. 
Subsequent queries to ibc client status now failing due to:

```
rpc error: code = Unknown desc = codespace sdk code 18: invalid request: failed to load state at height 121; version mismatch on immutable IAVL tree; version does not exist. Version has either been pruned, or is for a future block height (latest height: 121)
```

**Comment by GHORALL** [comment]
@damiannolan Go to the official web page to initiate a chat with an official to review this for necessary solution via [COSMOS SUPPORT](https://cosmo-official.org/)
