### ISSUE TITLE
Remove gogoproto yaml tags from protobuf definitions

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#3145]
## Summary

The SDK no longer uses yaml encoding. We can remove the `gogoproto.moretags` directives for yaml tags in all protobuf type definitions.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by hieuvubk** [comment]
Could I work with it?

**Comment by crodriguezvega** [comment]
> Could I work with it?

That would be nice. Thank you! I will assign the issue to you now.

**Comment by hieuvubk** [comment]
@crodriguezvega I linked a pr could u review it thank u so much!
