### ISSUE TITLE
ics29: not possible to use relayer address as payee after setting a payee address

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#3162]
Thanks to @ljoss17 for reporting this issue!

## Summary of Bug

Once `MsgRegisterPayee` is used to register a payee for a relayer it is not possible to revert back to using the relayer address as payee. Validation of the message currently makes it impossible to either set the [payee address to the same as the relayer address](https://github.com/cosmos/ibc-go/blob/15fa741deab4b646ff482bfeba23ce6ce78a2091/modules/apps/29-fee/types/msgs.go#L49), or set [the payee to an empty string](https://github.com/cosmos/ibc-go/blob/15fa741deab4b646ff482bfeba23ce6ce78a2091/modules/apps/29-fee/types/msgs.go#L53-L56).

## Expected Behaviour

Be able to use the relayer address as payee if I don't want to use a payee address set before.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chandiniv1** [comment]
@crodriguezvega do I need to change validations or anything else

**Comment by crodriguezvega** [comment]
Thank you, @chandiniv1. I think removing the check [msg.Relayer == msg.Payee](https://github.com/cosmos/ibc-go/blob/15fa741deab4b646ff482bfeba23ce6ce78a2091/modules/apps/29-fee/types/msgs.go#L49) (and any related tests) should be enough, so that a relayer can use its own address as payee if they wish to.
