### ISSUE TITLE
Add misbehaviour submission e2e test

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3185]
## Summary

Add an e2e test which generates misbehaviour and successfully submits it, thus resulting in a Frozen client. 

## Problem Definition

We should ensure there exist e2e testing for misbehaviour submission.

## Proposal

Write a test which:
- creates two chains with client, connection channels
- generate a conflicting header (an misbehaving header at a valid block height already updated to)
- attempts to update the client with the conflicting header
- ensure the client has been frozen

[Here's](https://github.com/cosmos/relayer/pull/485) a reference test written back in the day

My main question around this test is getting access to the validators private key. Not sure if this is currently available?

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
I don't think the public key is exposed as a field on any of the exported types, but it should be retrievable via the `Chain.Exec` function. There are also some existing functions which [fetch the keyring](https://github.com/strangelove-ventures/interchaintest/blob/main/internal/dockerutil/keyring.go#L21) from a container to the test host (that linked one is an internal function at the moment though)

**Comment by damiannolan** [comment]
Can we query the validator through the staking module and decode the [`consensus_pubkey`](https://github.com/cosmos/cosmos-sdk/blob/44495e7a7934f00fe289c9f059ff3dba6582b43e/proto/cosmos/staking/v1beta1/staking.proto#L97) Any to an [`ed25519`](https://github.com/cosmos/cosmos-sdk/blob/44495e7a7934f00fe289c9f059ff3dba6582b43e/proto/cosmos/crypto/ed25519/keys.proto#L14) public key?
