### ISSUE TITLE
Add `IsNativeDenom()` function to `DenomTrace`

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3187]
## Summary

Add the function:
```go
// IsNativeDenom returns true if the denomination is native, thus containing no trace history. 
func (dt DenomTrace) IsNativeDenom() bool {
    return dt.Path == "" 
}
        
```

## Problem Definition

We need to check if the path is empty to determine if it is native. This is less readable then the proposed function. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
I will add it as part of https://github.com/cosmos/ibc-go/pull/3019.
