### ISSUE TITLE
Localhost client audit concerns

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#3193]
- [x] Replace the `store.Get` usage in [verifyNonMembership](https://github.com/cosmos/ibc-go/blob/40ca344b124a87eb6238f4162caf96d280b1135a/modules/light-clients/09-localhost/client_state.go#L130-L134) with `store.Has`
- [x] Document in [verifyMembership](https://github.com/cosmos/ibc-go/blob/40ca344b124a87eb6238f4162caf96d280b1135a/modules/light-clients/09-localhost/client_state.go#L76) and [verifyNonMembership](https://github.com/cosmos/ibc-go/blob/40ca344b124a87eb6238f4162caf96d280b1135a/modules/light-clients/09-localhost/client_state.go#L111) that the store passed is the ibc store. 
- [x] In `verifyMembership` and  `verifyNonMembership` use `_` as variable name for unused parameters.
- [x] In [GetTimestampAtHeight](https://github.com/cosmos/ibc-go/blob/40ca344b124a87eb6238f4162caf96d280b1135a/modules/light-clients/09-localhost/client_state.go#L69-L72) Add a comment that this function is not doing exactly the same of what it does for other client types and that it just returns the latest context timestamp.
- [x] #3194
- [x] Move types.LocalhostID to exported and have two variables LocalhostClientId and LocahostConnectionId.
- [x] Add migration docs.
- [x] Update DefaultAllowedClients godoc
- [x] Rename getClientStateAndKVStore to getClientStateAndVerificationStore. Use clientID instead of clientState.ClientType in if check (to make sure that the whole ibc store is only returned for the sentinel localhost client).
- [x] Use AttributeKeyConnectionId in all events in 04-channel/keeper/events

**Comment by damiannolan** [comment]
I'll pick up the sentinel proof work and create a separate PR for it.

**Comment by damiannolan** [comment]
Addressing points 1-4 in #3199

**Comment by colin-axner** [comment]
Addressing 6, 8, 9, 10

**Comment by colin-axner** [comment]
Nice one y'all!
