### ISSUE TITLE
add import/export genesis e2e

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3241]
## Summary

Add an e2e test for init and export genesis. 

## Proposal

- startup chains
- create channel/send packets
- halt chain, export genesis, write file
- restart chain
- send packet over existing channel

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by ThanhNhann** [comment]
can I handle this ser?

**Comment by colin-axner** [comment]
Hi! Yes you can! That would be wonderful!

I've started looking into this so here's some more information:

I think we should add the test into the `e2e/tests/upgrades` directory under a `genesis_test.go` file. We should create a new `TestGenesisTestSuite` as the upgrades one is skipped on regular pr's to ibc-go. 
```go
func TestGenesisTestSuite(t *testing.T) {
    suite.Run(t, new(GenesisTestSuite))
}

type GenesisTestSuite struct {
    testsuite.E2ETestSuite
}
```

We will need to make modifications to interchain test to complete this issue. I've opened this issue https://github.com/strangelove-ventures/interchaintest/issues/418. You are welcome to take that on if you'd like, but I had planned to give it a shot tomorrow on my fork as I know the changes I'd like to do so I don't think it'll take me very long. 

The changes will add a function to the `CosmosChain` struct which will allow us to set the `halt-height` parameter in the `app.toml`. This would be the function we set on the cosmos chains we create. I think we could set the function by adding it as a field to `testconfig.ChainOptionConfiguration` and then calling `GetChains(opts)` before `SetupChainsRelayersAndChannel`
```go
func setHaltHeight(node *cosmos.ChainNode) error {
    appToml := make(testutil.Toml)

    appToml["halt-height"] = haltHeight

    return testutil.ModifyTomlConfigFile(
        ctx, 
        node.logger(),
        node.DockerClient,
        node.TestName,
        node.VolumeName,
        "config/app.toml",
        appToml,   
    )    
}
```
see similar [code](https://github.com/strangelove-ventures/interchaintest/blob/main/chain/cosmos/chain_node.go#L255)

For the genesis import/export test we would set the halt height to X so all nodes would halt at X. Once all the nodes are halted, we should export state from each validator. We can use exec cmd `<bin> export`. I'm not sure if there's an rpc we could call instead?

After exporting. Stop all nodes (remove containers). Write the exported genesis file to the `genesis.json` file location (replacing the old), have the `unsafe-reset-all` be ran on each node. Start all nodes. 

Let me know if you have any questions I can answer. There should be some reusable logic in the `upgrade_test.go`

**Comment by colin-axner** [comment]
Hi again @ThanhNhann. A couple updates. 

You can see [here](https://github.com/strangelove-ventures/interchaintest/issues/418#issuecomment-1457040896) on how to modify the halt height config.

I tested this manually with @chatton, we ran into one issue on updating the client post export/restart. Since the data is wiped on the chain, relayers may have difficulty getting a trusted header to submit for a client update. Here's an issue I wrote on [hermes](https://github.com/informalsystems/hermes/issues/11520) a while back. I'm not sure if the same issue exists on the go relayer, but if it does we can open an issue there. I'd be okay with merging a test which simply sends a second packet, but doesn't attempt to relay the second packet. We can address that second functionality once relayers support genesis restarts as a valid upgrade

**Comment by ThanhNhann** [comment]
thank @colin-axner for the update, love it

**Comment by ThanhNhann** [comment]
hey @colin-axner, it seems like I also face the problem as you said - the data is wiped on the chain, can you plz check my draft pull request to see if it had set up as you above
