### ISSUE TITLE
Add script to have dependabot update all go mods in the same pr

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3256]
## Summary

see https://github.com/cosmos/ibc-go/pull/3248#issuecomment-1458401449

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
worth nothing that the linked script uses a deprecated `::set-output`, this should be replaced with the [new way](https://github.com/cosmos/ibc-go/blob/b4503f4b8f910d46e4c69fff8ea13e91812d8a75/.github/workflows/e2e-compatibility-workflow-call.yaml#L28) of doing it using `>> $GITHUB_OUTPUT`

**Comment by colin-axner** [comment]
closing in favour of #5035
