### ISSUE TITLE
Remove unnecessary anonymous functions in defer statements

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#3298]
## Summary

Throughout the codebase I've noticed several defer statements that are wrapped in an anonymous function, e.g. [this one](https://github.com/cosmos/ibc-go/blob/d840c699d988e32cb55f2c289d69f8ef2e5cea50/modules/core/03-connection/keeper/handshake.go#L153-L155)

```golang
	defer func() {
		telemetry.IncrCounter(1, "ibc", "connection", "open-try")
	}()
```

can be changed to

```golang
defer telemetry.IncrCounter(1, "ibc", "connection", "open-try")
```
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by GNaD13** [comment]
Hi sir @chatton, Can I take this issue?

**Comment by crodriguezvega** [comment]
> Hi sir @chatton, Can I take this issue?

Yes, that would be lovely. Thank you!
