### ISSUE TITLE
x/capability: miscellany and documentation

### ISSUE THREAD

**Issue by cwgoes** [cosmos/ibc-go#3312]
- [ ] Change CapabilityOwners.Set to document better why we need this index (keep list sorted)
- [ ] Add comment for DefaultIndex (cannot start at zero) in genesis.go Godocs
- [ ] Add comment on `capMap` describing what it is for
- [ ] Don't use capabilities with empty names, or check if name is empty in `AuthenticateCapability`
- [ ] Add check for nil capability + empty name to `ClaimCapability`
- [ ] Better document invariants around `GetModuleOwner`
- [ ] Add a note to ExportGenesis on why we can't use the starting index
- [ ] Rename `SetIndex` so it's clearer that it can only be called on genesis initialisation

**Comment by colin-axner** [comment]
capability module will be removed in v10! #7107
