### ISSUE TITLE
rename addr1 to sender, and addr2 to receiver in transfer types testing

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3324]
## Summary

To improve test readability:
- rename [`addr1`](https://github.com/cosmos/ibc-go/blob/main/modules/apps/transfer/types/msgs_test.go#L30) to `sender`
- rename [`addr2`](https://github.com/cosmos/ibc-go/blob/main/modules/apps/transfer/types/msgs_test.go#L31) to `receiver`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by PanGan21** [comment]
Could I pick this up?  Seems quite clear :)

**Comment by crodriguezvega** [comment]
> Could I pick this up? Seems quite clear :)

Yeah, definitely! Thanks, @PanGan21!
