### ISSUE TITLE
Do you have any examples of solo machines being used?

### ISSUE THREAD

**Issue by DaviRain-Su** [cosmos/ibc-go#3334]
## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
crypto.com has developed [this IBC solo machine](https://github.com/devashishdxt/stag). We have a [tutorial in the wiki](https://github.com/cosmos/ibc-go/wiki/IBC-solo-machine) explaining how to use it, in case you're interested.

I will close the issue now, feel free to comment if you have any more questions. For the future, we would appreciate if general questions are asked [on Discord ](https://discord.gg/CMfYR4Ny) or in the Q&A section of [this repo's Discussions](https://github.com/cosmos/ibc-go/discussions/categories/q-a), then other the answer will also be visible for other people as well. Thanks!
