### ISSUE TITLE
Use state in enums in channel handshake logs 

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#3335]
## Summary

Update hardcoded strings used within the ibc channel handshake code to use enum `String()` methods.

At the end of each handshake handler the previous state and current state is logged. Currently, the states are hardcoded. 
Update them to use the correct enum `String()` methods.

See 04-channel/keeper/handshake.go. E.g. https://github.com/cosmos/ibc-go/blob/main/modules/core/04-channel/keeper/handshake.go#L96

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by expertdicer** [comment]
You want the logging msg to stay the same ? Or I can use the enum here https://github.com/cosmos/ibc-go/blob/8c77cb576ed3aa06a234d6166a6b1c3cd58afc5f/modules/core/04-channel/types/channel.pb.go#L31

**Comment by damiannolan** [comment]
Hey @expertdicer! Thanks for comment! 
Yes the logging msg can stay the same ("channel state updated"), but we want to change the hardcoded enum strings to use enums you've linked and their `String()` methods.

E.g.

```diff
- k.Logger(ctx).Info("channel state updated", "port-id", portID, "channel-id", channelID, "previous-state", "NONE", "new-state", "INIT")
+ k.Logger(ctx).Info("channel state updated", "port-id", portID, "channel-id", channelID, "previous-state", types.UNITIALIZED.String(), "new-state", types.INIT.String())
```

Would you like to me to assign you to the issue? :)

**Comment by expertdicer** [comment]
yes of course

**Comment by crodriguezvega** [comment]
Thank you, @expertdicer! If you want to work on this one, I will assign it to you now.
