### ISSUE TITLE
Add length validation of connection hops in channel upgradability msgs

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#3341]
## Summary

We should include basic validation of connection hops length of the `proposedUpgradeChannel` and `counterpartyChannel` in channel upgrades rpc msgs.

Return an error from `ValidateBasic` if `len(connectionHops) != 1`
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Is the [check we currently have in `ValidateBasic` of `UpgradeFields`](https://github.com/cosmos/ibc-go/blob/04-channel-upgrades/modules/core/04-channel/types/upgrade.go#L57-L59) enough, @damiannolan?

**Comment by damiannolan** [comment]
Nice one @crodriguezvega, that should be good given the new `UpgradeFields` type! Closing this
