### ISSUE TITLE
Consistent event handling for an error ACK on packet received

### ISSUE THREAD

**Issue by alpe** [cosmos/ibc-go#3358]
## Summary
Consistent event handling for an error ACK on packet received. 

## Problem Definition

I can see that core/keeper emits them although the state is rolled back: https://github.com/cosmos/ibc-go/blob/v7.0.0/modules/core/keeper/msg_server.go#L459
This was a bit unexpected for me as this is different to the SDK default. I can see some cases where this can make sense but on the other hand there is some risk for clients when events are emitted for operations that never succeeded. I would consider this 2 layers of events.
For example in ICS-20: there are https://github.com/cosmos/ibc-go/blob/v7.0.0/modules/apps/transfer/ibc_module.go#L191 which is correct for both Acks but then there are EventTypeDenomTrace, bank: mint, transfer,..  further upstream.
In ICS-27 execution events are not emitted on error.

## Proposal
Filter out events that are not correct in a state rollback scenario
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by damiannolan** [comment]
completed in https://github.com/cosmos/ibc-go/commit/4973957900d70969d99371e6ed24c47400f5abe6
