### ISSUE TITLE
NewErrorAcknowledgement misses codespace in error message

### ISSUE THREAD

**Issue by webmaster128** [cosmos/ibc-go#3390]
## Summary of Bug

When receiving an error ack created by `NewErrorAcknowledgement` you get an error message that includes the error code but misses the codespace.

## Expected Behaviour

The error ack text "ABCI code: 10: error handling packet: see events for details." includes the codespace.

## Version

Latest main

## Steps to Reproduce

Don't know

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
I think [the codespace is not included in the error message because it's not deterministic](https://github.com/cosmos/ibc-go/blob/a24a6c65f14ceee5e9c8dd3f0f79d63439f1db23/modules/core/04-channel/types/acknowledgement.go#L33-L35) and only the ABCI code is?

**Comment by webmaster128** [comment]
How can the codespace be non deterministic? Isn't the code pretty useless without the codespace? If I understand correctly codespace/code work like street and house number where you only find the house if you have both.

**Comment by colin-axner** [comment]
Hi @webmaster128, I agree it is quite odd that the codespace is non deterministic, but this unfortunately appears to be the case, see [`determinsticExecTxResult`](https://github.com/cometbft/cometbft/blob/main/types/results.go#L47). As you can see, the codespace is not included in the response which is included in the block hash. While it is unlikely that the codespace would change between versions, it does make including the codespace within the acknowledgement unsafe. I think the appropriate solution is to see if we can change this on cometbft as I don't see a reason why we shouldn't include the codespace? Is there an immediate for this to be fixed, or is it simply odd behaviour you noticed? Thanks for opening the issue

**Comment by webmaster128** [comment]
Thank you for the explanation. Either this is super weired or I don't understand codespaces. Is this for historical reasons (first there was code only, then namespacing was required)?

> Is there an immediate for this to be fixed, or is it simply odd behaviour you noticed? Thanks for opening the issue

This is of practical importance when more and more IBC devs try to debug error acks. Not having the error message is hard enough (not the topic of this ticket though). But then an error code like `10` does not even tell me if I have to search in Cosmos SDK or wasmd for that number (sdk/10 or wasm/10).

**Comment by colin-axner** [comment]
> Is this for historical reasons (first there was code only, then namespacing was required)?

I crawled down the rabbit hole, and I cannot find any reasoning for why it wasn't included. It seems it might have been an oversight. This [pr](https://github.com/tendermint/tendermint/pull/4845) introduced the code into the deterministic values. This [adr](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-022-abci-errors.md#decision) indicates:
> How the codespace is hashed into block headers (ie. so it can be queried efficiently by lite clients) is left for a separate ADR.

I see how this could be quite frustrating to debug and it will likely be applicable to every IBC app. The primary intention of the existing `NewErrorAcknowledgement` constructor is to provide a safe entry point for IBC app developers to avoid accidentally introducing a halting bug via non-determinism. I think we definitely should ask to include the codespace in the results hash, thus allowing to it to be included in error acknowledgements, but there are likely additional improvements we can support.

Can you provide me with example workflows you have been using so far? I believe logging has been added for these errors, so I guess the primary pain point would be receiving the error acknowledgement in production? Where logs are not readily available?

One idea is to add an additional constructor `NewErrorAcknowledgementWithDeterminsticInfo` to allow the IBC app to provide constant string it treats as state machine breaking. This seems like a fair compromise between safety/UX. It would help to justify this addition if we could identify situations where it may be common for an IBC app to return an error acknowledgement in production?

If you follow the discussion linked in the above pr, there was a lot of interesting discussion around the usage of `code` and `codespace`. It appears `code` was intended to be a condensed version of the error string, it was expected that the UI would replace the code with the registered string, but this actually seems like quite the expectation. I'm not quite sure how we could safely perform such an action as error string are generally not considered state machine breaking at the moment.

**Comment by webmaster128** [comment]
Okay, thanks a lot. I think for the sake of completeness we should get the codespace in there.

My scenario is this [integration testing setup](https://github.com/noislabs/nois-contracts/tree/main/tests):
- 2 chains running in docker
- IBC integration tests written in TypeScript
- ts-relayer relays between them

Now if anything goes wrong, I get an error output like this:

```
  tests › submit randomness for various job counts
  src/tests.spec.ts:673

   672: 
   673: 
   674: 

  Rejected promise returned by test. Reason:

  Error {
    message: 'Unexpected error in ack: ABCI code: 5: error handling packet: see events for details',
  }

  › Error: Unexpected error in ack: ABCI code: 5: error handling packet: see events for details
  › assertAckSuccess (src/utils.ts:77:13)
  › assertPacketsFromA (src/utils.ts:106:5)
  › <anonymous> (src/tests.spec.ts:673:23)
  › Generator.next (<anonymous>)
  › fulfilled (build/tests.spec.js:5:58)
  › runMicrotasks (<anonymous>)
```

Sure, pulling out the string from somewhere burried in the docker or even events might be an option. But often enough the error code was sufficient to get an idea what the problem is. Just that "ABCI code: 5" is incomplete because it does not fully specify the error due to the missing codespace.

**Comment by colin-axner** [comment]
I will open an issue on cometbft. Thanks for the example use. I think we should encourage using logs to determine the error message for development purposes to get more find grained details. Is there anything we could do to help your testing workflow in the meantime?

**Comment by colin-axner** [comment]
opened https://github.com/cometbft/cometbft/issues/844!

**Comment by colin-axner** [comment]
> In addition to that I was thinking about just adding codespace to the error ack contents in NewErrorAcknowledgement since it should be safe to consider the codespace to be stable, even if not hashed into the app hash. Thoughts on that option?

This sounds like a reasonable option to me. I'd like to discuss with the team to see if we have any concerns about this option

> Are you talking about logs in the sense of node logging or events as suggested in the error message? The nodes are not somthing app develops have access to (think about development on testnets, nodes running in docker containers, nodes producing blocks at 10 blocks/second in dev environments. Events are practical but adding debug information to events just because they are not part of consensus also feels a bit hacky.

Node logs! I agree with your latter comment.

**Comment by puneet2019** [comment]
hi!
even I am having problems with this behaviour.
example I take a look at this txn ->
[relayer tx](https://rest.cosmos.audit.one/cosmos/tx/v1beta1/txs/1FA8FE72A2005BD65676FC62492031ACBAA5945E8278BC292FA061653715D323)

 It says `ABCI code: 107: error handling packet: see events for details` 
 And if I look at events that is the only error present there. 
 
1. look up at cosmos-sdk code and finding the error code and it's occurances.
2. find node logs.
3. sometimes I have even synced the mainnet chain to add a debug point.

And I believe it should be easier to know the reason just from the tx response. 

Can we just actually add an event for error? As events are not part of consensus.

**Comment by puneet2019** [comment]
Agree that 
> Events are practical but adding debug information to events just because they are not part of consensus also feels a bit hacky
but I would still be ok with this/ having something than not having anything at all.

**Comment by webmaster128** [comment]
Closing in favour of the specific proposal in #5736
