### ISSUE TITLE
Replace 03-connection versioning contains with internal generics Contains function

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3400]
## Summary

The channel upgradability branch added a nifty [Contains](https://github.com/cosmos/ibc-go/blob/04-channel-upgrades/internal/collections/collections.go#L4) function. We should upstream this change to main so that 03-connection [version.go](https://github.com/cosmos/ibc-go/blob/main/modules/core/03-connection/types/version.go#L213) can make use of it as well

I think the change can be added to main since it is unrelated to channel uggradability

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by pysel** [comment]
is it available to pick up?

**Comment by DimitrisJim** [comment]
Afaik the change hasn't been upstream yet @pysel. When it is I'm sure you should be able to pick it up.

**Comment by DimitrisJim** [comment]
@pysel you can go for it now!
