### ISSUE TITLE
Write modified channel upgrade init rather than user provided argument

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3401]
## Summary of Bug

**Edit:** see comment below

No check exists within 04-channel asserting the state of the proposed upgrade channel. The provided upgrade channel is set into state. 

## Expected Behaviour

The proposed upgrade channel provided in UpgradeInit must be in INITUPGRADE state

## Steps to Reproduce

```diff
diff --git a/modules/core/04-channel/keeper/upgrade_test.go b/modules/core/04-channel/keeper/upgrade_test.go
index 5bacf0ce6..b3674055a 100644
--- a/modules/core/04-channel/keeper/upgrade_test.go
+++ b/modules/core/04-channel/keeper/upgrade_test.go
@@ -100,6 +100,13 @@ func (suite *KeeperTestSuite) TestChanUpgradeInit() {
                        },
                        false,
                },
+               {
+                       "invalid proposed channel upgrade ordering",
+                       func() {
+                               channelUpgrade.State = types.OPEN
+                       },
+                       false,
+               },
        }
 
        for _, tc := range testCases {

```

```
--- FAIL: TestKeeperTestSuite (48.75s)
    --- FAIL: TestKeeperTestSuite/TestChanUpgradeInit (2.60s)
        --- FAIL: TestKeeperTestSuite/TestChanUpgradeInit/invalid_proposed_channel_upgrade_ordering#01 (0.22s)
            upgrade_test.go:138: 
                	Error Trace:	/home/bartleby/work/go/src/github.com/cosmos/ibc-go/modules/core/04-channel/keeper/upgrade_test.go:138
                	            				/home/bartleby/work/go/pkg/mod/github.com/stretchr/testify@v1.8.2/suite/suite.go:112
                	Error:      	An error is expected but got nil.
                	Test:       	TestKeeperTestSuite/TestChanUpgradeInit/invalid_proposed_channel_upgrade_ordering#01
FAIL
exit status 1
FAIL	github.com/cosmos/ibc-go/v7/modules/core/04-channel/keeper	48.772s

```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
I found the check in the [`msg.ValidateBasic()`](https://github.com/cosmos/ibc-go/blob/04-channel-upgrades/modules/core/04-channel/types/msgs.go#L511) which is safe enough. I still believe we should not be writing the entire `proposedUpgradeChannel` but rather modifying the existing channel based on the verified arguments provided. I'm going to modify this issue for that aim

**Comment by chatton** [comment]
I think this issue can be closed now as it doesn't apply with the new design. Please re-open if the issue is still relevant!
