### ISSUE TITLE
improper test case on channel upgrade branch

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3403]
## Summary

Should say [UNORDERED](https://github.com/cosmos/ibc-go/blob/04-channel-upgrades/modules/core/04-channel/types/channel_test.go#L101). Test case name is correct

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closed by #3405
