### ISSUE TITLE
Use UpgradeTimeout type instead of two separate fields

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3410]
## Summary

In all instances of timeouts being passed around in relation to channel upgrades, we should use the `UpgradeTimeout` type. 

## Problem Definition

The upgrade timeout timestamp and the upgrade timeout height are never used in isolation of each other. Given that we have a verifiable type that wraps both, we should make use of it to simplify the API

## Proposal

Change all instances of upgrade timeouts being passed around to utilize the `UpgradeTimeout` type. This should occur in the msg [types](https://github.com/cosmos/ibc-go/blob/04-channel-upgrades/modules/core/04-channel/types/msgs.go#L489-#L490), as well as to the [channel handshake functions](https://github.com/cosmos/ibc-go/blob/04-channel-upgrades/modules/core/04-channel/keeper/upgrade.go#L27)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by vishal-kanna** [comment]
@colin-axner Is it replacing the timeoutTimestamp and timeoutHeight  with UpgradeTimeout in the msgs.go and upgrade.go

**Comment by colin-axner** [comment]
Yes that is correct. The changes should be applied to the 04-channel-upgrades branch

**Comment by damiannolan** [comment]
do you think the protobufs should also be changed? e.g. in [`MsgChannelUpgradeInit`](https://github.com/cosmos/ibc-go/blob/04-channel-upgrades/proto/ibc/core/channel/v1/tx.proto#L267-L268) and [`MsgChannelUpgradeTry`](https://github.com/cosmos/ibc-go/blob/04-channel-upgrades/proto/ibc/core/channel/v1/tx.proto#L289-L290)

**Comment by damiannolan** [comment]
Going to close this is issue as I think its redundant with the changes proposed in https://github.com/cosmos/ibc-go/pull/3438
