### ISSUE TITLE
Code consistency nits in grpc handler

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3422]
## Summary

- Use `k` instead of `q, see [comment](https://github.com/cosmos/ibc-go/pull/3019#discussion_r1138913048)
- Unwrap the sdk context first, see [comment](https://github.com/cosmos/ibc-go/pull/2193#discussion_r964639500)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by ruthishvitwit** [comment]
I have changed the q's to k but I am not able to undertand on how to unwrap the sdk context first .
