### ISSUE TITLE
Rejecting a handshake causes future valid handshakes to fail in testing

### ISSUE THREAD

**Issue by 0xekez** [cosmos/ibc-go#3428]
possibly related to #3264.

I am attempting to test rejected handshakes and noticing some issues with both ibctesting and interchaintest.

I have two module types "note" and "voice". I want to disallow note <-> note and voice <-> voice connections, and allow note <-> voice connections. To test this, I do the following:

1. Attempt a handshake between noteA <-> noteB, this fails during the `try` step of the handshake.
2. Attempt handshake between noteA <-> voiceB, this should work but does not.

I can test that (2) works independently, so I know that it is performing (1) that is causing the problem.

## ibctesting

reprodued [here](https://github.com/DA0-DA0/polytone/blob/406fb5e4576a1ca97b9d4932ac969ccb7cdb64e0/tests/simtests/functionality_test.go#L175-L179).

For ibctesting, the issue that occurs is that after the failed handshake, the sequence number of the account performing the handshake becomes off-by-one. I can resolve the issue by manually incrementing the sending account's sequence number.

## interchaintest

reproduced [here](https://github.com/DA0-DA0/polytone/blob/406fb5e4576a1ca97b9d4932ac969ccb7cdb64e0/tests/strangelove/incompatible_handshake_test.go#L37-L44).

For interchaintest, using real docker nodes and the cosmos/rly relayer, the second step also fails with the error:

```
exit code 1:  Error: channel {channel-1} with port {wasm.juno14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9skjuwg8} already exists on chain {juno1-1}
```

## summary

Using both ibctesting and interchaintest i am unable to handshake with a module after a previous handshake with that module has failed. I'm wondering if this is a known issue? If there are tests for host <-> host handshakes in ICA they should also have this problem - so possible i'm missing something as well.

thanks for your time and help!

**Comment by chatton** [comment]
Hi @0xekez  thanks for creating the issue! Just looking at the interchain test implementation you have, I noticed that the `suite.QueryChannelsInState` function isn't actually respecting the input argument and is just looking for [STATE_OPEN](https://github.com/DA0-DA0/polytone/blob/406fb5e4576a1ca97b9d4932ac969ccb7cdb64e0/tests/strangelove/suite.go#L250)

**Comment by damiannolan** [comment]
> I can test that (2) works independently, so I know that it is performing (1) that is causing the problem.

Judging from the error provided from interchaintest I can only assume that your application code does something similar to ICA(?) with respect to port allocation. It looks to me as if the same address is being provided on the second attempt, and this is causing the channel/port already exists error as step (1) would've written a channel end in state `INIT` to store and created the port `wasm.juno14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9skjuwg8`

**Comment by 0xekez** [comment]
> @chatton:  I noticed that the suite.QueryChannelsInState function isn't actually respecting the input argument

Thanks for taking a look and good catch! I'll fix this up, though this doesn't resolve the issue of the second handshake failing.

> @damiannolan: It looks to me as if the same address is being provided on the second attempt

Yeah this is what's happening. In terms of ICA, my test:

1. Tries to create a connection between two host modules.
2. The connection fails during the try step of the handshake as the host modules won't connect to other hosts.
3. I then try to make a connection between one of the previously used host modules and a controller module.

My understanding is that step 3 should work, but in both test frameworks it does not. I'm trying to understand if this is an issue with the testing frameworks or an issue with the IBC code as I think this is an interesting DOS vector.

**Comment by crodriguezvega** [comment]
Regarding the issue with ibctesting: I might be wrong, but could the explanation be that the [sequence number is only updated if the transaction succeeds](https://github.com/cosmos/ibc-go/blob/main/testing/chain.go#L338)? If `ChanOpenTry` fails during the handshake, then the sequence number for the sender account on chain B will not be updated, right?

Also, I just noticed that in the code you link I think there's a typo [here](https://github.com/DA0-DA0/polytone/blob/406fb5e4576a1ca97b9d4932ac969ccb7cdb64e0/tests/simtests/functionality_test.go#L180) because you're using chain A sender's sequence to update chain Bs sender's sequence...

**Comment by crodriguezvega** [comment]
@mmsqe did you succeeded with the test you were writing? do you think there's anything else we need to look into?

**Comment by crodriguezvega** [comment]
Issue is stale, so closing for now.
