### ISSUE TITLE
e2e: Replace `AssertValidTxResponse` and error check with `AssertSuccessTx` or `AssertFailedTx`

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3435]
## Summary

Instead of asserting that a response from broadcasting a tx is not nil, we should immediately fail if it is nil and provide helper functions to see if the tx was successful or not. See [comment](https://github.com/cosmos/ibc-go/pull/3402#discussion_r1159885971):

Instead of:
```go
    transferTxResp, err := s.Transfer(args)
    s.Require().NoError(err)
    s.AssertValidTxResponse(transferTxResp)
```
use
```go
    resp := s.Transfer(args)
    s.AssertTxSuccess(resp)
```
or
```go
    resp := s.Transfer(args)
    s.AssertTxFailure(resp, transfertypes.ErrInsufficientBalance) // expected error code 
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
Updated link to [BroadcastMessages](https://github.com/cosmos/ibc-go/blob/d3038f8317bbf4a9f43c578f7b6d4a6a5c4ebda5/e2e/testsuite/tx.go#L31) and the [error return](https://github.com/cosmos/ibc-go/blob/d3038f8317bbf4a9f43c578f7b6d4a6a5c4ebda5/e2e/testsuite/tx.go#L58)
