### ISSUE TITLE
Maybe found a bug which ScopeKeeper.capMap maybe wrong

### ISSUE THREAD

**Issue by BananaLF** [cosmos/ibc-go#3442]
I watched the capMap of ScopeKeeper which is wrote/read by follow code. It is not safe on concurrency. 
https://github.com/cosmos/ibc-go/blob/2632ae24926e251fb70efabaa1a8b92755c7bccc/modules/capability/keeper/keeper.go#L268

https://github.com/cosmos/ibc-go/blob/2632ae24926e251fb70efabaa1a8b92755c7bccc/modules/capability/keeper/keeper.go#L390

 As far as I know, the simulate tx which is will call 'NewCapability' can update wrong value to capMap at a node . Then, it will call 'GetCapability' to got wrong value when deliver tx . But it will call 'GetCapability' to got wrong value at other node.  

So i think ScopeKeeper.capMap will be cause state machine broken ,or fork a chain.

Please help me to solve this problem！

**Comment by DimitrisJim** [comment]
> It is not safe on concurrency.

Afaik, concurrency isn't an issue since each message is executed deterministically. Unless I am not seeing something here in which case someone else will chime in!

**Comment by BananaLF** [comment]
> Afaik, concurrency isn't an issue since each message is executed sequentially in a deterministic order
I thinks each message is executed sequentially within BaseApp.DeliverTx. it's safe concurrency within DeliverTxs. 
But some message is executed within BaseApp.Simulate, then 'capMap' is not safe between BaseApp.Simulate with BaseApp.DeliverTx
