### ISSUE TITLE
Add verifiable upgrade type and validate basic functions

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#3445]
## Summary 

Part of #3438

Reference [this commit](https://github.com/cosmos/ibc-go/pull/3438/commits/7c4a32ccd19d98ad0b8ffb9ace470947ab4a9076) and [this one](https://github.com/cosmos/ibc-go/pull/3438/commits/c4857a0810e4304ce8f330e839c7e263934d15d6).
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
I believe this has been completed!
