### ISSUE TITLE
Modify UpgradeInit to use new upgrade type

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#3447]
## Summary

Part of #3438

See [this commit](https://github.com/cosmos/ibc-go/pull/3438/commits/e9b06ad461457a1f5d1a0289a0bbe56db9ccee99).
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by charleenfei** [comment]
closed with https://github.com/cosmos/ibc-go/pull/3456
