### ISSUE TITLE
Modify UpgradeTry to use new structure

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#3448]
## Summary 

Part of #3438 

Reference [this commit](https://github.com/cosmos/ibc-go/pull/3438/commits/d38cc189e4597ff2954f589e3de4acb4e9f0b3d0)

Note: **these changes should go into [this branch](https://github.com/cosmos/ibc-go/tree/cian/issue%231619-implement-channelupgradetry-functionality-for-04-channel)**.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
Closing as the msg field types have been modified, see #1619 to track the implementation of the upgrade try handler
