### ISSUE TITLE
Cleanup unused functions (Channel Upgradability)

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#3449]
## Summary

Part of #3438

Reference [this commit](https://github.com/cosmos/ibc-go/pull/3438/commits/bf8621d61a958a5ddb6d0e1b457f8fd83e7e403b).

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by damiannolan** [comment]
completed in #3498
