### ISSUE TITLE
Add ValidateBasic tests for Channel Upgrade Types

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#3464]
## Summary 

Follow up for #3451

Add validate basic tests for [Upgrade](https://github.com/cosmos/ibc-go/blob/d66fe9de8a34f6c931751046a44522ab750e02a2/modules/core/04-channel/types/upgrade.pb.go#L31) and [Upgrade Fields](https://github.com/cosmos/ibc-go/blob/d66fe9de8a34f6c931751046a44522ab750e02a2/modules/core/04-channel/types/upgrade.pb.go#L93)
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by phamminh0811** [comment]
can I handle this issue?

**Comment by DimitrisJim** [comment]
seems this was done with 6d80a3698ff4996c460e14fa299a76939bee165c?

**Comment by crodriguezvega** [comment]
Indeed, thanks for noticing that, @DimitrisJim!

Closed by https://github.com/cosmos/ibc-go/pull/3709.
