### ISSUE TITLE
Add helper for checking if a connection exists and is open

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#3466]
## Summary

There's many instances of code that requires a connection to exist and be open:

1. During [`AcknowledgePacket`](https://github.com/cosmos/ibc-go/blob/c043dbdeef4929988a02578606f8d8fdf21a3f25/modules/core/04-channel/keeper/packet.go#L404)

2. During [`RecvPacket`](https://github.com/cosmos/ibc-go/blob/c043dbdeef4929988a02578606f8d8fdf21a3f25/modules/core/04-channel/keeper/packet.go#L166)

3. During [`ChanOpenTry`](https://github.com/cosmos/ibc-go/blob/c043dbdeef4929988a02578606f8d8fdf21a3f25/modules/core/04-channel/keeper/handshake.go#L128)

4. During [`ChanOpenAck`](https://github.com/cosmos/ibc-go/blob/c043dbdeef4929988a02578606f8d8fdf21a3f25/modules/core/04-channel/keeper/handshake.go#L239)

5. During [`ChanOpenConfirm`](https://github.com/cosmos/ibc-go/blob/c043dbdeef4929988a02578606f8d8fdf21a3f25/modules/core/04-channel/keeper/handshake.go#L318)

6. During [`ChanCloseInit`](https://github.com/cosmos/ibc-go/blob/c043dbdeef4929988a02578606f8d8fdf21a3f25/modules/core/04-channel/keeper/handshake.go#L391)

7. During [`ChanCloseConfirm`](https://github.com/cosmos/ibc-go/blob/c043dbdeef4929988a02578606f8d8fdf21a3f25/modules/core/04-channel/keeper/handshake.go#L447)

Additionally, it seems it will also be required in `validateProposedUpgradeFields` as added at some point in #3451 where it was initially conceived.

In most cases, the `connectionEnd` that is retrieved using `GetConnection` is required at some later
step in the function, as such, if a new function is to be added, it should return the open connection end if it exists.

## Proposal

Add a new function that encapsulates both these steps; checks for existence and if the connection's state is OPEN, [Bikeshed](https://en.wiktionary.org/wiki/bikeshedding) the naming.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Let's create an `IsOpen` function in the `Connection` type that does the open check:

```golang
if !connection.IsOpen() {
  return errorsmod.Wrapf(connectiontypes.ErrInvalidConnectionState, "expected %s, got %s", connectiontypes.Open, connectionEnd.State)
}
```

```golang
function (connection Connection) IsOpen() bool {
  return connection.State == int32(connectiontypes.OPEN) 
}
```

Make different issues for:
- Try to get rid of `GetState` getter. It's in the go code, not proto file. (API breaking to be released in next major release)
- Change `connectiontypes.ErrInvalidConnectionState` to `connectiontypes.ErrUnexpectedConnectionState`.
- Do the same for channel.

**Comment by damiannolan** [comment]
Closing based on the comment in #5691 from @crodriguezvega. I think the general consensus has been: explicit is better
