### ISSUE TITLE
grpc query for type.Upgrade

### ISSUE THREAD

**Issue by charleenfei** [cosmos/ibc-go#3481]
## Summary of Bug

Previously, we exposed a grpc query for UpgradeSequence. As we have now refactored to using type.Upgrade, we should expose instead a grpc query for each Upgrade per port/channelID pair

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by damiannolan** [comment]
completed in #3491
