### ISSUE TITLE
Consider testing Upgrade handshake at the message server layer

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#3489]
## Summary 

Currently we are testing the functionality at the [keeper](https://github.com/cosmos/ibc-go/blob/dfd9be37b1ce5594f4ea5bb2f40acaf22fd43b52/modules/core/04-channel/keeper/upgrade.go#L13) level.

See [this test](https://github.com/cosmos/ibc-go/blob/0e8092b8bf523dd1dd4dfdd3c530f66d9829c511/modules/core/04-channel/keeper/upgrade_test.go#L128-L130) as an example.

This has some problems. We are not able to verify the final state of the channel without mocking what is happening at [the message server layer](https://github.com/cosmos/ibc-go/blob/b8b5ca4b6b3228564f426d39c27e19997a7408e8/modules/core/keeper/msg_server.go#L741).

This would have some overlap with our e2e tests, but I think it will be a more comprehensive test.

e.g. if we change the message server code in the future, the existing tests might still pass. (however e2e would fail)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
I believe we can add tests at the msg server layer no problem? See the [existing tests](https://github.com/cosmos/ibc-go/blob/main/modules/core/keeper/msg_server_test.go#L205)

**Comment by colin-axner** [comment]
I believe we have added tests at the msg server layer now so we can close this issue?

**Comment by chatton** [comment]
You are correct! We can close this.
