### ISSUE TITLE
e2e test for ChanUpgradeTry

### ISSUE THREAD

**Issue by charleenfei** [cosmos/ibc-go#3490]
## Summary of Bug

we should have an e2e testing the functionality of ChanUpgradeTry, this would also allow us to test the msg_server layer.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
This isn't an E2E test we're talking about right, this is more of a unit/integration test using our testing library (not using interchain test in the e2e directory)

**Comment by crodriguezvega** [comment]
Closing now as we have coverage of `ChanUpgradeTry` both in e2e tests now.
