### ISSUE TITLE
Add Unit Tests for Channel Upgrade Event Emission

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#3497]
## Summary 

Ref: [this comment](https://github.com/cosmos/ibc-go/pull/3456#discussion_r1170917426)
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by DimitrisJim** [comment]
Guess this can stay open to keep track of `ChanUpgradeConfirm`? (Or we could just open an additional issue tbh)

**Comment by chatton** [comment]
Un-assigning myself for now since the original PR was merged, can leave this issue open until all the events are tested.

**Comment by charleenfei** [comment]
I think the only one left is `UpgradeError`? can update with this one

**Comment by charleenfei** [comment]
on hold until [this pr](https://github.com/cosmos/ibc-go/pull/5264) is merged

**Comment by colin-axner** [comment]
There's commented out tests in `TestWriteUpgradeOpenChannel_UnorderedToOrdered()`

**Comment by charleenfei** [comment]
Yea, I think all of them need the event testing now after the events were moved, will work on all of them in one go now
