### ISSUE TITLE
Can the keeper of IBC transfer be changed to an interface?

### ISSUE THREAD

**Issue by wangfeiping** [cosmos/ibc-go#35]
## Summary

Can the keeper of IBC transfer be changed to an interface?

## Problem Definition

I am currently working on a project to automatically mint some vouchers to the user when the user transfers tokens. I think there is a need to ensure the transactional of these operations, so the mint needs to be completed at the same time as the transfer takes place.

This is easy to achieve in the keeper of the bank module, because the keeper of the bank is an interface.

https://github.com/cosmos/cosmos-sdk/blob/dd9ef120f3415c4d84d3ce34267453ecb94b797f/x/bank/keeper/keeper.go#L22

I just need to refer to the keeper of the bank module and wrap the SendCoins(...) method, and then replace the keeper of the bank module:

https://github.com/wangfeiping/flares/blob/1ed7d65a6f5cd8566267adc038c8fe47c42f32d5/app/app.go#L272

https://github.com/wangfeiping/flares/blob/1ed7d65a6f5cd8566267adc038c8fe47c42f32d5/x/bank/keeper/keeper_wrapper.go#L15

https://github.com/wangfeiping/flares/blob/1ed7d65a6f5cd8566267adc038c8fe47c42f32d5/x/bank/keeper/keeper_wrapper.go#L41

But IBC transfer's keeper is not an interface, so it can't be implemented that way.

https://github.com/cosmos/cosmos-sdk/blob/dd9ef120f3415c4d84d3ce34267453ecb94b797f/x/ibc/applications/transfer/keeper/keeper.go#L36

If the keeper of IBC transfer is also defined by interface, will it be more in line with OCP (Open Close Principles ) and more conducive to future maintenance and expansion?

## Proposal

Please change the keeper of IBC transfer to the interface.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by colin-axner** [comment]
It is possible for you to create the interface for ics20? This should be similar to how our modules use `expected_interface.go` in each types package. 

Closing this issue for now
