### ISSUE TITLE
Migrate `27-interchain-accounts` host params to be self managed

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#3504]
Part of https://github.com/cosmos/ibc-go/issues/2010. Please read that issue for more information.

**Comment by aleem1314** [comment]
@crodriguezvega can I take this issue?

**Comment by crodriguezvega** [comment]
> @crodriguezvega can I take this issue?

Yes, @aleem1314. Thank you very much! Please check #2010 and [this comment](https://github.com/cosmos/ibc-go/issues/2010#issuecomment-1399618502) for guidance on how to go about it. :)
