### ISSUE TITLE
No type registered for ibc.core.client.v1.ClientUpdateProposal

### ISSUE THREAD

**Issue by ryanchristo** [cosmos/ibc-go#3539]
## Summary of Bug

Ref: https://github.com/regen-network/regen-ledger/issues/1895

A message-based governance proposal with type `/ibc.core.client.v1.ClientUpdateProposal` produces the following error:

```
Error: no concrete type registered for type URL /ibc.core.client.v1.ClientUpdateProposal against interface *types.Msg
```
 
## Expected Behaviour

Submitting a message-based governance proposal with type `/ibc.core.client.v1.ClientUpdateProposal` produces no error.

## Version

`v5.2.0`

## Steps to Reproduce

1. start simapp using version `v5.2.0`
2. create proposal json
```
nano proposal.json

...

{
  "messages": [
    {
      "@type": "/ibc.core.client.v1.ClientUpdateProposal",
      "title": "Update IBC Client",
      "description": "Update IBC Client",
      "subject_client_id": "07-tendermint-100",
      "substitute_client_id": "07-tendermint-116"
    }
  ],
  "metadata": "",
  "deposit": "1stake"
}
```
3. submit proposal
```
./build/simd tx gov submit-proposal proposal.json --from test
```
4. confirm error
```
Error: no concrete type registered for type URL /ibc.core.client.v1.ClientUpdateProposal against interface *types.Msg
```
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by damiannolan** [comment]
Hey, thanks for opening the issue! I believe https://github.com/cosmos/ibc-go/issues/1282 was created for supporting gov v1 msg execution. I think this will likely be completed as part of the next major release ibc-go/v8.

**Comment by ryanchristo** [comment]
Just noting here that the documentation is a bit misleading atm. As far as I understand, the non-recommended way of submitting a proposal to update a client (i.e. `submit-legacy-proposal`) is the only option for a chain running v0.46 with ibc-go v5.x.

https://ibc.cosmos.network/main/ibc/proposals.html#step-2

**Comment by crodriguezvega** [comment]
> As far as I understand, the non-recommended way of submitting a proposal to update a client (i.e. submit-legacy-proposal) is the only option for a chain running v0.46 with ibc-go v5.x.

Yes, I think you're correct and we should then update our docs. Once #1282 is implemented and we can support gov v1 message execution we will update the docs again.

**Comment by crodriguezvega** [comment]
Closed by https://github.com/cosmos/ibc-go/pull/4580
