### ISSUE TITLE
UpgradeTimeout type should be renamed to Timeout

### ISSUE THREAD

**Issue by charleenfei** [cosmos/ibc-go#3551]
## Summary of Bug

Described [in this pr comment](https://github.com/cosmos/ibc-go/pull/3535/files#r1183800431). The new `Timeout` type should be used for packet timeouts as well.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
closed by #3572
