### ISSUE TITLE
Create an API on the transfer module that allows to construct an IBC denom given the channel, port and original denom

### ISSUE THREAD

**Issue by srdtrk** [cosmos/ibc-go#3575]
## Summary

Design an API to Return Full IBC Denomination Based on Channel, Port, and Original Denomination.

## Problem Definition

External modules or applications that need to generate the IBC denomination often find themselves replicating code from the transfer module. An example of such replication can be found [here](https://github.com/cosmos/interchain-security/blob/ab5201f67d4c138a1dd14383ebda8c35986f2210/x/ccv/consumer/keeper/distribution.go#L174-L188)

## Proposal

To address this issue, it is proposed to create an API that returns the full IBC denomination given the channel, port, and original denomination. The solution would look like (and reside in `types/coin.go`):

```go
// GetIBCDenom generates the full IBC denomination string based on
// the provided portID, channelID, and baseDenom.
func GetIBCDenom(portID, channelID, baseDenom string) string {
	denomTrace := ParseDenomTrace(GetPrefixedDenom(portID, channelID, baseDenom))
	return denomTrace.IBCDenom()
}
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
See [comment](https://github.com/cosmos/ibc-go/pull/3579#issuecomment-1637662636).
