### ISSUE TITLE
ICS 721 nft-transfer module that is compatible for IBC v5 and v7

### ISSUE THREAD

**Issue by KimuraYu45z** [cosmos/ibc-go#3576]
## Summary

I forked https://github.com/bianjieai/ibc-go/tree/develop/modules/apps/nft-transfer this repo and then made it compatible with IBC v5 and v7.

https://github.com/cosmos/ibc-go/compare/v5.3.0...KimuraYu45z:v5-nft-transfer?expand=1
https://github.com/cosmos/ibc-go/compare/v7.0.0...KimuraYu45z:v7-nft-transfer?expand=1

I want to ask the most proper place to be merged.

- https://github.com/cosmos/ibc-go
- https://github.com/bianjieai/ibc-go
- https://github.com/bianjieai/nft-transfer

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Hi @KimuraYu45z. Thanks for your work. The proper repository where you can contribute to the nft-transfer app is https://github.com/bianjieai/nft-transfer. I will close this issue now then.
