### ISSUE TITLE
update NewPacket API to use new Timeout type

### ISSUE THREAD

**Issue by charleenfei** [cosmos/ibc-go#3600]
## Summary of Bug

Currently, the [`NewPacket` API](https://github.com/cosmos/ibc-go/blob/1f323ce126c1362809c69a616a5c0390ed5f726d/modules/core/04-channel/types/packet.go#L47) expects separate timeout height and timeout timestamp parameters. We should update this to use the new `Timeout` type.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by vishal-kanna** [comment]
@charleenfei  can you please explain about new TImeout type? is it UpgradeTimeout or anything else?

**Comment by hieuvubk** [comment]
Is this issue still available?

**Comment by charleenfei** [comment]
Hi @vishal-kanna, @hieuvubk -- sorry for the delay in reply. 

The new `Timeout` type is referring to [this type](https://github.com/cosmos/ibc-go/blob/fff59082feb2488013ab7660e80e5e8814cf58ed/proto/ibc/core/channel/v1/channel.proto#LL166C18-L166C18), which should replace the separate params in the `NewPacket` API.

Please note that if either of you would like to work on this this issue, the PR should be branched off of `main`, and as it will be an API breaking change it will only released in the next major release.

**Comment by shreya0288** [comment]
@charleenfei can I work on this issue?

**Comment by crodriguezvega** [comment]
See [here](https://github.com/cosmos/ibc-go/pull/6906#pullrequestreview-2190399915) for reasoning to close the issue.
