### ISSUE TITLE
Use option extension to signal message signers in protobuf files

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#3624]
Cosmos SDK introduced a [message option extension to signal message signers in a language agnostic way](https://github.com/cosmos/cosmos-sdk/pull/10977) that we can also adopt in our messages. See [usage in `x/bank`](https://github.com/cosmos/cosmos-sdk/pull/10977/files#diff-bea15b4c34f611322832ce50942a0ccbf7ef460548227795a504c3e72f6e85d4) for an example.

**Comment by vishal-kanna** [comment]
@crodriguezvega  i would like to work on this

**Comment by crodriguezvega** [comment]
Thank you, @vishal-kanna! I will assign it to you now.
