### ISSUE TITLE
Use option extension to signal services in protobuf files

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#3625]
The SDK introduced a [message option extension to signal services in a language agnostic way](https://github.com/cosmos/cosmos-sdk/pull/13178) that we can also adopt in our services. See the PR linked for a set of how the changes ought to be made.

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by vishal-kanna** [comment]
@DimitrisJim i would like to work on this issue

**Comment by DimitrisJim** [comment]
Nice, thanks @vishal-kanna!
