### ISSUE TITLE
`UpdateState` panics if client message is of type `Misbehaviour`

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#3636]
_Many thanks to @plafer for finding this bug._

## Summary of Bug

It is possible for [`CheckForMisbehaviour` to return false](https://github.com/cosmos/ibc-go/blob/d3038f8317bbf4a9f43c578f7b6d4a6a5c4ebda5/modules/light-clients/07-tendermint/misbehaviour_handle.go#L80) for a client message of type `Misbehaviour`, and if this happens, then [`UpdateState` will panic](https://github.com/cosmos/ibc-go/blob/d3038f8317bbf4a9f43c578f7b6d4a6a5c4ebda5/modules/light-clients/07-tendermint/update.go#L134). 

## Expected Behaviour

`UpdateState` does not panic if client message is of type `Misbehaviour`.

## Version

v7.0.0

## Steps to Reproduce

Submit an `MsgUpdateClient` where `ClientMessage` is of type `Misbehaviour` and contains two valid headers (e.g. two headers where `Header1` has a higher height and later timestamp than `Header2`).

## Proposed Solution

If the client message received by `UpdateState` if of type `Misbehaviour` then no-op (return `[]exported.Height{}`). This solution is preferred at this moment because it is not API breaking. 
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
Required for https://github.com/cosmos/ibc-go/issues/6232

The logic is: if a user submits a valid client message using the misbehaviour type (two headers) which is not actually misbehaviour, then there are no updates to perform (noop)
