### ISSUE TITLE
remove upgrade specific event attribute keys

### ISSUE THREAD

**Issue by charleenfei** [cosmos/ibc-go#3666]
## Summary of Bug

Currently, we use upgrade-specific attribute keys for the events emitted from channel upgrade handlers. However, we could [potentially use the keys already specified for 04 channel events for these events as well.](https://github.com/cosmos/ibc-go/pull/3658#discussion_r1205990955)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
I asked Luca and he would be fine if we don't use `upgrade`-prefixed attributes. I will have this changed today or tomorrow.
