### ISSUE TITLE
Add message and rpc handler to recover clients using v1 governance proposals

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#3672]
_Part of #1282._ 

Overview of changes:

### Protobuf

- Add a new rpc handler to 02-client [`MsgService`](https://github.com/cosmos/ibc-go/blob/main/proto/ibc/core/client/v1/tx.proto#L11). Something like this:

```proto
rpc RecoverClient(MsgRecoverClient) returns (MsgRecoverClientResponse);
```

where `MsgRecoverClient` could look like this:

```proto
message MsgRecoverClient {
  option (gogoproto.equal)           = false;
  option (gogoproto.goproto_getters) = false;
  option (cosmos.msg.v1.signer)      = "authority";

  // authority is the address of the governance account.
  string authority = 1;
  // the client identifier for the client to be updated if the proposal passes
  string subject_client_id = 2;
  // the substitute client identifier for the client standing in for the subject
  // client
  string substitute_client_id = 3;
}
```

and `MsgRecoverClientResponse` can be empty:

```proto
message MsgRecoverClientResponse {}
```

### 02-client

- Add function `RecoverClient` to 02-client keeper with logic to recover client. The signature of the function could look like this:

```go
func (k Keeper) RecoverClient(ctx sdk.Context, subjectClientId, substituteClientId string) error
```

- Add implementation of `RecoverClient`, which could be similar to [`ClientUpdateProposal`'s implementation](https://github.com/cosmos/ibc-go/blob/main/modules/core/02-client/keeper/proposal.go#L21C1-L66).

- Implement `sdk.Msg` interface for `MsgRecoverClient`.

- If it's possible to re-use the error code for [`ErrInvalidUpdateClientProposal`](https://github.com/cosmos/ibc-go/blob/cf519bc4d4285aa0b69511ba08d69b7456744f5d/modules/core/02-client/types/errors.go#L31), then rename the error to, for example, `ErrInvalidRecoveryClient` and adjust the error description to `invalid recovery client`.

### Core

- Add implementation of `RecoverClient` rpc handler in IBC core `msg_server.go` (`modules/core/keeper/msg_server.go`). The signature of the handler could look like this:

```go
func (k Keeper) RecoverClient(
  goCtx context.Context, 
  msg *clienttypes.MsgRecoverClient
) (*clienttypes.MsgRecoverClientResponse, error)
```

and the implementation could look like this:

```go
// check message signer matches authority set
if k.authority != msg.Signer {
  return nil, errorsmod.Wrapf(
    govtypes.ErrInvalidSigner, 
    "invalid authority: expected %s, got %s", k.authority, msg.Signer
  )
}

ctx := sdk.UnwrapSDKContext(goCtx)

err := k.ClientKeeper.RecoverClient(ctx, msg.SubjectClientId, msg.SubstituteClientId)
if err != nil {
  return nil, errorsmod(err, "client recovery failed")
}

return &types. MsgRecoverClientResponse{}, nil
```

- Add extra `&MsgRecoverClient{}` as input to [`RegisterImplementations`](https://github.com/cosmos/ibc-go/blob/main/modules/core/02-client/types/codec.go#L43).

### CLI

- Implement a CLI command (`NewCmdSubmitClientRecoverProposal`) in 02-client with flag `recover-client` and parameters `subject-client-id` and `substitute-client-id` to construct a `MsgRecoverClient` and include it in a `MsgSubmitProposal`. Use [v1beta1 legacy `NewCmdSubmitUpdateClientProposal` command](https://github.com/cosmos/ibc-go/blob/4bb1b5101da975bb5e990742dd008357d64f4ed8/modules/core/02-client/client/cli/tx.go#L245) and SDK's [`NewCmdSubmitUpgradeProposal`](https://github.com/cosmos/cosmos-sdk/blob/1b0fcdc9f059419328ed2b6b2393320fb042270f/x/upgrade/client/cli/tx.go#L47) as examples.

### Documentation

- Update the [documentation for client recovery via governance proposals](https://ibc.cosmos.network/main/ibc/proposals.html).

Break up the implementation in multiple PRs. One possible suggestion:

- [x] #4493
- [x] #4498
- [x] #4500
- [x] #4530
- [x] #4584
- [x] #4521

**Comment by colin-axner** [comment]
Closed by all the linked issues!
