### ISSUE TITLE
Remove legacy governance v1beta1 proposal handlers

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#3674]
_Part of #1282._ 

Pre-requisites: 
- [x] https://github.com/cosmos/ibc-go/issues/3672
- [x] https://github.com/cosmos/ibc-go/issues/3673

Overview of changes:

- Mark [`ClientUpdateProposal`](https://github.com/cosmos/ibc-go/blob/main/proto/ibc/core/client/v1/client.proto#L43) and [`UpgradeProposal`](https://github.com/cosmos/ibc-go/blob/main/proto/ibc/core/client/v1/client.proto#L59) messages as deprecated with adding `option deprecated = true;`.
- Remove [proposal handlers in app.go](https://github.com/cosmos/ibc-go/blob/main/testing/simapp/app.go#L155-L156).
- Remove [call to `NewClientProposalHandler` in app.go](https://github.com/cosmos/ibc-go/blob/main/testing/simapp/app.go#L384).
- Remove [`ClientUpdateProposal` implementation registration](https://github.com/cosmos/ibc-go/blob/main/modules/core/02-client/types/codec.go#L40) and [`UpgradeProposal` implementation registration](https://github.com/cosmos/ibc-go/blob/main/modules/core/02-client/types/codec.go#L41).
- Remove [`NewUpgradeClientCmd`](https://github.com/cosmos/ibc-go/blob/main/modules/core/02-client/client/cli/tx.go#L178) and [`NewCmdSubmitUpdateClientProposal`](https://github.com/cosmos/ibc-go/blob/main/modules/core/02-client/client/cli/tx.go#L244).
- Remove files `modules/core/02-client/keeper/proposal.go` and `modules/core/02-client/client/proposal-handler.go`.
- Remove [e2e test `TestClientUpdateProposal_Succeeds`](https://github.com/cosmos/ibc-go/blob/0dbd3f811928b216418a45ea164d184eec86cc67/e2e/tests/core/02-client/client_test.go#L71).
- Update v8 migration docs, if needed.

**Comment by colin-axner** [comment]
We should migrate the proposals to messages first right? Maybe we can add those issues as pre reqs?

**Comment by crodriguezvega** [comment]
@womensrights verified that relayers are not using the CLI commands so we can remove them.

**Comment by colin-axner** [comment]
What's the benefit of marking protos as deprecated as opposed to removing entirely? I don't think we have an rpc for submitting the legacy proposal?

**Comment by colin-axner** [comment]
removed by #4581 and #4602, will be merged to main by #4620, migration docs will be handled by #4544
