### ISSUE TITLE
Get current channel before writing updated state in `WriteUpgradeInitChannel`

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3678]
## Summary

In `WriteUpgradeInitChannel`, get the current channel before updating state. This will prevent accidental reference of a stale channel

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by DimitrisJim** [comment]
can the application call-back cause a channel to go stale? (Granted it succeeds) I'm trying to understand where it might happen in the [current code](https://github.com/cosmos/ibc-go/blob/5023f6e4a4d268b938369d51d3c582c9bf53b758/modules/core/keeper/msg_server.go#L720-L741).

**Comment by colin-axner** [comment]
In the current code, it is safe, but previously there was a version of the TRY handler which created a bug without this [code pattern](https://github.com/cosmos/ibc-go/pull/3478#discussion_r1172682786). For safety/readability, I think it makes sense to be a bit defensive and ensure you write only a fresh channel, even if in this case the current code is fine
