### ISSUE TITLE
Add endpoint.ChanUpgradeAck function

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3685]
## Summary

Similar to [`endpoint.ChanOpenAck`](https://github.com/cosmos/ibc-go/blob/04-channel-upgrades/testing/endpoint.go#L372) and [`endpoint.ChanUpgradeInit`](https://github.com/cosmos/ibc-go/blob/04-channel-upgrades/testing/endpoint.go#L567), we should have a `endpoint.ChanUpgradeTry`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by DimitrisJim** [comment]
pending on spec changes getting merged.
