### ISSUE TITLE
adapt connection e2e params test to use gov v1 message

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#3704]
_Part of https://github.com/cosmos/ibc-go/issues/2010_

Pre-requisite:
- [ ] #3650

Adjust [`TestMaxExpectedTimePerBlockParam`](https://github.com/cosmos/ibc-go/blob/main/e2e/tests/core/03-connection/connection_test.go#L49) to use gov v1 message when the version of the chain supports it (keep using legacy params for versions that don't support gov v1).

Alternatively we could also not test legacy params anymore and test only with gov v1. Open to the opinion of others.

**Comment by DimitrisJim** [comment]
Done in #3650
