### ISSUE TITLE
rename proof params to differentiate from `proofHeight` param

### ISSUE THREAD

**Issue by charleenfei** [cosmos/ibc-go#3726]
## Summary of Bug

see [this comment.](https://github.com/cosmos/ibc-go/pull/3628#discussion_r1210488680)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chandiniv1** [comment]
Hi @charleenfei 
I would like to work on this, Is this just rename to  `counterpartyChannelProof` or anything else

**Comment by charleenfei** [comment]
the initial concept proposed, rename proof params to ie: `consensusProof` or `clientProof` instead of `proofConsensus` `clientProof`, etc, for readability and also to differentiate from `proofHeight`
