### ISSUE TITLE
update `SendPacket` API to use new `Timeout` type

### ISSUE THREAD

**Issue by charleenfei** [cosmos/ibc-go#3727]
## Summary of Bug

Currently, the [SendPacket API](https://github.com/cosmos/ibc-go/blob/861c6756eefafec6f4cbac958a650f157b9bf74c/modules/core/04-channel/keeper/packet.go#L22-L23) expects separate timeout height and timeout timestamp parameters. We should update this to use the [new `Timeout` type](https://github.com/cosmos/ibc-go/blob/861c6756eefafec6f4cbac958a650f157b9bf74c/proto/ibc/core/channel/v1/channel.proto#L166).

see #3600 as a related issue.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by vishal-kanna** [comment]
@charleenfei  I would like to work on it

**Comment by colin-axner** [comment]
I wonder if we should delay implementation on this? It's mostly a code-hygiene issue and it breaks the IBC app API, thus requiring IBC applications to update to the new version of ibc-go before a chain could update. I think it'd make more sense to be a little conservative and wait until we need to break the IBC app API regardless

**Comment by colin-axner** [comment]
Timeouts will be moved to be a single uint64, so the timeout type may be dropped entirely. Timeout checking should also be moved to light clients in #7055
