### ISSUE TITLE
Implement `endpoint.ChanUpgradeOpen`

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3744]
## Summary

requires #3743 

Should be very similar to `endpoint.ChanUpgradeTry` and `endpoint.ChanUpgradeAck`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closed by https://github.com/cosmos/ibc-go/pull/3770
