### ISSUE TITLE
Remove counterparty channel ID from OnChanUpgradeAck callback handler

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#3756]
## Summary

The counterparty channel ID should not be required in the `OnChanUpgradeAck` handler.

It can be removed.

see: https://github.com/cosmos/ibc-go/blob/04-channel-upgrades/modules/core/05-port/types/module.go#L136
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by DimitrisJim** [comment]
closed by #3785
