### ISSUE TITLE
Revisit the app callback handlers for 04-channel upgrades

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#3757]
## Summary

Since many changes have taken place wrt channel upgrades spec and implementation we should revisit the app callback handlers defined in `05-port`. 

[See `UpgradeModule` interface](https://github.com/cosmos/ibc-go/blob/04-channel-upgrades/modules/core/05-port/types/module.go#L111)

We should also include informative doc strings to the interface methods.

Some arguments may not be required, adding needs discussion label.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by DimitrisJim** [comment]
Also relevant with some additional discussion (linking) https://github.com/cosmos/ibc-go/issues/1614

**Comment by damiannolan** [comment]
closing in favour of #1614
