### ISSUE TITLE
export util functions such as `StartFlushUpgradeHandshake`

### ISSUE THREAD

**Issue by charleenfei** [cosmos/ibc-go#3765]
is there a strong reason that we don't just want to let `StartFlushUpgradeHandshake` be an exported function and not need these wrappers?

To me, adding this additional level of indirection hurts my ability to reason about where things can be used in certain ways and why. 

I don't think it's so bad to just export `k.startFlushUpgradeHandshake` .

This is a mild preference though, if the general consensus is to have this additional wrapper I'm okay with it 👍

_Originally posted by @chatton in https://github.com/cosmos/ibc-go/pull/3671#discussion_r1219407458_

**Comment by colin-axner** [comment]
see followup https://github.com/cosmos/ibc-go/pull/3671#discussion_r1221235449

**Comment by DimitrisJim** [comment]
I agree with Colin's approach. It is a hassle due to go's visibility rules to these tested but the benefit of not exposing a large API outweighs that hassle.

**Comment by chatton** [comment]
I think I'm convinced by @colin-axner's response, it's not ideal but I agree it's worth doing 👍 I think we can close this issue!

**Comment by charleenfei** [comment]
closing this issue in favour of our current design
