### ISSUE TITLE
Consider adding a helper function to clear state stored during an Upgrade

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#3781]
## Summary

Consider adding a helper function to clean up the state added during an upgrade. Possible name suggested `cleanUpgradeInfo`. See relevant comment: https://github.com/cosmos/ibc-go/pull/3759/files#r1221383080

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by DimitrisJim** [comment]
note: currently could possibly be used in `restoreChannel` and `WriteUpgradeOpenChannel`. Unsure how warranted an additional func might be atm.

**Comment by crodriguezvega** [comment]
> note: currently could possibly be used in restoreChannel and WriteUpgradeOpenChannel. Unsure how warranted an additional func might be atm.

I agree that it doesn't look like we need it at the moment: a function that could be used in two places an wrap two lines of code... Should we then close the issue for now and reopen if it becomes clearer that we need this?

**Comment by DimitrisJim** [comment]
> Should we then close the issue for now and reopen if it becomes clearer that we need this?

I'd be fine with that. I could also see us go through these issues in an internal call and just closing them after a small discussion.

**Comment by crodriguezvega** [comment]
Discussed in engineering call and decided to create the function.

**Comment by crodriguezvega** [comment]
Closed by #4147.
