### ISSUE TITLE
add `GetVersions()` as an interface method for `exported.ConnecionI`

### ISSUE THREAD

**Issue by charleenfei** [cosmos/ibc-go#3786]
currently, we need to get an instance of `ConnectionEnd` in order to use `GetVersions()`

should we add `GetVersions()` as an interface method to `exported.ConnectionI`? cc. @colin-axner

_Originally posted by @damiannolan in https://github.com/cosmos/ibc-go/pull/3774#discussion_r1221443268_

**Comment by damiannolan** [comment]
Awesome, thanks for opening this issue @charleenfei. We can update the code from where I made the comment on the `04-channel-upgrades` branch once this is changed :) 

We can make this to main and then resync the feat branch whenever 👍

**Comment by crodriguezvega** [comment]
This is [the issue](https://github.com/cosmos/ibc-go/issues/1689) that we had in the past to remove `GetVersions` from the interface.

**Comment by colin-axner** [comment]
I think we can just modify `channelKeeper.GetConnection()` to return the concrete connection type? I see connection types is imported by channel types, so I'm not sure what import cycle is being avoided using exported. 

The usage of interface to avoid import cycles is quite dated. We didn't think it through too much at the time for the sake of delivering IBC faster, so I think it's worth trying to remove some of these unnecessary interfaces

**Comment by crodriguezvega** [comment]
If that's ok, I will close this for now, since we [decided](https://github.com/cosmos/ibc-go/issues/3840#issuecomment-1637719415) (and [already implemented](https://github.com/cosmos/ibc-go/pull/4146)) to use the connection keeper to get the connection (which returns the concrete type), so this should not be needed anymore.
