### ISSUE TITLE
Documentation issues on IBC packet code

### ISSUE THREAD

**Issue by AdityaSripal** [cosmos/ibc-go#38]
- [ ] Remove antehandler comments on packet functions since everything happens in handler now.
- [ ] Clarify documentation around ordered/unordered differences in receipt handling (note: relayer may be wrong regarding this)
- [ ] Add comment on the timeout height check in TimeoutPacket, it is very confusing

**Comment by crodriguezvega** [comment]
I feel like comments in this area are now pretty good, so I will close this issue.
