### ISSUE TITLE
update method signatures of `verify` functions in 03-connection for readability

### ISSUE THREAD

**Issue by charleenfei** [cosmos/ibc-go#3801]
## Summary of Bug

some of the methods (`VerifyNextSequenceRecv`, `VerifyPacketReceiptAbsence`, `VerifyPacketAcknowledgement`, `VerifyPacketCommitment`, `VerifyChannelState`) in `03-connection` `verify.go` have the `portID` and `channelID` params ordered at the end. 

we should try to be consistent by having `portID` and `channelID` after the `ctx` param, for readability
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by DimitrisJim** [comment]
aren't these currently part of our public API? I agree with the issue (and I've found other places where, e.g unused vars exist) but have reservations because in theory someone might be depending on these.

**Comment by charleenfei** [comment]
You make a good point. I guess channel upgradeability would anyway have other API breaking changes though, so it could all go into the release...but maybe you're right that it's worth looking into if other projects might be using this proof verification logic.

**Comment by colin-axner** [comment]
These functions are used for the core IBC handlers. There is a world in which they are not public, so I think it'd be okay to make these changes along with a major version release, but I agree, it isn't high priority. If a release has a lot of breaking changes, it might make sense not to bundle it into that release (the more changes, the more headaches our users will have)

**Comment by chandiniv1** [comment]
@charleenfei can I work on this issue?

**Comment by crodriguezvega** [comment]
See [here](https://github.com/cosmos/ibc-go/pull/6896#issuecomment-2242345530) for reasoning to close the issue.
