### ISSUE TITLE
Fix dead markdown links

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#381]
Since the addition of #377 a number of dead links have been identified via the CI workflow.
These links should be updated to point to the correct locations.

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Thanks for fixing the link checker, @damiannolan!
I can take this one, since I already had a branch open where I was fixing some broken links.

**Comment by crodriguezvega** [comment]
It has been solved in #415.
