### ISSUE TITLE
create helper function to check if at least one packet commitment exists in a given channel

### ISSUE THREAD

**Issue by charleenfei** [cosmos/ibc-go#3816]
we need to check if at least one packet commitment exists before writing state for `ChanUpgradeAck`. the current method we have available, `GetAllPacketCommitments`, is inefficient as it will do the full iteration and give you all packet commitments when really you just need to check if there exists at least one.

_Originally posted by @AdityaSripal in https://github.com/cosmos/ibc-go/pull/3787#discussion_r1226394345_

**Comment by DimitrisJim** [comment]
I'll take a look at this at some point (though I'll punt it for a bit later since it isn't pressing).

**Comment by colin-axner** [comment]
I would suggest an API like:
```go
func (k Keeper) hasInflightPackets(ctx sdk.Context, portID, channelID string) bool 
```
