### ISSUE TITLE
Simplify IBC app callback lookup

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3817]
## Summary

Simplify the application callback lookup

## Problem Definition

Currently the `msg_server.go` performs a repetitive calls to `LookupModuleByPort` and `LookupModuleByChannel`. These function are only used to get the `module` which is then passed to `k.Router.GetRoute(module)` to obtain the application callbacks. 

Currently some of the calls to these lookup function use the returned capability, but this will likely be removed after this [spec](https://github.com/cosmos/ibc/issues/886) issue is addressed. 

## Proposal

We can likely reduce this 2 step lookup into one call:
```go
cbs, err := k.PortKeeper.LookupCallbacksByChannel(ctx, msg.PortId, msg.ChannelId)
If err != nil {
    return err
}
```

Another alternative is to have the port keeper implement each callback function, such that you call through the port keeper:
```go
err := k.PortKeeper.OnChanInit()
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by DimitrisJim** [comment]
I was wondering about this yesterday while looking at the ChannelUpgradeTry PR. 

I can see the benefit in `LookupCallbackByChannel` in that it would keep the current requirement to get the capability localized and facilitate an easier transition. (Apart from the obvious code duplication savings).

What would be the proposed operation of `OnChanInit`? Would it offer any benefits over the other approach? Wouldn't it require adding an additional function on `PortKeeper` for all handlers?

**Comment by colin-axner** [comment]
> What would be the proposed operation of OnChanInit? Would it offer any benefits over the other approach? Wouldn't it require adding an additional function on PortKeeper for all handlers? These functions are available to all applications so having these on PortKeeper might make it additionally confusing.

I agree, because of the size of the IBC app interface, it could become confusing. The main benefit is that the concept of app callback lookup becomes internal to the port keeper rather than being invoked by the msgs associated with the channel keeper. The msg server handler would become a lot simpler as they would simply perform 04-channel logic and then directly call the `On` callbacks via the port keeper without callback lookup

**Comment by colin-axner** [comment]
Closed by latest upstreaming of capability removal!
