### ISSUE TITLE
Consider wrapping `ChanUpgradeTry` call in cache ctx

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3823]
## Summary

Consider using a cache ctx when making a call to `ChanUpgradeTry`

see [comment](https://github.com/cosmos/ibc-go/pull/3791#discussion_r1226482366)

## Problem Definition

If the returned error is an `UpgradeError` all state changes and events are committed to state (even though the function failed). We should consider wrapping the function in a `cacheCtx` call to fully revert state

One awkward thing with that solution is that the upgrade error might return an upgrade sequence != current upgrade sequence, but this is also true if it uses the counterparty upgrade sequence which is greater than its own. 

One current issue is that `UpgradeInit` event may be emitted even though the upgrade is aborted in this transaction

## Proposal

Use a cache context when calling `k.ChannelKeeper.ChanUpgradeTry`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
I don't think this needs to be done, see the comment [here](https://github.com/cosmos/ibc-go/pull/4108#issuecomment-1640154695).

**Comment by crodriguezvega** [comment]
With the [latest spec updates](https://github.com/cosmos/ibc/pull/999) this should not be needed anymore.
