### ISSUE TITLE
Response formatting for channel upgrades msg server handlers

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#3825]
## Summary

Discuss alternatives for formatting response information in channel upgrades msg server handlers.

[See thread](https://github.com/cosmos/ibc-go/pull/3791#discussion_r1225792629) and [thread](https://github.com/cosmos/ibc-go/pull/3791#discussion_r1226424744).

We currently chose to opt for returning `(Channel, Upgrade)` from `WriteUpgradeTryChannel` in order to have the response values up to date. However, ideally we would keep `WriteX` funcs void, with zero return args. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
Discussing with @damiannolan , we can keep the `WriteUpgradeTryChannel` fn the same, but update `WriteUpgradeInitChannel` to use the same method signature (return Channel, Upgrade) to stay consistent.

**Comment by crodriguezvega** [comment]
The [signature of `WriteUpgradeInitChannel` changed already](https://github.com/cosmos/ibc-go/pull/5264/files#diff-0fca3dc84b5a25a4a314bceed2fdee673da45a5381aed16d164bb84cd891642eR49) in #5264, therefore the issue can be closed.
