### ISSUE TITLE
Add flush status check in `SendPacket` 

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#3875]
Pre-requisite:

- [x] https://github.com/cosmos/ibc/pull/982

We already [check if the channel state is `OPEN`](https://github.com/cosmos/ibc-go/blob/main/modules/core/04-channel/keeper/packet.go#L36-L41), so we need to add a check to allow sending packets only if flush status is `NOTINFLUSH` as well.

**Comment by chatton** [comment]
PR is merged, but we can keep this issue open in case changes happen in the spec and create a follow up PR.

**Comment by crodriguezvega** [comment]
Spec changes are [merged now](https://github.com/cosmos/ibc/pull/982), so I will close the issue. 

Closed by #3912
