### ISSUE TITLE
"/ibc/core/channel/v1/connections/connection-501/channels" does not return all channels 

### ISSUE THREAD

**Issue by liangping** [cosmos/ibc-go#3898]
## expected result:

return all channels of `connection-501`

## issues:

sometime return channels(but not all),  sometime return []

## version:
On all version

https://cosmos-rest.publicnode.com/ibc/core/channel/v1/connections/connection-501/channels

**Comment by damiannolan** [comment]
Hey, is this the same behaviour using an rpc endpoint and CLI? 

e.g. `gaiad q ibc channel connections connection-501`

**Comment by liangping** [comment]
I believe it's.

you can visis here for more information, this is where we use it.
https://ping.pub/cosmos/ibc/connection/connection-0

**Comment by liangping** [comment]
Seems Agoric returns correct result

**Comment by colin-axner** [comment]
Is this issue still relevant?
