### ISSUE TITLE
AbortUpgrade returns an error despite being an non-failure action

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3903]
## Summary

`AbortUpgrade` should not return an error unless there is an internal error in the code written (an error returned is not expected behaviour in the system)

## Problem Definition

When an upgrade handshake fails, we call `AbortUpgrade` which returns an error. In instances where we have successfully timed out an upgrade, that abort must not fail. I believe in all instances, `AbortUpgrade` should be treated as a non-failure event, that is it must occur. 

The importance of this scenario is the fact that if an `AbortUpgrade` fails, a channel will be unable to revert to normal processing, thus manual intervention will be required.

## Proposal

Panic or return a base error which indicates there is a internal code failure

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closed by #4011.
