### ISSUE TITLE
Remove `GetSignBytes` with Eden upgrade

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3911]
## Summary

`GetSignBytes` is being removed as an interface as apart of the Eden SDK upgrade. It can be removed after we have updated to SDK v0.50.x

## Proposal

Remove `GetSignBytes` function from 29-fee msgs and transfer msgs. Please do this pr after the upgrade to SDK v0.50.x has occurred to reduce changes to review in the pr which bumps the SDK version

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by tac0turtle** [comment]
in 0.50 this is automatically inferred based off the proto name, but for backwards compatability we introduced a few proto annotations to recreate the same bytes as before. 

Amino name annotation: https://github.com/cosmos/cosmos-sdk/blob/b990cb783a25fbcb9c95da570a7918ec29172514/proto/cosmos/auth/v1beta1/auth.proto#L15
Amino message encoding: https://github.com/cosmos/cosmos-sdk/blob/b990cb783a25fbcb9c95da570a7918ec29172514/proto/cosmos/auth/v1beta1/auth.proto#L35

We are working on documentation for this as well

**Comment by damiannolan** [comment]
Looks like there is some `Route()` and `Type()` methods on these msgs left hanging around. Should we remove them as well here? What do you think?

**Comment by tac0turtle** [comment]
yea they are not needed anymore

**Comment by damiannolan** [comment]
Indeed! Figured as much, thanks @tac0turtle

**Comment by tac0turtle** [comment]
its not needed anymore, we still need to clean up docs for 0.50
