### ISSUE TITLE
Remove `sdk.MustSortJSON` usage

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3916]
## Summary

This is an issue to track the usage of `sdk.MustSortJSON` as it has been deprecated in the SDK. It has been kept in the SDK at our request, so this issue will indicate when we no longer rely on the function. 

- [x] #3911 
- [x] #3915 
- [x] #3917 
- [x] #3918 
- [x] #3919 
- [x] #3920 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
All sub-issues have been completed! 🥳
