### ISSUE TITLE
Remove `sdk.MustSortJSON` from channel types `Acknowledgement`

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3920]
## Summary

Same reasoning as #3915, the sorting order should not change cross compatibility

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by expertdicer** [comment]
I don't think we can use standard encoding/json lib because the proto of Acknowledgement contains enum
```
message Acknowledgement {
  // response contains either a result or an error and must be non-empty
  oneof response {
    bytes  result = 21;
    string error  = 22;
  }
}
```
