### ISSUE TITLE
Add flushing check to WriteUpgradeAckChannel

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3929]
## Summary

In `WriteUpgradeAckChannel` add:
```go
if  !k.hasInflightPackets(ctx, portID, channelID) {
    channel.FlushStatus = types.FLUSHCOMPLETE
}
```

It would be nice to have some tests as well (maybe some unit tests for the write func)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
looks like @charleenfei  got this one over the line thanks!
