### ISSUE TITLE
bug: returns inside defer statements

### ISSUE THREAD

**Issue by faddat** [cosmos/ibc-go#3941]
While working through #3888, I think that I have found a bug.  The returns inside of the defer statement won't return.

* #3888 

Example:
```go
// IteratePacketSequence provides an iterator over all send, receive or ack sequences.
// For each sequence, cb will be called. If the cb returns true, the iterator
// will close and stop.
func (Keeper) IteratePacketSequence(ctx sdk.Context, iterator db.Iterator, cb func(portID, channelID string, sequence uint64) bool) {
	defer sdk.LogDeferred(ctx.Logger(), func() error { return iterator.Close() })
	for ; iterator.Valid(); iterator.Next() {
		portID, channelID, err := host.ParseChannelPath(string(iterator.Key()))
		if err != nil {
			// return if the key is not a channel key
			return
		}

		sequence := sdk.BigEndianToUint64(iterator.Value())

		if cb(portID, channelID, sequence) {
			break
		}
	}
}
```

According to GPT:

```
 A return statement inside a defer function will not have any effect on the return value of the enclosing function. This is because defer functions are executed after the enclosing function has already returned.
```

Thing is I am not too sure what the best way to solve this is?

If we wanted to preserve the functionality as is, then we could just log in error here. If we want a return to happen, we might need to get rid of the diverse statement?

**Comment by damiannolan** [comment]
`sdk.LogDeferred` is using that func call and logging if it errors on `iteratlor.Close()`, which seems valid to me.

```go
func LogDeferred(logger log.Logger, f func() error) {
	if err := f(); err != nil {
		logger.Error(err.Error())
	}
}
```

I believe the machine (GPT) is saying something more leaning towards this example, where `return` in `defer` has no affect.


```go
func DeferDontDoThat(f func()) string {
    defer func() { 
        return "deferred"
    }()

    if f() {
        return "a"
    }

    return "b"
}
```

If you adapt the code to this and step through with a debugger you'll land on `iterator.Close()`, so it looks like the cb passed in is being executed.

```go
defer sdk.LogDeferred(ctx.Logger(), func() error { 
    return iterator.Close() 
})
```

**Comment by faddat** [comment]
In this case, it is the machine (revive) -- I did turn to gpt for help though.  I guess that it makes sense to disable that linter, however.  

Also, thank you very much for running me through this!
