### ISSUE TITLE
Be consistent when formatting enums

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#3946]
## Summary

There's mixed usage when formatting enums in our error wrapping, older code seems to use `.String()` while newer code does not. The result is the same (since we do not implement `Format` on them).

Would be nice to be consistent with this and probably use the version w/o the explicit calls to `.String()`.
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by DimitrisJim** [comment]
note: should probably be done _after_ 04-channel-upgrades is merged.

**Comment by faddat** [comment]
Hey Jim, I've noticed that there are a lot of issues that I could handle here, and I'm really happy to do so.  Just a quick FYI for you and the ibc team, I have very very pending baby coming, so I may be in and out but happy to handle some of these on a best effort basis :).
