### ISSUE TITLE
Add SetChannelFlushStatus in Endpoint

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#3947]
## Summary

Similar to SetChannelState helper, SetChannelFlushStatus would be a nice convenience function to have. It seems that tweaking the FlushStatus will be a relatively common thing to do as more tests are written.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
Can this be closed in favour of #3984 ?

**Comment by DimitrisJim** [comment]
ish, yeah, forgot about this one
