### ISSUE TITLE
SDK 50 upgrade target branch

### ISSUE THREAD

**Issue by faddat** [cosmos/ibc-go#3949]
Hey, so a few thoughts on:

origin/feat/upgrade-sdk-v0.50

* I've made a PR, https://github.com/cosmos/ibc-go/pull/3948. that targets the v50 upgrade feature branch
* Is it possible to get https://github.com/cosmos/ibc-go/pull/3874 merged to main and there?

Reasoning for the requests:

1) the branch we are targeting for the 50 upgrade would now be very hard to merge to main so I'd like to target at least v7.2.0
2)  https://github.com/cosmos/ibc-go/pull/3874 will eliminate many changes from the sdk 50 upgrade.

**Comment by crodriguezvega** [comment]
We'll try to review #3874 next week, @faddat!

**Comment by crodriguezvega** [comment]
We are going to start reviewing the PRs this iteration, and since we are going to continue with the feature branch, then I will close the issue for now.
