### ISSUE TITLE
Add SetConnectionState in Endpoint

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#3955]
## Summary

Similar to #3947, this is a common operation in many tests, can be:

```go
// SetConnectionState sets a connection state
func (endpoint *Endpoint) SetConnectionState(state connectiontypes.State) error {
	connection := endpoint.GetConnection()

	connection.State = state
	endpoint.SetConnection(connection)

	endpoint.Chain.Coordinator.CommitBlock(endpoint.Chain)

	return endpoint.Counterparty.UpdateClient()
}
```

there's quite a few instances of this in both main and in 04-channel-upgrade.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
Added my thoughts [here](https://github.com/cosmos/ibc-go/pull/3953#issuecomment-1607005896)!

**Comment by chatton** [comment]
See [this suggestion](https://github.com/cosmos/ibc-go/pull/3953#issuecomment-1607005896) a similar concept could be applied to the connection.

**Comment by colin-axner** [comment]
> See [this suggestion](https://github.com/cosmos/ibc-go/pull/3953#issuecomment-1607005896) a similar concept could be applied to the connection.

Yay! I like this suggestion, so `SetChannel` becomes internal and we replace:
```go
chan := endpointA.GetChannel()
chan.State = types.OPEN
endpointA.SetChannel(chan)
```
with
```go
endpointA.UpdateChannel(func(channel *channeltypes.Channel) {
    channel.State = types.OPEN
})
```

and 

```go
func (endpoint Endpoint) UpdateChannel(mutate func(channel *channeltypes.Channel)) {
    channel := endpoint.GetChannel()
    
    mutate(channel)
    
    endpoint.setChannel(channel)
}
```

**Comment by colin-axner** [comment]
Love to see the testing pkg get some design love :)

**Comment by DimitrisJim** [comment]
ohhh that's a nice suggestion. I'll get on that.

**Comment by DimitrisJim** [comment]
note: going to close this issue at some point and open another with Cians suggestion for both Channel/Connection/anything else.

Would be best to implement and refactor relevant usages after 04-channel-ugprades has been merged.

**Comment by DimitrisJim** [comment]
Closing in preference to #3985
