### ISSUE TITLE
Question: Is the comment at ChanOpenConfirm in handshake.go correct ? 

### ISSUE THREAD

**Issue by vishal-kanna** [cosmos/ibc-go#3962]
https://github.com/cosmos/ibc-go/blob/8b82ec4c0c2907905865c42e400860803d332237/modules/core/04-channel/keeper/handshake.go#L293-L302

**Comment by crodriguezvega** [comment]
No, that's definitely not correct! 😓😄. Would you like to open a PR to fix it?
