### ISSUE TITLE
Move simapp binary into own go.mod or e2e

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3968]
## Summary

The ibc-go simapp should be its own go.mod

## Problem Definition

With the upgrade to Eden (sdk v0.50), a lot of sdk modules have become their own go.mod. This is creating a lot of unnecessary dependencies for ibc-go modules, ibc core and the ibc-go apps do not need to depend on several sdk modules included in simapp.

I believe there will be side benefits as well, such as having ibc-go always be a dependency of any binary, see https://github.com/cosmos/ibc-go/issues/3039#issuecomment-1431592487

## Proposal

Make simapp its own go.mod. I don't have a suggestion yet if we should pin the version or update it as necessary. The main concern would probably be compatibility with e2e's

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by damiannolan** [comment]
Preliminary add to v8 milestone, lets see if we can get this in before releasing v8!

**Comment by colin-axner** [comment]
> What do you think about moving simapp to the root of the repo when making it it’s own go module?

This sounds great to me

> Would you propose we shadow the ibc-go major version suffix, or not? 

Probably shadow or never do a major version release of simapp. ie we could do `v0.8.0` for v8

**Comment by chatton** [comment]
Did very brief investigation in #4117, I think we can tackle this as soon as the sdk 0.50 upgrade is done.

**Comment by crodriguezvega** [comment]
We decided in the engineering call to move it to its own go.mod.
