### ISSUE TITLE
Rename `TestChain` field `LastHeader` to `LatestCommittedHeader`

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3971]
## Summary

Rename `TestChain` field `LastHeader` to `LatestCommittedHeader`

The testing package keeps track of what is currently called the last header and a current header. In reality, these are the latest committed header and the current uncommitted header. I propose we make these fields more explicitly named as reading the testing code can get confusing if you don't have the distinction between committed and uncommitted, otherwise you may think that if the current header is 6, then it's block state is considered committed

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chandiniv1** [comment]
@colin-axner can I work on this issue?

**Comment by DimitrisJim** [comment]
go for it @chandiniv1!
