### ISSUE TITLE
Rename test chain `CurrentHeader` to `CurrentUncommittedHeader`

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3973]
## Summary

Rename test chain `CurrentHeader` to `CurrentUncommittedHeader`

similar logic to #3971 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
Could also be `proposedHeader`

**Comment by colin-axner** [comment]
We decided to go with proposedHeader

**Comment by chandiniv1** [comment]
@colin-axner can I work on this issue?

**Comment by DimitrisJim** [comment]
you most definitely can! @chandiniv1
