### ISSUE TITLE
Use []abci.Event instead of sdk.Events in argument to testing pkg event parsing functions

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3979]
## Summary

Change functions in [`testing/event.go`](https://github.com/cosmos/ibc-go/blob/main/testing/events.go) to use `[]abci.Event` instead of `sdk.Events`

## Problem Definition

In v0.47 SDK, `SendMsgs()` will end up calling [`SimDeliver`](https://github.com/cosmos/cosmos-sdk/blob/release/v0.47.x/baseapp/test_helpers.go#L29) which has access to `sdk.Result` which has `sdk.Events` because of this [conversion](https://github.com/cosmos/cosmos-sdk/blob/main/types/result.go#L27) 

In v0.50, begin block, deliver tx, and end block are combined into `FinalizeBlock` which returns a [`ResponseFinalizeBlock`](https://github.com/cometbft/cometbft/blob/v0.38.0-rc2/proto/tendermint/abci/types.proto#L351) which contains `[]abci.ExecTxResult`. These tx results will contain `[]abci.Event` instead of `sdk.Events`

Instead of converting `[]abci.Event` into `sdk.Events`, we should pass around `[]abci.Event` (SendMsgs will also be updated to return a `abci.ExecTxResult` instead of `sdk.Result` (but this will occur with the SDK bump)

## Proposal

Change functions in [`testing/event.go`](https://github.com/cosmos/ibc-go/blob/main/testing/events.go) to use `[]abci.Event` instead of `sdk.Events`

Thanks @alpe for the reference fix

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by DimitrisJim** [comment]
Just for clarity, this is not in any way affected if we moved to typed events, correct? Typed or not typed, we'll still be getting an array of `abci.Event` from `SendMsgs`.

**Comment by colin-axner** [comment]
I think that's correct. By typed events you mean creating a type per event type. For example:

```go
type CreateClientEvent struct {}
```
?

In this situation, indeed `FinalizeBlock` will still return us a `abci.Event` as the typed event would only be typed until we emit it. There was discussion a couple years ago to add typed events to the SDK, but it was partially implemented and I'm not sure if it is used today.

**Comment by DimitrisJim** [comment]
ah, typed events in the way the SDK defined them was what I was referring to. Missing the fact that they aren't really used, there's an old issue you opened on this which might need to be re-examined https://github.com/cosmos/ibc-go/issues/54 (and possibly closed)
