### ISSUE TITLE
Add UpdateChannel to Endpoint

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#3984]
## Summary

Would be nice to add a helper function on Endpoint that takes care of setting channel fields as needed. We currently have `SetChannelState`, would be nice if we could also set the flush status, order, etc without requiring a different function each time. Taking inspiration from Cians [suggestion](https://github.com/cosmos/ibc-go/pull/3953#issuecomment-1607005896), we could have:

```go
func (endpoint *Endpoint) UpdateChannel(updater func(channel *channeltypes.Channel)) error {
	channel := endpoint.GetChannel()
	updater(&channel)
	endpoint.SetChannel(channel)

	endpoint.Chain.Coordinator.CommitBlock(endpoint.Chain)

	return endpoint.Counterparty.UpdateClient()
}
```

This could resolve most instances of the pattern: get channel, modify, set channel. Adding this function ideally removes `SetChannelState` completely and allows `SetChannel/GetChannel` to be private or, _possibly_, inlined into `UpdateChannel`.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by DimitrisJim** [comment]
Would be best to implement and refactor relevant usages after 04-channel-ugprades has been merged.

**Comment by colin-axner** [comment]
Going to note we should not remove any functions which can be handled with this improvement (`SetChannelState` for example). We can update our usage internally and add notes in the migration doc but should mark the function as deprecated. There are too many breaking changes in v8 (big release for us + sdk bump + cometbft bump) to justify any code-hygenie breaking changes. We can remove those functions in v9 if we so wish

**Comment by DimitrisJim** [comment]
ah right, had completely forgotten testing package is actually part of API, that is wild.
