### ISSUE TITLE
Add extra documentation to `wasmCall` and `wasmQuery` functions

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#3991]
Explaining what type of errors the [function](https://github.com/strangelove-ventures/ibc-go/blob/bf9ec205f108d10d21ade2b62e35da4d6b66300b/modules/light-clients/08-wasm/types/client_state.go#L247) may return.

**Comment by DimitrisJim** [comment]
may or may not be superseded by https://github.com/cosmos/ibc-go/issues/4179, discussions in slack with the folks developing the contacts seem to indicate this additional error was something used in early development and can be dropped.

**Comment by crodriguezvega** [comment]
Closed by #4752
