### ISSUE TITLE
Add coordinator `Setup` functions to the Path type

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3999]
## Summary

The coordinator has the following functions:
```go
type Coordinator interface {
    IncrementTime() 
    IncrementTimeBy(increment time.Duration)
    UpdateTime()
    UpdateTimeForChain(chain *TestChain)
    
    Setup(path *Path) 
    SetupClients(path *Path)
    SetupConnections(path *Path)

    CreateConnections(path *Path)
    CreateMockChannels(path *Path)
    CreateTransferChannels(path *Path)
    CreateChannels(path *Path)
    
    GetChain(chainID string) *TestChain
    
    CommitBlock(chains ...*TestChain)
    CommitNBlocks(chain *TestChain, n uint64)
}
```

The following functions should be moved to be under the path type:
```go
type Path interface {
    Setup() 
    SetupClients()
    SetupConnections()
    
    CreateConnections()
    CreateChannels()
}
```

I think we could consider a way to reduce this API further (definitely keeping `Setup()`, but maybe reducing the redundancy between `SetupConnections` and `CreateConnections`)

## Problem Definition

The coordinator is an unnecessary type in the setup of the path. It is more natural to simply reference the path type directly. This clears the way to reduce the usage of coordinator which in the long run may be an unnecessary layer of the testing pkg. 

## Proposal

Change:
```go
    path := ibctesting.NewPath(suite.chainA, suite.chainB)
    suite.coordinator.Setup(path)
```

to
```go
    path := ibctesting.NewPath(suite.chainA, suite.chainB)
    path.Setup()
```

**NOTE**: I recommend we leave the coordinator functions (deprecation) and add the functions to the path and replace our internal usage. After release of v8, then I think we can remove the unnecessary coordinator functions. Because v8 is a massive release that is intermixed with a SDK and cometbft update, I think we should limit unnecessary breaking changes

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
Lets add the proposed functions to path and deprecate the legacy functions on the coordinator. I will open a separate issue to remove the deprecated functions. That way we can make this change and choose when to have users update at a reasonable time period

**Comment by hoangdv2429** [comment]
Can I work on this sir ?
