### ISSUE TITLE
Link Checker is reporting false positives

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#402]
## Summary

Many of the links reported as an "error" in the link checker have a response of 429 which comes from rate limiting. 

We should address this by adding a [custom configuration](https://github.com/gaurav-nelson/github-action-markdown-link-check#too-many-requests) file to retry on 429s

We could also switch to scheduled checks like [tendermint](https://github.com/tendermint/tendermint/blob/master/.github/workflows/linkchecker.yml)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
I also noticed this while fixing the broken links and @damiannolan pointed me to the configuration file. I have added it in the [branch](https://github.com/cosmos/ibc-go/tree/carlos/fix-broken-links), but the 429 still happen, so I need to work on it a bit more

**Comment by crodriguezvega** [comment]
It has been solved in #415.
