### ISSUE TITLE
Add `WasmTendermintConfig` struct implementing `ClientConfig` interface

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#4048]
_Thank you @damiannolan for this suggestion._

In order to be able to write tests with the Tendermint wasm light client, a change in the testing package was made to specify where the light client is a regular Tendermint light client or a Tendermint wasm light client. A [bool parameter was added to `NewTendermintConfig`](https://github.com/strangelove-ventures/ibc-go/blob/d46298f6a7e51651bb16074086d0811a0eb2dbaf/testing/config.go#L25) to indicate this.

As proposed by @damiannolan, instead of using a bool to add behaviour to an existing type, add a new type (as that is what the `ClientConfig` interface is intended for):

- Remove [`UseWasmClient` bool from `TestChain`](https://github.com/strangelove-ventures/ibc-go/blob/d46298f6a7e51651bb16074086d0811a0eb2dbaf/testing/chain.go#L83), and [setter `SetWasm(bool)`](https://github.com/strangelove-ventures/ibc-go/blob/d46298f6a7e51651bb16074086d0811a0eb2dbaf/testing/chain.go#L197).
- The [`CodeID` field being added to the `Coordinator` type](https://github.com/strangelove-ventures/ibc-go/blob/d46298f6a7e51651bb16074086d0811a0eb2dbaf/testing/coordinator.go#L29) can be moved to the `WasmTendermintConfig` type as a new field. Add a new `ClientConfig` implementation to satisfy the interface:

```golang
type WasmTendermintConfig struct {
	TendermintConfig
	CodeID []byte // or string??
}

func NewWasmTendermintConfig(codeID []byte) *WasmTendermintConfig {
	return &WasmTendermintConfig{
		CodeID:                 codeID,
		TendermintConfig: TendermintConfig{
			TrustLevel:      DefaultTrustLevel,
			TrustingPeriod:  TrustingPeriod,
			UnbondingPeriod: UnbondingPeriod,
			MaxClockDrift:   MaxClockDrift,
		},
	}
}

func (wasmcfg *WasmTendermintConfig) GetClientType() string {
	// return exported.Wasm
	return "08-wasm"
}
```

- Add a `WithClientConfig` method to the testing Endpoint:
 
```golang
// WithClientConfig sets the client config on the associated Endpoint and returns it.
func (endpoint *Endpoint) WithClientConfig(clientCfg ClientConfig) *Endpoint {
	endpoint.ClientConfig = clientCfg
	return endpoint
}
```

**Comment by colin-axner** [comment]
Closing as this is not necessary. I think we will likely take an approach more in line with #4807 and #4808 as the testing pkg will need to avoid importing light client types
