### ISSUE TITLE
Use consistent naming throughout handlers

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#4053]
## Summary

See discussion [aqui](https://github.com/cosmos/ibc-go/pull/4052#discussion_r1258152437). Would be ideal to land on one way to name arguments for both the upgrade handlers and the existing ones.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
We decided to use `proofHeight` and then `xyzProof` in functions everywhere (also in verify functions in `verify.go`) except in the proto files.
