### ISSUE TITLE
Extend Verify interface functions to add read-only access to full client store

### ISSUE THREAD

**Issue by AdityaSripal** [cosmos/ibc-go#4060]
In order to support conditional clients say `clientX`, we must be able to read the state of other clients that we depend on say `clientY`.

We can support this behaviour in ibc-go by allowing clientX to have an internal reference to `clientY`'s identifier

```
clientX {
     dependencies: [clientY],
     ...
}
```

We still will not want to grant the ability for clientX to write in clientY store, but we can give read access to the whole client store safely. Then clientX, may do the prefixing internally to access clientY's substore.

This will require the following minimal changes to the clientState API.

```go
VerifyMembership(
                 ctx sdk.Context,
		clientPrefixedStore sdk.KVStore,
		cdc codec.BinaryCodec,
		height Height,
		delayTimePeriod uint64,
		delayBlockPeriod uint64,
		proof []byte,
		path Path,
		value []byte,
                 fullReadonlyClientStore sdk.KVStore,
	) error

VerifyNonMembership(
                 ctx sdk.Context,
		clientPrefixedStore sdk.KVStore,
		cdc codec.BinaryCodec,
		height Height,
		delayTimePeriod uint64,
		delayBlockPeriod uint64,
		proof []byte,
		path Path,
		value []byte,
                 fullReadonlyClientStore sdk.KVStore,
	) error
```

Unfortunately this makes the API a bit ugly so open to other proposals

**Comment by AdityaSripal** [comment]
cc: @notbdu @jackzampolin to add context on why this is needed (usecases)
cc: @colin-axner @damiannolan for potentially cleaner solutions

**Comment by damiannolan** [comment]
Is this issue still relevant @AdityaSripal?

Given the approach of using wasm clients with the callback to another client using the querier or msg router then this wouldn't be needed, right?

**Comment by AdityaSripal** [comment]
No it shouldn't be necessary anymore. Thanks @damiannolan
