### ISSUE TITLE
Generate distinct Channel/Connection identifiers when running tests

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#4062]
## Summary

Subtle bugs can slip through when we use the same channel/connection (client?) identifiers since many of the verification functions expect those to verify the given proofs. These will work in our testing environment but would fail in the most common real-life case where identifiers are unique.

Case in point: https://github.com/cosmos/ibc-go/pull/4052. A similar bug was also found in UpgradeCancel after forcing distinct identifiers for channels.

One possible hacky solution is forcing a channel/connection init in the coordinators functions before actually setting up the connection/channel (hack inspiration https://github.com/cosmos/ibc-go/pull/4052#issuecomment-1631065794). This was we ensure distinct connection/channel identifiers for our internal tests.
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by DimitrisJim** [comment]
we currently make assumptions about channel/connection ids in the tests so maybe not do this for all tests atm.

**Comment by crodriguezvega** [comment]
Maybe this is too hacky, but sounds simple to me: before the connection and channel handshakes complete, on one of the chains we write in the `nextConnectionSequence` and `nextChannelSequence` keys the value 1, so that when the connection and channel identifiers are generated in the handshake they use that number instead of 0.

**Comment by chatton** [comment]
Since the channelIDs are generated dynamically in core ibc and we parse them from events in our test, it sounds like @crodriguezvega 's solution seems reasonable to me. A little hacky but I think it is worth it to eliminate this class of error.
