### ISSUE TITLE
Consider renaming `startFlushUpgradeHandshake`

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#4096]
The name of the function suggests that the channel switches to `FLUSHING` status (assuming there are in-flight packets), which is what happens in the pseudocode of the spec, but in the implementation the flush status changes in the functions `WriteUpgrade{Try, Ack}Channel`.

**Comment by DimitrisJim** [comment]
I remember we had a small discussion on this with Cian in slack, naming also implies theres some sort of handshake going on when there isn't. We should def discuss it.
