### ISSUE TITLE
Remove `GetSignBytes`

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#4102]
## Summary

In the bump to v0.50, we can remove `GetSignBytes`, see [sdk pr](https://github.com/cosmos/cosmos-sdk/pull/16062). We should ensure the amino annotations are correct so ledger signing can still be used

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
We already had this other [issue](https://github.com/cosmos/ibc-go/issues/3911). Can we close this one?

**Comment by colin-axner** [comment]
ah yes, perfect
