### ISSUE TITLE
`WriteUpgradeRestoreChannel` should be called before app callback `OnChanUpgradeRestore`

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#4125]
## Summary

We should perform the channel state writes before calling into the application callback.

This is particularly important for `29-fee` which has been implemented to allow both upgrading to a fee enabled channel and downgrading to disable fees on the channel.

We need to lookup using `GetAppVersion()` In order to determine whether or not we should restore the channel to either be fee enabled or fee disabled:

Enable fees:
```go
im.keeper.SetFeeEnabled(ctx, portID, channelID)
```

Disable fees:
```go
im.keeper.DeleteFeeEnabled(ctx, portID, channelID)
```

We can't perform this action unless the channel state has been written (particularly the channel version).

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by charleenfei** [comment]
was thinking about picking up this issue but realised that we might not consolidate the two functions, so this issue should come after https://github.com/cosmos/ibc-go/issues/4124 is fleshed out a bit more.

**Comment by crodriguezvega** [comment]
I see that except from these two calls:

- in [`ChannelUpgradeTimeout`](https://github.com/cosmos/ibc-go/blob/347346b51c9a2bec220f85c2406e021311ede5b4/modules/core/keeper/msg_server.go#L918-L920), where restoring the channel happens in `WriteUpgradeTimeoutChannel` after calling the `OnChanUpgradeRestore`;
- in [`ChannelUpgradeCancel`](https://github.com/cosmos/ibc-go/blob/347346b51c9a2bec220f85c2406e021311ede5b4/modules/core/keeper/msg_server.go#L950-L952), where restoring the channel happens in `WriteUpgradeCancelChannel`  after calling the `OnChanUpgradeRestore`;

in the rest of the places `OnChanUpgradeRestore` is called after `MustAbortUpgrade`, which restores the channel.

Do we need then to simply swap the calls of `OnChanUpgradeRestore` and `WriteUpgradeTimeoutChannel` in `ChannelUpgradeTimeout` and the calls `OnChanUpgradeRestore` and `WriteUpgradeCancelChannel` in `WriteUpgradeCancelChannel`?

**Comment by DimitrisJim** [comment]
done in #4166

**Comment by colin-axner** [comment]
Question, when would the outlined problem occur? My understanding is that the channel version will not change after calling restore. Restoring a channel should only change its state and maybe its upgrade sequence

**Comment by damiannolan** [comment]
Aha, you are 100% correct @colin-axner, for some reason I had it in my head with the old design when I wrote this up. 

I still think it could be worth doing app callbacks last for ack, confirm, restore - similarly to how to we only do app callbacks first in INIT and TRY (opening handshake) in order to do the version negotiation, what do you think?
