### ISSUE TITLE
Remove //notlint:staticcheck for deprecated tags

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#4143]
## Summary

The `//nolint:staticcheck` seems to be unnecessary in this [file](https://github.com/cosmos/ibc-go/blob/main/modules/core/04-channel/keeper/events.go#L128)

While testing update to sdk, these were removed and it looks like the linter still passes

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by lazyfuhrer** [comment]
Assign me @crodriguezvega

**Comment by crodriguezvega** [comment]
Thank you, @lazyfuhrer!

**Comment by lazyfuhrer** [comment]
check #4175

**Comment by DimitrisJim** [comment]
ah, I'm hitting the linter complaints here now, this was revive.

I think the rule does make sense to have (catch usages of deprecated names) so I'd say we should probably roll this back.
