### ISSUE TITLE
Remove `GetState` function of `ConnectionEnd`

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#4148]
Get rid of [`GetState`](https://github.com/cosmos/ibc-go/blob/31b3c6000ca05be316d5bb49d34e073ed07a82e8/modules/core/03-connection/types/connection.go#L26), since we can use directly the `State` field of `ConnectionEnd`.

**Comment by SurajAnand88** [comment]
@crodriguezvega assign this to me

**Comment by crodriguezvega** [comment]
Hi @SurajAnand88, I am going to close the issue, because when I opened it I didn't realise the `GetState` function was part of the `ConnectionI` interface. Thanks for offering!
