### ISSUE TITLE
Remove `GetState` function of `Channel` 

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#4150]
Get rid of [`GetState`](https://github.com/cosmos/ibc-go/blob/31b3c6000ca05be316d5bb49d34e073ed07a82e8/modules/core/04-channel/types/channel.go#L30), since it is not used at the moment.

**Comment by DimitrisJim** [comment]
we came to consensus on this? I remember talking about it but seem to recall the bigger problem being the `exported` interfaces. I.e it seems weird singling out `GetState`here (e.g `GetOrdering` similarly is not used).

**Comment by crodriguezvega** [comment]
True, just realised that, so I will close the issue.
