### ISSUE TITLE
Add helper function for checking if a channel is open

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#4152]
Similary as for #3466, create an `IsOpen` function in the `Channel` type that does the open check:

```golang
if !channel.IsOpen() {
  return errorsmod.Wrapf(channeltypes.ErrInvalidChannelState, "expected %s, got %s", channeltypes.Open, channel.State)
}
```

```golang
func (channel Channel) IsOpen() bool {
  return channel.State == OPEN
}
```

And use it everywhere where we check if the channel is open or not.

**Comment by DimitrisJim** [comment]
reminder comment: needs to be changed in 04-channel branch too.
