### ISSUE TITLE
ContractResponse errors don't appear to be used

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#4179]
## Summary

Opening this issue to track. It appears as if the current response we're getting back from contracts doesn't populate the `ErrMsg` field based on viewing the contracts. (Looking specifically for a call to `ContractResult::error`).

In short, it appears as if both `IsValid` and `ErrMsg` might not hold information. Have raised this issue in the relevant slack channel and will update this issue as required.

Relevant #3991 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
I don't see any harm leaving it. Even though the 2 contracts we have now don't use, I could that other contracts in the future might make use of it. Seems to me like a potentially useful thing to have.

**Comment by colin-axner** [comment]
closed by #4750, will be merged to upstream feature branch soon enough

**Comment by DimitrisJim** [comment]
pending contract updates are [in a separate PR](https://github.com/misko9/centauri/pull/2).
