### ISSUE TITLE
Replace `tm` prefix with `cmt` prefix

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#4184]
## Summary

Reference https://github.com/cosmos/ibc-go/pull/4178#pullrequestreview-1548034500

The PR linked changed instances in a couple of places but more exist through-out. Specifically, any cometbft import that uses `tm*` prefix can be replaced with `ctm*` (i.e `tmproto` -> `ctmproto`, `tmtypes` -> `ctmtypes` etc).

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by yashsolanki22** [comment]
Hi team, just saw this issue open and went through the Reference https://github.com/cosmos/ibc-go/pull/4178#pullrequestreview-1548034500 to understand the changes that needed to be done. I think I can work on it. 
Let me know if specific files that we are planning to change these prefixes.

**Comment by DimitrisJim** [comment]
hey @yashsolanki22! Don't have any specific list of files tbh, I'd just grep for imports of those packages and just replace references wherever I found em!

Lmk if you want to be assigned to it.

**Comment by yashsolanki22** [comment]
hello @DimitrisJim! let me have the code setup on my local up and running, then I'll update you on it.
