### ISSUE TITLE
Remove `store-code` CLI command

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#4201]
There is currently there is [CLI command to broadcast a transaction with the `MsgStoreCode`](https://github.com/cosmos/ibc-go/blob/f822b4fa7932a657420aba219c563e06c4465221/modules/light-clients/08-wasm/client/cli/tx.go#L19) signed by the user of the CLI. This CLI has been useful (still is) for testing, but when the moment of releasing the feature approaches we should remove it completely.

**Comment by colin-axner** [comment]
closed by #4990
