### ISSUE TITLE
Add CLI to submit governance proposal with `MsgStoreCode`

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#4202]
To make it easier for users to submit a proposal to upload a new light client contract, we should add a CLI command that creates and broadcasts a gov v1 `MsgSubmitProposal` with the `MsgStoreCode`. The CLI will be much easier to use than using the `submit-proposal` command and passing a JSON file with the base64 encoded string of the contract bytecode.

The CLI could look like: `simd tx ibc-wasm store-code [path/to/wasm-file] [flags]`

We can use the [CLI command in Cosmos SDK for submitting a software upgrade proposal](https://github.com/cosmos/cosmos-sdk/blob/1b0fcdc9f059419328ed2b6b2393320fb042270f/x/upgrade/client/cli/tx.go#L47) as an example.

Note that [`store-code` is currently in use](https://github.com/cosmos/ibc-go/blob/f822b4fa7932a657420aba219c563e06c4465221/modules/light-clients/08-wasm/client/cli/tx.go#L19), but it should [eventually be removed](https://github.com/cosmos/ibc-go/issues/4201), so it's ok to use a different flag for that command in the meantime. 

Update also [this section](https://github.com/cosmos/ibc-go/blob/a7cab2d3779bd9acb0380cd584f68a290e3def90/docs/ibc/light-clients/wasm/client.md#store-code) of the docs.

**Comment by stackman27** [comment]
hi @crodriguezvega i think i can take on this issue

**Comment by DimitrisJim** [comment]
go for it @stackman27

**Comment by stackman27** [comment]
@crodriguezvega @DimitrisJim 

the example provided "We can use the [CLI command in Cosmos SDK for submitting a software upgrade proposal](https://github.com/cosmos/cosmos-sdk/blob/1b0fcdc9f059419328ed2b6b2393320fb042270f/x/upgrade/client/cli/tx.go#L47) as an example." 

is off of the latest cosmos-sdk version, whereas ibc-go uses v0.47.4 which doesnot have the functionality as described in this issue link: https://github.com/cosmos/cosmos-sdk/blob/release/v0.47.x/x/upgrade/client/cli/tx.go#L39

**Comment by crodriguezvega** [comment]
Thanks for picking this one up, @stackman27. Yes, you're right the link I added in the description is from main, but do you see any impediment to implement this CLI using the gov v1 design? I thought we could, but maybe I'm missing something, so  please let me know.

**Comment by stackman27** [comment]
yea unfortunately  gov v1 `MsgSubmitProposal` interface has some functions missing in v0.47.4 that doesnot allow us to use it for ex: 

`proposal.SetMsgs`
main: https://github.com/cosmos/cosmos-sdk/blob/main/x/gov/types/v1/msgs.go#L48
v0.47.4: https://github.com/cosmos/cosmos-sdk/blob/release/v0.47.x/x/gov/types/v1/msgs.go

i can use x/group but it might be a little hacky: https://github.com/cosmos/cosmos-sdk/blob/release/v0.47.x/x/group/proposal.go

**Comment by julienrbrt** [comment]
We cut a patch release every month, so there will be a v0.47.5 in probably about 5 to 10days. It's on my list :)

**Comment by crodriguezvega** [comment]
> We cut a patch release every month, so there will be a v0.47.5 in probably about 5 to 10days. It's on my list :)
> In the meantime, you could just use the latest commit from the release branch for the integration until we tag.

Great! Then we'll upgrade as soon as it is out.

@stackman27 Do you think you can do some groundwork on this issue in the meantime until the SDK release is available?

**Comment by stackman27** [comment]
@crodriguezvega sounds good. Will do

**Comment by crodriguezvega** [comment]
@stackman27 Sorry for not replying earlier; I think I missed your message. We have just bumped SDK to 0.47.5 in the `feat/wasm-clients` feature branch, so it should good to go now. Are you still happy to work on this one?

**Comment by crodriguezvega** [comment]
@stackman27 Sorry for being a bit pushy, but this issue is soon going to enter our critical path. I don't want to stress you, so no problem if you're busy and cannot work on it; we can pick it up ourselves.

**Comment by stackman27** [comment]
no worries @crodriguezvega, i've been a little busy recently so feel free to pick this issue up

i generally prefer working on non-blocking issues :))

**Comment by crodriguezvega** [comment]
Closed by #4565
