### ISSUE TITLE
Re-assigning global VM in Keeper

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#4235]
## Summary

Opening this issue to keep this topic tracked for discussion.

We should eventually decide if re-assigning the global VM instance to point to another, different object should be allowed and any implications that would have.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Since the global VM variable is now internal to 08-wasm, there is. no risk of reassigning outside of the module, so I will close this issue for now.
