### ISSUE TITLE
Add version checking to `checkUpgradeForCompability`

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#4238]
## Summary

Ensure both counterparty upgrade and self upgrade version fields are equal in [checkUpgradeForCompability](https://github.com/cosmos/ibc-go/blob/04-channel-upgrades/modules/core/04-channel/keeper/upgrade.go#L735)

[spec ref](https://github.com/cosmos/ibc/pull/999/files#diff-69d7c4ac1d4cdeeabcc757d3a34e85945ebc5613a034a52ebd0769cd8a0fc560R277)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
This might require waiting for some of the other changes in the TRY/ACK handlers (unsure)
