### ISSUE TITLE
Modify upgrade ack expected channel

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#4243]
## Summary

https://github.com/cosmos/ibc-go/blob/04-channel-upgrades/modules/core/04-channel/keeper/upgrade.go#L252-L260

Modify the upgrade ack expected channel to be `FLUSHING` in favour of the previous `TRYUPGRADE` state.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
This will require changing the state set in TRY to be FLUSHING, note we will remove the TRY state from the proto in a separate pr
