### ISSUE TITLE
Add helper function for verifying counterparty upgrade info

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#4266]
## Summary

Add a helper function `VerifyCounterpartyUpgradeInfo` which verifies the counterparty upgrade and channel. The API should be agreed upon here before an implementation is made

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by expertdicer** [comment]
Is my implementation good? Please review. Tysm
```go
func (k Keeper) VerifyCounterpartyUpgradeInfo(
	ctx sdk.Context, portID,
	channelID string,
	counterparty types.Counterparty,
	proofCounterpartyUpgrade []byte,
	proofHeight clienttypes.Height,
) error {

	channel, found := k.GetChannel(ctx, portID, channelID)
	if !found {
		return errorsmod.Wrapf(types.ErrChannelNotFound, "port ID (%s) channel ID (%s)", portID, channelID)
	}

	if !channel.IsOpen() {
		return errorsmod.Wrapf(types.ErrInvalidChannelState, "expected %s, got %s", types.OPEN, channel.State)
	}

	upgrade, found := k.GetCounterpartyUpgrade(ctx, counterparty.PortId, counterparty.ChannelId)

	if !found {
		return errorsmod.Wrap(types.ErrUpgradeNotFound, channel.ConnectionHops[0])
	}

	connection, found := k.connectionKeeper.GetConnection(ctx, upgrade.Fields.ConnectionHops[0])
	if !found {
		return errorsmod.Wrap(connectiontypes.ErrConnectionNotFound, channel.ConnectionHops[0])
	}

	if err := k.connectionKeeper.VerifyChannelUpgrade(
		ctx,
		connection,
		proofHeight, proofCounterpartyUpgrade,
		channel.Counterparty.PortId,
		channel.Counterparty.ChannelId,
		types.NewUpgrade(upgrade.Fields, types.Timeout{}),
	); err != nil {
		return errorsmod.Wrap(err, "failed to verify counterparty upgrade")
	}

	return nil
}
```

**Comment by crodriguezvega** [comment]
Thank you for the proposal, @expertdicer. Please let me come back to you in a couple of days, because we might not need to do this anymore and then the issue could be closed.

**Comment by colin-axner** [comment]
Thanks for your interest @expertdicer! I think this issue is a bit outdated, the code looks great as is and I don't think we would benefit much since each handler needs to construct the expected counterparty channel and upgrade which is likely based on existing connection and channel fields so it doesn't seem to be much deduplication that can be performed
