### ISSUE TITLE
Write an error receipt for the counterparty to fast forward in try handler

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#4267]
## Summary

In the try handler, if the counterparty sequence is less than our own, write an error receipt (without restoring) to indicate the counterparty should fast forward their sequence. 

Note, the rest of the upgrade handler should be skipped and the tx should be successful

```
// if the counterparty sequence is less than the current sequence, then either the counterparty chain is out-of-sync or
    // the message is out-of-sync and we write an error receipt with our sequence - 1 so that the counterparty can update
    // their sequence as well.
    if counterpartyUpgradeSequence < channel.sequence {     
        errorReceipt = ErrorReceipt{
        channel.sequence - 1,
        "sequence out of sync", // constant string changable by implementation
        }
        provableStore.set(channelUpgradeErrorPath(portIdentifier, channelIdentifier), errorReceipt)
        return
    }
```
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by damiannolan** [comment]
Before closing this issue let's add a unit test for error receipt written on TRY and cancellation on the counterparty (fast forwarding the sequence) + proceeding with new upgrade sequence
