### ISSUE TITLE
Document ibc app expectations and recommendations for channel upgrades

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#4277]
## Summary

Add documentation for applications expectations and recommendations when upgrading a channel.

Apps should be recommended to *NOT* process packets under new conditions until the upgrade is complete. 
Application callbacks should be used for data fields validation and compatibility, and applications should only begin to act and process packets when `OnChanUpgradeOpen()` has succeeded. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closed by #5506
