### ISSUE TITLE
ibctesting: func ParsePacketFromEvents only returns one packet from events

### ISSUE THREAD

**Issue by puneet2019** [cosmos/ibc-go#4287]
## Problem Definition
- ibctesting package has a function ParsePacketFromEvents which helps to parse events so they can be relayed.
- but when I try to send multiple packets. this function only parses first packet and returns.

- inorder to relay all the packets that are part of events while testing my ibc app, a function is required which parses all packets which then can be relayed.
## Proposal
- create a function which rather returns array of Packets instead of first found.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by tbruyelle** [comment]
I came to the same conclusion, I don't understand why `ParsePacketFromEvents` returns a single packet, while it takes a slice of events. On my side I had to write a very similar function to overcome that : 

```go
func ParsePacketsFromEvents(events []abci.Event) ([]channeltypes.Packet, error) {
	var packets []channeltypes.Packet
	for i, ev := range events {
		if ev.Type == channeltypes.EventTypeSendPacket {
			packet, err := ibctesting.ParsePacketFromEvents(events[i:])
			if err != nil {
				return nil, err
			}
			packets = append(packets, packet)
		}
	}
	return packets, nil
}
```

Maybe this is just for convenience, in that case do you have any objection if I open a PR to add `ParsePacketsFromEvents` ?

**Comment by puneet2019** [comment]
I have none, all yours!

**Comment by tbruyelle** [comment]
Thanks @puneet2019, any input from the IBC team ? @crodriguezvega ?
