### ISSUE TITLE
govv1 proposal for ClientUpdateProposal

### ISSUE THREAD

**Issue by puneet2019** [cosmos/ibc-go#4289]
## Summary of Bug

Documentation mentions creating ClientUpdateProposal using govv1 msg, https://ibc.cosmos.network/main/ibc/proposals.html#step-2
`From SDK v0.46.x onwards`.. usage of Msgs for `/ibc.core.client.v1.ClientUpdateProposal`

But after creating a msg and executing it, it gives an error:
`Error: no concrete type registered for type URL /ibc.core.client.v1.ClientUpdateProposal against interface *types.Msg`
And rightfully so, because there is no codec registered for ClientUpdateProposal, and it doesn't implement Msg interface.

It is also not found in the interface list present in `tx gov draft-proposal`

## Expected Behaviour
this transaction should work with govv1

## Version
v7.2.0

## Steps to Reproduce
create and execute a ClientUpdateProposal as per docs https://ibc.cosmos.network/v7.2.0/ibc/proposals.html#step-2 using gov-v1 instead of legacy proposals

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Thanks for opening this issue, @puneet2019. This was raised already in https://github.com/cosmos/ibc-go/issues/3539. Our documentation is wrong and should be updated. And once we complete https://github.com/cosmos/ibc-go/issues/3672 then we will have gov v1 support (which will be released with ibc-go/v8).
