### ISSUE TITLE
Add error for indicating Mashal/Unmarshaling failures in ICA

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#4291]
## Summary

Found in https://github.com/cosmos/ibc-go/pull/4161#discussion_r1281675550 and issues of this kind might be opened for other places while https://github.com/cosmos/ibc-go/issues/3778 is getting worked on.

In short, we seem to be using `ErrUnknownDataType` liberally in `ica` even in cases where it doesn't make much sense (i.e marshalling/unmarhalling errors).

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chandiniv1** [comment]
@DimitrisJim can I work on this issue?

**Comment by crodriguezvega** [comment]
> @DimitrisJim can I work on this issue?

Yes, @chandiniv1. Thank you!

**Comment by chandiniv1** [comment]
@crodriguezvega  Is this issue about returning the actual error instead of the custom error (ErrUnknownDataType) during marshalling and unmarshalling failures, or is there something else involved?
