### ISSUE TITLE
Move empty contract check into getCallbackData function

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#4296]
## Summary

Currently the contract address is checked after getting the callback data. We can assert that the types packet should only return us a valid callback data, otherwise it should return an error

Move this check:
```
    if callbackData.ContractAddress == "" {
        types.Logger(ctx).Debug(fmt.Sprintf("No %s callback found for packet.", callbackType), "packet", packet)
        return nil 
    }
```

into `getCallbackData`, probably by modifiying `getCallbackAddress` to return an error

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by srdtrk** [comment]
Done in https://github.com/cosmos/ibc-go/pull/3939/commits/a926b02ce42f81a89ddb24c043f97e36ebadac96. I've also stopped logging this.
