### ISSUE TITLE
Consider moving callbackDataGetter up a level

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#4297]
## Summary

Currently a closure is created and passed to `processCallback` to get the callback data. The benefit of this is that if `getCallbackData` returns an error, we handle this in a single place, as a presence of an error which actually have us return nil. 

Another approach is to directly call `getCallbackData` within the `SendPacket`/`OnAcknowledgePacket`/etc functions. This requires handling the presence of an error with a nil return, but it reduces args to `processCallback` and improves code readability

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by srdtrk** [comment]
done in https://github.com/cosmos/ibc-go/pull/3939/commits/39622c02f163e97dcc291d43b11abae347187c84
