### ISSUE TITLE
Move event emission outside of processCallback

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#4298]
## Summary

The caller of processCallback should be responsible for emitting the correct events. This will allow us to remove the `packet` and `callbackType` args to `processCallback` as well

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by srdtrk** [comment]
Was done in https://github.com/cosmos/ibc-go/pull/3939/commits/a18c8778ea81969c64298d7df84b782e415c6b2d
