### ISSUE TITLE
Check for error returned in channel msg_tests

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#4304]
## Summary

We should check for the error returned in tests that check each message's ValidateBasic.

:umbrella: issue #3778 
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by DimitrisJim** [comment]
should probably be done after 04-channel-upgrades is merged.

**Comment by expertdicer** [comment]
Can i take the issue ? TYSM
