### ISSUE TITLE
Use consistent argument order in update verification functions

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#4311]
## Summary

Brought up by damian here https://github.com/cosmos/ibc-go/pull/4310#pullrequestreview-1567602390

This applies to most of the verification functions added for 04-channel-upgrades. At least it appears we have been consistent with the inconsistency, would be nice to have all in sync.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by ThanhNhann** [comment]
hey @DimitrisJim, can I handle this issue?

**Comment by DimitrisJim** [comment]
hey hey, would be nice for us to decide which of the two variations we use should be the one we go for, probably at a later eng. call, I'll drop a ping here after we discuss it :muscle:

**Comment by ThanhNhann** [comment]
Hey hey @DimitrisJim, is there any update for this?

**Comment by DimitrisJim** [comment]
Yup! Discussed just a little bit ago, old verification functions should be changed to use `portID, channelID, connection` as the new ones do (e.g see `VerifyChannelUpgradeError` for an example).

**Comment by crodriguezvega** [comment]
Closed by #4545
