### ISSUE TITLE
Prevent maxCallbackGas from being 0 in NewIBCMiddleware for callbacks

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#4324]
## Summary

The IBC middleware constructor function for callbacks should not allow the maxCallbackGas to be 0 as a defensive check

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by srdtrk** [comment]
addressed in https://github.com/cosmos/ibc-go/pull/3939/commits/01483b1d2f51372c8a81e86f9046f38ef495323f
