### ISSUE TITLE
Add inline comments for explicitly returning early in callback's handlers

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#4325]
## Summary

Each handler in the callbacks module for:
* SendPacket
* OnAcknowledgementPacket
* OnTimeoutPacket
* OnRecvPacket
* WriteAcknowledgement

should each add inline comments explaining that we explicitly return nil or the existing ack when the callback data cannot be retrieved or is invalid as callbacks should not act on this packet

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by srdtrk** [comment]
addressed in https://github.com/cosmos/ibc-go/pull/3939/commits/1058d4546027209ee5a28bcc786c76dfc0a6f9cd and https://github.com/cosmos/ibc-go/pull/3939/commits/9a0984508c44759f32ddca5b8240d85a77044d14
