### ISSUE TITLE
Fee Middleware: write documentation

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#433]
Feedback from [IBC Core Coordination #76](https://hackmd.io/qBt0tdWgTYCByLfPTa-u8g?view#IBC-Core-Coordination-76) is that we should write documentation on how to write a middleware application (similar to the documentation we have to create an [IBC application module](https://github.com/cosmos/ibc-go/blob/main/docs/ibc/apps.md). We should also add a couple of examples of different complexity.

**Comment by colin-axner** [comment]
closing, duplicate of #359
