### ISSUE TITLE
Add test case for empty contract address in callback types

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#4330]
## Summary

In `types/callbacks_test.go` a test case should be added for an empty callback address (in getCallbackData)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by srdtrk** [comment]
addressed in https://github.com/cosmos/ibc-go/pull/3939/commits/955887739775366b693ab4861f098b8bbc731954
