### ISSUE TITLE
Refactor `TestWriteUpgradeOpenChannel` to be use table driven test

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#4378]
## Summary

Refactor `TestWriteUpgradeOpenChannel` to use table tests.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by ThanhNhann** [comment]
Hey @damiannolan, can you plz assign me for this task
