### ISSUE TITLE
Refactor `TestWriteUpgradeCancelChannel` to use table tests

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#4409]
Refactor `TestWriteUpgradeCancelChannel` to use table-driven tests.

_Originally posted by @damiannolan in https://github.com/cosmos/ibc-go/pull/4404#discussion_r1300134533_

**Comment by damiannolan** [comment]
That'd be awesome, I was thinking we could use this kind of test structure:

```golang
testCases := []struct{
    name string
    malleate func()
    expError error
}{
        {
             "success",
             func() {},
             nil,
        },
        // failure scenarios with expected error
}
```

We can take the [existing test setup](https://github.com/cosmos/ibc-go/pull/4404/files#diff-2c64c23dc0c03e76759788d5c03a6ec1d86d1cccb797a762edaf47859a19be67R1267-R1298) and move it to the test body and make some assertions based on the inputs of [`WriteUpgradeCancelChannel`](https://github.com/cosmos/ibc-go/pull/4404/files#diff-2c64c23dc0c03e76759788d5c03a6ec1d86d1cccb797a762edaf47859a19be67R1298) mutated by `malleate()`.

I'll assign @ThanhNhann, feel free to make a PR and reach out if you've any questions

**Comment by DimitrisJim** [comment]
I think @ThanhNhann might need to drop a comment here, assigning has some restrictions apparently https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users#about-issue-and-pull-request-assignees

**Comment by crodriguezvega** [comment]
> I think @ThanhNhann might need to drop a comment here, assigning has some restrictions apparently https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users#about-issue-and-pull-request-assignees

Yes, correct. @ThanhNhann needs to comment here first. :)

**Comment by ThanhNhann** [comment]
Hi all, I'm here now 😄
