### ISSUE TITLE
Consistenly rebind loop variable in tests

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#4419]
## Summary

Ref: https://github.com/cosmos/ibc-go/pull/4413#discussion_r1301257466

Though in many cases not necessary, this is a nice defensive rebinding to do in order to guard against the possibility of running things in parallel. A quick grep showed me that there's other instances where this is omitted, would be nice to get them consistent.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by srdtrk** [comment]
I think in this case, we should also wrap the actual test logic inside a `suite.Run` like this:
```go
	for _, tc := range testCases {
		tc := tc
		suite.Run(tc.name, func() {
			suite.SetupTest()

			// ...
		})
	}
```
