### ISSUE TITLE
Refactor acknowledgePacket tests to use expResult func

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#4433]
The `AcknowledgePacket` tests in 04-channel currently expose an `expError` var and in #4412 an additional `assertFn` has been added. 

We can refactor the test case structure to use an `expResult` func and perform explicit error checking and posterior state checks after tests are run.

_Originally posted by @damiannolan in https://github.com/cosmos/ibc-go/pull/4412#discussion_r1301437559_

**Comment by DimitrisJim** [comment]
would definitely be nice to do this for others, `recv` has this `expError` variable that is set in malleate, easy to miss (as I did). Would be nice to also amend it to use `expResult` instead. Can pick it up.
