### ISSUE TITLE
Allow `recvPacket` to proceed in `FLUSHING` channel state, without counterparty last sequence set

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#4447]
Original comment text below.

---

There is one gotcha here! 

After TRY handler executes, we have `counterpartyUpgrade` and are in `FLUSHING` channel state **BUT** `LastSequenceSend` is not set yet, until after `ACK` and `CONFIRM` succeed. 
Right now, that means relayer will have `recvPacket` rejected until it goes further in the upgrade handshake and then it would need to retry packets. 

I wonder if wrapping this check in:
```go
if counterpartyUpgrade.LastSequenceSend != 0 { 
    // do greater than checking 
}

// otherwise carry on with `recvPacket`
```

This way we know that if `LastSequenceSend` is still 0 that we can safely continue to receive packets while in `FLUSHING` state.

Happy to leave this as a future improvement, I'll open an issue based off this comment.

_Originally posted by @damiannolan in https://github.com/cosmos/ibc-go/pull/4386#discussion_r1304147989_

**Comment by damiannolan** [comment]
I think it makes sense to allow packets to proceed in this state, rather than erroring and having to retry them later.

**Comment by damiannolan** [comment]
Let's go a head with this after discussion. I will open an issue on the spec

**Comment by DimitrisJim** [comment]
will pick up after #4448 to use fresh tests
