### ISSUE TITLE
Create separate event emission for ibc software upgrades vs an upgraded client

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#4507]
## Summary

Currently the same event is used to indicate a IBC software upgrade has been scheduled and that a client has been upgraded.

These are not the same events. One refers to a plan scheduled on the source chain and the other refers to clients upgraded on the counterparty chains. We should differentiate the two by creating a separate event for scheduling an IBC software upgrade. We can start by making a separate function and then see if we can change the type (unsure if this event is used by relayers, but I believe they rely on the `emitUpgradeChainEvent` instead)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closed by #4594
