### ISSUE TITLE
Specify sane default for default upgrade timeout timestamp

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#4513]
## Summary 

We're currently hardcoding [1 hour as a default timeout](https://github.com/cosmos/ibc-go/blob/fa3f92fbb546cc7f450f796eaac14bfc21d60022/modules/core/04-channel/types/params.go#L12) for channel upgrades. We need to decide on a sane default for this value.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by womensrights** [comment]
My recommendation for the default time is 10 minutes. 

Feedback from relayer operators has indicated that under typical conditions, where you might typically have a packet backlog between 1-10 packets, then flushing would take a few seconds, therefore 10 minutes is already relatively conservative, but is in line with existing defaults. 

The only scenario to consider more carefully is the case where flushing would require an archival node to complete and packets are still in the channel that have not been timed-out for quite some time. I don't think it makes sense to cater for this edge case where the flushing process would take much longer, instead we should recommend that a chain should not start the governance process for upgrading that specific channel and this should be made clear in the accompanying documentation and tutorial for adding fee middleware to existing channels.
