### ISSUE TITLE
New channel queries

### ISSUE THREAD

**Issue by alpe** [cosmos/ibc-go#4525]
## Summary
Smart contracts can query all *open* ibc channels (and optional with a given port) . We use [`channelKeeper.IterateChannels`](https://github.com/CosmWasm/wasmd/blob/v0.41.0/x/wasm/keeper/query_plugins.go#L250) for this, which is not very efficient. It would be great to have an api that does this better with pagination support.

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Thanks for opening the issue, @alpe. 

Maybe this would not be possible, but just thinking out loud here: we have a [`Channels` RPC query](https://github.com/cosmos/ibc-go/blob/6f5d5ee19215990e60ca328831e0926327d4f7b7/modules/core/04-channel/keeper/grpc_query.go#L49) that supports pagination by using SDK's `query.Paginate`. Would it be possible for you to replicate part of the functionality of this endpoint in your code (i.e. [the part that does the query with pagination](https://github.com/cosmos/ibc-go/blob/6f5d5ee19215990e60ca328831e0926327d4f7b7/modules/core/04-channel/keeper/grpc_query.go#L56-L76))?

**Comment by alpe** [comment]
Thanks for your quick response!
Iterating on the whole channel set is very inefficient on our side. In ibc-go you can make use of the port-id in the storage key  for a prefix iterator.
The SDK pagination comes with some options that are not very efficient either. It is also not a good fit as we need a filter for open channels. I am thinking that a keeper method may be better for us than a GRPC endpoint with non default pagination settings. We only need support for:
* pagination key
* limit
* reverse

WDYT?

**Comment by crodriguezvega** [comment]
Thank you for the comments, @alpe and @webmaster128.

Maybe you haven't seen it already, but we already have this keeper [function `GetAllChannelsWithPortPrefix`](https://github.com/cosmos/ibc-go/blob/057cd27111b310513e690454c69ccec38454dbd2/modules/core/04-channel/keeper/keeper.go#L397) that returns all channels on a given port ID. It doesn't support pagination, limit or reverse iteration, but it does support filtering by port ID. Would this function satisfy your needs?

**Comment by alpe** [comment]
`GetAllChannelsWithPortPrefix` works with our use case. Thanks for pointing to this method!
We use this in our [query handler](https://github.com/CosmWasm/wasmd/pull/1620/files#diff-31a3ad60ef3595b573c7ea5150e6bb8176b41e261ba7faa5a5e7769cc4a7b928R257) now
