### ISSUE TITLE
Switch back to informalsystems hermes image

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#4551]
## Summary

https://github.com/cosmos/ibc-go/pull/4535 switches the hermes image to use a custom image I built with ubuntu 22 as the operating system. 

We can switch back once a new image has been built by informal systems following the closure of this issue https://github.com/informalsystems/hermes/issues/3580

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
We can switch back with hermes releases v1.7 (end of September).

**Comment by crodriguezvega** [comment]
We switched back [here](https://github.com/cosmos/ibc-go/pull/4643) to tag from master. We can still update to v1.7 when it gets out.
