### ISSUE TITLE
Remove unnecessary deps in simapp

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#4552]
## Summary

Remove dependencies which are not strictly needed

## Problem Definition

Our simapp contains module we do not use nor test, see [comment](https://github.com/cosmos/ibc-go/pull/4535#discussion_r1314757074) on the circuit module

## Proposal

Remove unnecessary deps such as:
- circuit
- evidence 
- feegrant

**Discussion point**:
our simapp is likely used as a reference for chains, that would be the primary benefit of including unnecessary deps

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by faddat** [comment]
I recommend keeping these dependencies, as well as adding x/nft due the fact that I'm certain that the ibc-go simapp is used as a reference. 

We should also make sure that when using the wasm clients feature, we don't leave any naming ambiguous.

**Comment by crodriguezvega** [comment]
We'll work on this once we make the testing simapp have its own go.mod.

**Comment by crodriguezvega** [comment]
Now that #3968 is closed, those dependencies have been [removed from ibc-go's go.mod](https://github.com/cosmos/ibc-go/pull/6710/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L15-L18).
