### ISSUE TITLE
Use SDK helper function for parsing AppGenesis from bytes

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#4556]
## Summary

Use the added [function](https://github.com/cosmos/cosmos-sdk/pull/17571) in the e2e genesis setup to read the app genesis from the provided bytes

see [relevant comment](https://github.com/cosmos/ibc-go/pull/4535#discussion_r1314745821)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
this is actually required for our backwards compatibility tests to work, I'll add this to the v8 milestone

**Comment by chatton** [comment]
looks like this was implemented [here](https://github.com/cosmos/ibc-go/commit/e49f741ddcd98c601855bf4a954dc1fbdc3499c6)
