### ISSUE TITLE
Create dedicated test for BeginBlocker

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#4579]
Currently we have logic in a transfer test to verify begin blocker is executed. We should move this out into its own dedicated test.

_Originally posted by @damiannolan in https://github.com/cosmos/ibc-go/pull/4563#discussion_r1316000446_

**Comment by muku314115** [comment]
Is this issue still up for development?
If yes then would it make sense to just shift restart test to capability_test or genesis_state and use it wherever required? Seems fairly doable

**Comment by colin-axner** [comment]
Now that capabilities is removed, I'm unsure if the begin block check still exists? We can close this issue?
