### ISSUE TITLE
Cleanup and determine how to handle intertx e2e tests

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#4592]
## Summary

https://github.com/cosmos/ibc-go/pull/4590 required commenting out intertx e2e tests in order to get things passing.

Intertx requires an upgrade to v0.50 of cosmos-sdk. Or alternatively we can take a different approach towards phasing out the intertx tests.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by womensrights** [comment]
I asked around some of the existing ICA controller users and Confio, consensus is that it is fine to archive the interchain accounts demo repo so these tests can also be removed
