### ISSUE TITLE
Refactor OnRecvPacket test in transfer

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#4598]
## Summary

This [test](https://github.com/cosmos/ibc-go/blob/main/modules/apps/transfer/keeper/relay_test.go#L244) should be refactored to reduce setup/verification complexity. 

## Problem Definition

The test is trying to test many cases in addition to asserting various expected results. This has become difficult to maintain as new features tend to insert their setup/exp result assertions into the body of the for loop iterating over test cases. 

## Proposal

We should simplify rework this test to separate concerns. I don't have a concrete proposal atm, mostly opening for signaling. It's possible this might be achieved by cleaning up the main handlers to separate concerns (currently logic for if a recv is the source chain or not the source chain are bundled into the same handler rather than being brought into smaller private functions).

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
I was thinking the same thing. Every time I have to do something we that test, I get a headache.
