### ISSUE TITLE
add proposal simulations for MsgRecoverClient and MsgIBCSoftwareUpgrade

### ISSUE THREAD

**Issue by charleenfei** [cosmos/ibc-go#4599]
similar to the proposal sims in [this pr](https://github.com/cosmos/ibc-go/pull/4466)
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by trinity6569** [comment]
hi @charleenfei, can I try to do this ?

**Comment by trinitys7** [comment]
@charleenfei got it, thanks for your suggestion.
