### ISSUE TITLE
Add documentation for ISC-20 memo format and keys

### ISSUE THREAD

**Issue by srdtrk** [cosmos/ibc-go#4617]
## Summary

Add some documentation about the memo keys (and memo format) for ICS-20 (and potentially ICS-27). It suffices to make a reference to [the chain registry's memo key documentation](https://github.com/cosmos/chain-registry/blob/master/_memo_keys/ICS20_memo_keys.json)

## Problem Definition

Until we allow additional packet data for middlewares, the memo field's current usage should be documented. Chain Registry already has a list of memo keys and their format.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
I think this is a duplicate of https://github.com/cosmos/ibc-go/issues/3008, right?

**Comment by srdtrk** [comment]
right @crodriguezvega
