### ISSUE TITLE
V7 to V8 Upgrade Test Part #2

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#4645]
## Summary

Follow up to [this PR](https://github.com/cosmos/ibc-go/pull/4591).

We need to also check for the human readable denom added in #3104

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
We already had [this issue](https://github.com/cosmos/ibc-go/issues/4216). Do we need both? I guess the same PR would close both...

**Comment by chatton** [comment]
ah right, we can just use the other one!
