### ISSUE TITLE
Investigate failing TestV6ToV7ChainUpgrade test

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#4646]
## Summary

ref https://github.com/cosmos/ibc-go/pull/4591#issuecomment-1717315083

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
I ran the test locally with the golang relayer (`ghcr.io/cosmos/relayer:latest`) and it passes, it seems to only fail with hermes (`colinaxner/hermes:v1.6.0`

**Comment by chatton** [comment]
Another update, making the following changes causes the test to pass

```diff
--- a/e2e/tests/upgrades/upgrade_test.go
+++ b/e2e/tests/upgrades/upgrade_test.go
@@ -578,6 +578,11 @@ func (s *UpgradeTestSuite) TestV6ToV7ChainUpgrade() {
                s.AssertTxSuccess(transferTxResp)
        })

+       s.StopRelayer(ctx, relayer)
+       s.StartRelayer(relayer)
+
+       s.Require().NoError(test.WaitForBlocks(ctx, 5, chainA, chainB), "failed to wait for blocks")
+
        t.Run("packets are relayed", func(t *testing.T) {
                s.AssertPacketRelayed(ctx, chainA, channelA.PortID, channelA.ChannelID, 1)

```

I recall a setting for hermes which caused it to not pick up on new chains (potentially losing track of them after the chain upgrade), restarting may be causing it to do a search and find them again.

**Comment by colin-axner** [comment]
Is this issue still relevant?

**Comment by chatton** [comment]
I think it's not, we ended up [adding code](https://github.com/cosmos/ibc-go/blob/60bbee1afb7319727b17fb84ee769d0112ce320d/e2e/tests/upgrades/upgrade_test.go#L387-L390) to do a restart of hermes.


The [hermes issue](https://github.com/informalsystems/hermes/issues/3579) seems to still be open.

I'll close this issue as the upgrade test is resolved on our side.
