### ISSUE TITLE
e2e: add function to get balance and migrate existing calls to `CosmosChain`'s `GetBalance` 

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#4661]
[This PR](https://github.com/cosmos/ibc-go/pull/4642) added a [function to query all balances](https://github.com/cosmos/ibc-go/blob/d4e2afc35830e20923405a5c3a6a3b2bcd49ff92/e2e/testsuite/grpc_query.go#L283). We should implement a similar function to get the balance for a specific account address and denomination, and migrate the calls to `GetBalance` in our e2e tests (like this one [here](https://github.com/cosmos/ibc-go/blob/e49f741ddcd98c601855bf4a954dc1fbdc3499c6/e2e/testsuite/testsuite.go#L380)) to use the new function instead.

**Comment by trinitys7** [comment]
hi @crodriguezvega can I try to do this ?

**Comment by crodriguezvega** [comment]
Yes, sure! Thank you, @trinitys7!
