### ISSUE TITLE
Implement `PreBlocker` changes from sdk v0.50 Eden

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#4666]
## Summary

Implement the necessary changes in `simapp/app.go` for `PreBlocker` outlined in the SDK v0.50 Eden `UPGRADING.md`

https://github.com/cosmos/cosmos-sdk/blob/main/UPGRADING.md#Set-PreBlocker

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by faddat** [comment]
Done, but in a messy branch.  Will do this cleanly tonight or tomorrow.
