### ISSUE TITLE
Validate the `authority` field is non-empty in `NewKeeper` funcs

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#4667]
## Summary

Validate the `authority` fields passed to each `NewKeeper` function.
Ensure that it is not an empty string. 

Open question:

Can we validate that it is an `sdk.AccAddress` or not?
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
We can check that is a valid address. Some modules of the SDK [do that in `NewKeeper`](https://github.com/cosmos/cosmos-sdk/blob/b7d9d4c8a9b6b8b61716d2023982d29bdc9839a6/x/staking/keeper/keeper.go#L56-L59) and in general, if wiring with app v2, all of them [set gov module address as default](https://github.com/cosmos/cosmos-sdk/blob/b7d9d4c8a9b6b8b61716d2023982d29bdc9839a6/x/mint/module.go#L236-L240).

**Comment by damiannolan** [comment]
so shall we default to x/gov and close #4668 in the process?

**Comment by crodriguezvega** [comment]
Just check that is not empty.
