### ISSUE TITLE
Replace all `collections.Contains` instances with `slices.Contains`

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#4669]
## Summary

Go 1.21 provides built in functionality for a generic `silces.Contains` function. 

Replace the instances of `collections.Contains` with `slices.Contains` across the codebase.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by CyberGA** [comment]
Can I work on this?
