### ISSUE TITLE
Why Query/NextSequenceSend is not available for UNORDERED channels?  

### ISSUE THREAD

**Issue by dzmitry-lahoda** [cosmos/ibc-go#4698]
## Summary

`Query/NextSequenceSend` to return real packet sequence for UNORDERED channels instead of zero.

## Problem Definition

Handler of `Query/NextSequenceSend` has next code:

```go
	var sequence uint64
	if channel.Ordering != types.UNORDERED {
		sequence, found = k.GetNextSequenceSend(ctx, req.PortId, req.ChannelId)
		if !found {
			return nil, status.Error(
				codes.NotFound,
				errorsmod.Wrapf(types.ErrSequenceSendNotFound, "port-id: %s, channel-id %s", req.PortId, req.ChannelId).Error(),
			)
		}
	}
	selfHeight := clienttypes.GetSelfHeight(ctx)
	return types.NewQueryNextSequenceSendResponse(sequence, nil, selfHeight), nil
```

returning zero for request. 

But `GetNextSequenceSend` works for UNORDERED for sure. Because it is used in ICS-20 transfer application, here is transfer send method

```
	sequence, err := k.ics4Wrapper.SendPacket(ctx, channelCap, sourcePort, sourceChannel, timeoutHeight, timeoutTimestamp, packetData.GetBytes())
	if err != nil {
		return 0, err
	}
```

If to allow getting next sequence query handling for UNORDERED channels it will simplify correlation of message sent with IBC timeouts/ack callbacks for various forms of handling. 

## Proposal

Remove check of UNORDERED

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Thanks, @dzmitry-lahoda. Yeah, this looks like an oversight from our side. I see that you opened a PR already, so thank you also for that!
