### ISSUE TITLE
Ammend 08-wasm simapp with testing/simapp changes

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#4744]
Requires sdk50 and a sync of feat/wasm-clients to main. Then the following need to be done:

 - Add Preblocker (ref: https://github.com/cosmos/ibc-go/pull/4676)
 - Use port keeper directly, as it has been changed to be a pointer (ref: https://github.com/cosmos/ibc-go/pull/4703)
 - ~~Remove v1beta1 router (ref: https://github.com/cosmos/ibc-go/pull/4714). I believe this can still be done for wasm since we know no inflight proposals will exist.~~ Tracked as part of https://github.com/cosmos/ibc-go/issues/4671

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
We can probably remove the gov router in the callbacks and wasm simapps, but I don't think there's any rush to do it all, I think we can still just do it all in the one PR when we merge it in the end.

**Comment by DimitrisJim** [comment]
sounds like a plan, can amend parent issue

**Comment by DimitrisJim** [comment]
Done in https://github.com/cosmos/ibc-go/pull/4805, router removal is tracked in #4671
