### ISSUE TITLE
Add codec type registration tests

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#4747]
Add codec type registration tests for each ibc app and core submodule.

- [x] 02-client
- [x] 03-connection
- [x] 04-channel
- [x] 23-commitment
- [x] 06-solomachine
- [x] 07-tendermint
- [x] 09-localhost 
- [x] transfer
- [x] 29-fee
- [x] 27-interchain-accounts
- [x] 08-wasm (use [feat/wasm-clients](https://github.com/cosmos/ibc-go/tree/feat/wasm-clients))

> We should replicate this testing to each `codec.go` of our apps and submodules.

See the provided pull request as an reference example:

ref: https://github.com/cosmos/ibc-go/pull/4746

**Comment by DimitrisJim** [comment]
note for 08-wasm, we could use `InterfaceRegistry` on `TestEncodingConfig` directly since `Codec` doesn't have the function to get it (on 0.47.5).
