### ISSUE TITLE
IBC message simulation

### ISSUE THREAD

**Issue by cwgoes** [cosmos/ibc-go#48]
Would be useful to simulate, if we can cover the state space well:
- Client creation, client updates
- Handshakes for connection & channels (opening & closing)
- Packets, acks, timeouts

**Comment by colin-axner** [comment]
Do we still need to support this? Seems like it adds more technical debt than usefulness

The current testing strategy of IBC
- beefy unit tests with our testing package
- generative tests with mbt eventually integrated into each handler 
- end to end tests generated by mbt using docker as a driver in a language agnostic fashion

The end to end tests are still far out but would cover this area of simulation needed. It would also occur at the relayer level

From my understanding, simapp doesn't even run with a validator. We would need dynamic validator sets to get good usage from it, which would be a lot of work. 

I'd be in favor closing this issue and abandoning usage of SDKs simapp. If the simulator is rewritten with IBC in mind, then I think this would be a worthwhile issue to bring back up

**Comment by cwgoes** [comment]
I agree. Closing unless anyone objects.
