### ISSUE TITLE
Run grandpa e2e test in CI

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#4800]
There is [an e2e test in interchain test](https://github.com/strangelove-ventures/interchaintest/blob/steve/hyperspace_v39/examples/hyperspace/hyperspace_test.go) that uses the grandpa light client contract and executes an ICS20 transfer with a substrate chain. We should run this test as part of our CI.

**Comment by chatton** [comment]
Thinking a bit more about this, I think it's worth taking this test and making it plug in nicely with our current setup. Especially if we are using a mock VM in unit tests, we want to ensure we robust E2E coverage.

To support this, we need to make a few changes.

1. Support the `hyperspace` relayer in our tests. We can add a new case [here](https://github.com/cosmos/ibc-go/blob/47fba08c833122260959db7246855bd6d8a4acf1/e2e/relayer/relayer.go#L42) with the relevant configuration.
2. No longer assume every chain config is a simd. We can make some changes [here](https://github.com/cosmos/ibc-go/blob/c543ac912ba6083ca87bbb3761fac8cb6808197b/e2e/testsuite/testconfig.go#L441) to account for a polkadot chain (can determine the type from `tc` )

**Comment by crodriguezvega** [comment]
Closed by #4959
