### ISSUE TITLE
helper function to parse proposalID from events

### ISSUE THREAD

**Issue by charleenfei** [cosmos/ibc-go#4809]
> Should we encapsulate this code in a helper function [here](https://github.com/cosmos/ibc-go/blob/main/testing/events.go), like we have for `ParseClientIDFromEvents` and other functions?

_Originally posted by @crodriguezvega in https://github.com/cosmos/ibc-go/pull/4773#discussion_r1343594867_

Add `ParseProposalIDFromEvents` utility function to the testing pkg. 

> we could sweep this under a `ibctesting.ParseProposalIDFromEvents()` func but can be a future improvement 👍

_Originally posted by @damiannolan in https://github.com/cosmos/ibc-go/pull/4773#discussion_r1347004935_

**Comment by ThanhNhann** [comment]
Can I handle this issue?

**Comment by damiannolan** [comment]
Sure thing, I can assign you! Thanks very much @ThanhNhann

**Comment by damiannolan** [comment]
closed by #4942
