### ISSUE TITLE
Ensure wasmvm static library version matches wasmv import in go.mod

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#4821]
Currently we import wasmvm 1.4.0 in our go.mod while we statically link against 1.2.4 in our dockerfile, Would be good to ensure these are always in sync.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
I think we can maybe just fetch the value from our go mod, and add it as a build arg to the wasm dockerfile.

```bash
lib_version="$(modules/light-clients/08-wasm/go.mod | grep "github.com/CosmWasm/wasmvm" | awk '{print $NF}')"
docker build ... --build-arg LIB_VERSION=${lib_version}
```

**Comment by DimitrisJim** [comment]
> Or use a sane language like python :D

pls

**Comment by DimitrisJim** [comment]
Ah, we did have a small TODO in the dockerfile that offers a nicer approach:

> # TODO: nice to have: a script to download version matching the wasmvm version in go.mod.

that way it'll automatically be handled for us

**Comment by chatton** [comment]
how do we assign @TODO to do it for us

**Comment by webmaster128** [comment]
You can do this just like wasmd:
- https://github.com/CosmWasm/wasmd/blob/v0.41.0/x/wasm/module.go#L314-L326
- https://github.com/CosmWasm/wasmd/blob/v0.41.0/x/wasm/module.go#L286-L301

**Comment by chatton** [comment]
Thank you @webmaster128 , I added your suggestion to our simapp too!

**Comment by DimitrisJim** [comment]
ref #4837
