### ISSUE TITLE
Add TestCheckForMisbehaviour using mock vm for 08-wasm

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#4824]
## Summary

Add TestCheckForMisbehaviour. See this [commented out test](https://github.com/cosmos/ibc-go/blob/feat/wasm-clients/modules/light-clients/08-wasm/types/misbehaviour_handle_test.go#L579). There is currently no equivalent test with the grandpa client

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closed by #4901
