### ISSUE TITLE
Add TestCheckSubstituteAndUpdateState using mock vm for 08-wasm

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#4829]
## Summary

Add TestCheckSubstituteAndUpdateState using mock vm. See [commented out test](https://github.com/cosmos/ibc-go/blob/feat/wasm-clients/modules/light-clients/08-wasm/types/proposal_handle_test.go#L148) (though it can likely be much simpler

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by DimitrisJim** [comment]
closed in #4950
