### ISSUE TITLE
 Add TestVerifyClientMessage using mock vm for 08-wasm 

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#4830]
## Summary

Add `TestVerifyClientMessage` using mock vm. See [commented out test](https://github.com/cosmos/ibc-go/blob/feat/wasm-clients/modules/light-clients/08-wasm/types/update_test.go#L78) (though it can likely be simplified a lot)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by DimitrisJim** [comment]
handled in #4921 since both Misbehavior and Header are bundled in the `ClientMessage`. Re-open if I misunderstood.
