### ISSUE TITLE
Add TestUpdateState using mock vm for 08-wasm

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#4831]
## Summary

Add TestUpdateState using mock vm. See [commented out test](https://github.com/cosmos/ibc-go/blob/feat/wasm-clients/modules/light-clients/08-wasm/types/update_test.go#L452)
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closed by #4914
