### ISSUE TITLE
Add `ParseProposalIDFromEvents` func to ibctesting pkg

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#4836]
Add `ParseProposalIDFromEvents` utility function to the testing pkg. 

> we could sweep this under a `ibctesting.ParseProposalIDFromEvents()` func but can be a future improvement 👍

_Originally posted by @damiannolan in https://github.com/cosmos/ibc-go/pull/4773#discussion_r1347004935_

**Comment by crodriguezvega** [comment]
@damiannolan we had already [this issue](https://github.com/cosmos/ibc-go/issues/4809) opened for the same thing. I will close this as duplicate then, ok?
