### ISSUE TITLE
Add Code Coverage for `HasCodeHash`

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#4838]
Add code coverage for `if !HasCodeHash(ctx, cdc, cs.CodeHash) {}`

_Originally posted by @charleenfei in https://github.com/cosmos/ibc-go/pull/4292#discussion_r1341293094_

**Comment by DimitrisJim** [comment]
can be an additional test case in each of the test funcs that call `Initialize` (currently `TestInitializeGrandpa` as Tendermint one is commented out).
