### ISSUE TITLE
Decide on a convention for naming wasm byte code/byte code hash.

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#4852]
## Summary

This is unfortunately a messy situation at the moment.

For the wasm code, specifically:

 - [`code_bytes` in `Contract`](https://github.com/cosmos/ibc-go/blob/32e4bd77ebf094429190fc9cffadf4f57a42186b/proto/ibc/lightclients/wasm/v1/genesis.proto#L19) stored in `GenesisState`.
 - [`wasm_byte_code` in `MsgStoreCode`](https://github.com/cosmos/ibc-go/blob/32e4bd77ebf094429190fc9cffadf4f57a42186b/proto/ibc/lightclients/wasm/v1/tx.proto#L22).

For the codeHash/checkSum:

 - [`checkSum` in `MsgStoreCodeResponse`](https://github.com/cosmos/ibc-go/blob/feat/wasm-clients/proto/ibc/lightclients/wasm/v1/tx.proto#L28)
 - [`codeHash` in both `ClientState`](https://github.com/cosmos/ibc-go/blob/32e4bd77ebf094429190fc9cffadf4f57a42186b/proto/ibc/lightclients/wasm/v1/wasm.proto#L16) and used in messages/names [for the `CodeHashes` rpc](https://github.com/cosmos/ibc-go/blob/32e4bd77ebf094429190fc9cffadf4f57a42186b/proto/ibc/lightclients/wasm/v1/query.proto#L12).

The [mockVM added](https://github.com/cosmos/ibc-go/blob/32e4bd77ebf094429190fc9cffadf4f57a42186b/modules/light-clients/08-wasm/testing/mock_engine.go#L18-L23) also introduced some names that are used in wasmd: `WasmCode/CheckSum` as the types and `codeID`/`checksum` as names, there's some discrepancy here that can be cleaned easily (`codeID` being used for both code/codeHash in these funcs, `PinFn` having it named checksum).

---

All these names make it difficult to follow along and make it easy to make subtle mistakes. It would be nice if all we had some form of consistency.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by DimitrisJim** [comment]
Note that `codeID` is a separate concept in wasmd and [is used for storing `CodeInfo`'s in state](https://github.com/CosmWasm/wasmd/blob/bb7d3e56424fb52cd37158376774d07e91dc928a/x/wasm/keeper/keeper.go#L201).

**Comment by crodriguezvega** [comment]
> For the wasm code, specifically:
> 
> [code_bytes in Contract](https://github.com/cosmos/ibc-go/blob/32e4bd77ebf094429190fc9cffadf4f57a42186b/proto/ibc/lightclients/wasm/v1/genesis.proto#L19) stored in GenesisState.
> [wasm_byte_code in MsgStoreCode](https://github.com/cosmos/ibc-go/blob/32e4bd77ebf094429190fc9cffadf4f57a42186b/proto/ibc/lightclients/wasm/v1/tx.proto#L22).
> For the codeHash/checkSum:
> 
> [checkSum in MsgStoreCodeResponse](https://github.com/cosmos/ibc-go/blob/feat/wasm-clients/proto/ibc/lightclients/wasm/v1/tx.proto#L28)
> [codeHash in both ClientState](https://github.com/cosmos/ibc-go/blob/32e4bd77ebf094429190fc9cffadf4f57a42186b/proto/ibc/lightclients/wasm/v1/wasm.proto#L16) and used in messages/names [for the CodeHashes rpc](https://github.com/cosmos/ibc-go/blob/32e4bd77ebf094429190fc9cffadf4f57a42186b/proto/ibc/lightclients/wasm/v1/query.proto#L12).
> 

In [this PR](https://github.com/cosmos/ibc-go/pull/4091) I chose those names to follow wasmd's convention. During the walkthrough we agreed to keep the naming like that.

I agree though that it's probably a good idea to change the naming in the mock functions to avoid the `codeId` / `codeHash` confusion.

**Comment by DimitrisJim** [comment]
yeah, for one I think maybe the response for StoreCode should be the same as what is then used directly in ClientState?
