### ISSUE TITLE
Unbounded field lengths

### ISSUE THREAD

**Issue by faddat** [cosmos/ibc-go#4859]
## Summary of Bug

In ibc-go, there are many unbounded field lengths, and in production, this can result in ibc messages that are as large as several megabytes, which are seen as valid and relayed.  

## Expected Behaviour

With the exception of the total size of client updates, I'm not aware of any ibc transaction that benefits from a field length of over 5kb for any field.  Even if this is incorrect and we need to exceed 5kb in some places, we need to introduce bounds to fields in ibc for safety.

## Version

all

## Steps to Reproduce

Contact Jacob Gadikian or another Notional team member via slack for information on reproduction

## fix

We should ensure that every field in IBC has a maximum length.  Marko from the SDK team says that length limitations are done on a per module basis in the SDK, and so IBC should comply.  We are checking internally to determine if we have time / financial resources to complete this task.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Thank you for opening the PR, @faddat.

On a first pass, I think we have the following string fields whose maximum length is not checked:

- [`receiver` and `memo` in `MsgTransfer`](https://github.com/cosmos/ibc-go/blob/2ec9c7d745c3a763530a53cff9dc72eb09056fd4/proto/ibc/applications/transfer/v1/tx.proto#L43)
- [`counterparty_payee` in `MsgRegisterCounterpartyPayee`](https://github.com/cosmos/ibc-go/blob/2ec9c7d745c3a763530a53cff9dc72eb09056fd4/proto/ibc/applications/fee/v1/tx.proto#L78)
- [`owner` in `MsgRegisterInterchainAccount`](https://github.com/cosmos/ibc-go/blob/2ec9c7d745c3a763530a53cff9dc72eb09056fd4/proto/ibc/applications/interchain_accounts/controller/v1/tx.proto#L30)
- [`version` in `MsgRegisterInterchainAccount`](https://github.com/cosmos/ibc-go/blob/2ec9c7d745c3a763530a53cff9dc72eb09056fd4/proto/ibc/applications/interchain_accounts/controller/v1/tx.proto#L30)
- [`owner` in `MsgSendTx`](https://github.com/cosmos/ibc-go/blob/2ec9c7d745c3a763530a53cff9dc72eb09056fd4/proto/ibc/applications/interchain_accounts/controller/v1/tx.proto#L49)
- [`version` of `channel` in `MsgChannelOpenInit`](https://github.com/cosmos/ibc-go/blob/2ec9c7d745c3a763530a53cff9dc72eb09056fd4/proto/ibc/core/channel/v1/tx.proto#L68)
- [`version` of `channel` and `counterparty_version` in `MsgChannelOpenTry`](https://github.com/cosmos/ibc-go/blob/2ec9c7d745c3a763530a53cff9dc72eb09056fd4/proto/ibc/core/channel/v1/tx.proto#L92-L93)
- [`counterparty_version` in `MsgChannelOpenAck`](https://github.com/cosmos/ibc-go/blob/2ec9c7d745c3a763530a53cff9dc72eb09056fd4/proto/ibc/core/channel/v1/tx.proto#L117)
- [The string fields of `version` in `MsgConnectionOpenInit`](https://github.com/cosmos/ibc-go/blob/2ec9c7d745c3a763530a53cff9dc72eb09056fd4/proto/ibc/core/connection/v1/tx.proto#L44)
- [The string fields of `counterparty_versions` in `MsgConnectionOpenTry`](https://github.com/cosmos/ibc-go/blob/2ec9c7d745c3a763530a53cff9dc72eb09056fd4/proto/ibc/core/connection/v1/tx.proto#L66)
- [The string field of `version` in `MsgConnectionOpenAck`](https://github.com/cosmos/ibc-go/blob/2ec9c7d745c3a763530a53cff9dc72eb09056fd4/proto/ibc/core/connection/v1/tx.proto#L93)

**Comment by faddat** [comment]
Thank you!

**Comment by tac0turtle** [comment]
technically every module in existence may have this issue, it would be good to understand why longer length cause larger amounts of computation on certain fields over others. I dont think this is limited to ibc.

**Comment by faddat** [comment]
It is unfortunate that this was not addressed in a serious and rigorous manner when it was reported in October 2022.

Later, a chain-comber found the osmosis banana kings:

https://twitter.com/web3_analyst/status/1635687287962112000

Given that Amulet has released information about a related matter direct to the public on the cosmos hub forum, I will be releasing a set of targeted mitigations that cite this issue today at midnight Bali time, which is 4PM GMT. 

The mitigations are available in the p2p-storms channel, and feedback from all teams is welcome, but timeline cannot be extended beyond then due to amulet's release of related information against my explicit and direct wishes.

* https://forum.cosmos.network/t/amulet-security-advisory-for-cometbft-asa-2023-002/11604/14

@tac0turtle can you think of a rapid way to check modules for unbounded field length, or should the suggested mitigation be to instruct authors of modules to ensure that every field has a length limitation?

**Comment by tac0turtle** [comment]
almost all fields in existence, you would need check each by hand, but this doesnt answer the question at hand, why does this tx take a long time to confirm? is it the bech32 decoding? Can we get a test case in ibc for a single message type to test what is going on here before making a bunch of length checks. 

the fix overall is to reduce total block sizes, there is no need to have 10mb+ blocks. That would prevent the tweet issue. I havent seen the submitted report so dont know if a test case was added, if so can you point me to a gist i can run locally to test?

**Comment by faddat** [comment]
@tac0turtle can you check HackerOne?

https://twitter.com/ctrl_Felix/status/1714714816625934383?t=0TTLNJYmd07vt3G52Lj2Bg&s=19

Felix mentioned that he reported this -- even before contacting me.  I thought the order was the other way around though it doesn't really matter what the order is.  Issues slip by and that's bad.
