### ISSUE TITLE
Implement `migrateClient` function in `ClientState`

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#4861]
Based on feedback received on Ethan Frey's audit of 08-wasm, the `CheckSubsituteAndUpdateState` function of the `ClientState` interface is overloaded (updates the client state, the consensus state and its associated metadata) and error prone. We acknowledge this and see the benefit of splitting this API into 2 different functions. 

This issue addresses the implementation of the first function, one that would update only the client state. For the time being, the 02-client `ClientState` interface function is not modified and this new function may be implemented only in 08-wasm's own `ClientState` implementation and be used in its implementation of `CheckSubsituteAndUpdateState`.

Possible pseudo-code for the function:

```go
func (cs ClientState) migrateClient(store storetypes.KVStore, substituteClient exported.ClientState) error {
  substituteClientState, ok := substituteClient.(*ClientState)
  if !ok {
    return errorsmod.Wrapf(
      clienttypes.ErrInvalidClient,
      fmt.Sprintf("invalid substitute client state. expected type %T, got %T", &ClientState{}, substituteClient),
    )
  }

  // 08-wasm's implementation of Status will check that the code hash in substituteClientState
  // is in the allow list of code hashes 
  if status := substituteClientState.Status(ctx, substituteClientStore, cdc); status != exported.Active {
    return errorsmod.Wrapf(types.ErrClientNotActive, "cannot migrate to client with status %s", status)
  }

  payload := sudoMsg{
    MigrateClient: &migrateClientMsg{ // new payload message
      ClientState: substituteClientState,
    },
  }

  _, err := wasmCall[emptyResult](ctx, store, &cs, payload)
  return err
}
```

Contracts will need to implement the function to handle the `migrateClientMsg` message.

We also agreed that we could use the client recovery flow to migrate to a new contract, if needed (e.g. in the situation that a new contract needs to be deployed to fix a bug). However, as I am writing this I just realised that for this to work we need the light client with the existing contract to expire first (or make it not active somehow), since [we check in 02-client's `RecoverClient` that the subject client is not active](https://github.com/cosmos/ibc-go/blob/eb1892a4e7a490453fbc495f764ae0329c12fa0b/modules/core/02-client/keeper/client.go#L168-L170). For this reason I am adding the `needs discussion` label to discuss how to handle this.

**Comment by crodriguezvega** [comment]
Thinking about an alternative flow for migrating clients (i.e. a flow that is different to the client recovery flow).

### Context

In `x/wasm` [contract migration](https://github.com/CosmWasm/wasmd/blob/cd7837680b2368f3257dade4daf54127aebc71f3/x/wasm/keeper/keeper.go#L475) requires the contract to have an address, which is passed in the [`env` parameter](https://github.com/CosmWasm/wasmd/blob/cd7837680b2368f3257dade4daf54127aebc71f3/x/wasm/keeper/keeper.go#L467). In 08-wasm we currently do not have addresses for the light client contracts. In `x/wasm` the [contract address is generated during contract instantiation](https://github.com/CosmWasm/wasmd/blob/cd7837680b2368f3257dade4daf54127aebc71f3/x/wasm/keeper/keeper.go#L262)

In `x/wasm` there is [`MsgMigrateContract` with a field `contract`](https://github.com/CosmWasm/wasmd/blob/894076a25cb2ff5219486e3d3628a5dd982e7ac6/proto/cosmwasm/wasm/v1/tx.proto#L205-L218) that is the address of the contract that should be migrated. The `code_id` field references the new contract that migrates to. [`MsgInstantiateContract` has an `admin` field](https://github.com/CosmWasm/wasmd/blob/894076a25cb2ff5219486e3d3628a5dd982e7ac6/proto/cosmwasm/wasm/v1/tx.proto#L120) that specify who can perform migrations and this [is stored in the `ContractInfo` during contract instantiation](https://github.com/CosmWasm/wasmd/blob/894076a25cb2ff5219486e3d3628a5dd982e7ac6/x/wasm/keeper/keeper.go#L328).

During migration it [is checked that the caller (the signer of `MsgMigrateContract` can modify the contract](https://github.com/CosmWasm/wasmd/blob/894076a25cb2ff5219486e3d3628a5dd982e7ac6/x/wasm/keeper/keeper.go#L438) (it uses the [admin address stored in `ContractInto` during instantiation](https://github.com/CosmWasm/wasmd/blob/894076a25cb2ff5219486e3d3628a5dd982e7ac6/x/wasm/keeper/keeper.go#L328). In case of governance, the admin address does not matter, since the governance policy will allow migration if the signer is the governance module.

To execute the migration, [the `env` variable passed to `wasmVM.Migrate`](https://github.com/CosmWasm/wasmd/blob/894076a25cb2ff5219486e3d3628a5dd982e7ac6/x/wasm/keeper/keeper.go#L467) contains the address of the contract that should be migrated. In the call to `wasmVM.Migrate` the [code hash of the new contract](https://github.com/CosmWasm/wasmd/blob/894076a25cb2ff5219486e3d3628a5dd982e7ac6/x/wasm/keeper/keeper.go#L475) is also passed.

### Proposal

This proposal requires doing some changes in https://github.com/cosmos/ibc-go/pull/4292. Instead of only storing the code hash of the contracts that are uploaded, we go back to the initial design, where we had a key in the store of the form `code_hash/{code_hash}`, but instead of storing the byte code of the contract, we store the contract address that we generate. If we want to use the migrate feature of `wasmVM` we need to have an address for each contract that is uploaded. We could generate a contract address using the code hash and a similar trick as we do when we [generate the interchain account address](https://github.com/cosmos/ibc-go/blob/0d524eca07e0a99519356f1767c5c4c267a31779/modules/apps/27-interchain-accounts/types/account.go#L46). Then during `StoreCode` we generate the address and store it under the specified code hash (i.e. we have a mapping like `code_hash/{code_hash}` -> `{contract_address}`).  

During the `Initialize` call we already have access to 08-wasm store to check that the code hash of the contract that we are going to instantiate is part of the allow list (https://github.com/cosmos/ibc-go/pull/4292). We use the store to query the given code hash and get the contract address, and we use this contract address pass it to `wasmVM.Instantiate` in the `env` parameter.

`x/wasm` exposes contract addresses to the external world and implements a elaborate permission scheme for migration, but in 08-wasm we could keep it simple and:

- Do not use contract addresses outside of the module (i.e. addresses would only be known and used inside the module).
- Allow only governance to migrate a contract.

Then we could have a new message (e.g. `MsgMigrateContract`) and RPC endpoint (e.g. `MigrateContract`). `MsgMigrateContract` could have the following fields:

- The code hash of the contract that we will migrate from.
- The code hash of the contract we will migrate to.

Using the code hash of the contract we migrate from, we retrieve the contract address and can use it in the call to `wasmVM.Migrate`. If possible, it might be nice to determine in `MigrateContract` endpoint the client IDs that use the old code hash and change their client states to use the new code hash, but I am not sure how to achieve this. Alternatively, `MsgMigrateContract` could also include a list of client IDs that should be migrated and we could check that the client state of those do use the old code hash before migrating to the new one. I guess if a contract should be migrate to a new version, it would be nice to migrate all clients; I cannot see any situation where you would keep the client using the old contract, but maybe I am missing something.

#### Advantages

- We do not require modifications to 02-client to change the check that enforces subject clients to not be active if they are going to be recovered.

### Questions

- What happens to a contract when you migrate from it? Is it still usable? Can it still be instantiated?
- Is `wasmVM.Migrate` idempotent? In case we cannot/should not migrate all clients in one go and we need to migrate the clients specified in the message, then `wasmVM.Migrate` may be called multiple times, so it would be good to know if it is idempotent.

**Comment by srdtrk** [comment]
I'm in favour of using `wasmVM.Migrate`. Isn't it possible for us to use the clientID (ex `08-wasm-0`) as the contract address? We could also make this a more general thing (for example providing the clientID as contract address to the Env)

**Comment by crodriguezvega** [comment]
We discussed and decided to implement the new RPC endpoint for migrating the byte code of a contract (for which I will open a new issue). We will close this issue and use https://github.com/cosmos/ibc-go/issues/4862 for the implementation changes needed in `CheckSubstituteAndUpdateState`.
