### ISSUE TITLE
Check in `Status` that contract's code hash is in the allow list

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#4863]
In 08-wasm's implementation of [`ClientState`](https://github.com/cosmos/ibc-go/blob/bd8e2015a67d33d879833374c6638277c067499c/modules/light-clients/08-wasm/types/client_state.go#L63) we should check that the code hash in the client state is part of the allow list (i.e. the list of code hashes of contracts that have been uploaded via governance using `StoreCode`). This check is needed so that we make sure that we migrate to an allowed contract when using the client recovery flow.

**Comment by trinitys7** [comment]
hi @crodriguezvega could I work on this issue ?

**Comment by crodriguezvega** [comment]
@trinitys7 I think it's fine to pick up this issue. I will assign it to you. Thanks!

**Comment by trinitys7** [comment]
got it sir !
