### ISSUE TITLE
Make 08-wasm contract api types exported

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#4913]
## Summary

Consider making the `08-wasm` contract API types exported/public. 

## Problem Definition

The `08-wasm` module defines a number of structs used for encoding the contract payloads to JSON. 
It is not necessarily the types themselves but the serialized JSON bytes of these types which define the API, as contracts are not written natively in Go and rather in Rust. Contracts written in Rust will likely define their own types to which they unmarshal to or consume some common library. 

We currently need to export these types in [`export_test.go`](https://github.com/cosmos/ibc-go/blob/feat/wasm-clients/modules/light-clients/08-wasm/types/export_test.go) in order to expose them for testing. Note, that this is the reason the mock wasm engine implementation lives still within the `types` package. When implementing some test cases I stumbled upon this and would have expected for the mock wasm engine to live within the `08-wasm/testing` package. 

At the moment I am struggling to see the value in keeping these types unexported / private. If anyone can highlight some good points or concerns about making them exported we should discuss them here. I believe it was also pointed out that this API is final and can only be extended in future, which suggests further than there is little value in maintaining them as private structs.

## Proposal

Make the types defined in [`contract_api.go`](https://github.com/cosmos/ibc-go/blob/feat/wasm-clients/modules/light-clients/08-wasm/types/contract_api.go) public / exported symbols. With this we can then move the mock wasm engine implementation to the `testing` package and remove `export_test.go` and the overhead associated with this for testing. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by DimitrisJim** [comment]
I'd say the main reason I see is not requiring a major/minor bump any time we might make changes to the Go types. We might make some changes to go structs that don't affect contract API but do change 08-wasm's public API if that is exposed (i.e https://github.com/cosmos/ibc-go/pull/4909). 

I'd be more favorable if we make all their fields private, if possible.

**Comment by damiannolan** [comment]
Unfortunately I don't think we can make the fields private afaik, as `encoding/json` requires them to be public

**Comment by DimitrisJim** [comment]
Yea, that seems to be the case. You can create a dummy private struct that holds the exported fields and embed that as exported into the struct you want to marshal/unmarshal but that seems like an equally annoying workaround.

**Comment by DimitrisJim** [comment]
closed in #4927 another issue will be opened for moving mock engine into testing.
