### ISSUE TITLE
Use a contract address in every call to `wasmVM.Instantiate`

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#4928]
In order to be able to migrate contract instances we need to instantiate contracts with contract addresses.

### Context

In `x/wasm` [contract migration](https://github.com/CosmWasm/wasmd/blob/cd7837680b2368f3257dade4daf54127aebc71f3/x/wasm/keeper/keeper.go#L475) requires the contract to have an address, which is passed in the [`env` parameter](https://github.com/CosmWasm/wasmd/blob/cd7837680b2368f3257dade4daf54127aebc71f3/x/wasm/keeper/keeper.go#L467). In 08-wasm we currently do not have addresses for the light client contracts. In `x/wasm` the [contract address is generated during contract instantiation](https://github.com/CosmWasm/wasmd/blob/cd7837680b2368f3257dade4daf54127aebc71f3/x/wasm/keeper/keeper.go#L262), each contract instance gets its own contract address.

In `x/wasm` there is [`MsgMigrateContract` with a field `contract`](https://github.com/CosmWasm/wasmd/blob/894076a25cb2ff5219486e3d3628a5dd982e7ac6/proto/cosmwasm/wasm/v1/tx.proto#L205-L218) that is the address of the contract that should be migrated. The `code_id` field references the new contract that migrates to.

### Proposal

Investigate if we can use the client identifier as contract address (thanks @srdtrk for this suggestion). The 08-wasm module does not have knowledge of the client identifiers, so we need to investigate if we can retrieve it from the client-prefixed store that is passed to `Initialize`.

If we cannot use the client identifier as contract address, then we could generate a contract address using the code hash and a similar trick as we do when we [generate the interchain account address](https://github.com/cosmos/ibc-go/blob/0d524eca07e0a99519356f1767c5c4c267a31779/modules/apps/27-interchain-accounts/types/account.go#L46). In the `Initialize` function we also have access to the client store, so we could store the contract address under a `contracAddress` key. We need this for https://github.com/cosmos/ibc-go/issues/4925 so that we can retrieve the contract address in `MigrateContract`. 

Regardless of the contract address that we use, [it needs to be passed to `wasmVM.Instantiate` in the `env` parameter](https://github.com/CosmWasm/wasmd/blob/2eee755048f34295d581c44a56227cb932043367/x/wasm/types/types.go#L288).

**Comment by srdtrk** [comment]
Some initial thoughts after some research but before experimenting:
- It seems possible to retrieve the clientID from the prefixed store (will verify experimentally later)
- It is probably not necessary to pass the clientID or contractAddress to the env. Passing to env only allows the contract to know its own clientID. Regardless, I think we should pass it to env.
- I don't know why this issue only covers `wasmVM.Instantiate`. We should be able to pass whatever address we use to `Sudo`, and `Query` as well (in the env).

**Comment by crodriguezvega** [comment]
> I don't know why this issue only covers wasmVM.Instantiate. We should be able to pass whatever address we use to Sudo, and Query as well (in the env).

You're right! Should be used in the other calls as well. Do you mind to add that as well in your PR?

**Comment by srdtrk** [comment]
Already in my PR @crodriguezvega. The only issue I faced is having to use `reflect` to get the value of `prefix` since it is a private field. (I didn't find any public getters for it)

**Comment by colin-axner** [comment]
closed by #4939, many thanks @srdtrk
