### ISSUE TITLE
Add tests for wasmQuery/wasmCall in vm

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#4931]
Currently there's no dedicated tests for these functions. Using the mockVM these should be relatively straight-forward to add tests for.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
closed by #4934, thanks @DimitrisJim!! Wonderful addition :heart:
