### ISSUE TITLE
create mock var in wasm testing suite for mock client state bytes

### ISSUE THREAD

**Issue by charleenfei** [cosmos/ibc-go#4946]
I'd be happy to just use a `[]byte()` directly in the tests atm instead of adding a mock var (just in case we lose a bunch of places this could be reused). 

Maybe we could add one later and replace all mock `[]byte()` occurrences thereafter, or until the linter cries oceans once again 🥲 

Also fine if you wanna use this PR to replace all now, you'd just have to comb through all the tests to see, I definitely added `[]byte("client-state-data")` somewhere in verify membership tests

_Originally posted by @damiannolan in https://github.com/cosmos/ibc-go/pull/4919#discussion_r1371288825_

**Comment by crodriguezvega** [comment]
Closed by #4978.
