### ISSUE TITLE
Panic in `GetCodeHash` and `AddCodeHash`

### ISSUE THREAD

**Issue by srdtrk** [cosmos/ibc-go#4947]
## Summary of Issue

[GetCodeHash](https://github.com/cosmos/ibc-go/blob/e2522b2212f4656f05f4ae5a0fe408951d4bc31e/modules/light-clients/08-wasm/types/wasm.go#L22) and [AddCodeHash](https://github.com/cosmos/ibc-go/blob/e2522b2212f4656f05f4ae5a0fe408951d4bc31e/modules/light-clients/08-wasm/types/wasm.go#L33) functions panic upon incorrect serialization/deserialization. This may lead to chain halt as these functions are expected to run inside a governance proposal.

## Expected Behaviour

They return errors instead of panicking for added safety.

## Version

`feat/wasm-clients`
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closed by #4948
