### ISSUE TITLE
Use `collections.KeySet` from the SDK to store CodeHashes

### ISSUE THREAD

**Issue by srdtrk** [cosmos/ibc-go#4958]
## Summary

[`KeySet`](https://github.com/cosmos/cosmos-sdk/blob/e0d84b765c28399831df435b3207be445da2d6af/collections/README.md?plain=1#L330) provides a much more efficient storage implementation for our use case. It also comes with a stable API. 

## Problem Definition

Our current implementation [in here](https://github.com/cosmos/ibc-go/blob/6eb154c7624656f86d59ba3c4d005e41c553af9c/modules/light-clients/08-wasm/types/wasm.go#L13-L61). Stores the entire list of code hashes as one item. This means that we have to load the entire list in order to add an item or check if an item is in the list.

## Proposal

[Here is](https://github.com/srdtrk/linked-packets/blob/main/keeper/keeper.go#L27) an example of a working KeySet storage object I wrote. I'd need to investigate what is the best way to initialise it inside `types/` since we cannot move these storage objects to keeper because it'd create a circular dependency.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closed by #4973.
