### ISSUE TITLE
Refactor Grandpa Test IBC Transfer to use suite.Transfer

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#4963]
## Summary

ref: #4959

Refactor the cli usage of ibc transfers in `TestMsgTransfer_Succeeds_GrandpaContract` to use `suite.Transfer(...)`

____

#### For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Same [reasoning](https://github.com/cosmos/ibc-go/issues/4964#issuecomment-2278148011).
