### ISSUE TITLE
Clean up denom specified in TestMsgTransfer_Succeeds_GrandpaContract

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#4964]
## Summary

ref: #4959

Currently the denom of `stake` is specified in this test. It appears as if this is an assumption made in [interchaintest](https://github.com/strangelove-ventures/interchaintest/blob/31c0cdb1a28f881b199a079badd9b118b19230a0/relayer/hyperspace/hyperspace_config.go#L132). When this is not the case, we can remove the code that specifies `Denom` and `GasPrices` as they will default to denoms configured in our tests.
____

#### For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Gonna close this one since we have disabled the grandpa tests and we are trying to replace them with wasm tendermint tests, so it's unlikely we will ever do this.
