### ISSUE TITLE
Fix TestScheduleIBCUpgrade_Succeeds on wasm branch

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#4966]
## Summary 

ref: https://github.com/cosmos/ibc-go/pull/4959#issuecomment-1781377717

It looks like the E2E changes somehow did break the test in question.

I checked out main, and ran the same test and it passes, but it fails on the feature branch in [this](https://github.com/cosmos/ibc-go/blob/1d31c7376d7c0ad3fedf768090ad188ed0018316/e2e/testsuite/tx.go#L171-L177) condition.

____

#### For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
Assigned this to myself, but if someone wants to tackle this before next Tuesday feel free to re-assign! Otherwise I'll grab it when I'm back.

**Comment by DimitrisJim** [comment]
closed in #4997
