### ISSUE TITLE
amino json for other transaction types?

### ISSUE THREAD

**Issue by tomtau** [cosmos/ibc-go#502]
## Summary
Right now, only ibc transfer is supported, but other IBC transaction types are not.

## Problem Definition

The only viable use case is to be able to sign IBC messages using the existing Ledger app in the context of solo machines.

## Proposal

Register all IBC message types for amino? But given the use case is quite niche, not sure if worth it?

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
IBC core message types were intentionally not registered for amino. The primary reason being that core IBC messages are for relaying purposes which in almost all cases require non-interactive signing thus making ledger support unnecessary. Until the ledger supports textual proto signing, I'd expect all IBC applications to register their associated messages with amino (this is true in ibc-go as we only have the transfer application)

**Comment by tomtau** [comment]
In solo machines, I assume signing core IBC messages can be interactive -- but as mentioned, it may be a niche use case, hence closing this issue
