### ISSUE TITLE
Call `Pin` during app inisitalization 

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#5073]
Feedback from Simon's peer review:

Pin needs to be called on every start. See https://github.com/CosmWasm/wasmd/blob/v0.44.0/app/app.go#L808 for the wasmd equivalent

Can be done after feature branch is merged.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by vuong177** [comment]
@DimitrisJim could I work on this issue ?

**Comment by damiannolan** [comment]
Hi @vuong177, are you still planning to PR this issue? I believe the feature branch has been merged

**Comment by vuong177** [comment]
@damiannolan yes I'm working on this. I'll make a PR soon !
