### ISSUE TITLE
Replace occurences of codeHash, code_hash with checkSum

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#5074]
Feedback from Simon's peer review:

Consistently rename code_hash -> checksum. Those are two terms for the same thing, which is confusing. cosmwasm-vm/wasmvm uses “checksum” everywhere.

We might want to use a different name for the hex encoded checksums returned by the `QueryCodeHashesRequest` and the one supplied to `QueryCodeRequest`. `checkSumHex` is an unimaginative first stab at it.

Can be done after feature branch is merged.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
This can be closed?
