### ISSUE TITLE
Check response in Instantiate and Migrate from wasm VM calls.

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#5097]
In the same vein that we do for sudo. We need to ensure that only data can flow back from the contract, not messages, events, attributes.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closed by #5101
