### ISSUE TITLE
Add check if codeHash has been stored in Status call.

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#5098]
As we do for `Initialize`, this should check if the code hash is stored in the store and if not return `Unauthorized` (review might think of a better return for this).

Tests should be added for this.

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closed by #5102.
