### ISSUE TITLE
Build wasm simd image for E2Es run on forks 

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#5124]
## Summary

We need to update the e2e-fork.yml workflow to pass the correct image for the grandpa tests. Currently in our tests, we are hard coding an [image](https://github.com/cosmos/ibc-go/blob/0bee18ba317c38992f7f4e4f37e84e97bbe0359d/e2e/tests/wasm/grandpa_test.go#L49).

This means the local image that is built on forks does not exist. We need to ensure we build the wasm image as well as the regular simd on forks.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by anhductn2001** [comment]
Can I take this issue

**Comment by crodriguezvega** [comment]
Sure you can, @anhductn2001! Thank you and let us know if you have any questions!

**Comment by anhductn2001** [comment]
Hey @chatton, I see GrandpaTestSuite has been exclusioned in [e2e-fork.yml ](https://github.com/cosmos/ibc-go/blob/a9cf9d2211b4275283608c4e80f93fc755b6bfc0/.github/workflows/e2e-fork.yml#L27)

**Comment by chatton** [comment]
@anhductn2001, ah right this is annoying. At the moment we have a separate workflow that runs on PRs that only runs wasm tests [here](https://github.com/cosmos/ibc-go/blob/f177b2111836d28787dd4f1201e6531d883c07bf/.github/workflows/e2e-wasm.yaml) however this method won't work on forks since it builds and pushes images to the ghcr registry (these credentials aren't included when there are PRs for forks. )

We might want to update the fork workflow to do a similar thing for wasm. I can try and do this now to unblock you!

**Comment by chatton** [comment]
@anhductn2001 sorry I didn't actually notice that the purpose of this issue was to build wasm images on forks, I was thinking it something that required the images being built on forks to proceed! I opened [this pr](https://github.com/cosmos/ibc-go/pull/5234) which should hopefully resolve the issue. I didn't mean to stand on your toes with this one!

**Comment by anhductn2001** [comment]
Ah no problem, hope your PR will solve it, thank you @chatton
