### ISSUE TITLE
Use `StoreCodeUnchecked` instead of `StoreCode` in snapshotter/init genesis.

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#5155]
This was brought up by @alpe on slack a while back:

> yes, use `StoreCodeUnchecked` for genesis import/ state sync. This will ensure that the files are restored whatever the current constraints for new files are

Should amend snapshotter's `restore` and `InitGenesis` to do this.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by GNaD13** [comment]
Hi @DimitrisJim, can I take this issue?
