### ISSUE TITLE
Panic in `WriteErrorReceipt` instead of returning an error

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#5207]
Panic in WriteErrorReceipt [instead of returning an error](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/04-channel/keeper/upgrade.go#L932), which is ignored.

**Comment by hieuvubk** [comment]
I will take this one, thanks @crodriguezvega
