### ISSUE TITLE
Pass the upgrade version returned by `OnChanUpgradeInit` to `WriteUpgradeInitChannel` instead of updating `upgrade.Fields.Version` in the message server.

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#5208]
Pass the upgrade version returned by `OnChanUpgradeInit` to `WriteUpgradeInitChannel` instead of [updating `upgrade.Fields.Version`](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/keeper/msg_server.go#L775) in the message server.

**Comment by hieuvubk** [comment]
I will work with this. Thank u
