### ISSUE TITLE
Remove `latestPacketSend` from `NewUpgrade` constructor

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#5209]
Remove latestPacketSend from [NewUpgrade constructor](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/04-channel/types/upgrade.go#L15).

**Comment by ThanhNhann** [comment]
Can I do this @DimitrisJim ?

**Comment by ThanhNhann** [comment]
Oh sorry for being late :)) I didn't see you assigned yourself
