### ISSUE TITLE
Emit an event when we move to `FLUSHCOMPLETE`

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#5215]
Emit an event when we move to `FLUSHCOMPLETE` [here](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/04-channel/keeper/timeout.go#L169) and [here](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/04-channel/keeper/packet.go#L495).

**Comment by sontrinh16** [comment]
@chatton hey can i work on this ?

**Comment by chatton** [comment]
of course @sontrinh16

**Comment by crodriguezvega** [comment]
Closed by #5245
