### ISSUE TITLE
In `ChanUpgradeTry` move fast forward sequence down below after the call to `ChanUpgradeInit`.

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#5218]
In `ChanUpgradeTry` move [fast forward sequence](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/04-channel/keeper/upgrade.go#L118-L122) down below after the call to `ChanUpgradeInit`.

**Comment by ThanhNhann** [comment]
plz assign me this ser @chatton

**Comment by colin-axner** [comment]
closed by #5231
