### ISSUE TITLE
Change so that if the counterparty upgrade is found then we execute the code below

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#5225]
Change [this condition](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/04-channel/keeper/timeout.go#L156) so that if the counterparty upgrade is found then we execute the code below, otherwise we just continue instead of returning an error.

**Comment by GNaD13** [comment]
Hi sir @chatton, can I take this issue?

**Comment by chatton** [comment]
Thanks @GNaD13 !

**Comment by crodriguezvega** [comment]
@GNaD13 you're right!

Closed by #5238
