### ISSUE TITLE
Emit an event when we move to `FLUSHCOMPLETE` 

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#5228]
Emit an event when we move to `FLUSHCOMPLETE` [here](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/04-channel/keeper/timeout.go#L169) and [here](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/04-channel/keeper/packet.go#L495).

**Comment by GNaD13** [comment]
I think this issue is duplicate with #5215

**Comment by chatton** [comment]
you are correct @GNaD13 thanks!
