### ISSUE TITLE
add check to make sure upgrade sequences of both channel ends are in sync after `ChanUpgradeTry` succeeds

### ISSUE THREAD

**Issue by charleenfei** [cosmos/ibc-go#5299]
we are missing a check to make sure that the upgrade sequences of both channel ends are in sync after `ChannelUpgradeTry` succeeds. If you add after [this line](https://github.com/cosmos/ibc-go/blob/63d7fc1eaec82c2af6f8ee4654abb0b5206d8f7f/modules/core/04-channel/keeper/upgrade_test.go#L304) a check like this `suite.Require().Equal(path.EndpointA.GetChannel().UpgradeSequence, path.EndpointB.GetChannel().UpgradeSequence)` you will see that [this test](https://github.com/cosmos/ibc-go/blob/63d7fc1eaec82c2af6f8ee4654abb0b5206d8f7f/modules/core/04-channel/keeper/upgrade_test.go#L170) will fail.

_Originally posted by @crodriguezvega in https://github.com/cosmos/ibc-go/pull/5231#discussion_r1412889148_

**Comment by damiannolan** [comment]
is this issue necessary? should this not be addressed in the open PR?

**Comment by charleenfei** [comment]
sure, I can just try to wrap up that PR!

**Comment by colin-axner** [comment]
closed by #5231
