### ISSUE TITLE
Implement ADR 25: IBC Passive Channels

### ISSUE THREAD

**Issue by fedekunze** [cosmos/ibc-go#53]
Implement [ADR 025 - IBC passive Channels](https://github.com/cosmos/cosmos-sdk/blob/master/docs/architecture/adr-025-ibc-passive-channels.md)
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ethanfrey** [comment]
This may be obsolete now. I managed to get all this functionality (passively watching all channels on a given connection) simply by adding a packetConnection attribute to sendpackets and acknowledgement events: https://github.com/cosmos/cosmos-sdk/pull/8458

This is enough for our ts-relayer to handle two channels

**Comment by colin-axner** [comment]
Closing since I believe the desired features are already supported. Please let me know if I am incorrect in this assumption
