### ISSUE TITLE
E2E: add `08-wasm` into allowed clients at genesis

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#5311]
Could we just hardcode `08-wasm` into allowed clients at genesis? I feel like there's already a many proposals run in these tests. Each one uses a store code proposal, and the client expiry/recovery test uses both store code and recover client props.

_Originally posted by @damiannolan in https://github.com/cosmos/ibc-go/pull/5306#discussion_r1415185674_

**Comment by crodriguezvega** [comment]
Closing because this will not be needed once https://github.com/cosmos/ibc-go/issues/5316 is completed.
