### ISSUE TITLE
Authority cancelling upgrade can lead to accidental resets of the upgrade sequence

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#5340]
## Summary

If the authority cancels the upgrade, they are not required to specify an error receipt which is proved, yet we [use](https://github.com/cosmos/ibc-go/blob/04-channel-upgrades/modules/core/keeper/msg_server.go#L1033) that error receipt when updating the [upgrade sequence](https://github.com/cosmos/ibc-go/blob/04-channel-upgrades/modules/core/04-channel/keeper/upgrade.go#L632C53-L632C75). The authority might do a valid cancellation and accidentally reset their upgrade sequence to 0. 

Maybe `ChanUpgradeCancel` should return the upgrade sequence to update to:
- channel.UpgradeSequence if authority cancels without proof
- errorreceipt.UpgradeSequence if error receipt is proved

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
update docs written in #5274 when fixing this issue

**Comment by charleenfei** [comment]
nice catch @colin-axner!
