### ISSUE TITLE
Duplicate error creation in core msg server handlers for error logging and returns

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#5378]
## Summary

Raised in https://github.com/cosmos/ibc-go/pull/5375, see https://github.com/cosmos/ibc-go/pull/5375#discussion_r1423008401
Errors created and used for the logger and duplicated/recreated for the return statement.

This is present across many of the handlers in `core/keeper/msg_server.go`. We should create an error: `err`, and reuse it for both the logger and the return where possible.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by vishal-kanna** [comment]
Can i work on this issue?

**Comment by damiannolan** [comment]
Hey @vishal-kanna, sure! I've assigned you

**Comment by vishal-kanna** [comment]
@damiannolan  I made some changes and raised the PR.If it looks good ,I'll continue it.
Is there any other changes other than that
