### ISSUE TITLE
deps: update tendermint to v0.35

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#539]
## Summary

Tendermint has released [v0.35](https://github.com/tendermint/tendermint/releases/tag/v0.35.0). I did a quick check and seems like it introduces some code breaking changes in ibc-go. Maybe we can wait for SDK to release a version that also upgrades Tendermint to v0.35 before we upgrade. 

Tendermint v0.35 has breaking changes for hermes, so we need to align with them when we do this.

cc: @adizere

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by adizere** [comment]
Thank you for the heads-up Carlos, appreciate that!

For completeness, on the Hermes side there are (at least) two specific points we want to address wrt upgrading to tm-go 0.35:
- https://github.com/informalsystems/ibc-rs/issues/1560
- a new [mempool_error](https://github.com/tendermint/tendermint/blob/97a3e44e0724f2017079ce24d36433f03124c09e/proto/tendermint/abci/types.proto#L202) field in `ResponseCheckTx` that affects Hermes behavior and we therefore need to parse and interpret that field.

**Comment by crodriguezvega** [comment]
Since SDK 0.46 will be released with Tendermint 0.34, I am putting this issue on hold for now back in the backlog. We will pick it up again when SDK team plans to release a version with Tendermint 0.35.

**Comment by crodriguezvega** [comment]
Closing this since Tendermint 0.35 has been [discontinued](https://interchain-io.medium.com/discontinuing-tendermint-v0-35-a-postmortem-on-the-new-networking-layer-3696c811dabc).
