### ISSUE TITLE
Remove call to `SetUpgradeErrorReceipt` from `restoreChannel`.

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#5399]
Remove call to `SetUpgradeErrorReceipt` from `restoreChannel`.

This feels like a side effect, and might be cleaner to call separately afterwards.

_Originally posted by @damiannolan in https://github.com/cosmos/ibc-go/pull/5237#discussion_r1417154224_

**Comment by vishal-kanna** [comment]
@chatton  Can i work on this issue?

**Comment by chatton** [comment]
sure @vishal-kanna, this one should be going into the `04-channel-upgrades` feature branch, thanks!

**Comment by vishal-kanna** [comment]
@chatton  Is it removing the SetUpgradeErrorReceipt from restoreChannel .
Do we need to add it anywhere else?

**Comment by chatton** [comment]
@vishal-kanna yeah we'll need to add it everywhere that restore channel is currently being called to ensure the behaviour is the same. It looks like that is 

1. [here](https://github.com/cosmos/ibc-go/blob/0323942d0f3b570b39750e7076de4e41249f8f04/modules/core/04-channel/keeper/upgrade.go#L632)
2. [here](https://github.com/cosmos/ibc-go/blob/0323942d0f3b570b39750e7076de4e41249f8f04/modules/core/04-channel/keeper/upgrade.go#L750)
3. And [here](https://github.com/cosmos/ibc-go/blob/0323942d0f3b570b39750e7076de4e41249f8f04/modules/core/04-channel/keeper/upgrade.go#L926)

There may be some tests that fail after you move these things, I can help out with the refactors of the tests if you run into this issue!
