### ISSUE TITLE
Update to typed IBC events

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#54]
## Summary
see [comment](https://github.com/cosmos/cosmos-sdk/pull/6798#discussion_r458139752). 

This would ideally happen in all of the ibc module as well as the ibc-transfer module. Documentation would need to be added to the relayer guide to give example interaction with consuming the events

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by crodriguezvega** [comment]
Looking at the Akash codebase (as mentioned in the comment linked in the description), looks like for each event we would have a type and the event would have an attribute where all the fields of the type are JSON-encoded (see example [here](https://github.com/akash-network/akash-api/blob/d05c262a17178a33e3e5383dcceea384d6260a17/go/node/deployment/v1beta3/event.go#L26-L55)). Do we still consider this as something we would do in the future?

**Comment by colin-axner** [comment]
Personally I think we should close this issue. There hasn't been any activity on this issue nor requests to complete it, which makes me believe the events we have now work just fine

**Comment by crodriguezvega** [comment]
> Personally I think we should close this issue. There hasn't been any activity on this issue nor requests to complete it, which makes me believe the events we have now work just fine

Agree!
