### ISSUE TITLE
The new client is suddenly replaced by the old client

### ISSUE THREAD

**Issue by 99Kies** [cosmos/ibc-go#5425]
My `07-tendermint-0` has expired, so I replaced `07-tendermin-0` with `07-tendermint-11` via governance some time ago, but today, after upgrading hermes to 1.7.3 and rebooting, `07-tendermin-11` was not detected on startup. why is this?

[Reviving an IBC Client with Governance — Hermes Relayer](https://medium.com/simplystaking/reviving-an-ibc-client-with-governance-hermes-relayer-362a1da4814d)

**client status:**
```
➜  ~ hermes query client status --chain vota-ash --client 07-tendermint-11
2023-12-15T07:25:28.213218Z  INFO ThreadId(01) using default configuration from '/home/ubuntu/.hermes/config.toml'
2023-12-15T07:25:28.213998Z  INFO ThreadId(01) running Hermes v1.7.3
SUCCESS Active
➜  ~ hermes query client status --chain vota-ash --client 07-tendermint-0
2023-12-15T07:25:36.839591Z  INFO ThreadId(01) using default configuration from '/home/ubuntu/.hermes/config.toml'
2023-12-15T07:25:36.840393Z  INFO ThreadId(01) running Hermes v1.7.3
SUCCESS Expired
```

and `ClientUpdateProposal(07-tendermint-0, 07-tendcermint-11)` is already passed.

![image](https://github.com/cosmos/ibc-go/assets/45918704/1a576624-924c-4019-b957-cc9ab4751b8e)

> I tried the ibc transfer at the end of the poll and that would have really solved the problem. But today it suddenly went back to 07-tendermint-0, which caused my ibc transfer to fail.

----

but now, my client still is `07-tendermint-0`.

**hermes logs:**
```
2023-12-15T07:16:44.382629Z  INFO ThreadId(01) scanned chains:
2023-12-15T07:16:44.382647Z  INFO ThreadId(01) # Chain: vota-ash
  - Client: 07-tendermint-0
    * Connection: connection-1
      | State: OPEN
      | Counterparty state: OPEN
      + Channel: channel-0
        | Port: transfer
        | State: OPEN
        | Counterparty: channel-2694
# Chain: osmosis-1
  - Client: 07-tendermint-2959
    * Connection: connection-2454
      | State: OPEN
      | Counterparty state: OPEN
      + Channel: channel-2694
        | Port: transfer
        | State: OPEN
        | Counterparty: channel-0
...
...
2023-12-15T07:16:45.160549Z ERROR ThreadId(01) spawn:chain{chain=vota-ash}:client{client=07-tendermint-0}:connection{connection=connection-1}:channel{channel=channel-0}:foreign_client.validated_client_state{client=osmosis-1->vota-ash:07-tendermint-0}: client state is not valid: latest height is outside of trusting period! latest_height=1-12572400 network_timestmap=2023-12-15T07:16:23.458077841Z consensus_state_timestamp=2023-11-30T16:09:47.18390436Z elapsed=1263996.274173481s
2023-12-15T07:16:45.160604Z  WARN ThreadId(01) spawn:chain{chain=vota-ash}:client{client=07-tendermint-0}:connection{connection=connection-1}:channel{channel=channel-0}: skipping refresh client task on frozen client client=07-tendermint-0
```

**Comment by 99Kies** [comment]
https://github.com/cosmos/chain-registry/blob/master/_IBC/doravota-osmosis.json#L5

Is it because I updated the new client and I need to replace the client here?

**Comment by srdtrk** [comment]
chain registry shouldn't effect on chain logic. Could it be one of these two things?
1. The node you are using is out of sync
2. You've tried to change parameters that you're not allowed to change in recovery proposal. Which means [this check](https://github.com/cosmos/ibc-go/blob/d0cf5b64dc8756206dad6c922e3530535ab78b79/modules/light-clients/07-tendermint/proposal_handle.go#L84-L103) has failed between the two clients and that means gov proposal never succeeded even if it passed.

**Comment by 99Kies** [comment]
> chain registry shouldn't effect on chain logic. Could it be one of these two things?
> 
> 1. The node you are using is out of sync
> 2. You've tried to change parameters that you're not allowed to change in recovery proposal. Which means [this check](https://github.com/cosmos/ibc-go/blob/d0cf5b64dc8756206dad6c922e3530535ab78b79/modules/light-clients/07-tendermint/proposal_handle.go#L84-L103) has failed between the two clients and that means gov proposal never succeeded even if it passed.

![image](https://github.com/cosmos/ibc-go/assets/45918704/a0666cff-9574-4af9-9c2a-fa83884cca50)
It's weird because after the propsoal went through, I actually made an ibc transfer and the ibc transfer was successful at that point.
https://www.mintscan.io/osmosis/tx/891A59F56DD73FF9BE5A4D2C39E401AEFA3332243874234F10E75148C629C3E7?height=12640808
https://www.mintscan.io/osmosis/tx/138C6882E28CA2E9CCFF67E3D85C7D3B8AC044DBEC627C0B63836442D4F2989C?height=12555904

**Comment by 99Kies** [comment]
@srdtrk  and this: 
https://vota-explorer.dorafactory.org/doravota/tx/1A40BAEF4A2D4BB229F187AA465EE9AD4EEF95202557FB93458FF70F0A5446F1 

You can see that after the proposal was passed, it was indeed possible to make ibc transfers, but now it's suddenly invalid.

**Comment by srdtrk** [comment]
Then you might be right. Perhaps hermes wasn't relaying the update messages for `07-tendermint-0` because it was using chain registry. So it ended up expiring again.

**Comment by 99Kies** [comment]
@srdtrk  I'm not sure exactly what's going on, but I think you're right, "this won't be affected by the registry information"

the registry hasn't been updated, but it was able to do ibc transfers successfully before.(after ClientUpdateProposal passed)

**Comment by srdtrk** [comment]
Yes, I'll just summarise the most likely scenario so we are on the same page. I think there is some confusion. The governance proposal proposal doesn't replace `subjectClient` with `substituteClient`. Instead, at that the moment the proposal passes, the state of `substituteClient` (`07-tendermint-11`) is copied to the state of `subjectClient` (`07-tendermint-0`). After this point, `07-tendermint-0` should be updated regularly or it will become expired again.

For whatever reason, `07-tendermint-0` wasn't updated after the proposal passed so it became expired again. The most likely reason why subjectClient wasn't updated is the chain registry (but this is a relayer issue). Would it be ok if we closed this issue now? If you continue having these problems, you can try raising an issue in hermes repo?

**Comment by 99Kies** [comment]
@srdtrk Sorry, just for double check, after **ClientUpdateProposal(07-tendermint-0, 07-tendermint-11)** passed, I need to update the client state of `07-tendermint-0`, not `07-tendermint-11`?

**Comment by srdtrk** [comment]
Correct

**Comment by 99Kies** [comment]
Ok, I think that's why my channel is failing, I've actually been thinking that I'm replacing `07-tendermint-0` with `07-tendermint-11`, so I've been updating the client state of `07-tendermint-11`. (is there have any document about ibc-operator?)

**Comment by 99Kies** [comment]
Since I'm still Active with `07-tendermin-11`, I need to submit another **ClientUpdateProposal(`07-tendermint-0`, `07-tendermint-11`)**? Right? @srdtrk

**Comment by 99Kies** [comment]
![image](https://github.com/cosmos/ibc-go/assets/45918704/a8f7c218-0c24-4240-99d7-1261bbe13151)
![image](https://github.com/cosmos/ibc-go/assets/45918704/63c044a9-c678-437b-865a-d4d57905fbfa)

https://ibc.cosmos.network/architecture/adr-026-ibc-client-recovery-mechanisms
https://medium.com/simplystaking/reviving-an-ibc-client-with-governance-hermes-relayer-362a1da4814d

But why do these docs refer to `replace`? @srdtrk

**Comment by crodriguezvega** [comment]
> Since I'm still Active with `07-tendermin-11`, I need to submit another **ClientUpdateProposal(`07-tendermint-0`, `07-tendermint-11`)**? Right? @srdtrk

Yes, that's correct: you need a new proposal.

And sorry that it was not clear what was happening in the client recovery process. We could probably improve the wording in the documentation, but as @srdtrk mentioned this process simply copies the client state from one light client to the other, so basically you end up with two active light clients and then you need to keep updating the one you want to use to prevent that it expires.

**Comment by 99Kies** [comment]
> Ok, I think that's why my channel is failing, I've actually been thinking that I'm replacing `07-tendermint-0` with `07-tendermint-11`, so I've been updating the client state of `07-tendermint-11`. (is there have any document about ibc-operator?)

@crodriguezvega Thanks bro,and do you know where there is a more detailed maintenance document(IBC-Operator Document)? I think we need this.

**Comment by 99Kies** [comment]
> And sorry that it was not clear what was happening in the client recovery process. We could probably improve the wording in the documentation, but as @srdtrk mentioned this process simply copies the client state from one light client to the other, so basically you end up with two active light clients and then you need to keep updating the one you want to use to prevent that it expires.

Since the rpc I've been using is the rpc of the pured node, I set up a timed update client timed task after the previous clientUpdateProposal, but I've been assuming that I'd just update the new client (07-tendermint-11) and our channel usage isn't that great, which caused 07-tendermint-0 to never get updated in time, so it failed.

If I replace the timed update task with timed update 07-tendermint-0 I don't get this now.

**Comment by crodriguezvega** [comment]
>@crodriguezvega Thanks bro,and do you know where there is a more detailed maintenance document(IBC-Operator Document)? I think we need this.

No, unfortunately I don't know if there's such document. Maybe hermes team has something, you could check with them.

>If I replace the timed update task with the timed update 07-tendermint-0, I don't get this now.

🥳 Cool, then mystery solved and we can close the issue, right? :)

**Comment by 99Kies** [comment]
yes thanks. @crodriguezvega @srdtrk
