### ISSUE TITLE
Increase MaxMemoCharLength in ICA to a higher number than 256. 

### ISSUE THREAD

**Issue by puneet2019** [cosmos/ibc-go#5428]
## Summary

Increase MaxMemoCharLength in ICA packet data to match Transfer memo length. 

## Problem Definition

With coming of callbacks, memo in ICA Packet too can be used to trigger callbacks, and encoding of json might easily exceed the current limit of 256 chars

## Proposal
We should take into account the memos that Transfers are using in various routers, and apply it to ICA too. 1024 seems to be a good number

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Thanks for opening the issue, @puneet2019! This sounds good to me. Maybe we could even use the [same limit as the one we use for the memo field of transfer](https://github.com/cosmos/ibc-go/blob/a047fa531105d1bfafe484deb1d5a30f1a44371d/modules/apps/transfer/types/msgs.go#L17) (32768).

**Comment by chandiniv1** [comment]
@crodriguezvega can I work on this issue?

**Comment by puneet2019** [comment]
@crodriguezvega Ah! thanks, I could not find memo length var before, sounds good to me :) thank you! 
@chandiniv1 go ahead! reference this Issue to the PR
