### ISSUE TITLE
Allow `host_connection_id` in version metadata to be empty on ChanOpenInit

### ISSUE THREAD

**Issue by srdtrk** [cosmos/ibc-go#5437]
## Problem Definition

`host_connection_id` is not used by the controller. It is also very difficult for a controller contract to obtain the correct value for this parameter on ChanOpenInit (see https://github.com/cosmos/ibc-go/issues/3942).

## Proposal

We should allow this to be empty at `ChanOpenInit` and let the icahost fill in the value during version negotiation.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by GNaD13** [comment]
Hi @srdtrk, Can i take this issue?

**Comment by crodriguezvega** [comment]
> Hi @srdtrk, Can i take this issue?

Yes, thank you @GNaD13!
