### ISSUE TITLE
ics27(upgrades): Ensure upgrade parameters are checked explicitly in app callbacks

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#5462]
## Summary

- `OnChanUpgradeInit` function on keeper should verify that proposed version is valid (only encoding, tx type can change), the order is valid and connection hops are valid.
- `OnChanUpgradeAck` should ensure the version is valid doing the same checks as in `ChanUpgradeInit`. (can have common function they both call OR just make the checks explicit).
- Document what can be changed in upgrade and what cannot.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
Is this needed for host?

**Comment by crodriguezvega** [comment]
> Is this needed for host?

[I think so](https://github.com/cosmos/ibc-go/pull/5519)!

**Comment by crodriguezvega** [comment]
Closed by #5472 and #5519
