### ISSUE TITLE
Excercise panic cases in tests for UpgradeOpen/UpgradeRestore

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#5471]
Ref [review comment](https://github.com/cosmos/ibc-go/pull/5467#discussion_r1431928222):

> Suppose there will never an `expError` because the func can only panic in one case.
> 
> It should be possible to set some mock app or middleware as the app which doesn't implement the interface. Maybe could reuse something from #5406 with `expPanics`, where instead of using `nil` we use a mock that doesn't implement the interface:
> 
> ```
> if expPanics {
>     cbs = controller.NewIBCMiddleware(ibcmock.NewBlockUpgradeMiddleware(), suite.chainA.GetSimApp().ICAControllerKeeper)
> }
> ```
> 
> Happy to do it in a follow up if we go with the mock upgrade middleware

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by neitdung** [comment]
Hi sir @DimitrisJim, can I pick up this issue?
