### ISSUE TITLE
Rename `MsgPruneAcknowledgements`

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#5473]
Ideally something along the lines of `MsgPruneStalePacketState`? Can be done in #5444 if people prefer or afterwards with a quick PR.

**Comment by chandiniv1** [comment]
@DimitrisJim can I work on this issue?

**Comment by crodriguezvega** [comment]
Thank you for offering to work on this issue, @chandiniv1. We are a bit on a hurry to get the prune acknowledgement functionality in, so I am just going to do this my self now.

**Comment by crodriguezvega** [comment]
Done [here](https://github.com/cosmos/ibc-go/pull/5444/commits/089afaabec8d701d57e7ed59104c67c429b82519).
