### ISSUE TITLE
Testing improvements for `PruneAcknowledgements` rpc

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#5476]
## Summary

Testing improvements to `PruneAcknowledgements` suggested by @colin-axner in https://github.com/cosmos/ibc-go/pull/5444

- [ ] Add a test case where a middle sequence doesn't have an ack stored (because a timeout occurred) https://github.com/cosmos/ibc-go/pull/5444#discussion_r1434061102
- [ ] Add a test where limit is set higher (attempting to prune post upgrade packet sends) demonstrating that this is safe, and only packet sequences within range are deleted. https://github.com/cosmos/ibc-go/pull/5444#discussion_r1434056575
- [ ] nit: https://github.com/cosmos/ibc-go/pull/5444#discussion_r1434041409

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by ThanhNhann** [comment]
Can I handle this issue?
