### ISSUE TITLE
Remove `VerifyChannelUpgradeErrorAbsence` from 03-connection

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#5477]
Remove `VerifyChannelUpgradeErrorAbsence` from 03-connection. 

It's no longer required

_Originally posted by @damiannolan in https://github.com/cosmos/ibc-go/pull/1613#discussion_r1434157798_

**Comment by vishal-kanna** [comment]
@damiannolan  I would like to work on it

**Comment by crodriguezvega** [comment]
Sorry for the later reply, we've all been on holiday during the Christmas break. :)

Yes, I will assign it to you now. Thank you!
