### ISSUE TITLE
When a channel reopens the ordering and metadata must not change

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#5523]
Implement this pseudocode from the [spec](https://github.com/cosmos/ibc/blob/main/spec/app/ics-027-interchain-accounts/README.md#channel-lifecycle-management) in [`OnChanOpenInit` of the controller](https://github.com/cosmos/ibc-go/blob/fadf8f2b0ab184798d021d220d877e00c7634e26/modules/apps/27-interchain-accounts/controller/keeper/handshake.go#L24):

```typescript
// only open the channel if:
// - there is no active channel already set (with status OPEN)
// OR
// - there is already an active channel (with status CLOSED) AND
// the metadata matches exactly the existing metadata in the 
// version string of the active channel AND the ordering of the 
// new channel matches the ordering of the active channel.
activeChannelId, activeChannelFound = GetActiveChannelID(portId, connectionId)
if activeChannelFound {
  activeChannel = provableStore.get(channelPath(portId, activeChannelId))
  abortTransactionUnless(activeChannel.state === CLOSED)
  previousOrder = activeChannel.order
  abortTransactionUnless(previousOrder === order)
  previousMetadata = UnmarshalJSON(activeChannel.version)
  abortTransactionUnless(previousMetadata === metadata)
}
```

**Comment by ThanhNhann** [comment]
Can I handle this issue?

**Comment by crodriguezvega** [comment]
> Can I handle this issue? And I see the link you add with `OnChanOpenInit of the controller` maybe wrong

@ThanhNhann Thank you for the offer. The issues linked to #3996 are a bit time sensitive, since we want to include the whole feature in the release of v8.1 by the end of the month, so I think it will be better if we manage these internally. Thank you again!

**Comment by srdtrk** [comment]
Why are we enforcing this? I'd like to allow ordering (and even encoding) to change.

**Comment by crodriguezvega** [comment]
> Why do we want to enforce this? I'd like to allow ordering (and even encoding) to change.

Then you would be able to change ordering/encoding without the need to go through a channel upgrade. It sounds to me like a sneaky way of doing an upgrade because you remove the negotiation part with the counterparty. I know it is unlikely if the counterparty runs also ibc-go, but in a future world where the counterpart might run a different IBC implementation I guess it would be good to allow the counptarty also to have a saying in the change of the channel parameters, otherwise the controller is changing them unilaterally.

But I am fine to remove the restriction if @AdityaSripal agrees.

**Comment by crodriguezvega** [comment]
We agreed that for v8.1 we will implement this and we can find ways to relax the restriction afterwards.

**Comment by AdityaSripal** [comment]
Given this is a highly requested feature, seems weird to me to disable and then find a way to reenable later when a solution already exists. i'd prefer to change the spec in this case
