### ISSUE TITLE
Update ICA upgrade callbacks to remove ordering restriction

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#5524]
Remove the check in all the upgrade callbacks of both controller and host.

**Comment by GNaD13** [comment]
Hi @crodriguezvega , can I take this issue?

**Comment by crodriguezvega** [comment]
> Hi @crodriguezvega , can I take this issue?

Thank you, @GNaD13, but I think I prefer that the team picks up the issues linked to #3996, because we want to include this feature in v8.1 and we are a bit in time pressure. I hope you understand!
