### ISSUE TITLE
Clean up event testing functions 

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#5551]
Mostly in reference to the following chain of comments: https://github.com/cosmos/ibc-go/pull/5475#pullrequestreview-1809053253

`AssertEvents`  seems to currently be used in only one place (event testing for 29-fee). Elsewhere we're currently using `AssertEventsLegacy`. These should be consolidated and cleaned up, there should ideally be one way to check for event emission.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
I propose we use `AssertEvents` and remove `AssertEventsLegacy` (which has the added benefit of removing the complicated `EventsMap` type alias). `AssertEvents` also supports asserting an slice of events where multiple events are of the same type.

**Comment by vishal-kanna** [comment]
@crodriguezvega Can i work on it?

**Comment by crodriguezvega** [comment]
Hi @vishal-kanna, yes, thank you! Please branch off from main to avoid weird diffs in the PR. :)

**Comment by akaladarshi** [comment]
Hey @crodriguezvega is this task still open?

**Comment by crodriguezvega** [comment]
@akaladarshi Yes, I think this is still open, so would be great if you pick it up. I will assign it to you.
