### ISSUE TITLE
Check active channel is `CLOSED` when reopening an ICA channel

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#5580]
We should check [here](https://github.com/cosmos/ibc-go/blob/8624ecda3ccb8eb53c1763531ce74a97a459453f/modules/apps/27-interchain-accounts/controller/keeper/handshake.go#L75) that the channel is not closed instead, because it could be possible to reopen a channel that is going through an upgrade (in `FLUSHING` or `FLUSH_COMPLETE` state).

 > Thinking now if we should change this condition to `channel.State != channeltypes.CLOSED`... I am thinking of the following scenario: an ICA channel is going through a channel upgrade and the channel state is either `FLUSHING` or `FLUSH_COMPLETE`, and a relayer submits a `MsgChannelOpenInit` with the same metadata version as the channel going through the upgrade. With the current check the opening handshake would go through, right? I guess we should prevent that?
> If we need to change this, we can do it in a follow up PR.

_Originally posted by @crodriguezvega in https://github.com/cosmos/ibc-go/pull/5562#discussion_r1447835747_

**Comment by DimitrisJim** [comment]
done in #5601
