### ISSUE TITLE
Change Default ProofSpecs for SDK SMT change

### ISSUE THREAD

**Issue by AdityaSripal** [cosmos/ibc-go#559]
When the SDK SMT change comes in, we'll have to change our default proofspecs to reflect the new proofspecs for SDK chains.

This would involve changing the following line:
https://github.com/cosmos/ibc-go/blob/main/modules/core/23-commitment/types/merkle.go#L17

to `SMTSpec, TendermintSpec`

and then testing the combined SDK/IBC changes

**Comment by crodriguezvega** [comment]
@AdityaSripal I think at the moment hermes is using [these default proof specs](https://github.com/informalsystems/ibc-rs/blob/master/modules/src/core/ics23_commitment/specs.rs#L18) in the `MsgCreateClient` that creates the light client. With the upcoming `SMTSpec`, will the hermes relayer need to implement and use this new spec when creating the light client for a chain that supports `SMTSpec` and `TendermintSpec`?

**Comment by AdityaSripal** [comment]
We need to implement a query that is available on all chains so that relayers can simply query the chain to determine what proof specs to use for the client. cc: @colin-axner

**Comment by robert-zaremba** [comment]
Why there is a default proof spec? Shoudn't that be implied by the SDK / IBC config? Default sounds dangerous here - what if someone will forget to configure?

**Comment by crodriguezvega** [comment]
Thanks for the comment, @robert-zaremba. Yes, I guess you're right and it would be more flexible if ibc-go could dynamically figure out what proof specs to use. @AdityaSripal, any idea if this could be feasible?

**Comment by damiannolan** [comment]
can we close this? IIRC sdk do not plan to migrate away from iavl anytime soon?
