### ISSUE TITLE
Deprecate `ErrPacketTimeout` error

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#5600]
See following discussion https://github.com/cosmos/ibc-go/pull/5572#pullrequestreview-1813680436. Usages of `ErrPacketTimeout` have been replaced by `ErrTimeoutElapsed`.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by natebeauregard** [comment]
@DimitrisJim @crodriguezvega I can take a look at this!

**Comment by crodriguezvega** [comment]
> @DimitrisJim @crodriguezvega I can take a look at this!

Go for it, @natebeauregard. Thank you!

**Comment by natebeauregard** [comment]
For this PR should I remove the `ErrPacketTimeout` error entirely or just add a comment like `// Deprecated: ErrPacketTimeout is deprecated and will be removed in a future release. Please use ErrTimeoutElapsed instead.` above the error?

**Comment by DimitrisJim** [comment]
I'd go with deprecation @natebeauregard. We can check what the rest of the team thinks in the PR :smile:
