### ISSUE TITLE
re-enable logic sending transfer in ICA upgrade ordered -> unordered e2e

### ISSUE THREAD

**Issue by charleenfei** [cosmos/ibc-go#5628]
regarding [this commented out code](https://github.com/cosmos/ibc-go/pull/5616#discussion_r1453327006), pending stable relayer image

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closed by https://github.com/cosmos/ibc-go/pull/5756
