### ISSUE TITLE
[E2E] Add Upgrade Test to verify channel params migration

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#5641]
## Summary of Bug

Add an upgrade test which does the following

- Perform a software upgrade from v8.0.0 -> v8.1.0
- Perform a channel upgrade

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closed by https://github.com/cosmos/ibc-go/pull/5661
