### ISSUE TITLE
Bundle the transition to FLUSHCOMPLETE into a single function

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#5733]
## Summary

When transitioning to FLUSHCOMPLETE, two invariants MUST be true:
* the counterparty timeout has not elapsed
* there are no in-flight packets for our end to process

We have verified as the main branch stands today, the implementation is correct. To future proof maintenance, we can make this invariant easier to maintain by bundling these checks and state transitions into a single function. This may require some reworkings of the Ack and Confirm handlers as we currently check the timeout in the handler and perform the state transition in the write function

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
@hoangdv2429 Sorry for the late reply: yes, you can work on this one. Thank you!
