### ISSUE TITLE
protect against wrapped upgrade error leading to panic

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#5737]
## Summary

It is possible that `ChanUpgradeTry` could return a wrapped upgrade error which would be returned as true in `IsUpgradeError` but panic when being casted to an [`UpgradeError`](https://github.com/cosmos/ibc-go/blob/main/modules/core/keeper/msg_server.go#L818). This is not an immediate concern as we have verified this will never occur and even if this was changed, the tests should fail, but as a way to future proof maintenance, we may restructure the code slightly so we don't have the possibility to panic if we have been returned a wrapped upgrade error.  

_Discussed during our internal security audit_

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
Sure @hoangdv2429! Thanks for picking this up, I'll assign it to you.
