### ISSUE TITLE
Trim event emission on channel upgrades

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#5741]
## Summary

The upgrade fields only need to be emitted on INIT or anywhere the relayer needs the upgrade fields for the start of the next message. Outside of that, we may remove emitting the full upgrade on every handler. We can emit the channel upgrade sequence as a key on a particular upgrade attempt

_Discussed during our internal security audit for channel upgradability_

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by hoangdv2429** [comment]
Can I work on this sir @colin-axner ?

**Comment by colin-axner** [comment]
Hi @hoangdv2429, my apologies for the late reply! Feel free to take on the issue. You might need to take a closer look at the code to see which events attributes are necessary. Look at the `MsgChannelUpgrade` types to see what arguments are necessary for the next step in the channel upgrade process

cc @crodriguezvega

**Comment by crodriguezvega** [comment]
@hoangdv2429 sorry for the late reply. I talked to hermes team and we can remove the [connection hops, ordering and version attributes](https://github.com/cosmos/ibc-go/blob/6c8c50c5fdc0d7fd0f74ca9d463a0f04c0f0cddc/modules/core/04-channel/keeper/events.go#L283-L285) for `channel_upgrade_init`, `channel_upgrade_try`, `channel_upgrade_ack`, `channel_upgrade_open`, `channel_upgrade_timeout` and `channel_upgrade_cancelled`. I will assign you the issue; if you cannot work on it anymore, let me know and will un-assign.

**Comment by hoangdv2429** [comment]
Thank you sir, I'm still a bit busy right now. I'll tackle it at the end of this week.
