### ISSUE TITLE
Applying UNORDERED channel support for ICA on v7

### ISSUE THREAD

**Issue by jununifi** [cosmos/ibc-go#5789]
We've built an ICA application, and when one ICA tx has unexpected behavior on destination chain (e.g. panic), timeout happens even though IBC relayers are running.

We realized that IBC v8.1.0 has a feature to convert ICA channels from ORDERED channels to UNORDERED channels which will help several unexpected issues in state management for channel close and reopening a new channel.

Most of the live chains are on Cosmos SDK v0.47.x and IBC v7.x.x and IBC v8's only compatible with Cosmos SDK v0.50.x

This will be pretty helpful for us to have IBC v7 compatible version for this feature.

**Comment by crodriguezvega** [comment]
Hi @jununifi, we will discuss internally what is possible, but the reason why it was released only in v8 is because v8 contains API breaking changes that were needed for the feature. Unfortunately it would be quite difficult (if not impossible) and very time consuming to backport the feature to the v7 line, so we need to see if this is something we could accommodate.

**Comment by jununifi** [comment]
> Hi @jununifi, we will discuss internally what is possible, but the reason why it was released only in v8 is because v8 contains API breaking changes that were needed for the feature. Unfortunately it would be quite difficult (if not impossible) and very time consuming to backport the feature to the v7 line, so we need to see if this is something we could accommodate.

Okay

**Comment by crodriguezvega** [comment]
Hi @jununifi, we discussed internally and we are very reluctant to backport the feature to v7. It would require a significant amount of work for us to deal with API breaking changes and back porting it to SDK v0.47. This would impact significantly our next priority feature work. For those reasons, we think it's best that chains upgrade to ibc-go v8 to take advantage of the feature. I hope you understand. I will close therefore the issue for now.
