### ISSUE TITLE
Implement channel open application callbacks

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#5797]
The transfer channel handshake callbacks need to be modified to handle multiple versions.

implementation [here](https://github.com/cosmos/ibc-go/blob/0107475b51e644c5cb30a9e81545aad16035b858/modules/apps/transfer/ibc_module.go#L340-L389)

**Comment by crodriguezvega** [comment]
Closed by https://github.com/cosmos/ibc-go/pull/6175.
