### ISSUE TITLE
[ICS20-2]  Add conversion function to convert `FungibleTokenPacketData` into `FungibleTokenPacketDataV2`

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#5800]
A utility function which converts a `FungibleTokenPacketData` into a `FungibleTokenPacketDataV2` can be used to massively reduce noise in the diff, and makes ensuring backwards compatibility more streamlined.

See the implementation [here](https://github.com/cosmos/ibc-go/blob/ca83d455d6a1d0d54389bdb069e169e9dfd9a8dc/modules/apps/transfer/v2/transferv2.go#L10-L82)

**Comment by crodriguezvega** [comment]
Closed by https://github.com/cosmos/ibc-go/pull/6116
