### ISSUE TITLE
Remove 08-wasm globals

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#5833]
## Summary

Following merge of #5806 the globals within 08-wasm can be moved to the `LightClientModule` type. It should be all the types within [here](https://github.com/cosmos/ibc-go/blob/main/modules/light-clients/08-wasm/internal/ibcwasm/wasm.go)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closed by https://github.com/cosmos/ibc-go/pull/6103
