### ISSUE TITLE
Remove complex self introspection to obtain clientID

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#5834]
## Summary

Following merge of #5806, this [function](https://github.com/cosmos/ibc-go/blob/main/modules/light-clients/08-wasm/types/store.go#L287) will no longer be necessary as the clientID is passed in as an argument to all light client module functions

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closed by https://github.com/cosmos/ibc-go/pull/6103
