### ISSUE TITLE
Backport 08-wasm default accepted query list to v8 compatibility branch

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#5851]
- [x] Create new release branch for 08-wasm + ibc-go/v8 (v8.2.x)
- [ ] Upgrade to latest wasmvm version (in progress [here](https://github.com/cosmos/ibc-go/pull/5909))

> I added the `backport-to-v8.2.x` label to the PR, but I guess we also need to create a new release branch for 08-wasm that will depend on ibc-go v8.2 and backport to that branch the 08-wasm changes of the PR? Like `release/v0.2.x+ibc-go-v8.2.x-wasmvm-v2.0.x` (and then we can also upgrade to the latest wasmvm version)?

_Originally posted by @crodriguezvega in https://github.com/cosmos/ibc-go/issues/5821#issuecomment-1942769524_

**Comment by crodriguezvega** [comment]
Done in https://github.com/cosmos/ibc-go/pull/5868.
