### ISSUE TITLE
Test rollkit app ibc connection to cosmos sdk app with tm wasm clients (step 2)

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#5854]
## Summary

Requires https://github.com/cosmos/ibc-go/issues/5853

- [x] Create a rollkit app and counterparty cosmos-sdk app (ibc-go-wasm-simd should be fine)
    - https://github.com/chatton/gm-demo
- [x] Wire up wasm light client module and custom self client validation defined in #5853 
- [x] Deploy and test ibc connection using ibc transfer with rollkit app and ibc-go-wasm-simd 

NOTE: we can also swap out the ibc-go-simd app chain for something like celestia testnet, as was done for step 1 of integration work already.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chandiniv1** [comment]
@damiannolan we have tested the ibc connection between rollup chain(gm) and cosmos app chain(paloma) by taking avail and celestia as data availability layers. The ibc transfers got succeeded. But here I have a doubt like, If we do `ibc-transfer` from  `cosmos app chain` to `rollup chain`, It will be easy for the rollup chain to verify,that it will just look whether the block header is signed by 2/3 validators or not. But if we do `ibc-transfers` from `rollup chain` to `cosmos-app` chain, as currently rollkit is following pessimistic approach, it have neither fraud proofs nor validators (as only sequencer will execute blocks and post it), how does the `cosmos app chain` verifies the transaction?
![Screenshot from 2024-02-23 11-24-56](https://github.com/cosmos/ibc-go/assets/117723967/1ddf389d-9e87-414d-8db7-768ba0b4eebf)

**Comment by damiannolan** [comment]
Hey @chandiniv1, thanks for the question! Indeed, you are correct - rollkit blocks will be executed by a single centralised sequencer and requires a more complex architecture in order to verify correct of ibc packets.

This issue is essentially a stepping stone as part of the greater body of work feeding into this. 

Verification of updates to rollkit clients will need an additional step in order to prove blocks are posted to DA. This is where a concept known as conditional clients was introduced. We will also be looking into fraud proof windows etc as part of ongoing work. There is more context available on conditional clients and architecture for rollkit/celestia in these issues:
- https://github.com/cosmos/ibc-go/issues/5112
- https://github.com/cosmos/ibc-go/issues/5310
- https://github.com/cosmos/ibc-go/issues/5318 (draft PR open on ibc-go for initial impl)

**Comment by charleenfei** [comment]
finished

**Comment by damiannolan** [comment]
Will update step docs to this repo for playground for test setup: https://github.com/chatton/gm-demo/tree/master
