### ISSUE TITLE
Remove GetHeight from ClientMessage interface

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#594]
## Summary

Following implementation of #284, #285, and #286, GetHeight will no longer be necessary. This removal is necessary for the Wasm Light Client

Remove [`GetHeight`](https://github.com/cosmos/ibc-go/blob/main/modules/core/exported/client.go#L211) from the ~Header~ `ClientMessage` interface. Usage in 07-tendermint can use the casted header function (cast to 07-tendermint type and use the concrete function)

Should be done after no longer setting the consensus state in updates in 02-client

____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [x] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Relayer operators might need `consensusHeight` (see [comment](https://github.com/cosmos/ibc-go/pull/1208/files#r839691927))

**Comment by damiannolan** [comment]
Updated issue to reflect new interface naming 👍

**Comment by damiannolan** [comment]
After the [discussion](https://github.com/cosmos/ibc-go/pull/1208/files#r839691927) in #1208 linked above, the proposed solution moving forward is as follows:

- Remove the `GetHeight` interface method from `ClientMessage`.
- Return a list of heights `[]exported.Height` from the new `UpdateState` interface.
- Maintain the `consensus_height` event emitted from `02-client` client update handler, but mark as deprecated for future removal. For example, with tendermint lightclients this will simply be `heights[0]` following a successful update.
- Add an additional `consensus_heights` event, containing a list of updated heights. This provides flexibility for emitting multiple consensus heights from batched header updates.

**Comment by colin-axner** [comment]
closed! Great work @damiannolan
