### ISSUE TITLE
Implementing cross-chain transfer on the Cosmos SDK with IBC (Inter-Blockchain Communication) interoperability to connect with Ethereum Virtual Machine (EVM) smart contracts 

### ISSUE THREAD

**Issue by AHMEDSAIDEV** [cosmos/ibc-go#5947]
Please allow Implementing a complete cross-chain transfer system with IBC interoperability and EVM smart contract integrations

**Comment by crodriguezvega** [comment]
Thanks for the issue, we (and other teams in the ecosystem) are working on it! Take also a look at this: https://github.com/hyperledger-labs/yui-ibc-solidity.
