### ISSUE TITLE
Move client state testing to light client module entry points

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#6001]
## Summary

https://github.com/cosmos/ibc-go/pull/5806 introduced the light client module interface and its associated implementations within ibc-go.

We should migrate unit tests to use the entrypoints for methods on the light client module. This should increase code coverage.
This can be broken into separate PRs for each client module. Existing tests should be refactored to use the `expError error` pattern in favour of `expPass bool`

- [x] 06-solomachine #6038
- [ ] 07-tendermint #6074
- [x] 08-wasm #6052
- [ ] 09-localhost testing can be handled with https://github.com/cosmos/ibc-go/issues/5959 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
I am working on the 06-solomachine tests.
