### ISSUE TITLE
Move initialization of storeProvider to light client modules

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#6009]
Based on these two comments: https://github.com/cosmos/ibc-go/pull/5806#discussion_r1523474395 and https://github.com/cosmos/ibc-go/pull/5806#discussion_r1523478627. Opening to keep track as a point of discussion.

Will try to do a minor investigation pre v9 audit to see if something is stopping this change from occurring and will update issue.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by damiannolan** [comment]
Happy to discuss this, I do agree that its kind of weird to inject it via the interface method on `AddRoute`. It might just be cleaner to give it to client module on instantiation
