### ISSUE TITLE
Interchain build options not being propagated in E2E tests

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#6031]
## Summary

Currently, the call to [`ConfigureRelayer`](https://github.com/cosmos/ibc-go/blob/5358ee240dab1d79e292d0203959611e3a2321b7/e2e/testsuite/testsuite.go#L98) does not propagate options to [here](https://github.com/cosmos/ibc-go/blob/5358ee240dab1d79e292d0203959611e3a2321b7/e2e/testsuite/testsuite.go#L134-L136)

We need to decide the best way to pass configuration functions.

If we were to continue with the current structure, we would add a configuration fn which modifies `interchaintest.InterchainBuildOptions` to the `SetupChainsRelayerAndChannel` function, however this seems like it will bloat the method signature a bit too much. It may be nicer to consolidation all of these configration fns into a single type. Maybe something along the lines of:

```golang
type SetupOptions struct {
 ChannelOptions func(*ibc.CreateChannelOptions)
 BuildOptions func(options *interchaintest.InterchainBuildOptions)
 ChainSpecOptions ChainOptionConfiguration
}
```

This could easily be extended as required.

As a side note, it looks like this fn is very poorly named, it is not just configuring the relayer, it is configuring the relayer and also creating all the docker resources for the chains!

We can rename this / split up functionality in a follow up.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by bznein** [comment]
Hi @chatton, I'd like to get this assigned :)

**Comment by crodriguezvega** [comment]
@bznein If you continue at this pace, there's not going to be issues left for the rest of the team, man!

**Comment by chatton** [comment]
the structure of the tests has changed enough with the test suite level refactor that this issue isn't relevant anymore
