### ISSUE TITLE
Add support for dumping genesis files in E2Es

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#6032]
## Summary

Interchaintest currently supports dumping genesis files for debugging via two environment variables [here](https://github.com/strangelove-ventures/interchaintest/blob/7aa0fd6487f76238ab44231fdaebc34627bc5990/chain/cosmos/cosmos_chain.go#L1007-L1008)

In order to support this, I propose that we add two new fields to our [test config](https://github.com/cosmos/ibc-go/blob/40564ed01c2e059e7d12643c638b3cb854cdb178/e2e/testsuite/testconfig.go#L93) which will ultimately result in a  call to `os.SetEnv` before test execution in order to configure this environment variables.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by bznein** [comment]
@chatton I'd like to work on this one, since I haven't touched any e2e code so far :)

**Comment by chatton** [comment]
thank you @bznein! I hope you're a yaml fan :+1:
