### ISSUE TITLE
Mismatch of client type returned by `ClientState` and `ConsensusState` in `07-celestia` 

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#6061]
In the [PR that adds a light client module for `07-celestia`](https://github.com/cosmos/ibc-go/pull/6053) we have temporarily disabled [this check](https://github.com/cosmos/ibc-go/blob/1323a733d5b0d83478f1362ebc64cb1e42fa8caa/modules/core/02-client/types/msgs.go#L77) in `ValidateBasic` of `MsgCreateClient` because for this light client we have a `ClientState` implementation that returns "07-celestia" when calling `ClientType`, but we use Tendermint's implementation of `ConsensusState`, whose `ClientType` function returns "07-tendermint".

Potential solutions discussed so far:
- Removing the check form `ValidateBasic`.
- Removing `ClientType` function from `ConsensusState` if not really needed, then we can remove the check in `ValidateBasic`. Light client modules should make sure that `ConsensusState` bytes unmarshal to the expected type.
- Adding a customs `ConsensusState` type to `07-celestia` that wraps Tendermint's `ConsensusState` (in a similar way as it is done with the `ClientState` type).

ref: https://github.com/cosmos/ibc-go/pull/6053#discussion_r1537187862

**Comment by damiannolan** [comment]
Discussed with @AdityaSripal and grepped the codebase. Should be possible to remove `ClientType()` from `ConsensusState` and the checks in `ValidateBasics`.

If any incompatible consensus state is passed to the target light client module retrieve from `clientState.ClientType()` then unmarshalling will fail

**Comment by crodriguezvega** [comment]
Closed by https://github.com/cosmos/ibc-go/pull/6137
