### ISSUE TITLE
Support `nolink_libwasmvm` build directives with next wasmvm release

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#6078]
Upgrade to next patch release of cosmwasm/wasmvm to pick up new build directives for `nolink_libwasmvm`.

See https://github.com/CosmWasm/wasmvm/pull/527

_Originally posted by @damiannolan in https://github.com/cosmos/ibc-go/issues/5923#issuecomment-2032290362_

**Comment by damiannolan** [comment]
v2.0.1 is now available https://github.com/CosmWasm/wasmvm/releases/tag/v2.0.1

**Comment by crodriguezvega** [comment]
Closed by https://github.com/cosmos/ibc-go/pull/6097.
