### ISSUE TITLE
Bump golangci-lint to latest version

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#6086]
Seems that running the linter (locally) with `1.57.2` leads to many new linting errors popping up, many seem to be due to not checking if a cast to a type is ok (`x := y.(type)`.

We should bump the golangci-lint version in our workflows and address issues it brings up. Until then, installing and using `1.54.2` locally should do the trick.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by bznein** [comment]
I don't mind taking this if nobody disagrees :) I was already running a newer version and got confused by some errors :)

**Comment by bznein** [comment]
I definitely underestimated the number of errors shown by the new version :D I'll still work on this, but it's going to take some time :)
