### ISSUE TITLE
Move additional solomachine client state method functionality to light client methods

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#6087]
This is a follow up to https://github.com/cosmos/ibc-go/issues/5974

The same rationale applies for a couple of other functions, [`GetTimestampAtHeight`](https://github.com/cosmos/ibc-go/blob/23ffdd5a8308856521de37805696ed7b65bc643e/modules/light-clients/06-solomachine/client_state.go#L36), [`Status`
](https://github.com/cosmos/ibc-go/blob/23ffdd5a8308856521de37805696ed7b65bc643e/modules/light-clients/06-solomachine/client_state.go#L49) and [`UpdateStateOnMisbehaviour`](https://github.com/cosmos/ibc-go/blob/23ffdd5a8308856521de37805696ed7b65bc643e/modules/light-clients/06-solomachine/update.go#L105) seem to be some very obvious ones.

Not entirely sure what the line we want to draw is for moving the functionality over (line size is definitely one). Ideally we could have a rule to guide this decision.
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
The functions mentioned in the issue can be moved to the light client module.
