### ISSUE TITLE
IBC denom with trailing slash fails packet validation

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#6124]
## Summary of Bug

Currently, an ibc denom of `transfer/channel-0/atom/` (trailing slash) fails packet validation [here](https://github.com/cosmos/ibc-go/blob/0e3f428e66d6fc0fc6b10d2f3c658aaa5000daf7/modules/apps/transfer/types/trace.go#L203). This is due to strings.Split leaving an empty string as the last item.

However `atom/` is a valid native token denom and passes validation in this function.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closed by https://github.com/cosmos/ibc-go/pull/6148
