### ISSUE TITLE
Remove Router from IBCKeeper and use PortKeeper

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#6133]
## Summary

We currently maintain a reference to the IBC application router on the `IBCKeeper` as well as the `PortKeeper` submodule keeper.
This is often referred to as the "port router" as this is how we look up application callback stacks in order to route application handshake msgs and packet data to the appropriate handlers.

With moving towards a more consistent usage of standardising submodule keepers as reference types (see https://github.com/cosmos/ibc-go/pull/6081) we should now be able to remove the `Router` reference from the `IBCKeeper` and instead rely directly on the one in `PortKeeper`.

With this change we can also probably make `Router` unexported within `PortKeeper` and add a `Route()` method on the `PortKeeper` instead, and all application callback stack access can flow through there.

- [ ] Remove `Router` from `IBCKeeper`
- [ ] Add `GetRoute() types.IBCModule` to `PortKeeper`
- [ ] Replace usage of `Router` in `core/keeper/msg_server.go` with `PortKeeper.Route()`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by bznein** [comment]
@damiannolan I wouldn't mind taking this one :)

**Comment by chatton** [comment]
go for it @bznein this one depends on #6081 to me merged first
