### ISSUE TITLE
Update `08-wasm` documentation and migration docs for v0.4.x

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#6139]
Documentation for `08-wasm` and migration docs for v0.4.x with ibc-go v9.0 should be updated/added with changes from https://github.com/cosmos/ibc-go/pull/6088, https://github.com/cosmos/ibc-go/pull/6164, https://github.com/cosmos/ibc-go/pull/6176, https://github.com/cosmos/ibc-go/pull/6177.

**Comment by crodriguezvega** [comment]
Document also the change of `Path` to `commitmenttypesv2.MerklePath` if we finally decide to make it ([ref](https://github.com/cosmos/ibc-go/pull/6644/files#diff-bd0618ba11fca65b87c57f68bf9cbba25ee07b82cc8bb56579744709a2e27d11)).

**Comment by damiannolan** [comment]
> Document also the change of `Path` to `commitmenttypesv2.MerklePath` if we finally decide to make it ([ref](https://github.com/cosmos/ibc-go/pull/6644/files#diff-bd0618ba11fca65b87c57f68bf9cbba25ee07b82cc8bb56579744709a2e27d11)).

We can use this as reference: https://github.com/cosmos/ibc-go/pull/6757
