### ISSUE TITLE
End to End tests for IBC upgrade client

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#62]
## Summary

During internal audit we noticed that message handling was missing from `handler.go`. This means it was not possible to successfully execute an upgrade message (since it wasn't being routed). We should add tests to ensure upgrade works from end to end. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by crodriguezvega** [comment]
Closing this in favor of https://github.com/cosmos/ibc-go/issues/2074.
