### ISSUE TITLE
Adding v3 for ICA on Gaia spits dependency issues with modules

### ISSUE THREAD

**Issue by schnetzlerjoe** [cosmos/ibc-go#622]
## Summary of Bug

I am trying to run my own Gaia test net with Interchain Account support to help in my efforts in building a Cosmos-SDK chain I am building that needs the use of ICA. When I try to upgrade Gaia ibc-go to v3 in app.go, I am getting dependency issues with modules (see errors below). I pushed a version of Gaia with my changes here https://github.com/schnetzlerjoe/gaia.

1. cannot use transferModule (variable of type transfer.AppModule) as "github.com/cosmos/ibc-go/v2/modules/core/05-port/types".IBCModule value in argument to router.NewAppModule: missing method NegotiateAppVersion
2. (this is stemming from 1) cannot use routerModule (variable of type router.AppModule) as "github.com/cosmos/ibc-go/v3/modules/core/05-port/types".IBCModule value in argument to ibcRouter.AddRoute: wrong type for method NegotiateAppVersion (have func(ctx github.com/cosmos/cosmos-sdk/types.Context, order github.com/cosmos/ibc-go/v2/modules/core/04-channel/types.Order, connectionID string, portID string, counterparty github.com/cosmos/ibc-go/v2/modules/core/04-channel/types.Counterparty, proposedVersion string) (string, error), want func(ctx github.com/cosmos/cosmos-sdk/types.Context, order github.com/cosmos/ibc-go/v3/modules/core/04-channel/types.Order, connectionID string, portID string, 

3. cannot use app.IBCKeeper.ChannelKeeper (variable of type "github.com/cosmos/ibc-go/v3/modules/core/04-channel/keeper".Keeper) as "github.com/cosmos/ibc-go/v2/modules/core/04-channel/keeper".Keeper value in struct literal

## Version

v2 -> v3

## Steps to Reproduce

1. git clone https://github.com/schnetzlerjoe/gaia
2. Either check app.go if you are on VSCode or IDE that will display errors or "cd gaia" then "make install"
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by schnetzlerjoe** [comment]
> Hello! Thanks for taking the initiative to test out interchain accounts!
> 
> I think this is because `app/ante_handler.go` is still using `github.com/cosmos/ibc-go/v2` and the `strangelove-ventures/packet-forward-middleware` is also using `github.com/cosmos/ibc-go/v2`
> 
> v2 and v3 cannot be imported simultaneously
> 
> Also note that ibc-go does not provide an authentication module for interchain accounts so you'd need one of those to execute controller chain functionality

Gotcha! I tried just importing v3 but was running into an issue with Gaia deps but that is prob easy fix changing dependencies. I will try that and close this if that works.

For the auth module, Gaia already has the auth module so I can just tie into that, right? (I saw that so I was planning on doing that).

**Comment by colin-axner** [comment]
> For the auth module, Gaia already has the auth module so I can just use that for Host. And then on my own chain use that auth module with interchain module. Right? (I saw that so I was planning on doing that).

The interchain accounts authentication module is different than x/auth (perhaps we should work on the naming here). For testing purposes, [inter-tx](https://github.com/cosmos/interchain-accounts) is the only interchain accounts authentication module I know of.

**Comment by colin-axner** [comment]
Hello! Is this still an issue @schnetzlerjoe?

**Comment by crodriguezvega** [comment]
For further examples of ICA authentication modules, the Cosmos Hub team has been working also a module called `x/mauth` in this [branch](https://github.com/cosmos/gaia/tree/ica-acct-auth) of gaia.

**Comment by schnetzlerjoe** [comment]
> Hello! Is this still an issue @schnetzlerjoe?

Nope! Figured it out. I will close
