### ISSUE TITLE
Improve the documentation for module safe queries

### ISSUE THREAD

**Issue by srdtrk** [cosmos/ibc-go#6234]
The documentation should include a list of all module safe queries included in the cosmos-sdk and ibc-go.

It should also give more context about how to use the feature if possible.

**Comment by crodriguezvega** [comment]
Not sure about adding an explicit list of all messages for SDK, wouldn't this be it of maintenance burden if we need to keep the list up to date? Wouldn't be enough to mention all SDK queries that have the module safe query option (and give one example)?

Regarding context, there is some [information about how to use the feature](https://github.com/cosmos/ibc-go/blob/main/docs/docs/02-apps/02-interchain-accounts/05-messages.md#queries), would this be enough?

**Comment by womensrights** [comment]
Speaking to possible users of the feature, I find the documentation insufficient. 

There is no definition of module safe queries - you have to go to sdk documentation to find it. There is no way to understand which queries are module safe - you would need to do elsewhere to find it. 

Users should be able to read the documentation and not have to go elsewhere to understand how to use the feature imo

**Comment by womensrights** [comment]
it is a terrible experience if you have to navigate between multiple different documentation sites to be able to onboard to a new feature - a high level description of what a module safe query is would be appropriate in ibc-go docs [which can link to the sdk's description](https://docs.cosmos.network/main/build/building-modules/query-services#calling-queries-from-the-state-machine)

**Comment by srdtrk** [comment]
1. Module safe queries are consensus breaking, and can only be changed between major versions of the sdk. Thus, it can only be changed in the major versions of ibc-go.
2. Generating the list is very simple since we can simply run the script that I'm running in the icahost keeper initialization and paste the result here.

**Comment by crodriguezvega** [comment]
> a high level description of what a module safe query is would be appropriate in ibc-go docs [which can link to the sdk's description](https://docs.cosmos.network/main/build/building-modules/query-services#calling-queries-from-the-state-machine)

Oh, yeah, this is great, I hadn't been able to find in their docs where they had this. Definitely we can link to this.

> Generating the list is very simple since we can simply run the script that I'm running in the icahost keeper initialization and paste the result here.

Yeah, I agree, but why wouldn't the SDK maintain this list instead of us? We can then just link to it.
