### ISSUE TITLE
Update e2e infrastructure to be able to spin up 3 or more chains

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#6242]
For e2e test path forwarding we will need at least 3 chains, so we should prepare our CI infrastructure to be able to cope with that.

**Comment by chatton** [comment]
As a starting point we would be able to create a new setup function, `SetupPathForwardingChainsAndRelayer` or similar. It would be largely a copy paste with some tweaks.

We could then make it a bit more generic in a follow up.
