### ISSUE TITLE
Fix grandpa e2e tests

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#6243]
The grandpa e2e tests have started to [fail](https://github.com/cosmos/ibc-go/actions/runs/8881282881/job/24383409000?pr=6239).

**Comment by damiannolan** [comment]
any idea when exactly this started failing? was it an upgrade to interchaintest?

**Comment by damiannolan** [comment]
I suspect removing the non-hex encoded event attributes in https://github.com/cosmos/ibc-go/pull/6023 has something to do with this. Assuming that this test users hyperspace relayer its possible that they do not use the encoded event attributes.

**Comment by crodriguezvega** [comment]
yay, nice find, @damiannolan! Thank you also for opening the issue in composable-ibc.

**Comment by navyxie** [comment]
look nice

**Comment by crodriguezvega** [comment]
Fixed by disabling them 😓 We will go with https://github.com/cosmos/ibc-go/issues/6835 instead.
