### ISSUE TITLE
E2E test intermittent failures due to account not found

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#6295]
## Summary of Bug

We see many intermittent failures in CI runs due to account not found errors.
For example:
```
rpc error: code = NotFound desc = account cosmos1mk5rsujrduevj9sz95rq0y5upws7fcmvw6aqgf not found
```

One possible option to explore is wrapping the calls to fund users in a `WaitForBlocks`. This might reduce the number of account not found errors we see in tests from subsequent calls. E.g. broadcast MsgRegisterInterchainAccount after acc created 

See code: https://github.com/cosmos/ibc-go/blob/main/e2e/testsuite/testsuite.go#L344-L353
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Is this maybe a duplicate of https://github.com/cosmos/ibc-go/issues/4751? If is, maybe we can add your issue description as a comment to it?

**Comment by damiannolan** [comment]
Yeah, looks like it. I'll rename the linked issue and close this one.
