### ISSUE TITLE
24-host should use regex to parse out identifiers in a key path

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#63]
## Summary

In `parse.go` in `24-host` we currently use `strings.Split` to parse out identifiers from a key used to store IBC data. We should refactor this to use regex to verify the format and parse out the identifiers needed. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by colin-axner** [comment]
I know I opened this issue, but I think I've grown to prefer strings.Split. I'm not sure what regex gains us in this respect as I find `strings.Split` to be quite readable

**Comment by crodriguezvega** [comment]
Closing now since we agreed after discussion that we will keep `strings.Split`.
