### ISSUE TITLE
Apply depinject for IBC modules 

### ISSUE THREAD

**Issue by QuocThi** [cosmos/ibc-go#6328]
Hi team,
I checked and see that currently IBC's modules still not apply depinject, so I'd like to know if you have any plan to apply this new cosmos feature?

Thanks!

**Comment by crodriguezvega** [comment]
Hi @QuocThi, the work to support depinject has been started. We have [this feature branch](https://github.com/cosmos/ibc-go/tree/feat/depinject) with depinject support added to the modules and [this WiP PR](https://github.com/cosmos/ibc-go/pull/6216) where we are adding app v2 wiring. We are facing some obstacles to complete this work and need some help/advice from the SDK team, but we should be able to release this in v9.

We are using [this other issue](https://github.com/cosmos/ibc-go/issues/3560) to track this work, so I will close this one now.
