### ISSUE TITLE
ibc-apps repo issues are not maintained

### ISSUE THREAD

**Issue by ysv** [cosmos/ibc-go#6336]
Hello Cosmos team

I'm not 100% sure if this is correct place to open this issue, but since ibc-apps was inside ibc-go initially I think it is ok.

In last few months I created 2 issues (https://github.com/cosmos/ibc-apps/issues/189 & https://github.com/cosmos/ibc-apps/issues/187) in ibc-apps repo and they are still pending for comments from core team.

Also I mentioned that most of issues inside https://github.com/cosmos/ibc-apps/issues repo are just ignored.

If possible would be nice to assign someone to be responsible for the repo maintenance

**Comment by crodriguezvega** [comment]
Hi @ysv. Thanks for raising your concerns. We are not the maintainers of those apps in the inc-apps repository (and they were not initially inside ibc-go, but in other repositories). I can contact the maintainers and ask then to take a look though. Is there anything blocking you from the issues that you opened? Having a quick look at the issues you shared, looks like they are questions or documentation related, right?
