### ISSUE TITLE
Combine functions `TestGetSourceCallbackDataTransfer` and `TestGetDestCallbackDataTransfer`

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#6358]
Encountered during #6354

These two functions in `types/callbacks.go` seem like they should be able to be compined into a single function that uses table tests.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
we can use the suggestions made in the comments of #6400

**Comment by lacsomot** [comment]
Hi. I made a PR for the issue. Can you review. TYSM
