### ISSUE TITLE
Consistent terminology for coin/token in transfer.

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#6379]
Opening this after https://github.com/cosmos/ibc-go/pull/6364 and https://github.com/cosmos/ibc-go/pull/6352#discussion_r1611958976

Would be nice to use consistent terminology for coins and the newly added `Token` type so as to not cause confusion when reviewing/changing things. There should be some places where these are used interchangeably (as the review comment pointed out). Some internal private functions could also be renamed to better align with these types.

Can probably be left for until v2 of ics20 is merged.
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Can we already consider this done?

**Comment by colin-axner** [comment]
thanks, was gonna get to this :+1:
