### ISSUE TITLE
wasm-light-client v8.3 and wasmvm 1.5

### ISSUE THREAD

**Issue by jhernandezb** [cosmos/ibc-go#6381]
I just noticed the only tag for wasm light client module is for v8.3 and wasmvm v2.0 we are currently  on wasmvm 1.5.2 is there any plans to create a release for previous wasmvm version? wasmvm 2 is a big jump

**Comment by crodriguezvega** [comment]
Thank you for the issue, @jhernandezb. We would like to understand better the reasons why upgrading to wasmvm v2.0.0 would require a lot of effort. When we upgraded, it didn't take us longer than maybe a day to do all the changes, and the [migration docs](https://github.com/CosmWasm/wasmvm/blob/main/docs/MIGRATING.md) were very clear and helpful.

I see that in [Stargaze v14.0.0-alpha.3](https://github.com/public-awesome/stargaze/blob/v14.0.0-alpha.3/go.mod) wasmd v0.50.0 and ibc-go v8.2.1 are used. Are you planning to upgrade to ibc-go v8.3 in this upgrade? Does the upgrade from wasmd v0.50.0 to v0.51.0 require much effort for your team? If you would consider upgrade to wasmd v0.51.0 and ibc-go v8.3.0, I think both Confio and us would be glad to support you on upgrading to wasmvm v2.0.

**Comment by jhernandezb** [comment]
We currently have a [branch](https://github.com/public-awesome/stargaze/pull/1038) to be merged  that bumps to 8.3 and adds oracle/vote extensions, we often try to be conservative with too many changes on a single upgrade will ask the team how they feel about also shipping wasmd v0.51.0.

**Comment by crodriguezvega** [comment]
@jhernandezb I see in the PR that you linked above that you ended up [using the v8 compatible 08-wasm version](https://github.com/public-awesome/stargaze/pull/1038/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R47), so I will assume that there is no need from your side anymore to have a 08-wasm version compatible with ibc-go v7 and wasmvm v1.5. Therefore I will close the issue for now!
