### ISSUE TITLE
Add tests for `OnAcknowledgementPacket` when ack is received by middle chain

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#6382]
Add tests for `OnAcknowledgementPacket` when [the middle chain receives either a successful or an error acknowledgement](https://github.com/cosmos/ibc-go/blob/2519593ade4fe4fe2dd9c35ee918c23aa568b423/modules/apps/transfer/keeper/relay.go#L399-L415).

![image](https://github.com/cosmos/ibc-go/assets/6876468/bb487ac8-b811-49e8-ac6b-8e706a435266)

**Comment by bznein** [comment]
The error ack seems to be covered here: https://github.com/cosmos/ibc-go/blob/feat/ics20-v2-path-forwarding/modules/apps/transfer/keeper/relay_forwarding_test.go#L572 and the happy path by other tests in that file. I'm closing this issue but feel free to reopen if this is not correct
