### ISSUE TITLE
Add tests for `OnTimeoutPacket` when middle chain times out packet

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#6384]
Add tests for `OnTimeoutPacket` when:
- Capability is not found.
- [A middle chain times out the packet](https://github.com/cosmos/ibc-go/blob/2519593ade4fe4fe2dd9c35ee918c23aa568b423/modules/apps/transfer/keeper/relay.go#L436-L453).

![image](https://github.com/cosmos/ibc-go/assets/6876468/93aefd50-c6f5-4e56-83ea-d398148aa5c7)

**Comment by colin-axner** [comment]
This has been completed?
