### ISSUE TITLE
Rename denom.IBCDenom() function

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#6422]
>   @crodriguezvega suggest `OnChainDenom`, I guess it'd be `denom.OnChain()`. I like the naming direction, but feels it could be a little more descriptive. Any ideas?

_Originally posted by @colin-axner in https://github.com/cosmos/ibc-go/pull/6417#discussion_r1618712058_
            
 Opening as a placeholder to rename the `denom.IBCDenom()` function to a cleaner api name

**Comment by crodriguezvega** [comment]
We leave the name as is.
