### ISSUE TITLE
raw_log: 'failed to execute message; message index: 0: module does not own channel   capability: channel capability not found'[Bug]: 

### ISSUE THREAD

**Issue by DishaIISc** [cosmos/ibc-go#6445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am trying to transfer tokens between 2 chains via IBC. I have created an IBC-enabled module which is dependent on bank and account. I have connected the 2 chains through an IBC relayer. I am able to do intra-chain token transfers. When I give the following command : 
gridexd tx ibc-transfer transfer exchg channel-0 cosmos1nul4as275vwxfa83kcyn27n9vc2gj4wmjcj24e 50token --fees 200stake --from user2 --chain-id grid1 --home ~/.grid1 --node http://localhost:26657 --yes

I get the following error : 
raw_log: 'failed to execute message; message index: 0: module does not own channel
  capability: channel capability not found'

### Cosmos SDK Version

0.46.7

### How to reproduce?

I followed the IBC basics tutorial : 
https://docs.ignite.com/guide/ibc
Instead of the blog module, I created an IBC-enabled module exchg which is dependent on bank and account : 
ignite s module exchg --ibc --dep bank --dep account
I created two chains grid1 and grid2.
I connected the two chains using the relayer as shown in the tutorial. 
I use the following command for IBC token transfer : 
gridexd tx ibc-transfer transfer exchg channel-0 cosmos1nul4as275vwxfa83kcyn27n9vc2gj4wmjcj24e 50token --fees 200stake --from user2 --chain-id grid1 --home ~/.grid1 --node http://localhost:26657 --yes

**Comment by colin-axner** [comment]
Hi, 

> Instead of the blog module, I created an IBC-enabled module exchg which is dependent on bank and account :

During the channel handshake (OnChanOpenInit, OnChanOpenTry) does your code claim the capability provided in the callbacks?

**Comment by colin-axner** [comment]
Closing as stale, since there has been no followup
