### ISSUE TITLE
Move event emissions to functions

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#648]
## Summary

For all core IBC event emissions, we should put them in functions within their respective keepers, like [so](https://github.com/cosmos/ibc-go/blob/a8ebc3f8a2675321903403f861eb4814e1e77f69/modules/core/04-channel/keeper/events.go#L15)

It increases readability of the critical code, provides self documentation, and allows us to ensure consistency between event emission

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by nir1218** [comment]
@colin-axner @crodriguezvega Hey, I would like to work on this issue, kindly assign it to me.

**Comment by crodriguezvega** [comment]
hey @nir1218, glad to see that you want to work on another one. Thanks for your dedicating your time to it!

**Comment by colin-axner** [comment]
@nir1218 let us know if you have any questions

**Comment by nir1218** [comment]
@crodriguezvega @colin-axner  I noticed that in msg_server.go in the upgrade and update client methods there is an emit event of a message type , and then in the client keeper there is an emit of the operation type itself. So my question is, should I consolidate both emissions in one method and invoke it from the client keeper as done in events.go under channel module?

**Comment by crodriguezvega** [comment]
Yes, I think that makes sense. So, for example, for the case of update client to have a method that emits both [this event](https://github.com/cosmos/ibc-go/blob/main/modules/core/02-client/keeper/client.go#L141-L149) and [this event](https://github.com/cosmos/ibc-go/blob/main/modules/core/keeper/msg_server.go#L70-L75), right?

Do you agree, @colin-axner?

**Comment by colin-axner** [comment]
Yes that makes sense to me

**Comment by nir1218** [comment]
@crodriguezvega @colin-axner Will you be closing the issue and the PR? Is there anything else I can do on this?
