### ISSUE TITLE
docs: mobile header has overlapping search and menu

### ISSUE THREAD

**Issue by womensrights** [cosmos/ibc-go#6501]
The mobile docs site header is not responsive to display sizes for all cell phone displays. The menu and search button overlap. Users experience dead clicks because they click the wrong button by accident.

<img width="480" alt="image" src="https://github.com/cosmos/ibc-go/assets/65018876/1973b3ef-00c4-4abf-804d-c59783fd9c7f">

A fix could change the alignment of the search button to be centred instead for mobile to avoid overlap, or alignment should be changed so that the search is always to the left of the menu. Or alignment can be defined for different display sizes - whichever approach is simplest to implement will be fine

**Comment by crodriguezvega** [comment]
Hi @lichdu29. Yes, that would be wonderful; thank you!
