### ISSUE TITLE
docs: high click rate on relayer section should supply hyperlink

### ISSUE THREAD

**Issue by womensrights** [cosmos/ibc-go#6505]
[On the homepage](https://ibc.cosmos.network/main), last 3 bullet points on relayers, there are many attempts to click on words in the paragraph, likely looking to find more information on relayers. 

Suggestion would be to add in a hyperlink t[o the specs repo](https://github.com/cosmos/ibc/blob/main/spec/relayer/ics-018-relayer-algorithms/README.md) for the word Relayers in the first bullet point

**Comment by crodriguezvega** [comment]
Of course, @lichdu29. Thank you very much!
