### ISSUE TITLE
Make ibctesting.TestCoins be multiple coins

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#6531]
See discussion: https://github.com/cosmos/ibc-go/pull/6517#discussion_r1629638022

Todo after transfer tests have been refactored to not cause too many conflicts.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by NisTun** [comment]
Can you assign me this issue sir?

**Comment by crodriguezvega** [comment]
Thanks, @NisTun!
