### ISSUE TITLE
Use `ibctestcoin.TestCoin` through-out tests.

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#6532]
We currently use `sdk.Coin(sdk.DefaultBondDenom, sdkmath.NewInt(100))` throughout while `ibctesting.TestCoin` is defined to be the same, we can replace occurences as found.

Todo after transfer tests have been refactored to not cause too many conflicts.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by NisTun** [comment]
Can I handle this issue sir?

**Comment by crodriguezvega** [comment]
Sure thing, @NisTun. Thanks!
