### ISSUE TITLE
Mark fields not needing to be nullable as with `gogoproto.nullable = false` option

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#6550]
This applies to both fields on the MsgTransfer and fields of the new ForwardingInfo message.

Surfaced during internal walkthrough of ics20 v2 forwarding (commit [efcfa5d](https://github.com/cosmos/ibc-go/tree/efcfa5d877567731f6b4ff8dbd063a34ede5de00))

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
I was originally in favour of using a non-nullable field as I couldn't see a benefit from a go perspective. But I did some investigation. Both protobuf and json act in synchrony regarding the following behaviour. 

Pointer, empty = no field emitted/encoded
Pointer, set = field emitted/encoded
No pointer, empty = field emitted/encoded as empty (`{}` in json, `*\x00` something like this in protobuf)
No pointer, set = field emitted/encoded

Given this. By using nullable:
- the decoding actor can differentiate between non-set and empty values
- smaller encoding size (slightly more performant)
