### ISSUE TITLE
Simplify reverts of forwarding state on acknowledgement

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#6558]
Investigate if we can simplify revert logic by doing regular refund packet tokens first and then the logic for revert forwarding changes.

Surfaced during internal walkthrough of ics20 v2 forwarding (commit [efcfa5d](https://github.com/cosmos/ibc-go/tree/efcfa5d877567731f6b4ff8dbd063a34ede5de00))
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Looks like it should be possible. Opened https://github.com/cosmos/ibc/pull/1110 to update the spec.

**Comment by srdtrk** [comment]
I can take this if others agree

**Comment by srdtrk** [comment]
closed by #6574
