### ISSUE TITLE
Refactor code to separate forwarding logic in self composed functions

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#6559]
Mainly pertaining to changes added to `OnRecv`, investigate if changes can be refactored out to help in encapsulation of flow. The choice of naming for variables should also be tweaked to help with reasoning.

Surfaced during internal walkthrough of ics20 v2 forwarding (commit [efcfa5d](https://github.com/cosmos/ibc-go/tree/efcfa5d877567731f6b4ff8dbd063a34ede5de00))

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
closed by #6575
