### ISSUE TITLE
Update TransferChannelOptions function to accept chain versions instead of ChainOptionConfiguration

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#6577]
## Summary

Currently, the TransferChannelOptions function accepts a list of ChainOptionConfiguration. This is only there because the function calls `GetChains` to fetch the chains which requires the options. This can lead to some unexpected behaviour where this function actually establishes the initial chain configuration before overrides are applied.

If we provide a list of chain versions instead, this function will have no unexpected side effects and be easier to work with.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by gjermundgaraba** [comment]
@chatton I guess you solved this with the latest round of e2e improvements?

**Comment by chatton** [comment]
yes I think we can close it
