### ISSUE TITLE
ICS20-V2 Path Forwarding E2E Tests

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#6578]
## Summary

Tracking issue for ICS20-V2 Path Forwarding E2E tests

Tests:
- [x] Given 3 chains with `ics20-2` channels between A and B, and between B and C, perform a successful transfer of tokens from A to C through B. [Nikolas] https://github.com/cosmos/ibc-go/pull/6758
- [x] Given 3 chains with `ics20-2` channels between A and B, and between B and C, send first tokens from A to B, and then perform a successful unwind + forward transfer of the IBC tokens from B to C through A. Topology: A -> B -> C, and A -> C. [Nikolas] https://github.com/cosmos/ibc-go/pull/6778
- [x] Given 3 chains with `ics20-2` channels between A and B, and between B and C, perform a transfer of tokens from A to C through B, where the hop between B and C will fail. https://github.com/cosmos/ibc-go/pull/6876
- [x] Given 3 chains with `ics20-1` channels between A and B and B and C, perform a successful channel upgrade from v1 to v2 for both channels and send tokens from A to C through B. [Nikolas] https://github.com/cosmos/ibc-go/pull/6793
- [x] Integration test: [a test where the `memo` triggers the execution of a callback only on the final destination](https://github.com/cosmos/ibc-go/pull/6693#discussion_r1656816285). [Nikolas] https://github.com/cosmos/ibc-go/pull/6805
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by bznein** [comment]
I'll start by taking the following one:

> Given 3 chains with ics20-2 channels between A and B, and between B and C, perform a successful transfer of tokens from A to C through B.

**Comment by crodriguezvega** [comment]
Just a note to remember to update the [`unreleased` compatibility tests](https://github.com/cosmos/ibc-go/tree/main/.github/compatibility-test-matrices/unreleased) when we have all the e2e tests ready.

**Comment by bznein** [comment]
>  Given 3 chains with ics20-2 channels between A and B, and between B and C, perform a transfer of tokens from A to C through B, where the hop between B and C will time out. [Nikolas]

I discussed with @chatton on this one and it doesn't seem like we have a way to cause a timeout on e2e tests. We could arrange something like creating a relayer that only watches A->B, wait for timeout, and then update it to watch B to C, but that would be ugly and not possible to do cleanly right now. Right now we do have an integration timeout test (`TestOnTimeoutPacketForwarding`) which might be enough. @crodriguezvega what do you think?
