### ISSUE TITLE
Refactor tests to use different addresses for payee, relayer

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#6579]
Reference discussion: https://github.com/cosmos/ibc-go/pull/6545#discussion_r1633458148

> bit of an historical artefact here but relayerAddr and payeeAddr seem to be the same!
> 
> It's probably fine as is, but could refactor a bit to use ibctesting.TestAccAddress which should be different to both chainA and chainB sender accounts.

unsure yet if this applies in other tests.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by NisTun** [comment]
Can I handle this issue?

**Comment by crodriguezvega** [comment]
Go for it, @NisTun. Thank you!
