### ISSUE TITLE
Mark `MsgModuleQuerySafe` requests field as non-nullable

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#6582]
Randomly bumped into it, the requests field on the [query safe message](https://github.com/cosmos/ibc-go/blob/main/proto/ibc/applications/interchain_accounts/host/v1/tx.proto#L50) is required to be populated in the [Validation fn](https://github.com/cosmos/ibc-go/blob/2b887d7f1efabd42256464aa501f440a981e4eed/modules/apps/27-interchain-accounts/host/types/msgs.go#L52-L54). There's no benefit to keeping it as a pointer.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by neitdung** [comment]
Hi @DimitrisJim, could I take this issue?
