### ISSUE TITLE
Maybe found a query bug in interchain-accounts

### ISSUE THREAD

**Issue by okwme** [cosmos/ibc-go#665]
## Summary of Bug

When running a CLI query on the `interchain-accounts` module (`host` and `controller` subcommand) I see an error.

## Version

https://github.com/cosmos/gaia/tree/ica-acct-auth

## Steps to Reproduce

```
> gaiad q interchain-accounts controller params --home ~/.gaiad2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x51de662]

goroutine 1 [running]:
github.com/cosmos/ibc-go/v3/modules/apps/27-interchain-accounts/controller/client/cli.GetCmdParams.func1(0xc001135b80, {0xc001126ee0, 0x0, 0x2})
	github.com/cosmos/ibc-go/v3@v3.0.0-20211220113545-e3036e36200c/modules/apps/27-interchain-accounts/controller/client/cli/query.go:30 +0x182
github.com/spf13/cobra.(*Command).execute(0xc001135b80, {0xc001126ec0, 0x2, 0x2})
	github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc001048c80)
	github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.3.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.3.0/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0, {0xc000e752f0, 0x12})
	github.com/cosmos/cosmos-sdk@v0.44.5/server/cmd/execute.go:36 +0x1eb
main.main()
	github.com/cosmos/gaia/v6/cmd/gaiad/main.go:16 +0x2c
```

I maybe also jsut mis-configured the 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by okwme** [comment]
I found this bug while trying to see if I could see he status of a transaction that was submitted to the host chain from the controller chain. Would love to get something like a TX hash that I can use to see if my TX failed on the host chain. Or query the host chain with my account to see a list of transactions?

**Comment by colin-axner** [comment]
thanks @okwme! I opened #666 which fixes the issue (but you'll need to restart your chain with the updated binary)

As far as seeing the status of a tx. The ICA auth module will receive the acknowledgement result in OnAcknowledgement, it could log the result there or we can ensure the packet sequence used to send the transaction is returned to the user. Then you could query for the acknowledgement on the host chain. We could add a command to ica which parses the acknowledgement result
