### ISSUE TITLE
Reject transfer if channel version is `ics20-1` and forwarding hops is not empty

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#6654]
I think we should return an error in `sendTransfer` if channel version is `ics20-1` and `len(forwarding.Hops > 0)`, similarly as we do [if channel version is `ics20-1` and `len(coins) > 1`](https://github.com/cosmos/ibc-go/blob/14d54864cf9642687047d047d1aea08913c8944a/modules/apps/transfer/keeper/relay.go#L79-L82). Once https://github.com/cosmos/ibc-go/issues/6624 is worked on, the condition should be adjusted (`len(forwarding.Hops > 0)` or `unwind == true`).

**Comment by duonghb53** [comment]
@crodriguezvega Can I get this one?

**Comment by crodriguezvega** [comment]
@duonghb53 Yes, thank you! Please open the PR against the [feature branch](https://github.com/cosmos/ibc-go/tree/feat/ics20-v2-path-forwarding).

**Comment by duonghb53** [comment]
> can definitely target #6655 too to add the `unwind` clause. Can add it there otherwise.

Then I will wait #6655 has been close to resolve this.

**Comment by crodriguezvega** [comment]
@duonghb53 #6655 is now merged, so the way is all cleared for ya!

**Comment by crodriguezvega** [comment]
@duonghb53 Just a heads up that considering the implementation of unwinding that is going on in https://github.com/cosmos/ibc-go/pull/6656/files#diff-4e5ab230398f70dd609959741091ad8ff3a2e1af7aba3c161057f6b8a32080d9R39, then you will not need to account for the `unwind` flag in the condition I mentioned in the description. So it will be enough to check if channel version is `ics20-1` and `len(forwarding.Hops > 0)`. Thank you!

**Comment by duonghb53** [comment]
@crodriguezvega I got it. thank for your info.
