### ISSUE TITLE
Add flag for unwind in transfer cli

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#6657]
Add a flag to transfer's cli to allow accepting a boolean flag for `unwind`ing. Can be done after https://github.com/cosmos/ibc-go/pull/6655

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by neitdung** [comment]
Hi @DimitrisJim, could I take this issue?

**Comment by crodriguezvega** [comment]
Hi @neitdung. Yes, go for it. Please work off the [path forwarding feature branch](https://github.com/cosmos/ibc-go/tree/feat/ics20-v2-path-forwarding). Thanks!

**Comment by crodriguezvega** [comment]
Closed by #6680
