### ISSUE TITLE
Consolidate forwarding hops validation for transfer and packet data messages

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#6658]
Ref https://github.com/cosmos/ibc-go/pull/6655#discussion_r1647088877

> Nit (can be done in a follow-up, no need to block this PR): Since this `hops` validation is also done in `ForwardingPacketData` `Validate`, maybe it could be extracted into a separate function, but still care of slight differences in the error messages (e.g. `forwarding` vs `forwarding packet data`), if we want that.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closed by #6695
