### ISSUE TITLE
Add test that consumes forwarded memo

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#6663]
It appears [we currently do not have one](https://github.com/cosmos/ibc-go/pull/6655#discussion_r1647343333). We should add a test that forwards a packet with populated memo and ensures that memo in final destination is present as expected.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by gjermundgaraba** [comment]
Have the changes locally, but based off of #6691, so waiting for that to be merged before creating a PR

**Comment by crodriguezvega** [comment]
Closed by #6707
