### ISSUE TITLE
Add pre-commit hook to run `make proto-all`

### ISSUE THREAD

**Issue by bznein** [cosmos/ibc-go#6668]
We currently have no way to ensure that `make proto-all` has been run when changing `.proto` files  (except for manually reviewing the generated code). We could add a pre-commit hook that ensures this.

**Comment by PanGan21** [comment]
Hi! I am interested to work on this issue if noone else is working on it 🙂

**Comment by crodriguezvega** [comment]
I don't think anyone is working on it, so for for it @PanGan21. Thank you!

**Comment by PanGan21** [comment]
Hey @crodriguezvega  it would be helpful to get some feedback on #6678 whenever there is capacity

**Comment by bznein** [comment]
As discussed in the PR comment, we unfortunately decided to abandon this issue, thanks for the help!
