### ISSUE TITLE
Reduce notion of ConsensusState within core IBC

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#669]
## Summary

core IBC assumes there exists a consensus state for each height associated with an IBC client. In 02-client it will set the ConsensusState for a IBC client upon activities such as initialization, update, and upgrades

## Problem Definition

Not all IBC clients will want to store a consensus state per height, some client might only need the latest consensus state. This causes unnecessary storage.

## Proposal

Reduce the notion of ConsensusStates with core IBC. 02-client should not set consensus states upon initialization, updates, or upgrades. It should not assume there exists a ConsensusState for every height upgraded to. We probably should add `GetTimestampAtHeight` to the `ClientState` interface 

cc @AdityaSripal 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by AdityaSripal** [comment]
Where does the assumption that consensus state always exists after `UpdateClient`? I don't believe this is an assumption in IBC.

>  02-client should not set consensus states upon initialization, updates, or upgrades

I don't understand why this has to change. Since this is basically creating a new consensus state on each step. If that consensus state gets deleted as soon as the next update comes through, that's not an issue for IBC at all. Though it might be a practical one for relayers

**Comment by colin-axner** [comment]
> Where does the assumption that consensus state always exists after `UpdateClient`? I don't believe this is an assumption in IBC.

Sorry I misspoke. It doesn't assume the consensus state always exists, but it assumes the only way to update the consensus state is via UpdateClient. It also assumes UpdateClient can only update one consensus state. 

This restriction is enforced by [timeout](https://github.com/cosmos/ibc-go/blob/89ffaafb5956a5ea606e1f1bf249c880bea802ed/modules/core/03-connection/keeper/keeper.go#L89) logic.

**Comment by colin-axner** [comment]
Closing as the proposed action items are encapsulated by existing issues
