### ISSUE TITLE
Create a new test suite `ForwardingTestSuite`

### ISSUE THREAD

**Issue by bznein** [cosmos/ibc-go#6715]
>  Some food for thought for a future refactor or cleanup.. Maybe we should consider a `ForwardingTestSuite` for forwarding tests, since spinning up 4 in process apps is wasteful for most other transfer tests.

_Originally posted by @damiannolan in https://github.com/cosmos/ibc-go/pull/6713#discussion_r1656577517_

**Comment by NisTun** [comment]
Can I handle this issue @bznein
