### ISSUE TITLE
Add a `NoForwarding` helper function to use in tests

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#6723]
See review comment here https://github.com/cosmos/ibc-go/pull/6693#discussion_r1656714207

Basically a function that returns an `Forwarding` object with all values empty. Could do something similar for `ForwardingPacketData`.

should be done after feature branch is merged
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by hakuno2000** [comment]
Hello, may I work on this sir?
