### ISSUE TITLE
Add a way to query for acknowledgements in e2e tests 

### ISSUE THREAD

**Issue by bznein** [cosmos/ibc-go#6786]
Context here: https://github.com/cosmos/ibc-go/pull/6778#discussion_r1668512287

**Comment by PanGan21** [comment]
Hey guys, could I give it a try?

**Comment by crodriguezvega** [comment]
> Hey guys, could I give it a try?

Yes, definitely. Thank you, @PanGan21!

**Comment by damiannolan** [comment]
Is the request here to be able to query the acknowledgement commitment or have full access to the data type?

There is `QueryPacketAcknowledgement` [here](https://github.com/cosmos/ibc-go/blob/main/modules/core/04-channel/keeper/grpc_query.go#L311).

If we want access to the full acknowledgement data, then it can be parsed from the events in the tx response from `BroadcastMsgs` in e2e.
