### ISSUE TITLE
Add a unit test which sets unwind to true and has forwarding hops which forwards back to itself

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#6878]
## Summary

Like a boomerang, we should add a test to unwind back to the source and then have the forwarding hops be sending back to the user. This is a safety test against an edge case given that in the middlehop we compare the tokens in the failed packet data against the dest port/channel in the received packet

_arose from our internal security audit of ics20 v2_

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by vishal-kanna** [comment]
@colin-axner ,I would like to work on it

**Comment by crodriguezvega** [comment]
Go for it, @vishal-kanna!
