### ISSUE TITLE
ADR: ChainID format

### ISSUE THREAD

**Issue by fedekunze** [cosmos/ibc-go#70]
Write a complete ADR that documents the changes from cosmos/cosmos-sdk#7280. This format will be required by all chains implementing IBC. 

@AdityaSripal @colin-axner @cwgoes 
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by crodriguezvega** [comment]
Since the chain ID is a Cosmos/Tendermint thing and the format is already documented in the docs, I am going to close this issue. If somebody feels this is still relevant, we can reopen.
