### ISSUE TITLE
Turn ics29 into standalone ibc application

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#7032]
## Summary

With #6941 we can turn ics29 into a standalone application. With #7008 we can also remove its msg server (or repurpose) as the sync incentivization message will no longer be necessary (was work around to not having own packet data)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by womensrights** [comment]
we will not work on this
