### ISSUE TITLE
failed to load state

### ISSUE THREAD

**Issue by akankshadhyani05** [cosmos/ibc-go#7035]
Hi, I am trying to run a cosmos-sdk [v0.50.7] based chain, the chain is running fine and I can see the latest_block_height getting increased. I have posted the output as well:

`{"node_info":{"protocol_version":{"p2p":"8","block":"11","app":"0"},"id":"590958b0032b293a615691eb49a21e26861fd47d","listen_addr":"tcp://0.0.0.0:26656","network":"tfd","version":"0.38.7","channels":"40202122233038606100","moniker":"tfd","other":{"tx_index":"on","rpc_address":"tcp://127.0.0.1:26657"}},"sync_info":{"latest_block_hash":"494D7804EF1682A099A70E9A39BF5E9BCF5B77AC1E3EA8C5B2467D6F9CA463AF","latest_app_hash":"FC5C4525791F7D505A2EE0BED823BF76C015CFA88EC67B40B00B262A185EEEB4",**"latest_block_height":"192"**,"latest_block_time":"2024-07-26T10:51:11.616086639Z","earliest_block_hash":"5B0147B864E240C55D170B47D71CBCA2E6CEDD93FEBE551A2FB026841B5D8C37","earliest_app_hash":"E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855","earliest_block_height":"1","earliest_block_time":"2024-07-26T10:34:47.078732264Z","catching_up":false},"validator_info":{"address":"1EA664F8EA6EEE7B6BAEBFE68C83AA79C12C25F9","pub_key":{"type":"tendermint/PubKeyEd25519","value":"kKduCC/j9/1nrYyWnXAN6S1fT8EIY/Qd1ZtjrQ0j3RU="},"voting_power":"1000"}}`

but when i try to run commands like to query the bank balances or bank send command I am getting error as pasted below:

```
./bin/tfd query bank balances validator
rpc error: code = InvalidArgument desc = failed to load state at height 10; version does not exist (latest height: 10): invalid request
```

getting the same error even if I run the bank send command.

**Comment by crodriguezvega** [comment]
Hi @akankshadhyani05. I am sorry you are running into an issue, but the issue is not related to IBC. I would encourage you to ask this question in the [Cosmos Discussion Board](https://github.com/orgs/cosmos/discussions/categories/chain-builders-cosmos-sdk).
