### ISSUE TITLE
Create a `WrapAcknowledgement` function for backwards compatibility

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#7043]
## Summary

In 05-port router, we want to get away from middlewares wrapping acknoweledgements of applications below them. Core IBC will instead maintain a map from app name to the ack for that application. To maintain backwards compatibility, core IBC needs to be capable of setting the acknowledgement in the format the counterparty expects.  

We may need a `Unwrap` function, but it might be possible to have relayers pass in the flat map. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by damiannolan** [comment]
This issue is more or less solved in #7176, but we will hold off on cherry-picking out the code separately for this for the time being until we are happy with the direction.

> Core IBC will instead maintain a map from app name to the ack for that application.

This will be also relevant for forwards compatibility for multi packetdata / mutli acknowledgements.

**Comment by colin-axner** [comment]
This issue is being closed as the team has decided to move in another direction https://github.com/cosmos/ibc-go/issues/6941#issuecomment-2312559378 - it will be reopened if necessary
