### ISSUE TITLE
Remove capabilities

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#7107]
## Summary

The module should be deleted and usage removed from ibc-go

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by damiannolan** [comment]
Capabilities usage should now be removed from each of the core msg server handlers. Other places to remove references:
- [ ] Expected interfaces `Authenticate`
- [ ] Usage in 04-channel and apps
- [ ] Wiring module in simapps

**Comment by colin-axner** [comment]
Done in a series of pr's, but the capability module has been removed! https://github.com/cosmos/ibc-go/pull/7279 no references to it will be made starting v10!
