### ISSUE TITLE
Disallow app version to be specified if the packet protocol version is V1

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#7122]
## Summary

On the eureka feature branch, I believe it is currently possible to add an app version to a classic packet, even though it is not committed to or proved. We should assert in packet.ValidateBasic that:
```go
if packet.ProtocolVersion == V1, UNSPECIFIED && appVersion != "" {
    return err
}
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closed by https://github.com/cosmos/ibc-go/pull/7146.
