### ISSUE TITLE
Address logger todo

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#7150]
## Summary

See [TODO](https://github.com/cosmos/ibc-go/blob/2a07e6e060c8ba8778297528e9a826b6045e295e/modules/core/packet-server/keeper/keeper.go#L38)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chandiniv1** [comment]
@colin-axner can I work on this issue?

**Comment by crodriguezvega** [comment]
Thank you, @chandiniv1! I think a submodule name like `packetserver` would work for now.

**Comment by crodriguezvega** [comment]
Closed by #7196
