### ISSUE TITLE
Address custom prefix todo

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#7151]
## Summary

see [TODO](https://github.com/cosmos/ibc-go/blob/2a07e6e060c8ba8778297528e9a826b6045e295e/modules/core/packet-server/keeper/keeper.go#L156), I believe the todo can simply be removed

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closed by https://github.com/cosmos/ibc-go/pull/7155
