### ISSUE TITLE
Document capabilities in IBC core spec

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#72]
## Summary

Capabilities in the core spec for IBC needs to be finished

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by crodriguezvega** [comment]
I will leave it in v10 milestone for now, but since with the port router refactor we will probably get rid of the capability module, then this wouldn't be needed anymore.
