### ISSUE TITLE
Bump golang version to 1.23

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#7236]
We can bump in the release with [Cosmos SDK v0.52](https://github.com/cosmos/cosmos-sdk/blob/7f14281acdcb39d5399de511b22bb287d572f376/go.mod#L1), so that we stay in sync.

**Comment by DimitrisJim** [comment]
is currently being done in https://github.com/cosmos/ibc-go/pull/7261

**Comment by damiannolan** [comment]
Done
