### ISSUE TITLE
Handle applyReplayProtection in RecvPacketV2

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#7250]
## Summary

applyReplayProtection is temporarily [commented out](https://github.com/cosmos/ibc-go/blob/7c52580b870af0b7564819c3eace79bf8705bf74/modules/core/04-channel/keeper/packet.go#L286-L288) in RecvPacketV2.

This needs to be uncommented (which would require duplicate V2 functions to be added). Or we can wait until we fully use PacketV2 internally.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned
- [ ] Estimate provided

**Comment by DimitrisJim** [comment]
Obsolete! (Replay protection currently exists https://github.com/cosmos/ibc-go/blob/2ca28242fb9354aa0612e763dfabdd8d803a9cb9/modules/core/04-channel/v2/keeper/packet.go#L125)
