### ISSUE TITLE
Move SetMultiAcknowledgement to PacketServerKeeper

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#7251]
## Summary 

[SetMultiAcknowledgement](https://github.com/cosmos/ibc-go/blob/29f9ee3662a559183f9dfad8e04f70a96b4ea28f/modules/core/keeper/msg_server.go#L622-L623) is currently on the channel keeper.

With Eureka, we won't want to me adding new functionality onto the Channel Keeper, so it makes sense to move this onto the PacketServerKeeper instead.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned
- [ ] Estimate provided

**Comment by chandiniv1** [comment]
@chatton can I work on this issue?

**Comment by damiannolan** [comment]
Superseded by ibc-eureka work
