### ISSUE TITLE
Implement ValidateBasic function for packetV2

### ISSUE THREAD

**Issue by bznein** [cosmos/ibc-go#7255]
in [packet-server's SendPacket](https://github.com/cosmos/ibc-go/blob/aac9a4588127f1e6ec6de5d34bcbaaf5f0c88ac6/modules/core/keeper/msg_server.go), after https://github.com/cosmos/ibc-go/pull/7254 is merged

**Comment by chandiniv1** [comment]
@bznein can I work on this issue?

**Comment by bznein** [comment]
Hi @chandiniv1 apologies but this has actually be already done (https://github.com/cosmos/ibc-go/blob/feat/ibc-eureka/modules/core/04-channel/v2/types/packet.go#L34-L61) and whoever worked on it forgot to close the issue
