### ISSUE TITLE
Bug: `newModuleQuerySafeAllowList` panics

### ISSUE THREAD

**Issue by julienrbrt** [cosmos/ibc-go#7259]
When using IBC >= 8.2.0 with rollkit, the keeper will panic because of some proto definition not found. It looks like https://github.com/ignite/cli/issues/4318 hasn't entirely resolved the issue.

ref: https://github.com/ignite/cli/issues/4318#issuecomment-2332725202
ref: https://github.com/cosmos/ibc-go/issues/6436#issuecomment-2332727449

**Comment by damiannolan** [comment]
related https://github.com/CosmWasm/wasmd/issues/1785

**Comment by damiannolan** [comment]
We should test this with rollkit using https://github.com/cosmos/ibc-go/pull/7278 which is a branch against v8.5.x rather than the PR targetting main, which would contain a lot more diffs
