### ISSUE TITLE
update protobuf dependency 

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#733]
## Summary

`go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead.`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
How did you get this error?

**Comment by colin-axner** [comment]
Closing as stale
