### ISSUE TITLE
Run buf check on protobuf file changes

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#7426]
Corollary of https://github.com/cosmos/ics23/issues/376, it would be nice if we ran `buf breaking` on PRs that change proto files and add it as a required check.

We do not currently do so (close if mistaken)
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned
- [ ] Estimate provided

**Comment by kobakaku** [comment]
Hi! Can I handle this issue @DimitrisJim ?
