### ISSUE TITLE
Change TestCommitPacket to use table tests

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#7503]
See comment here https://github.com/cosmos/ibc-go/pull/7498#discussion_r1810391640

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned
- [ ] Estimate provided

**Comment by cl1ckname** [comment]
Hi, I would like to do this. I have already read the contributing guideline and feel empowered to write it. Can I get an assign?

**Comment by damiannolan** [comment]
Hey @cl1ckname, thanks for volunteering to pick this up! When you PR against the repo, please check the box that says "Allow edits from maintainers", that can help us keep the branch in sync and help you out with any follow up commits on your branch!
