### ISSUE TITLE
Generate swagger docs for channel/v2

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#7705]
`make proto-swagger-gen` for the new queries. For some reason this doesn't work locally for me using the makefile cmd. May need some tweaking?

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned
- [ ] Estimate provided

**Comment by iIvaki** [comment]
@DimitrisJim can I do this?

**Comment by DimitrisJim** [comment]
yea sure thanks! there must be some setting to tweak since this isn't generating them right now. Please target `feat/ibc-eurkea` branch!
