### ISSUE TITLE
Remove references to TestGrandpaTestSuite

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#7729]
This e2e suite was removed at some point during sdk 0.52 upgrade. It is still referenced in our workflows (and is one causing one of em to consistently fail).

Should be possible to remove references to it.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned
- [ ] Estimate provided

**Comment by gjermundgaraba** [comment]
We have #6835, as well, but we are def at place where we can just remove it entirely.

**Comment by DimitrisJim** [comment]
yea, I think for time being this is really just a clean-up of workflow files.
