### ISSUE TITLE
Remove error string from transfer. Replace with constant string

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#777]
## Summary

Any values included in an acknowledgement will be committed in the state machine. Thus the error message returned from `OnRecvPacket` is state machine breaking if it changes. This makes our code hard to change in patch releases (and this restriction applies to our dependencies). We should remove the `err.Error()` from the transfer ack and replace with a constant error string that won't change

see #744 for more information

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
The abci error code can be emitted in the error acknowledgement.

**Comment by damiannolan** [comment]
> The abci error code can be emitted in the error acknowledgement.

This refers to just ics27, right? Transfer just requires a string const [here](https://github.com/cosmos/ibc-go/blob/main/modules/apps/transfer/ibc_module.go#L184). 

`NewErrorAcknowledgement()` in 04-channel/types should probably be documented to specify a deterministic error string is required. Even still, we can't guarantee that developers will provide that.

**Comment by colin-axner** [comment]
> This refers to just ics27, right? Transfer just requires a string const [here](https://github.com/cosmos/ibc-go/blob/main/modules/apps/transfer/ibc_module.go#L184).

That string const being deterministic rests on the assumption that error strings are included in the state machine, which is not true. The ABCI code should be included in the same way it was done for ICS27 in #794 (I'd even copy the test)
