### ISSUE TITLE
Add a gRPC endpoint for fetching consensus state heights

### ISSUE THREAD

**Issue by seanchen1991** [cosmos/ibc-go#798]
## Summary

The ibc-rs codebase would benefit from a gRPC endpoint that only fetches consensus state heights for a given client. 

## Problem Definition

At the moment, height information is extracted after querying for all consensus states via the `QueryConsensusStatesRequest` query, which is suboptimal. It would be nice to be able to query just for consensus state heights so that the extra step of extracting all of the heights can be eliminated. 

## Proposal

Add a gRPC endpoint (perhaps something like `QueryConsensusHeightsRequest`) that returns all consensus state heights for a given client.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Thanks for the rationale, @adizere. :)

**Comment by adizere** [comment]
> Would a gRPC with the following request/response messages satisfy the requirements?

Yes, thank you!

> The heights in the response should be in decreasing order.

This would be great. We usually [sort](https://github.com/informalsystems/ibc-rs/blob/8b5f0d3198b15991d450d7583025835988aecc39/relayer/src/foreign_client.rs#L1080) the heights in descending order after we fetch them, so descending order is the semantic we'd like to achieve.

Note that the protobuf type `PageRequest` has already a `reverse` option. Our typical use-case is that we either want:
- _all_ consensus heights of a client, or
- the last X (in descending order) consensus heights installed for a client.

For the first case we use `PageRequest` parametrized with `limit: u64::MAX`. For the second case, we would expect to use `limit: X`. In both cases we set `reverse: true`.

**Comment by crodriguezvega** [comment]
Thanks for the feedback, @adizere. So if I understand you correctly, the heights should be in descending order if `reverse: true`? Otherwise, we should return them in increasing order?

**Comment by adizere** [comment]
> So if I understand you correctly, the heights should be in descending order if `reverse: true`? 

Yes.

The new request should probably adhere to the same semantics as the others requests. The default ordering semantics are "ascending order". On the client side (i.e., relayer side), we will probably set `reverse: true` to pull the heights in descending order (or we will sort the heights in the response entirely on the client side, alternatively).

> Otherwise, we should return them in increasing order?
Yep, I think this is the default that clients would expect, so I think it makes sense to retain the same expectations with this new request.

**Comment by adizere** [comment]
Anca [pointed out](https://github.com/informalsystems/ibc-rs/pull/2167#discussion_r870664573) that the default ordering in gRPC responses works on lexicographic value of Height, not on their numerical value.

> Here is an example (trimmed from an actual query). If the chain has states for heights:
830, 821, 766, 222, 104, 76, 30, 25, 20, 10
The gRPC query returns:
10, 104, 20, 222, 25, 30, 76, 766, 8, 821, 830

Shall I open a separate issue for this? Or will this PR have the correct ordering implemented (i.e., adhering to numerical, not lexicographical order)?

**Comment by crodriguezvega** [comment]
>Shall I open a separate issue for this? Or will this PR have the correct ordering implemented (i.e., adhering to numerical, not lexicographical order)?

@catShaark, can you please check this in #1336 and fix it and add a test if needed?

**Comment by catShaark** [comment]
> > Shall I open a separate issue for this? Or will this PR have the correct ordering implemented (i.e., adhering to numerical, not lexicographical order)?
> 
> @catShaark, can you please check this in #1336 and fix it and add a test if needed?

I think this belong to the sdk. I can't find any ways to do numerical ordering as the store iterator can only iterate in lexicographical order.

Should I open an issue about this in the sdk repo ?

**Comment by catShaark** [comment]
@crodriguezvega , I've opened an [issue](https://github.com/cosmos/ibc-go/issues/1483) to propose my solution

**Comment by crodriguezvega** [comment]
This is now available in [v3.1.0](https://github.com/cosmos/ibc-go/releases/tag/v3.1.0), [v3.0.1](https://github.com/cosmos/ibc-go/releases/tag/v3.0.1), [v2.3.0](https://github.com/cosmos/ibc-go/releases/tag/v2.3.0), [v2.2.1](https://github.com/cosmos/ibc-go/releases/tag/v2.2.1), [v2.1.1](https://github.com/cosmos/ibc-go/releases/tag/v2.1.1), [v1.5.0](https://github.com/cosmos/ibc-go/releases/tag/v1.5.0), [v1.4.1](https://github.com/cosmos/ibc-go/releases/tag/v1.4.1) and [v1.3.1](https://github.com/cosmos/ibc-go/releases/tag/v1.3.1).
