### ISSUE TITLE
Fix "proofs.proto" path

### ISSUE THREAD

**Issue by alpe** [cosmos/ibc-go#808]
## Summary

The `proofs.proto` file is in the [/third_party/proto](https://github.com/cosmos/cosmos-sdk/tree/master/third_party/proto) root folder while it was usually in [/third_party/proto/confio](https://github.com/cosmos/cosmos-sdk/tree/v0.45.0/third_party/proto/confio).
I modified the project proto files to be consistent but it would be more convenient to have common a standard within all cosmos projects.

The SDK uses the buf schema registry now:  https://github.com/cosmos/cosmos-sdk/pull/10669
I have opened https://github.com/confio/ics23/issues/67 to support this.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by alpe** [comment]
Same issue with v3

**Comment by damiannolan** [comment]
closed by https://github.com/cosmos/ibc-go/pull/2705

Updating ics23 to use BSR can be tracked separately
