### ISSUE TITLE
Find Elegant Solution if Fee Escrow account is out of balance

### ISSUE THREAD

**Issue by AdityaSripal** [cosmos/ibc-go#821]
The current way to deal with the worst-case scenario of when escrow account is out of balance is to disable the fee module on all channels.

However, this will only happen on our channel end. The other channel end will continue with the fee module enabled since there isn't a good way to communicate that our side has disabled fees once the channel is already open.

This will lead to an invalid state where one side has fee enabled and the other side does not. 

We should determine a better way to handle this case.

Perhaps we keep fee enabled, but just do not distribute the fee on our side.

Thanks to @soareschen for pointing this out

**Comment by colin-axner** [comment]
Should we close the channel? That would allow the counterparty to close as well

**Comment by colin-axner** [comment]
I'm working on this in smaller pieces, but in general:
- when escrow balance will be negative -> disable all channels
- when writing an acknowledgement, if the channel is disabled + the fee version is set -> return ics29 ack
