### ISSUE TITLE
broken link to adr-001

### ISSUE THREAD

**Issue by marbar3778** [cosmos/ibc-go#85]
## Summary of Bug

https://github.com/cosmos/ibc-go/blob/docs/architecture/adr-001-coin-source-tracing.md

this link is broken in https://github.com/cosmos/ibc-go/blob/main/modules/apps/transfer/spec/01_concepts.md 

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by AbhinavMir** [comment]
If someone could introduce me to the architecture of the website/docs I'd love to jump on this.

**Comment by colin-axner** [comment]
Current architecture docs are located [here](https://github.com/cosmos/cosmos-sdk/tree/master/docs/architecture)

In addition to the link being updated, we need to move ADRs that are IBC specific to this repository (links would need to be updated again in this step). They should also be removed from the SDK. ADRs (1, 15, 25, 26) appear to be the relevant ones
