### ISSUE TITLE
Remove GetClientID from Misbehaviour interface

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#874]
## Summary

Remove [`GetClientID`](https://github.com/cosmos/ibc-go/blob/c378ff3b9e637dbae171d2c5129d966b468a2305/modules/core/exported/client.go#L202) from the Misbehaviour interface. It will always be supplied in conjunction with submitting misbehaviour. Needed to remove the Misbehaviour interface

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
partially closed by #897 

we should remove `GetClientID` from the misbehaviour in each light client implementation
- [ ] tendermint
- [ ] solomachine

**Comment by colin-axner** [comment]
I'll do 07-tendermint

**Comment by damiannolan** [comment]
I'll do 06-solomachine for this! :)

**Comment by seantking** [comment]
Closing :)
