### ISSUE TITLE
Merge Misbehaviour and Header interface and rename it to ClientMessage

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#875]
## Summary

Remove misbehaviour interface and use the `Header` interface instead (they will have the same functions after #874)

#### PR 1 

Rename proto files of light client misbehaviour. For example, in 07-tendermint, [Misbehaviour](https://github.com/cosmos/ibc-go/blob/c378ff3b9e637dbae171d2c5129d966b468a2305/modules/light-clients/07-tendermint/types/misbehaviour.go#L21), should become a `DuplicateHeightHeader` or something like that. 

We should have a normal Header and a duplicate height header. A normal header may update the client if it does not validate BFT time and the duplicate height header may prove a fork resulting in the client becoming frozen. 

#### PR 2

Change the API to use Header instead of Misbehaviour

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by notbdu** [comment]
Within the misbehaviour header handler, we need to type cast `Header` to a concrete misbehaviour header type.

Maybe it's easier to use `MisbehaviourHeader` and `oneof` internally over misbehaviour types (e.g. `DuplicateHeightHeader` as an internal type)?

A series of attempted type casts doesn't hurt either if we add misbehaviour types I suppose haha.

**Comment by colin-axner** [comment]
Let's merge `Header` and `Misbehaviour` and name the interface `ClientMessage` as @AdityaSripal suggests [here](https://github.com/cosmos/ibc-go/pull/1090#discussion_r822876705)

**Comment by colin-axner** [comment]
closed by #1107
