### ISSUE TITLE
Add 668 functions to solo machine

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#878]
## Summary

In preparation for the additional functions to the client state interface, #668, add:
- VerifyClientMsg
- CheckForMisbehaviour
- UpdateStateOnMisbehaviour
- UpdateState

for solomachine

### PR 1

~Rename [`Misbehaviour`](https://github.com/cosmos/ibc-go/blob/c378ff3b9e637dbae171d2c5129d966b468a2305/modules/light-clients/06-solomachine/types/misbehaviour.go) to `DuplicateSignatureHeader`~

Decision to maintain existing naming: See [comment](https://github.com/cosmos/ibc-go/pull/1090#discussion_r822876705)

### PR 2

Rename [`checkHeader`](https://github.com/cosmos/ibc-go/blob/c378ff3b9e637dbae171d2c5129d966b468a2305/modules/light-clients/06-solomachine/types/update.go#L38) to `VerifyClientMsg`. 

Add functionality to account for `Misbehaviour`. Essentially [verifying signatures twice](https://github.com/cosmos/ibc-go/blob/c378ff3b9e637dbae171d2c5129d966b468a2305/modules/light-clients/06-solomachine/types/misbehaviour_handle.go#L37-#L44). Code between `checkHeader` and `verifySignatureAndData` can be deduplicated. 

Add a switch
```go
switch header.(type) {
case NormalHeader:
   // https://github.com/cosmos/ibc-go/blob/c378ff3b9e637dbae171d2c5129d966b468a2305/modules/light-clients/06-solomachine/types/update.go#L40-#L59)
    data := normal header update code
     checkSignature(data)
     
case Misbehaviour:
    // https://github.com/cosmos/ibc-go/blob/c378ff3b9e637dbae171d2c5129d966b468a2305/modules/light-clients/06-solomachine/types/misbehaviour_handle.go#L37-#L44
    checkSignature(sig1)
    checkSignature(sig2)
   
default:
    return error
}
```

### PR 3

Rename [`update`](https://github.com/cosmos/ibc-go/blob/c378ff3b9e637dbae171d2c5129d966b468a2305/modules/light-clients/06-solomachine/types/update.go#L79) to `UpdateState`

### PR 4

CheckForMisbehaviour returns true (it passed `VerifyClientMsg` check)

#### PR 5

UpdateStateOnMisbehaviour set client state in state to be [frozen](https://github.com/cosmos/ibc-go/blob/c378ff3b9e637dbae171d2c5129d966b468a2305/modules/light-clients/06-solomachine/types/misbehaviour_handle.go#L46)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by damiannolan** [comment]
I'll pick up PR 1 here to make a start!

**Comment by damiannolan** [comment]
I've got started with PR 2. @seantking I see you assigned but did you start any task? Happy to pair up on the work later today, let me know if you've started anything! :)

**Comment by colin-axner** [comment]
closed by the linked pr's!

**Comment by colin-axner** [comment]
great work @damiannolan
