### ISSUE TITLE
Add 668 functions to 07-tendermint

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#879]
In preparation for the additional functions to the client state interface, #668, add:
- VerifyHeader
- CheckForMisbehaviour
- UpdateStateOnMisbehaviour
- UpdateState

for tendermint client

### PR 1

~~Rename [`Misbehaviour`](https://github.com/cosmos/ibc-go/blob/c378ff3b9e637dbae171d2c5129d966b468a2305/modules/light-clients/07-tendermint/types/misbehaviour.go#L21) to `DuplicateHeightHeader` or some name like that (we can discuss on pr)~~

We decided to leave as Misbehaviour, see [comment](https://github.com/cosmos/ibc-go/pull/1090#discussion_r822876705)

### PR 2

Rename [`checkValidity`](https://github.com/cosmos/ibc-go/blob/c378ff3b9e637dbae171d2c5129d966b468a2305/modules/light-clients/07-tendermint/types/update.go#L87) to `VerifyHeader`. Code may need to be modified to fulfill the expected functionality of `VerifyHeader`, including changing API or pulling in/removing code from the existing function. 

Add a switch
```go
switch header.(type) {
case NormalHeader:
   // verify one TM header
  
case DuplicateHeightHeader:
    // verify both TM headers
   
default:
    return error
}
```

Additional code may need to be added to the normal header or duplicate height header. Code should be deduplicated from `CheckMisbehaviourAndUpdateState` as well

### PR 3

CheckForMisbehaviour should check for duplicate height misbehaviour and BFT Time violation misbehaviour. See existing [code](https://github.com/cosmos/ibc-go/blob/c378ff3b9e637dbae171d2c5129d966b468a2305/modules/light-clients/07-tendermint/types/update.go#L91-#L111). Code should be deduplicated from `CheckMisbehaviourAndUpdateState` as well. Ensure duplicate header misbehaviour is checked by seeing if a consensus state already exists for that height

#### PR 4

~UpdateStateOnMisbehaviour set client state in state to be [frozen](https://github.com/cosmos/ibc-go/blob/c378ff3b9e637dbae171d2c5129d966b468a2305/modules/light-clients/07-tendermint/types/update.go#L109)~

Closed by: #1168 

### PR 5

Rename [`update`](https://github.com/cosmos/ibc-go/blob/c378ff3b9e637dbae171d2c5129d966b468a2305/modules/light-clients/07-tendermint/types/update.go#L248) to `UpdateState`. Should account for no-ops for duplicate headers. Do [pruning logic](https://github.com/cosmos/ibc-go/blob/c378ff3b9e637dbae171d2c5129d966b468a2305/modules/light-clients/07-tendermint/types/update.go#L113-#L139) within this function as well

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
I will pickup PR 1

**Comment by seantking** [comment]
Picking up PR 2 today as @damiannolan is finishing off solo machine work

**Comment by seantking** [comment]
PR [2](https://github.com/cosmos/ibc-go/pull/1115) & [3/4 ](https://github.com/cosmos/ibc-go/pull/1116)

**Comment by colin-axner** [comment]
Heyo. I can pickup pr 5
