### ISSUE TITLE
Proof missing in ClientState response from grpc_query

### ISSUE THREAD

**Issue by sahith-narahari** [cosmos/ibc-go#97]
## Summary of Bug
Using cli to query ClientState has the ability to return the proof whereas grpc returns only clientState and proofHeight.

I'm trying to use the grpc to query clientState and proof but proof seems to be missing. I see the cli uses different function rather than the grpc query. Is it possible to also return the proof using grpc?
## Version
main 

`372eaa42a9082bcbeaca344fc41151ab95f8b5cd`
## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
gRPC doesn't support proof generation since it directly accesses the value from the Keeper. There is a tracking issue on the [SDK](https://github.com/cosmos/cosmos-sdk/issues/7036). Would love to see someone investigate potential solutions to fix this issue

**Comment by sahith-narahari** [comment]
Thanks for the clarification
